### ISSUE TITLE
Option source.toTexture is useless

### ISSUE THREAD

**Issue by gchoqueux** [iTowns/itowns#1002]
The option `toTexture`, for `FileSource`, is useless since the source is instantiated before creating the layer. This option avoids calculating altitudes when it isn't necessary. For this reason and the desire to unify data fetching in the `dataSourceProvider`, you don't have to fetch file in the `FileSource` constructor.

**Comment by zarov** [comment]
#1033 removes this

**Comment by zarov** [comment]
Solved with #1033
