### ISSUE TITLE
Factorize examples and tests shared code

### ISSUE THREAD

**Issue by jailln** [iTowns/itowns#1019]
I am writing an example which has code shared with already existing examples and with its tests. Where would be a good place to put shared functions between examples and tests ?

More generally, there already is code shared among existing examples that could be factorized in this to-be defined place.

**Comment by zarov** [comment]
This has always been a hot topic of discussion: what can we regroup between examples ? I think beside some helpers, we need to keep examples a minimum independent, to make them understandable without having to look everywhere, especially for someone that begins to have a look at itowns.

For your case, I would say that you can put it inside `examples/js`.

**Comment by jailln** [comment]
Ok, thanks for your response. 

In my case, I factorized the helpers not directly related to iTowns use and left the rest as is (i.e. duplicated). I'll close the issue and I suppose we will discuss it further on a case to case basis directly in the PR if needed.
