### ISSUE TITLE
WFS test doesn't pass on master

### ISSUE THREAD

**Issue by jailln** [iTowns/itowns#1030]
## Your Environment
* Version used: Current master: https://github.com/iTowns/itowns/commit/353bbb73747bc6c1fabb2df2a83c54c91b7d8234
* Operating System and version (desktop or mobile): Ubuntu 18.04.1 LTS 

## Steps to Reproduce (for bugs)
1. `npm install`
2. `npm run test`

## Expected Behavior
All tests should pass

## Actual Behavior
WFS functional test fails with the error:

```
1) wfs
       should pick the correct building:

      AssertionError [ERR_ASSERTION]: 'bati_indifferencie.5265944' == 'bati_indifferencie.5751442'
      + expected - actual

      -bati_indifferencie.5265944
      +bati_indifferencie.5751442
      
      at Context.it (test/functional/wfs.js:16:16)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by gchoqueux** [comment]
Thanks to report this issue, it will be fix after merge #1031
