### ISSUE TITLE
Click event on Color Layer

### ISSUE THREAD

**Issue by moutz** [iTowns/itowns#1051]
Hello,

I try to detect the click or mouseover event over a ColorLayer. The ColorLayer is created from a FileSource Object (projection EPSG:4326). And I listen for the event 'click' on window then use the view.pickObjectsAt(...) method as shown in the globe_wfs_extruded.html example.

But the ColorLayer is not returned by the pickObjectsAt method as it is no a Geometry Object.

Can you tell me what is the best practice to detect event on an ColorLayer ?

Thank you in advance
Mz

**Comment by gchoqueux** [comment]
You can try `/examples/globe_vector.html`, in this example, the mouse is detected when is over `ColorLayer` from Gpx, geojson and Kml. The useful code is in the file [FeatureToolTip.js](https://github.com/iTowns/itowns/blob/master/examples/js/FeatureToolTip.js).

**Comment by moutz** [comment]
Okay ! Thank you I made it work by using something like this 

```js
var geoCoord = this.view.controls.pickGeoPosition(this.view.eventToViewCoords(event))

var layers = this.view.getLayers(function _(l) { return l.source && l.source.isFileSource; });

var precision = 10;

for (var i = 0; i < layers.length; i++) {

     var layer = layers[i];

     var result = itowns.FeaturesUtils.filterFeaturesUnderCoordinate(geoCoord, layer.source.parsedData, precision);

     if(result.length){

     //get infos

     }

}
```

I didn't find the methods pickGeoPosition or .FeaturesUtils.filterFeaturesUnderCoordinate in the documentation : http://www.itowns-project.org/itowns/docs/#home

**Comment by zarov** [comment]
`pickGeoPosition` has documentation here http://www.itowns-project.org/itowns/docs/#api/Controls/GlobeControls, but `FeatureUtils` has none generated yet, but an approximate documentation can be read in the source https://github.com/iTowns/itowns/blob/master/src/Utils/FeaturesUtils.js#L127-L162

**Comment by moutz** [comment]
Sorry I didn't see your answer, thank you I'll watch comments in source now to find some tips and docs ;)
This issue can be closed now

**Comment by prashantthapaliya8989** [comment]
> You can try `/examples/globe_vector.html`, in this example, the mouse is detected when is over `ColorLayer` from Gpx, geojson and Kml. The useful code is in the file [FeatureToolTip.js](https://github.com/iTowns/itowns/blob/master/examples/js/FeatureToolTip.js).

I could not find the file in the examples. Could you please help me with that? @gchoqueux

**Comment by zarov** [comment]
@prashantthapaliya8989 files have been moved, you can find `FeatureToolTip.js` [here](https://github.com/iTowns/itowns/blob/3c3f041b43453dad1820f559a122160ece5c31f1/examples/js/plugins/FeatureToolTip.js) and the use of it [here for example](https://github.com/iTowns/itowns/blob/7db9bcbf31eff090d1a795390dd367202730e3ee/examples/source_file_geojson_raster.html#L110)

**Comment by prashantthapaliya8989** [comment]
> @prashantthapaliya8989 files have been moved, you can find `FeatureToolTip.js` [here](https://github.com/iTowns/itowns/blob/3c3f041b43453dad1820f559a122160ece5c31f1/examples/js/plugins/FeatureToolTip.js) and the use of it [here for example](https://github.com/iTowns/itowns/blob/7db9bcbf31eff090d1a795390dd367202730e3ee/examples/source_file_geojson_raster.html#L110)

Thank you for your response. @zarov
