### ISSUE TITLE
the loadGeometry funciton is error in VectorTileParser.js

### ISSUE THREAD

**Issue by dytmh** [iTowns/itowns#1059]
loadGeometry funciton is error in VectorTileParser.js

In toGeoJSON function,  loadGeometry does not exist

**Comment by zarov** [comment]
Could you please format your message and give more context to your problem ? A template for issues is available when you are creating one, please stick to it.

**Comment by dytmh** [comment]
> Could you please format your message and give more context to your problem ? A template for issues is available when you are creating one, please stick to it.

ok, I've redescribed it

**Comment by zarov** [comment]
I don't understand how this error could occur, as everything seems correctly bound. Can you give more context to this problem ?

**Comment by gchoqueux** [comment]
`VectorTileParser.js` no longer uses `toGeoJSON` function.
