### ISSUE TITLE
Error Move Globe when mouse isn't over the map/globe

### ISSUE THREAD

**Issue by gchoqueux** [iTowns/itowns#106]
The map doesn’t move when the mouse is on the sky.

**Comment by iamvdo** [comment]
Removing test from [`Renderer/ThreeExtended/GlobeControls.js:216-217`](https://github.com/iTowns/itowns2/blob/master/src/Renderer/ThreeExtented/GlobeControls.js#L216-L217) seems to solve the problem when globe reverts back to its initial position after mouse leaves it.

**Comment by gchoqueux** [comment]
fixed in #186
