### ISSUE TITLE
Inconsistency in DataSourceProvider if wrong extent

### ISSUE THREAD

**Issue by zarov** [iTowns/itowns#1063]
## Context

As said in [#1033](https://github.com/iTowns/itowns/pull/1033#discussion_r262529859), there is a problem in the parsing of data to features.

As we can see in [`DataSourceProvider`](), there is no utility in having `EPSG:4978` as an extent, as it is a geocentric extent and makes no sense to use it here. This case can occur if `buildExtent = true` and `crsOut = 'EPSG:4978'`, which is fortunately for now not the case for any of our samples.

## Possible fixes

In parsers, if `crsOut = 'EPSG:4978'`, we may need to force `crsOut` to switch to `crsIn`, or something appropriate. However, we don't control all parsers for iTowns, so something else may need to be found, something else than the simple check there is for now. In the meantime, checks and warning messages can be added.

**Comment by jailln** [comment]
DataSourceProvider no longer has this check.
