### ISSUE TITLE
IOS(test iphone 6/iphone X) Display Error

### ISSUE THREAD

**Issue by rindybo** [iTowns/itowns#1065]
![20190311164823](https://user-images.githubusercontent.com/7138939/54110900-8bb2c500-441d-11e9-938d-f767a61a78ae.png)

**Comment by zarov** [comment]
Hello, this is a similar problem as #964. It is a problem with the `DEPTH_BUFFER`. It can be reproduced on some computers (mine included) by disabling the hardware acceleration for the rendering. Unfortunately I am not yet aware of a solution to this problem, as it is not something we can fix.

**Comment by gchoqueux** [comment]
There is a solution: to replace the `DEPTH_BUFFER` logarithm with a dynamic near and far. A first step to solve this problem is already present in `iTowns` with `infoLayer.extent`. This is extent of displayed tiles, it could give easely the near and the distant.

**Comment by rindybo** [comment]
@zarov 
i check the code 
`new THREE.WebGLRenderer({
            canvas: document.createElement('canvas'),
            antialias: options.antialias,
            alpha: options.alpha,
            logarithmicDepthBuffer: options.logarithmicDepthBuffer,
});`

logarithmicDepthBuffer in mobile can not support,when i set this value false, not work

**Comment by rindybo** [comment]
@gchoqueux Ok,I will try,thank you

**Comment by gchoqueux** [comment]
visiting #164 to follow the subject
