### ISSUE TITLE
Plane mode examples crash when zooming with "TypeError: Cannot read property 'isQuaternion' of null"

### ISSUE THREAD

**Issue by ladislavhorky** [iTowns/itowns#1070]
I am trying to play with vector data in iTowns. Came across this when browsing vector examples on iTowns web.

Zooming on planar mode official examples from http://www.itowns-project.org/itowns/examples/index.html crashes with 

{{{
itowns.js:5 Uncaught TypeError: Cannot read property 'isQuaternion' of null
    at hn.initiateTravel (itowns.js:5)
    at hn.initiateZoom (itowns.js:5)
    at hn.<anonymous> (itowns.js:5)
}}}

Reproduce:

go to: http://www.itowns-project.org/itowns/examples/planar_vector_tiles.html or http://www.itowns-project.org/itowns/examples/planar_vector.html , open web console, try zooming in or out.

Env: Ubuntu 16.04, chormium-browser Version 72.0.3626.121

**Comment by gchoqueux** [comment]
Thanks to report this issue. we will fix the bug quickly.

**Comment by gchoqueux** [comment]
Fixed in #1071

**Comment by ladislavhorky** [comment]
:+1:
