### ISSUE TITLE
remove colon (ponctuation marks) in tutorial (CSS part)

### ISSUE THREAD

**Issue by vcoindet** [iTowns/itowns#1076]
## Your Environment
Any environment

## Context
In this tutorial, remove colon ponctuation marks after CSS tags 
https://github.com/iTowns/itowns/blob/master/docs/tutorials/Create-a-simple-globe.md

`<style>
            html: { height: 100%; }
            body: { margin: 0; overflow: hidden; height: 100%; }
            #viewerDiv: { margin: auto; height: 100%; width: 100%; padding: 0; }
            canvas: { display: block }
        </style>`

## Steps to Reproduce (for bugs)
Follow the tutorial step by step

## Actual Behavior
If you follow the tutorial step by step, it won't work at first cause the CSS is uncorrectly written in the first part.
The end of the tutorial is correctly written.

## Possible Cause/Fix/Solution
`<style>
            html { height: 100%; }
            body { margin: 0; overflow: hidden; height: 100%; }
            #viewerDiv { margin: auto; height: 100%; width: 100%; padding: 0; }
            canvas { display: block }
        </style>`

**Comment by gchoqueux** [comment]
Thanks to report this issue, could you open PR?

**Comment by vcoindet** [comment]
Yes, I will do it next week
