### ISSUE TITLE
Elevation WMTS for development purposes

### ISSUE THREAD

**Issue by ladislavhorky** [iTowns/itowns#1077]
Hello,

I tried to follow the simple-globe tutorial at http://www.itowns-project.org/itowns/docs/#tutorials/Create-a-simple-globe , simply copy-pasting the code. When displaying in a web browser, I get (slightly unsurprisingly) 403 errors on tiles from elevation and ortho WMTS services.

The question is: are there any recommended elevation WMTS services that are free for development and evaluation? I did not find so far any open-data WMTS serving elevation in BIL format. One option may be to set up my own GeoServer that might solve the problem but given I have zero experience with it, it may take too long.

I am aiming for global elevation, ideally with better than 100m resolution, in case of local setup I already have the data.

Any advise will be appreciated. It might help to know how your elevation WMTS service is set up - either I can replicate that or it at least narrows down my further search.

Thanks,
Ladislav

**Comment by gchoqueux** [comment]
Hello, thanks for your interest on iTowns.

Effectively, the tutorial have a minimal configuration to add `ColorLayer` and `ElevationLayer`. These configurations don't have `tileMatrixSetLimits` that specify data not present on the server.

Here's an example code, the limits are set and use a world elevation source.

```js
var viewerDiv = document.getElementById('viewerDiv');
var position = new itowns.Coordinates('WGS84', 2.35, 48.8, 25e6);
var view = new itowns.GlobeView(viewerDiv, position);

var orthoSource = new itowns.WMTSSource({
    url: 'http://wxs.ign.fr/3ht7xcw6f7nciopo16etuqp2/geoportail/wmts',
    name: 'ORTHOIMAGERY.ORTHOPHOTOS',
    tileMatrixSet: 'PM',
    format: 'image/jpeg',
    zoom: {min: 2, max: 12 }
});

var orthoLayer = new itowns.ColorLayer('Ortho', {
    source: orthoSource,
});

view.addLayer(orthoLayer);

itowns.Fetcher.json('examples/layers/JSONLayers/WORLD_DTM.json')
    .then((config) => {
        config.source = new itowns.WMTSSource(config.source);
        var layer = new itowns.ElevationLayer(config.id, config);
        view.addLayer(layer);
    });
```

> I am aiming for global elevation, ideally with better than 100m resolution, in case of local setup I already have the data.

In this [example file](https://github.com/iTowns/itowns/blob/master/index.html#L59), we mix world elevation source and local elevation source. You can take inspiration from the configuration files.
>  I did not find so far any open-data WMTS serving elevation in BIL format.

There's a alternative to `x-bil`, you could use image RGB for `ElevationLayer`, [see planar example](https://github.com/iTowns/itowns/blob/master/examples/planar.html#L88). The elevation data is represented in shades of gray in a given range between `colorTextureElevationMinZ` and `colorTextureElevationMaxZ`.

> Any advise will be appreciated. It might help to know how your elevation WMTS service is set up - either I can replicate that or it at least narrows down my further search.

For information, our elevation WMTS is generated by `Be4` and provided by WMTS service `Rok4`. ([visiting github](https://github.com/rok4))

**Comment by liujingjie** [comment]
Do you have any tutorials for publishing terrain services? I have not found a way to publish wmts on the be4 and rok4 websites. @gchoqueux

**Comment by nickredmark** [comment]
I'd be interested in this too. Both whether there are free alternative wmts servers, and how one would host one's own.

**Comment by gchoqueux** [comment]
There's new project rok4 in docker image : 
* [on github](https://github.com/rok4/docker-rok4-datasets)
* [on hub docker](https://hub.docker.com/r/rok4/dataset)

Otherwise, be4/rok4 team  plans to publish documentation and tutorials.

**Comment by Mkonini** [comment]
You can find Rok4 documentation and tutorials here 
https://github.com/rok4/rok4

**Comment by gchoqueux** [comment]
@etienleigh managed to set up a TMS server on a rasberry Pi. ([see comment](https://github.com/iTowns/itowns/issues/1515#issuecomment-725681903))

He may have an idea on the issue to `publishing terrain services` and free `alternative wmts servers`.

**Comment by etienleigh** [comment]
Kek. I have:
ASTER30 TMS
SRTM30 TMS
SRTM90 TMS
GEBCO 500 TMS
BLENDED GEBCO / SRTM for coastline and bathymetry

I just had no idea i built them for free.
I will think on this. Im new to opensource stuff.
