### ISSUE TITLE
How to get moment when all tiles are loaded

### ISSUE THREAD

**Issue by Sharpsturdy** [iTowns/itowns#1083]
Hello,

I have a task to capture frame when all tiles are loaded. Could you please advice how to get moment when all data is loaded and no more changes expected: 
- all tiles are loaded or loading finished with error or cancelled
- and frame is rendered

Is any event for this? or some workaround?

Thanks in advance.

**Comment by zarov** [comment]
Hello,

There isn't such a feature, as this is really specific to each layer, the level of zoom it currently is, the definition of its extent you give, etc...

There is different events you can use however:
- if you use the `GlobeView`, you can use [`GLOBE_VIEW_EVENTS`](https://github.com/iTowns/itowns/blob/master/src/Core/Prefab/GlobeView.js#L52) combined with some [`VIEW_EVENTS`](https://github.com/iTowns/itowns/blob/master/src/Core/View.js#L31)
- you can also use [`view.mainLoop.renderingState`](https://github.com/iTowns/itowns/blob/master/src/Core/MainLoop.js#L33) with the value `RENDERING_PAUSED` to know when there won't be anymore update

**Comment by gchoqueux** [comment]
you have too `VIEW_EVENTS.LAYERS_INITIALIZED` when tiles and all layers are loaded: 
```js
// Listen for viewer full initialisation event
view.addEventListener(itowns.VIEW_EVENTS.LAYERS_INITIALIZED, function _() {
  // your code...
});
```
