### ISSUE TITLE
Planar example is broken

### ISSUE THREAD

**Issue by jailln** [iTowns/itowns#1097]
## Your Environment
* Version used: current master
* Browser Name and version: Firefox 66.0.2 (same on Chromium 73.0.3683.75)
* Operating System and version (desktop or mobile): Desktop Ubuntu 18.04.2 LTS

## Steps to Reproduce (for bugs)
1. Run the [planar example](https://github.com/iTowns/itowns/blob/master/examples/planar.html) 

## Expected Behavior
The terrain should be displayed on the planar view.

## Actual Behavior
The terrain is not displayed. The console gives errors such as:

````
Access to image at 
'https://download.data.grandlyon.com/wms/grandlyon?SERVICE=WMS&REQUEST=GetMap&LAYERS=MNT2012_Altitude_10m_CC46&VERSION=1.3.0&STYLES=&FORMAT=image/jpeg&TRANSPARENT=false&BBOX=1841520.21,5171083.50,1842754.63,5172130.55&CRS=EPSG:3946&WIDTH=256&HEIGHT=256' 
from origin 'http://localhost:8080' has been blocked by CORS policy: 
The 'Access-Control-Allow-Origin' header contains multiple values '*, *', 
but only one is allowed.
````

## Possible Cause/Fix/Solution
It seems like a CORS problem; maybe something has changed on data grand lyon server ?

**Comment by zarov** [comment]
It seems to be an error from their server, because it is the response that is wrong.

Here is what is sent:
```
Host: download.data.grandlyon.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0
Accept: image/webp,*/*
Accept-Language: en,en-US;q=0.8,fr-FR;q=0.5,fr;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: http://localhost:8080/examples/planar.html
Origin: http://localhost:8080
Connection: keep-alive
Cache-Control: max-age=0
```

And here is what is received (notice almost everything in double):
```
HTTP/1.0 200 Connection established
Date: Tue, 09 Apr 2019 06:39:56 GMT
Server: Apache
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
Access-Control-Allow-Methods: GET,POST,OPTIONS,DELETE,PUT
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
Access-Control-Allow-Methods: GET,POST,OPTIONS,DELETE,PUT
Content-Type: image/jpeg
Connection: close
Transfer-Encoding: chunked
```

I don't know who to contact at grand lyon to fix that, but I hope they will notice soon ?

**Comment by jailln** [comment]
Thanks for looking into it; it is working again so they seem to have fixed it.
