### ISSUE TITLE
I need to modify the coordinate system

### ISSUE THREAD

**Issue by dytmh** [iTowns/itowns#1101]
I need to use the same coordinate system as threejs, Y axis up, what do I need to change?

**Comment by zarov** [comment]
You can use geocentric coordinates, that you can obtain from any coordinate using `Coordinates#xyz()`. See the related documentation http://www.itowns-project.org/itowns/docs/#api/Geographic/Coordinates

**Comment by gchoqueux** [comment]
the geomatics convention imposes the z axis up. If you have objects 3D with the Y axis up, you could to rotate yours objects 3D.
```js
group.rotateX(Math.PI * 0.5);
group.rotateZ(Math.PI * 0.5);
```
That's why you need to have the y-axis up?
