### ISSUE TITLE
Altitude in geometry layer tutorial incorrect

### ISSUE THREAD

**Issue by arover6** [iTowns/itowns#1106]
The example for creating a [geometry layer](http://www.itowns-project.org/itowns/docs/#tutorials/Display-a-geometry-layer) is producing "flying" buildings, with a gap between the ground and the extruded buildings bases. I am quite new to this kind of things, so I am not sure the culprit, but it seems the calculated altitude is off.

## Your Environment
Latest version of iTowns on latest stable release of Chrome.

## Steps to Reproduce (for bugs)
Simply copy the example given in the [documentation](http://www.itowns-project.org/itowns/docs/#tutorials/Display-a-geometry-layer).

## Expected Behavior
Buildings bases should be on the ground.

## Actual Behavior
Buildings are flying mid-air.

**Comment by zarov** [comment]
The example is out of date indeed, I'll update it soon. The reported bug is the same as #855. This is a good reminder that we really need to fix it, so I'll close this issue but we will work on #855 as quick as we can.

Meanwhile, you can toy with the computed value by changing it and finding a suitable one.
