### ISSUE TITLE
Support for OpenStreetMap building parts

### ISSUE THREAD

**Issue by arover6** [iTowns/itowns#1107]
OpenStreetMap offers [tags](https://wiki.openstreetmap.org/wiki/Simple_3D_buildings) to describe more complex shapes than simple building extruding, which can advantageously be used by providing models for each part, thus constructing more faithfully complex buildings. There are also tags for trees, lampposts, traffic lights, etc.

Would it be possible in iTowns to implement a setter, to assign models for each of these parts? The idea would be that for each part, the developer can assign a 3D model, and iTowns reconstructs according to the given models.
An example (but non-modular) implementation can be seen in [OSM-Go](https://wiki.openstreetmap.org/wiki/OSM_go).

**Comment by zarov** [comment]
We have not discussed something like that for the moment, but we are currently working on more visual customization on things like buildings. Maybe it will come up later, but in the meantime you are very welcomed to make some propositions for the implementation of this (being it PR or more discussion in this issue) ;)

**Comment by gchoqueux** [comment]
see #183
