### ISSUE TITLE
Project running at localhost

### ISSUE THREAD

**Issue by shrimpie1911** [iTowns/itowns#1115]
I have sucessfully install and compiled iTowns. But i saw in the beginning that my "project is running at http://localhost:8080/". Is there anyway i can change localhost to the address i want (for reseach purpose of course)?

Thank for the help in advance and sorry for my bad english.

**Comment by shrimpie1911** [comment]
I have sucessfully install and compiled iTowns. But i saw in the beginning that my "project is running at http://localhost:8080/". Is there anyway i can change localhost to the address i want (for reseach purpose of course)?

Thank for the help in advance and sorry for my bad english.

**Comment by nosy-b** [comment]
You can change the port with npm start -- --port=3000 for example

**Comment by shrimpie1911** [comment]
Thank you for the fast reply. I can change the port, but for example, i don't want to run on http:localhost but a diffrent address (for example one of my vhost)?

Thank for the help in advance and sorry for my bad english.

**Comment by tbroyer** [comment]
iTowns is a JS library/framework; the `npm start` (and `python -m SimpleHTTPServer`) is only there for development purpose.

If you want to deploy the existing "sample" that is used to develop iTowns features, then you can `npm run build` and then copy the `index.html` and the `dist/` and `examples/` folders out to your vhost, where you can use the web server you want to serve them through HTTP (Apache HTTPD, nginx, lighttpd, etc.)
