### ISSUE TITLE
Add Openstreetmap layer source from url

### ISSUE THREAD

**Issue by shrimpie1911** [iTowns/itowns#1116]
My project is to make a globe view for my openstreetmap tile server using iTowns. I have the globe, i have the tile server, but i don't know how to add openstreetmap layer to iTowns. I have try:
 
```js
var <name> = L.tileLayer('http://<tile.name>/{z}/{x}/{y}.png', {
 attribution: osmAttr + ', <a href="http://server.name"><name></a>'
});
view.addLayer(layer).then(menuGlobe.addLayerGUI.bind(menuGlobe));
```

But it show nothing. Can someone help me please?

Thank you in advance and sorry for my bad english.

**Comment by shrimpie1911** [comment]
My project is to make a globe view for my openstreetmap tile server using iTowns. I have the globe, i have the tile server, but i don't know how to add openstreetmap layer to iTowns. I have try:
 
var <name> = L.tileLayer('http://<tile.name>/{z}/{x}/{y}.png', {
 attribution: osmAttr + ', <a href="http://server.name"><name></a>'
});
view.addLayer(layer).then(menuGlobe.addLayerGUI.bind(menuGlobe));

But it show nothing. Can someone help me please?

Thank you in advance and sorry for my bad english.

**Comment by zarov** [comment]
You seem to be using code from Leaflet if I'm not mistaken ? Leaflet and itowns API are not compatible, you need to follow the itowns API. I invite you to:
- read the tutorials http://www.itowns-project.org/itowns/docs/#tutorials/Create-a-simple-globe
- read the documentation of the `TMSSource`, with its example adding an OSM layer http://www.itowns-project.org/itowns/docs/#api/Source/TMSSource
- check this example using `TMSSource` https://github.com/iTowns/itowns/blob/master/examples/orthographic.html

**Comment by shrimpie1911** [comment]
Thank your for the fast reply. For testing i use this. But when i go to my site there is only the empty globe. I don't know why. Can you help please?

For addtionnal information, i have run `npm run build` in the iTown repository, after that i've copy the `dist` and `examples` folder to my project.

Thank you in advance for the help and sorry for my bad english.

```html
<html>
    <head>
        <title>Globe</title>
        <link rel="stylesheet" type="text/css" href="examples/css/example.css">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="examples/js/GUI/dat.gui/dat.gui.min.js"></script>
    </head>
    <body>
        <div id="viewerDiv" class="viewer"></div>
        <script src="examples/js/GUI/GuiTools.js"></script>
        <script src="dist/itowns.js"></script>
        <script src="dist/debug.js"></script>
        <script type="text/javascript">
            var positionOnGlobe = { longitude: 2.351323, latitude: 48.856712, altitude: 25000000 };
            // iTowns namespace defined here
            var viewerDiv = document.getElementById('viewerDiv');
            var view = new itowns.GlobeView(viewerDiv, positionOnGlobe);

            const tmsSource = new itowns.TMSSource({
                format: 'image/png',
                url: 'http://tiles.test.local/${z}/${x}/${y}.png',
                attribution: {
                        name: 'Test',
                        url: 'http://osm.test.local/',
                },
                tileMatrixSet: 'PM',
            });

            // Create the layer
            const colorLayer = new itowns.ColorLayer('OPENSM', {
                source: tmsSource,
            });

            // Add the layer
            view.addLayer(colorLayer);
        </script>
    </body>
</html>

**Comment by zarov** [comment]
Do you have any error in the web console ?

**Comment by shrimpie1911** [comment]
I saw a JS error:

HREE.WebGLShader: gl.getShaderInfoLog() vertex 0:2(12): warning: extension `GL_ARB_gpu_shader5' unsupported in vertex shader

If i'm not mistaking there is already a thread about this but it closed beacause this is the web browser problem right?

Thank you in advance for the help and sorry for my bad english.

**Comment by shrimpie1911** [comment]
I saw a shader error while using Firefox. As i saw on some of the old threads this is the browser error, so i switch to Chrome, but in chrome i have an error for all the tiles on my server:

`Access to image at 'http://tiles.test.local/3/0/4.png' from origin 'http://test.local' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Can you have please?

Thank you in advance and sorry for my bad english.

**Comment by shrimpie1911** [comment]
Thank you for your fast reply. I have a shader error so i switch to chrome and its working now (although i have to enable Access-Control-Allow-Origin extension).

**Comment by zarov** [comment]
(I can't see your previous message, did you delete them ?)

For the CORS problem, you can play with `networkOptions` to add in the `TMSSource` declaration (see available options here https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch#Syntax) as well as `networkOptions.crossorigin` (with values here https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes).

**Comment by shrimpie1911** [comment]
I delete my previous comment because its no very clear. Yes in the begining i try with `networkOptions: { crossOrigin: 'anonymous' }` but it still crash so i have to add the extension manually.

**Comment by gchoqueux** [comment]
Could you open http://www.itowns-project.org/itowns/examples/split.html without crash?
This example use Open street map.
