### ISSUE TITLE
Whole map is freezing after upgrading to 2.9.0

### ISSUE THREAD

**Issue by moutz** [iTowns/itowns#1122]
* Version used: 2.9.0

After upgrading from 2.8.0 to 2.9.0 the map is not working anymore, after the map is loaded, when I try to move, the whole map freeze whith strange color : 

![image](https://user-images.githubusercontent.com/4683568/56566629-6f28b180-65b3-11e9-84e0-400950f06448.png)

I have no idea where to search and how to debug that.. I refresh my node modules, remove all my styles but there is always this bug.
Thank you for your help.

m.

**Comment by zarov** [comment]
Can you give us more context ? What type of layer are you displaying, what is the source used, etc...

**Comment by moutz** [comment]
Thank you for your answer. I'm in a VueJS app, and I use only 2 layers (for the moment): colorlayer like the example that fetch data fromI IGN (pro account with valid key) and elevationLayer. Here is my code : 

````javascript
var positionOnGlobe = { longitude: 4.846266, latitude: 45.076237, altitude: 6331 };
var viewerDiv = document.getElementById('viewerDiv');
this.view = new itowns.GlobeView(viewerDiv, positionOnGlobe);

// ADD ORTHO LAYER
this.promises.push(itowns.Fetcher.json('./layers/Ortho.json').then((config) => {
    config.source = new itowns.WMTSSource(config.source);
    var layer = new itowns.ColorLayer('Ortho', config);
    this.view.addLayer(layer);
}));

// ADD ELEVATION LAYER
this.promises.push(itowns.Fetcher.json('./layers/IGN_MNT_HIGHRES.json').then((config) => {
     config.source = new itowns.WMTSSource(config.source);
     var layer = new itowns.ElevationLayer(config.id, config);
     this.view.addLayer(layer);
}));
    
this.view.addEventListener(itowns.GLOBE_VIEW_EVENTS.GLOBE_INITIALIZED, () => {
        console.log("LOADED")   
        // make something with promises
});
````

The map is loading well, but once I click on it to start moving, the whole map freeze and there is no way make it move.

m.

**Comment by moutz** [comment]
Exact same code is working when I downgrade to 2.8.0

**Comment by zarov** [comment]
Thanks for verifying this. I'm not familiar to Vue.js app, is it like an Electron one ? If so, that may be something to do with WebGL, but it is something I hope we can fix in iTowns, especially if it was working in 2.8.0.

**Comment by moutz** [comment]
Thanks for answering. Actually Vue.js is a framework, and I'm not building it in an Electron app. So I suggest I use the presets of my browser for WebGL.

I have some warnings in my console : 
````
THREE.WebGLRenderer 101 three.module.js:22368

THREE.WebGLProgram: gl.getProgramInfoLog() C:\fakepath(138,1): warning X4000: use of potentially uninitialized variable (f_webgl_6d2c8645452cd6e2) three.module.js:17343

THREE.WebGLProgram: gl.getProgramInfoLog() C:\fakepath(85,28-103): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them

THREE.WebGLProgram: gl.getProgramInfoLog() C:\fakepath(122,1): warning X4000: use of potentially uninitialized variable (f_webgl_6d2c8645452cd6e2)
````

**Comment by zarov** [comment]
Sorry, I can't find what can be causing this problem when looking at the difference between 2.8.0 and 2.9.0. Maybe @gchoqueux have an idea about this ? In the meantime I'm sorry this is happening, maybe stick to 2.8.0 for the moment.

**Comment by gchoqueux** [comment]
@moutz, you would be possible to provide a example with `VueJs` and `iTowns` that reproduce the bug. We could fix `iTowns` more easily. Thanks

**Comment by gchoqueux** [comment]
You have this warning :
````
THREE.WebGLRenderer 101 three.module.js:22368
````
It's not normal because `itowns 2.9.0` uses `THREE 102.1`. It may be necessary to check the packages of your project.

**Comment by moutz** [comment]
Hello,

sorry didn't habe time to get back on my Itowns project. So I update to THREE 102.1 and it works now. 
As I am in a Vue project, I added it separatly from the Itowns package.
I have to change the way I create my ColorLayer and then everything came back as before.

Thank you for your answer and time.

m.
