### ISSUE TITLE
Finalize WFS feature

### ISSUE THREAD

**Issue by gchoqueux** [iTowns/itowns#115]
- Create Api functions for WFS (add,remove,visibility,opacity)
- Finalize WFS provide

**Comment by mlamure** [comment]
Working on this issue on the branch WFSFeature.

**Comment by qdnguyen** [comment]
cool, do your branch contain lastest changes from master? 

seem your branch is dated, ca you please update the branch from master so that i can aslo work on this?

**Comment by mlamure** [comment]
I haven't updated my branch from the master since the code sprint.

**Comment by qdnguyen** [comment]
can you please update it? i will work on your branch also.

**Comment by mlamure** [comment]
Yes, I will do it. I will warn you when it is done.

**Comment by mlamure** [comment]
I am not far from finishing my rebase but I need the pull request #163 to be accepted first. I will warn you has soon as it is done.

**Comment by qdnguyen** [comment]
do you have some progress on this work? i start to work on WFS this week, please let me know about your progess.

**Comment by qdnguyen** [comment]
I have created a new WFS2 branch and i have some progress on it, you can to take a look if you want!  

![sans titre](https://cloud.githubusercontent.com/assets/3224540/17406554/30dc74aa-5a64-11e6-8a0b-304014b0552c.png)

**Comment by qdnguyen** [comment]
Many problems related to alti/performance/etc to be solved but here is first look of WFS building 
![sans titre](https://cloud.githubusercontent.com/assets/3224540/17408441/7e89bd8c-5a6b-11e6-90c2-2a3d2a438eaf.png)

**Comment by gchoqueux** [comment]
Nice

**Comment by qdnguyen** [comment]
thanks! i will see how can i style these buildings tomorrow

**Comment by mlamure** [comment]
I am sorry that I did not push my code before. I am currently on holiday and I had some problems just during my last rebase. As you have done another branch and my code will not conflict with yours, I will push my code in the old one but you have to know that there is still some bugs.

**Comment by mlamure** [comment]
Hi,
I came back from holiday and took a look at your code. I would like to merge what I did with what you did on your branch if it is OK with you (I have made too many rebase on my branch and I can not find the origin of the problems have).
There is some things in your code that diverge from mine  and I would like to discuss it with you:
    - I intended to have a feature provider which would permit to have a general provider and you did put all your code inside the WFS provider. Do you think it is simplier to use only the WFS provider or can we create a provider for each type of feature (point, line, polygon, box,...) ?
    - Do you think that it is better to do a rebase before I do the merge ?
Thank you for your response

**Comment by mlamure** [comment]
For the first point, we can take into account the fact that we might need to use the feature fonctions with a type of request other than the WFS. So it might be better if we do a feature provider which can be more general.

**Comment by mlamure** [comment]
Bonjour,

Je suis actuellement en train de travailler sur la branche WFS2. J'ai notamment ajouté différents types de features et fait un travail sur le changement de représentation des features en fonction du niveau (SSE). Je suis prète à pusher ces changements si cela vous convient.

J'ai également plusieurs questions à vous poser concernant le système d’implémentation des features.

Pour le moment, nous faisons uniquement des requêtes en utilisant le protocole WFS ce qui justifie le fait de mettre les fonctions spécifiques aux features à l’intérieur du WFS_Provider mais qu’en sera-t-il quand nous voudrons afficher des features avec d’autres types de requêtes ? Ne serait-il pas plus judicieux de faire un Feature_Provider séparé du WFS_Provider qui deviendrait uniquement le responsable des requêtes et non plus du traitement des résultats ? Et dans le cas où nous déciderions de faire un provider séparé, ne faudrait-il pas faire un provider par type de feature (un Feature_Provider global ferait la répartition entre les Feature_Provider enfants) ?

La deuxième question concerne le calcul des positions des différents meshes. La position des tuiles de terrain est calculée par des shaders spécifiques utilisant la position de la caméra (RTC). Est-ce que le fait d’utiliser les shaders natifs de THREE js ne pourrait pas poser de problème au niveau de la précision du calcul des positions ? Pour le moment, lorsque nous sommes proches des features et que nous bougeons la camera, nous avons l’impression que les features ont des soubresauts.

En vous remerciant.

**Comment by vpicavet** [comment]
Thanks for keeping issues and PR and comments in english.
For general discussions you can use the mailing list too.

EDIT: not sure where the comment went inbetween ?

**Comment by qdnguyen** [comment]
Sorry for my late reply, i just come back from vacation

> Hi,
> I came back from holiday and took a look at your code. I would like to merge what I did with what you did on your branch if it is OK with you (I have made too many rebase on my branch and I can not find the origin of the problems have).

What is your branch? 

> There is some things in your code that diverge from mine and I would like to discuss it with you:
> - I intended to have a feature provider which would permit to have a general provider and you did put all your code inside the WFS provider. Do you think it is simplier to use only the WFS provider or can we create a provider for each type of feature (point, line, polygon, box,...) ?

We can keep WFS_provider for many data types

> - Do you think that it is better to do a rebase before I do the merge ?
>   Thank you for your response

Yes, it's better to do rebase before you merge two branches, but i can not do it this week, i have many deadline for paper, geoportail, etc. I can see it later but if you have time, dont hésitate to do it.

**Comment by mlamure** [comment]
Hi,

My branch was WFSFeature but I worked on the branch WFS2 for the last 2 weeks. I did the merge without using the git tools because my branch had some problems.

WFS_Provider refers to a specific protocol, the geometry construction (GeoJSON to Three geometry) is what I want to move out of the WFS provider so it can be used with other import methods. If you have no objection, I will proceed with this change.

**Comment by qdnguyen** [comment]
can you push your code please?

yeap, some functions can be moved to other modules.

**Comment by mlamure** [comment]
Hi,
I pushed my code as you requested.
I am about to do the rebase if that is ok with you.

**Comment by qdnguyen** [comment]
ok, thanks, mais addFeatureLayer should take protocol inputs as WFS, GPX, KML? but not WFSLine/WFSPoint, etc. You can pass datatype by Type.

**Comment by mlamure** [comment]
Ok, I will try to fix it before the rebase.

**Comment by qdnguyen** [comment]
Multiple layers for WFS should be supported before developing API functions such as pickFeature, addFeature, etc.

@gchoqueux : do you have any idea how to do it? for now, all features (building, points, line, etc) are stocked in kml object in Globe.

**Comment by qdnguyen** [comment]
OK, i added some features for WFS 
- support multiple layers for wfs 
- new functionalities : addFeature, removeFeature, getPickingFeature, etc.

@mlamure can you please clean your code for a PR?

**Comment by mlamure** [comment]
Yes of course. I will do it right now.

**Comment by gchoqueux** [comment]
Move in #195 and #214
