### ISSUE TITLE
Tiles in the same quality

### ISSUE THREAD

**Issue by OlegYarko** [iTowns/itowns#1158]
I would like to get all tiles in the same quality. How can I achieve it?
Thanks!
![dif](https://user-images.githubusercontent.com/33403994/59689731-d72cfa00-91e8-11e9-9110-f3f78bed62aa.JPG)

**Comment by gchoqueux** [comment]
You could increase the quality by decreasing  the `sseSubdivisionThreshold`:

```js
const view = new itowns.GlobeView(viewerDiv, positionOnGlobe, {
      sseSubdivisionThreshold: 0.8
});
```

You have to be careful with this parameter because it affects the performance.

**Comment by OlegYarko** [comment]
Thanks!
I just thought that if set maxSubdivisionLevel = minSubdivisionLevel then I will get the desired result.
Sometimes it works ( max, min<7 ), but sometimes it just hangs everything up ( max, min >8 ).
