### ISSUE TITLE
Add an event for 3DTiles tile loading

### ISSUE THREAD

**Issue by Crejak** [iTowns/itowns#1165]
In a project using iTowns and 3DTiles data, we need to retrieve information specific to tiles (especially the Batch Table and the Batch IDs). Ideally, this would only be done once when the 3DTiles layer is added. However, as the tiles are loaded only when needed (ie. when they need to be rendered), information such as Batch Tables & Batch IDs are mostly unavailable at this moment.

A solution would be to trigger an event when a 3DTiles tile is loaded, so that we could retrieve and store the information we need.

Do you think it would be possible to add such an event ?

**Comment by gchoqueux** [comment]
Yes, it's possible, I'll come back soon to plan this feature.

**Comment by Crejak** [comment]
Thank you for your reply !

**Comment by gchoqueux** [comment]
@Crejak #1208 fixes this issue?

**Comment by Crejak** [comment]
Yes, I tried it a bit and it seems to work fine. Thank you !
