### ISSUE TITLE
notifyChange() doesn't seem to correctly trigger rendering

### ISSUE THREAD

**Issue by Crejak** [iTowns/itowns#1167]
In our project, we are changing the color of some vertices in 3DTiles tiles. We do that by adding a color BufferAttribute to the Mesh of the tile (situated in the Object3D hierarchy of the layer). We wanted to call the function `notifyChange` in the View to trigger rendering, however it doesn't seem to work in our case. When we call the function, the objects in our scene just keep their original color, even if we move the camera.

After several trials, we found out that calling `view.mainLoop.gfxEngine.renderViewToBuffer` before `notifyChange` does the job. Below is the actual piece of code we use to update the view :

```js
view.mainLoop.gfxEngine.renderViewToBuffer({
    scene: view.getLayerById('3d-tiles-layer').object3d,
    camera: view.camera
  }, {x: 0, y: 0, width: 0, height: 0});
view.notifyChange();
```

We found out this function is called for example by `pickObjectsAt`, while `notifyChange` seems to call `view.mainLoop.gfxEngine.renderView` to do the rendering. Do you have any idea on why the rendering is not triggered with only `view.notifyChange` ?

**Comment by gchoqueux** [comment]
There's no need to do that.  Change the color buffer values and then assign `true` to `object.geometry.attributes.color.needsupdate` ([visiting](https://threejs.org/docs/#manual/en/introduction/How-to-update-things)) and call `view.notifyChange(view.camera)`.

**Comment by Crejak** [comment]
We are already doing this. Below is the piece of code we use to change the color :

```js
tile.geometry.attributes.color.set(colors);
tile.geometry.attributes.color.needsUpdate = true;
```

`tile` is the "Mesh" object representing the 3DTiles tile and `colors` is a `Float32Array` containing the new colors.

**Comment by gchoqueux** [comment]
ok, could provide you an example with data to fix your issue? (on jsfiddle by example)

**Comment by Crejak** [comment]
Creating a JSFiddle will probably take some time, I'll maybe do that later if needed.

At this address you can see an example app that colors buildings : switch the "3DTiles Debug" button on the left, and then you can color buildings by clicking on them.
http://rict.liris.cnrs.fr/UDVDemo-2/UDV/UDV-Core/src/Extensions/3DTilesDebug/examples/Demo.html

The whole code is available on [this repo](https://github.com/MEPP-team/UDV). If you want to test it you can simply run it with `npm install` and `npm start` in the UDV-Core folder.

To update the view after the building was colored, we call a function named `updateITownsView` defined at the bottom of this file : see this [permalink](
https://github.com/MEPP-team/UDV/blob/3434596bae9e6475ea35d7526c438bc899c0d832/UDV-Core/src/Utils/3DTiles/3DTilesUtils.js#L207). As you can see, it makes use of the piece of code mentioned in my issue. If you remove the first call, the view does not update correctly.
For the actual coloring, another function defined in the same file is used : [permalink](https://github.com/MEPP-team/UDV/blob/3434596bae9e6475ea35d7526c438bc899c0d832/UDV-Core/src/Utils/3DTiles/3DTilesUtils.js#L118). You can see that at the bottom of the function, the `needsUpdate=true` instruction is present.

**Comment by gchoqueux** [comment]
Hello, have you solved your problem?

Have you try to change vertex color  with only THREE example? (without iTowns) to identify problems. 

In your case `renderViewToBuffer` won't help you, this  function is used to copy rendering in buffer Array (to refresh view use `notifyChange`).

In your example, it's possible to change color by picking, in this case you change the material color?
