### ISSUE TITLE
3D Tiles cache ?

### ISSUE THREAD

**Issue by jailln** [iTowns/itowns#1170]
Cache does not seem enabled by default for 3D Tiles.

For instance, if you zoom in/out in [this example](http://rict.liris.cnrs.fr/iTownsPlanar3DTiles/itowns/examples/planar_3dtiles.html) (warning: temporary link) you can see from the network debugging tool that the tiles are re-requested.

Is there a way to enable cache for 3D Tiles ?

**Comment by zarov** [comment]
While it is not checked by iTowns, it should be checked in the browser cache. In your debugging tool, is the `Disable cache` option unchecked ?

Here is what I got

![image](https://user-images.githubusercontent.com/741255/60443952-85d72e80-9c1c-11e9-906a-48a515dd7496.png)

**Comment by jailln** [comment]
Yes you're right, my question was not well expressed.

While it is cached, it seems to be unloaded from iTowns' memory and hence requested again (from cache) and then parsed again ? If this is correct; is there an option to avoid unloading these tiles and to just not render them ?

**Comment by zarov** [comment]
I don't really know the 3dtiles part of iTowns, so I have no clue here. Maybe @jailln can help here ?

**Comment by jailln** [comment]
Haha that's actually me asking the question ;)

How does it work for other types of data ?

**Comment by zarov** [comment]
Damn sorry I got confused with another thread !

For most data in iTowns, apart from 3dtiles and pointclouds, it is set in the `Cache` in the [`DataSourceProvider`](https://github.com/iTowns/itowns/blob/master/src/Provider/DataSourceProvider.js#L126). For 3dtiles, I think tweaking things [here](https://github.com/iTowns/itowns/blob/master/src/Provider/3dTilesProvider.js#L316-L346) could be a solution.

**Comment by jailln** [comment]
Ok, thanks. I guess we should use the Cache object as well in 3D Tiles then. 

A solution might also be to turn the loaded tiles contents visible or not using Threejs' [Object3D.visible](https://threejs.org/docs/index.html#api/en/core/Object3D.visible) instead of unloading them after a fixed delay that is defined [here](https://github.com/iTowns/itowns/blob/master/src/Provider/3dTilesProvider.js#L162).

**Comment by gchoqueux** [comment]
> A solution might also be to turn the loaded tiles contents visible or not using Threejs' Object3D.visible instead of unloading them after a fixed delay that is defined here.

yes, and unloading children when theirs parent aren't visible.

**Comment by mgermerie** [comment]
The complete 3d-tiles support is planned in the short term road map. We are currently studying possibilities in terms of libraries to enhance support (as mentioned in https://github.com/iTowns/itowns/discussions/1917).

**Comment by jailln** [comment]
Now managed by 3DTilesRendererJS
