### ISSUE TITLE
Visual issues when using WFS and GeoJSON file

### ISSUE THREAD

**Issue by thomleysens** [iTowns/itowns#1179]
The [globe_wfs_extruded example](http://www.itowns-project.org/itowns/examples/globe_wfs_extruded.html) seems to have some visual bugs. Some buildings and bus lines disappear (*it seems they "go" under the elevation layer*) after zoom or orientation changes. 

I have similar problems locally (*with iTowns v2.12.0*) with the same WFS Bus lines and with a multipolygons with holes GeoJSON file in EPSG:3857 (*same results with reprojection to EPSG:4326*). 

## Your Environment

* Version used: iTowns v2.12.0
* Browser Name and version: Firefox Quantum 67.0.4 (64 bits) 
* Operating System and version (desktop or mobile): Ubuntu 18.04.2 LTS
* Link to your project:

## Context

Visual bugs on the [globe_wfs_extruded example](http://www.itowns-project.org/itowns/examples/globe_wfs_extruded.html) are similar on Firefox Quantum  67.0.4 and Firefox Quantum 68.0 (*both in 64 bits on Ubuntu 18.04.2 LTS*). 

On my local version with iTowns v2.12.0, some bus lines are missing and GeoJSON is very buggy (*see screenshot below*).  When I load the same WFS on QGIS, it works great as well as my GeoJSON file (*I also checked the validity of the geometry with QGIS and the GeoJSON appeared to be valid*). 

![bug](https://i.imgur.com/8RPmaUW.png)

I have these warnings in the console (*local version*). iTowns seems to have difficulties to manage the great number of points (```Feature to Polygon: integer overflow, too many points in polygons```):
```
Error: WebGL warning: linkProgram: Programs with more than 16 samplers are disallowed on Mesa drivers to avoid crashing. udvcore.js line 8256 > eval:6:157194
Programs with more than 16 samplers are disallowed on Mesa drivers to avoid crashing.: using a maximum of 16 texture units instead of the reported value (32) debug.js:5
It can come from a Mesa/Firefox bug;
                        the shader compiles to an error when using more than 16 sampler uniforms,
                        see https://bugzilla.mozilla.org/show_bug.cgi?id=777028 debug.js:5
Feature to Polygon: integer overflow, too many points in polygons
itowns.js:12:592866
Erreur dans les liens source : TypeError: Invalid URL: webpack://[name]/webpack/universalModuleDefinition
URL de la ressource : http://localhost:8080/node_modules/itowns/dist/itowns.js
URL du lien source : itowns.js.map
``` 

There are similar warnings (```Feature to Line: integer overflow, too many points in lines```) on the online [globe_wfs_extruded example](http://www.itowns-project.org/itowns/examples/globe_wfs_extruded.html) and similar visual bugs (*see screenshot below*). 

```
Error: WebGL warning: linkProgram: Programs with more than 16 samplers are disallowed on Mesa drivers to avoid crashing. itowns.js:5:98706
Programs with more than 16 samplers are disallowed on Mesa drivers to avoid crashing.: using a maximum of 16 texture units instead of the reported value (32) itowns.js:5:98981
It can come from a Mesa/Firefox bug;
                        the shader compiles to an error when using more than 16 sampler uniforms,
                        see https://bugzilla.mozilla.org/show_bug.cgi?id=777028 itowns.js:5:99099
Feature to Line: integer overflow, too many points in lines itowns.js:12:590373
err [object Object] 
error { target: img, isTrusted: true, srcElement: img, eventPhase: 0, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, timeStamp: 130022, … }
itowns.js:12:622667
err [object Object] 
error { target: img, isTrusted: true, srcElement: img, eventPhase: 0, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, timeStamp: 130022, … }
itowns.js:12:622667
err [object Object] 
error { target: img, isTrusted: true, srcElement: img, eventPhase: 0, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, timeStamp: 130024, … }
itowns.js:12:622667
err [object Object] 
error { target: img, isTrusted: true, srcElement: img, eventPhase: 0, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, timeStamp: 130024, … }
itowns.js:12:622667
err [object Object] 
error { target: img, isTrusted: true, srcElement: img, eventPhase: 0, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, timeStamp: 130841, … }
itowns.js:12:622667
err [object Object] 
error { target: img, isTrusted: true, srcElement: img, eventPhase: 0, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, timeStamp: 130841, … }
itowns.js:12:622667
```
![bug2](https://i.imgur.com/KFQ3r8u.jpg)

I have the same visual bugs with your online example on Opera Version :62.0.3331.66.

**Comment by gchoqueux** [comment]
It seems there are 2 problems:
- it would seem you use firefox with driver mesa, it's bugged  => you should install the GPU driver (or use Chrome)
- The visual glitchs come from the count of points on geojson line, it's Itowns bug.We will fix it.

**Comment by EricBoix** [comment]
With the same [itowns WFS example as above mentioned](http://www.itowns-project.org/itowns/examples/globe_wfs_extruded.html) (as of today July 16th) the same line rendering problem happens for both Firefox 68.0 (WebGL 1 Driver Version 4.1 ATI-2.9.26) and Chrome 75.0.3770.142 on an OSX (10.14.5) platform.

I also noticed that 
 - entire patches of buildings sometimes vanish (after some random translations and zoom in/out)
 - the "Line Width" slider in the "Layer WFS Bus Lines" control panel has no effect whatsoever

**Comment by thomleysens** [comment]
@gchoqueux @EricBoix 

I noticed the same issues with the buildings layer (*also after some translations and zoom in/out*) regardless of the web browser (*Opera, Firefox, Chromium*).

**Comment by gchoqueux** [comment]
I add the geojson file.
[out_geojson.zip](https://github.com/iTowns/itowns/files/6414877/out_geojson.zip)
