### ISSUE TITLE
WMS layers are not correctly added and freeze all the layer's requests

### ISSUE THREAD

**Issue by elias75015** [iTowns/itowns#1180]
Adding a WMS layer to the globe freeze all the requests

## Environment
OS :
Ubuntu 18.04

Browser :
Chrome 75.0.3770.100
FF 68.0

iTowns version :
iTowns 2.12.0 through the geoportal extensions for itowns

## Steps to Reproduce (for bugs)

1. add a WMS layer (ex : REGION.2016, UTILITYANDGOVERNMENTALSERVICES.IGN.POI.ENSEIGNEMENTMATERNELLE)
2. the layers are freezed, no request are launched
3. in the dev panel console an error is throwed (Extent.js:340) :

> Uncaught (in promise) Error: unsupported mix
>     at t.value (Extent.js:340)
>     at LayeredMaterialNodeProcessing.js:178
>     at Array.map (<anonymous>)
>     at LayeredMaterialNodeProcessing.js:177

**Comment by gchoqueux** [comment]
fixed in #1183
