### ISSUE TITLE
GeoJSON right hand rule question 

### ISSUE THREAD

**Issue by thomleysens** [iTowns/itowns#1182]
Hi, 

In order to identify the possible source(s) of a visual bug on iTowns when I load a GeoJSON (*via the FileSource method*), I would like to know if iTowns use only the 2008 standard or the 2016 standard or both regarding the GeoJSON and especially the right hand rule (*see below the 2016 standard*).  

```
3.1.6.  Polygon

   To specify a constraint specific to Polygons, it is useful to
   introduce the concept of a linear ring:

   o  A linear ring is a closed LineString with four or more positions.

   o  The first and last positions are equivalent, and they MUST contain
      identical values; their representation SHOULD also be identical.

   o  A linear ring is the boundary of a surface or the boundary of a
      hole in a surface.

   o  A linear ring MUST follow the right-hand rule with respect to the
      area it bounds, i.e., exterior rings are counterclockwise, and
      holes are clockwise.

   Note: the [GJ2008] specification did not discuss linear ring winding
   order.  For backwards compatibility, parsers SHOULD NOT reject
   Polygons that do not follow the right-hand rule.

   Though a linear ring is not explicitly represented as a GeoJSON
   geometry type, it leads to a canonical formulation of the Polygon
   geometry type definition as follows:

   o  For type "Polygon", the "coordinates" member MUST be an array of
      linear ring coordinate arrays.

   o  For Polygons with more than one of these rings, the first MUST be
      the exterior ring, and any others MUST be interior rings.  The
      exterior ring bounds the surface, and the interior rings (if
      present) bound holes within the surface.

3.1.7.  MultiPolygon

   For type "MultiPolygon", the "coordinates" member is an array of
   Polygon coordinate arrays.
```

(*Source: https://tools.ietf.org/html/rfc7946*)

I have a correct layer on QGIS, the validation of the geometry shows no error, and I have different warnings depending on the validator I use (*http://geojsonlint.com/* or *http://geojson.io/*). 

So depending on the standard my GeoJSON are valid or not but I don't know if iTowns accepts bot standards or only one of them. A better understanding of the iTowns behavior about GeoJSON polygons and multipolygons could help me.

**Comment by zarov** [comment]
> A linear ring MUST follow the right-hand rule with respect to the
> area it bounds, i.e., exterior rings are counterclockwise, and
> holes are clockwise.

I'm pretty sure this isn't taken into account, so to me we follow only the 2008 spec.

Could you share your usecase or maybe a screenshot so we can help you on this ? (or by email at `adrien dot berthet at ign dot fr` if this is sensitive)

**Comment by thomleysens** [comment]
Hi,

Thanks for your answer. You can see the GeoJSON I use on this [Umap map](https://umap.openstreetmap.fr/fr/map/carte-sans-nom_348158#13/45.7571/4.8553) (*maybe I do not correctly verify the geometry or the construction of the GeoJSON*):
- MultiPolygon with holes 
- 2008 standard
- EPSG:3946

When I use the geometry validity tool on QGIS with this file I get no error:
```
Traitement de l'algorithme…
Démarrage de l'algorithme 'Vérifier la validité'…

Exécution terminée en 0.46 secondes
Résultats:
{'ERROR_COUNT': 0,
'ERROR_OUTPUT': 'output_52bc341a_97e8_40c4_9e3f_26badc120829',
'INVALID_COUNT': 0,
'INVALID_OUTPUT': 'output_6e656020_3697_4902_b713_abdf9ba57f44',
'VALID_COUNT': 1,
'VALID_OUTPUT': 'output_001afb3c_03bd_4c6a_911c_c96e3756a058'}

Chargement des couches de résultat
Algorithme 'Vérifier la validité' terminé
```
On iTowns, I got some good results but also some big weird polygons (*see the pink layer on the following image from [this another issue](https://github.com/iTowns/itowns/issues/1179)*):
(![image](https://camo.githubusercontent.com/a8e2add0781671634927f5f18e956cb74c69b47f/68747470733a2f2f692e696d6775722e636f6d2f3852506d6155572e706e67)

Tell me if you need more explanations or if this is still not really clear.

**Comment by zarov** [comment]
From what I tested from the umap you linked, iTowns is reading it correctly: it is the transformation to meshes that cause problems here.

Concerning the winding order, I still have trouble to understand it (I can't find a simple explanation). If you have an idea on how to implement simply, I think you can tweak things [here](https://github.com/iTowns/itowns/blob/master/src/Parser/GeoJsonParser.js#L33-L44) and submit the appropriate PR. Otherwise I'll take note of it, but I don't know when it will be done.

Concerning visuals artefacts, let's keep it in the other issue I didn't see ;)

**Comment by thomleysens** [comment]
Ok thanks. 

I don't know if I can manage to change something in [here](https://github.com/iTowns/itowns/blob/master/src/Parser/GeoJsonParser.js#L33-L44) but I can, at least, take a look and see what I can do. ;-) 

In order to have a clearer idea of the situation, when you say: ```Otherwise I'll take note of it, but I don't know when it will be done```, do you have a milestone in mind or projections (*weeks, months, ...*) ?

**Comment by zarov** [comment]
> do you have a milestone in mind or projections (weeks, months, ...) ?

As it is currently summer, I would say do not expect it until fall.

**Comment by thomleysens** [comment]
Ok, thanks for this precision. ;-)
