### ISSUE TITLE
Map distance of the Planar mode is not equal to the real distance

### ISSUE THREAD

**Issue by zDawnING** [iTowns/itowns#1184]
## Environment
* Version used: 2.12.0
* Browser Name and version: Chrome 75.0.3770.142
* Operating System: Window 7

## Context

I want Google Map source to load into the Planar view and  add a distance measurement tool. What puzzles me is that the map distance is not equal to the real distance and differences in different latitudes. 
In contrast to the Globe view, I found that the map distance is equal to the real distance.
So I want to ask if this is a bug? Or is it wrong with my usage? 
I can not continue to develop follow-up functions by this problem. Can you fix it or provide 
me some suggestions for fixing it?

## Steps to Reproduce (for bugs)

Sample code:
``` javascript
var extent = new itowns.Extent(
                'EPSG:3857',
                -20037508.342789244, 20037508.342789244,
                -20037508.342789244, 20037508.342789244);
var viewerDiv = document.getElementById('viewerDiv');
var view = new itowns.PlanarView(viewerDiv, extent, { disableSkirt: true, maxSubdivisionLevel: 20 });
var googleSource = new itowns.TMSSource({
                isInverted: true,
                extent,
                format: 'image/png',
                url: 'http://www.google.cn/maps/vt?lyrs=s@716,h@245000000&gl=CN&x=${x}&y=${y}&z=${z}',
                attribution: {
                    name: 'GoogleMap',
                    url: 'http://www.google.cn',
                },
                tileMatrixSet: 'PM',
            });
var googleLayer = new itowns.ColorLayer('Google', {
                updateStrategy: {
                    type: itowns.STRATEGY_DICHOTOMY,
                },
                source: googleSource,
            });

            view.addLayer(googleLayer);

            view.notifyChange();
```
The distance measurement tool is calculated using Threejs' Vector3 distanceTo method.

## Expected Behavior

For example, I choose a specific building to measure. 
Google Map
![google](https://zdawning.github.io/MapTools/problem_sc/google_map.png)
[map link](http://www.google.cn/maps/@31.1506667,121.8054628,906m/data=!3m1!1e3)

## Actual Behavior

In Itowns
![itowns](https://zdawning.github.io/MapTools/problem_sc/itowns_google_source.png)
Planar Mode:
![planar](https://zdawning.github.io/MapTools/problem_sc/planar_mode_dis.png)
In this mode,  the deviation of the measured distance is too large and differences in different latitudes.
So, I can not set a relatively accurate building to match the tile.
Globe Mode:
![globe](https://zdawning.github.io/MapTools/problem_sc/globe_mode_dis.png)
Although the distance test in this mode is also somewhat inaccurate, it is an acceptable range.

## Test Demo
[planar](https://zdawning.github.io/MapTools/orthographic.html)
[globe](https://zdawning.github.io/MapTools/globe.html)

**Comment by zarov** [comment]
Can you provide a case with how you measure something, what you obtain and what you should be obtaining ? I know we have some problems with this in the Globe view, but I don't know about Planar. Thanks !

**Comment by zDawnING** [comment]
> Can you provide a case with how you measure something, what you obtain and what you should be obtaining ? I know we have some problems with this in the Globe view, but I don't know about Planar. Thanks !

Thanks for your reply, I have updated the content of the issue.

**Comment by zarov** [comment]
Thanks for this precise update ! 

Concerning the globe, I do find too relatively similar measurement. The inaccuracy may be caused by #855 but as you don't use an `ElevationLayer` here I am not sure. Maybe that is the case in fact, you are not using elevation.

Concerning the planar, I took a look at it but I can't seem to find what is wrong here. I'll come back to it next week !

**Comment by zarov** [comment]
So I found that modifying the extent of the view solves the problem: if you try something like `var extent = new itowns.Extent('EPSG:3857', -10e6, 10e6, -10e6, 10e6);` you get shorter distance when you measure. So maybe check that you extent is correct. 

However this might still be a bug on how we size the tiles (as the projection used here is only going from `85.06` to `-85.06` north-south, so no "complete" planet), so we'll look a bit more into that.

**Comment by zDawnING** [comment]
> So I found that modifying the extent of the view solves the problem: if you try something like `var extent = new itowns.Extent('EPSG:3857', -10e6, 10e6, -10e6, 10e6);` you get shorter distance when you measure. So maybe check that you extent is correct.
> 
> However this might still be a bug on how we size the tiles (as the projection used here is only going from `85.06` to `-85.06` north-south, so no "complete" planet), so we'll look a bit more into that.

I have tried to modify the extent, maybe it can solves the distance problem in specify latitude,  but there are some reasons why this is not feasible.

1. Measured distances are inconsistent at different latitudes.
2. The result of the Coordinates transformation position does not match the correct tile position.

In order to temporarily deal with this problem, I sample the actual distance for each location where the building model needs to be located, and then scale the corresponding ratio to the PlanarLayer.

I will continue to pay attention to the solution of this bug, I sincerely hope that this problem can be solved. Thank you for your help.

**Comment by gchoqueux** [comment]
In your case, your create planar viewer in  'EPSG:3857' ( cylindrical map projection ).
If your pick in this projection, the Vector3 is in 'EPSG:3857' (which doesn't correspond to reality).
If you want the real measure, it's necessary to convert  in 'EPSG:4978'.

```js
// declare before function
const c1 = new itowns.Coordinates('EPSG:4326', 0, 0, 0);
const c2 = new itowns.Coordinates('EPSG:4326', 0, 0, 0);

function handleClickPoint(event) {
    if(!this.enabled) return;
//...
```

```js
 // compute distance
// convert Vector3  'EPSG:3857' to Vector3  'EPSG:3857' to 'EPSG:4978'
c1.setFromVector3(this.startVec3);
c2.setFromVector3(this.endVec3);
c1.crs = 'EPSG:3857';
c2.crs = 'EPSG:3857';
c1.as('EPSG:4978', c1).toVector3(this.startVec3);
c2.as('EPSG:4978', c2).toVector3(this.endVec3);

let distance = computeDistance(this.startVec3, this.endVec3);          
```

**Comment by zDawnING** [comment]
> In your case, your create planar viewer in 'EPSG:3857' ( cylindrical map projection ).
> If your pick in this projection, the Vector3 is in 'EPSG:3857' (which doesn't correspond to reality).
> If you want the real measure, it's necessary to convert in 'EPSG:4978'.
> 
> ```js
> // declare before function
> const c1 = new itowns.Coordinates('EPSG:4326', 0, 0, 0);
> const c2 = new itowns.Coordinates('EPSG:4326', 0, 0, 0);
> 
> function handleClickPoint(event) {
>     if(!this.enabled) return;
> //...
> ```
> 
> ```js
>  // compute distance
> // convert Vector3  'EPSG:3857' to Vector3  'EPSG:3857' to 'EPSG:4978'
> c1.setFromVector3(this.startVec3);
> c2.setFromVector3(this.endVec3);
> c1.crs = 'EPSG:3857';
> c2.crs = 'EPSG:3857';
> c1.as('EPSG:4978', c1).toVector3(this.startVec3);
> c2.as('EPSG:4978', c2).toVector3(this.endVec3);
> 
> let distance = computeDistance(this.startVec3, this.endVec3);          
> ```

According to your code I tried it. The distance measurement in the planar mode is close to real
distance. I would like to express my gratitude. 

Although the measurement of the distance is correct by converting to EPSG: 4978, I have a few more confusing questions to consult.

1. I used Vector3 to create some buildings in GlobeView (or 3dtile from Cesium), and the building can  match the tile map  under the EPSG:3857 projection. At this time I put these buildings in the PlanarView,  so the size of these buildings can't correspond to the tiles. 
Is there a way to convert Planar's tile projection from EPSG:4978 to EPSG:3857, so I don't need to convert the buildings that have been created on GlobeView. Especially for 3dtile, if there is a scaling, it will cause a lot of problems.

2. I don't know much about WebGIS. I would like to ask why GlobeView tile map projection uses EPSG: 3857, and PlanarView tile map projection uses EPSG: 4978. I only know the 3857 latitude range (-85.06, 85.06), the 4978 is (-90,90).  I am very interested and want to learn more about it, but I didn't find the right information. Can you briefly describe it or provide some reference links for me? 
Thank you!!  (๑′ᴗ‵๑)

**Comment by gchoqueux** [comment]
> I used Vector3 to create some buildings in GlobeView (or 3dtile from Cesium), and the building can match the tile map under the EPSG:3857 projection. At this time I put these buildings in the PlanarView, so the size of these buildings can't correspond to the tiles.
Is there a way to convert Planar's tile projection from EPSG:4978 to EPSG:3857, so I don't need to convert the buildings that have been created on GlobeView. Especially for 3dtile, if there is a scaling, it will cause a lot of problems.

You could use `Coordinates` to convert all Vector3 from `EPSG:4978` to  `EPSG:3857`

```js
// vector to convert
const vector4978 = new THREE.Vector3(....);
// vector target 
const vector3857 = new THREE.Vector3();

// instance coordinates
const coord4978 = new itowns.Coordinates('EPSG:4978',...);
// Copy values
const coord4978.setFromVector3(vector4978);
// convert coordinates
const coord3857 = coord4978.as('EPSG:3857');

// copy to vector target
coord3857.toVector3(vector3857);
```

> I don't know much about WebGIS. I would like to ask why GlobeView tile map projection uses EPSG: 3857, and PlanarView tile map projection uses EPSG: 4978. I only know the 3857 latitude range (-85.06, 85.06), the 4978 is (-90,90). I am very interested and want to learn more about it, but I didn't find the right information. Can you briefly describe it or provide some reference links for me?

`GlobeView` raster projection are [`EPSG: 3857`](https://epsg.io/3857) or [`EPSG: 4326`](https://epsg.io/4326).

`EPSG: 3857` it's pseudo mercator, the unit isn't `degree` but `Meter`. (https://en.wikipedia.org/wiki/Web_Mercator_projection)
`EPSG: 4326` is long/lat  in `degree` ([2D X/Y projection in WGS84](https://en.wikipedia.org/wiki/World_Geodetic_System)).

Warning, [`EPSG: 4978` ](https://epsg.io/4978) it's not raster projection because it's 3d geocentric cartesian coordinate system  in meter.  ([3D X/Y/Z  WGS84](https://en.wikipedia.org/wiki/World_Geodetic_System#A_new_World_Geodetic_System:_WGS_84)).

>  PlanarView tile map projection uses EPSG: 4978

 PlanarView doesn't  use `EPSG: 4978` but [projection extent parameter](https://github.com/iTowns/itowns/blob/master/examples/view_25d_map.html#L44) when you [instance the viewer](https://github.com/iTowns/itowns/blob/master/examples/view_25d_map.html#L53).

**Comment by zDawnING** [comment]
Thank you for your reply. I have learned a lot from your one-by-one answer. I would like to express my heartfelt thanks.

From your answer, I understand that this question should not be a bug, to be precise is a problem of improper use. Just provide the correct instructions for using it.

So this question can already change the state.  (ﾉﾟ▽ﾟ)ﾉ
