### ISSUE TITLE
Develop Globe.getCurrentAltitude(longitude, latitude)

### ISSUE THREAD

**Issue by gchoqueux** [iTowns/itowns#119]
This function returns altitude of the current MNT displayed.

**Comment by qdnguyen** [comment]
I need also this function to get alti for my wfs data #115 

![sans titre](https://cloud.githubusercontent.com/assets/3224540/17402654/9f04485a-5a54-11e6-97f7-003779769be4.png)

**Comment by gchoqueux** [comment]
move in #118
