### ISSUE TITLE
Gap between tiles in planar mode

### ISSUE THREAD

**Issue by OlegYarko** [iTowns/itowns#1199]
Hello ! 
## Steps to Reproduce  

1. Open http://www.itowns-project.org/itowns/examples/planar.html
2. Zoom in

How can I fix it?

![1](https://user-images.githubusercontent.com/33403994/62622814-f95d1180-b927-11e9-8458-cf82decff68d.PNG)

**Comment by gchoqueux** [comment]
There is a option to remove tile skirt, if you want add skirt, remove `disableSkirt` option.
```js
view = new itowns.PlanarView(viewerDiv, extent);
```

**Comment by OlegYarko** [comment]
thank you!
