### ISSUE TITLE
Questions and issues on Vector Tiles

### ISSUE THREAD

**Issue by thomleysens** [iTowns/itowns#1213]
## Your Environment

* Version used: master
* Browser Name and version: Firefox Quantum 68.0 (64 bits) 
* Operating System and version (desktop or mobile): Ubuntu 18.04.2 LTS 64 bits 

## Context

We actually try to use Vector Tiles to avoid the visual glitches of [issue 1179 ](https://github.com/iTowns/itowns/issues/1179) and to test the possibilities. 

Some tools and examples are already available in iTows:
* [VectorTilesParser](https://github.com/iTowns/itowns/blob/a9a4951ecb69866489e72748ef99658130c24d17/src/Parser/VectorTileParser.js)
* [Example in test file](https://github.com/iTowns/itowns/blob/f439b2df2976126005f3895e2d9c225a4df6a9ee/test/unit/vectortiles.js)
* [Vector tiles 3D example](http://www.itowns-project.org/itowns/examples/index.html#vector_tile_raster_3d)
* [Vector tiles 2D example](http://www.itowns-project.org/itowns/examples/index.html#vector_tile_raster_2d)

## Issues
When we use these tools and examples, some problems appear:
* Glitches on 2D and 3D examples (*see below for example on [Vector tiles 2D example](http://www.itowns-project.org/itowns/examples/index.html#vector_tile_raster_2d), zoom on Lyon*)
![vector_tiles_2D_pb](https://user-images.githubusercontent.com/37185740/64013816-f1f0e880-cb20-11e9-9d60-d82f32fdbbdd.png)
* Style seems to be not correctly applied on [Vector tiles 3D example](http://www.itowns-project.org/itowns/examples/index.html#vector_tile_raster_3d). The source of the style doesn't change (```https://raw.githubusercontent.com/Oslandia/postile-openmaptiles/master/style.json```) and the code used seems to be very similar, but the rendering is different
* When we try the Vector tiles 3D example locally with other style [sources](https://openmaptiles.org/styles/), it doesn't seem to work although it works on 2D example.
* When we try to change the source of the data (*to switch to our local OpenMapTiles local server*), there is a rendering but the style is not correctly applied and we got some errors (*404 for some tiles and non-coherent result*) and glitches (*see screenshot below*).
![vector_tiles_3D_pb](https://user-images.githubusercontent.com/37185740/64013825-fa492380-cb20-11e9-8870-f77be9cf4a6b.png). 

## Questions

* Is it normal because the Vector Tiles management and addition are still under development ? 
* If not, do you know what could be the problem ?

**Comment by gchoqueux** [comment]
> Glitches on 2D and 3D examples (see below for example on Vector tiles 2D example, zoom on Lyon)

I work to fix it. (planned to [2.16.0](https://github.com/iTowns/itowns/milestone/17))

> Style seems to be not correctly applied on Vector tiles 3D example.

Remove `fx` [options, (click here)](https://github.com/iTowns/itowns/blob/master/examples/vector_tile_raster_3d.html#L94)

> When we try the Vector tiles 3D example locally with other style sources, it doesn't seem to work although it works on 2D example.

Could you link style files? to try it

> When we try to change the source of the data (to switch to our local OpenMapTiles local server), there is a rendering but the style is not correctly applied and we got some errors (404 for some tiles and non-coherent result) and glitches (see screenshot below).

Actually, I work on this bug when tiles aren't loaded.  (planned to [2.16.0](https://github.com/iTowns/itowns/milestone/17))
Apparently your tile, zoom 10, row 522 and col 364, doesn't exist on your server, isn't it?

**Comment by gchoqueux** [comment]
can you confirm that there are no longer these issues?

**Comment by thomleysens** [comment]
Hi, sorry for my absence of a response for your [questions and your help](https://github.com/iTowns/itowns/issues/1213#issuecomment-529375389).  

Recently I made some new tests with vector tiles, based on master branch (*commit cd43854107b6f274d702bd3c66328776e2376e10, Wed Nov 6 11:06:06 2019 +0100*). 
No glitches, no issues. 

Thanks. And again sorry for my absence of a response.
