### ISSUE TITLE
ShaderMaterial can not display on the map tiles

### ISSUE THREAD

**Issue by zDawnING** [iTowns/itowns#1214]
## Environment
* Version used: 2.12.0
* Browser Name and version: Chrome 75.0.3770.142
* Operating System: Window 7

## Context

I want to add some shaderMaterial building on the map tiles. But the result is that they can not display on the map. Materials that can be loaded properly are only basic materials provided by threejs and so on. After my tests, ShaderMaterial and RawShaderMaterial all have this problem, and the phenomenon shows that the map tiles shader has some problems effect on the custom shader. How do I configure my custom shader to make sure it works?

## Steps to Reproduce (for bugs)
Sample Code:
``` javascript
var shaderMaterial = new itowns.THREE.ShaderMaterial({
                vertexShader: `
                precision highp float;
                void main(){
                    gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
                }
                `,
                fragmentShader:`
                precision highp float;
                void main(){
                    gl_FragColor = vec4(vec3(1.0, 0.0, 0.0), 1.0);
                }
                `
            })
```

## Actual Behavior
I think this problem is the same in both the Globe view and the Planar view, but in order to better distinguish the source of the problem, I tried both.

In Globe View:
![globe](https://zdawning.github.io/MapTools/problem_sc/globe_shader_material.png)
[Demo](https://zdawning.github.io/MapTools/shader_material/globe.html)

In Planar View:
![planar](https://zdawning.github.io/MapTools/problem_sc/planar_shader_material.png)
[Demo](https://zdawning.github.io/MapTools/shader_material/orthographic.html)

**Comment by gchoqueux** [comment]
Yes, it's because we use log depth buffer.
Whan you write your shader, it's necessary to add 

- in fragment file ([see example](https://github.com/iTowns/itowns/blob/master/src/Renderer/Shader/ProjectiveTextureFS.glsl))
    - `#include <logdepthbuf_pars_fragment>` on the file beginning 
    - ` #include <logdepthbuf_fragment> ` in `main()` beginning 

- in vertex file ([see example](https://github.com/iTowns/itowns/blob/master/src/Renderer/Shader/TileVS.glsl))
    - `#include <logdepthbuf_pars_vertex>` on the file beginning 
    - ` #include <logdepthbuf_vertex> ` in `main()` beginning
