### ISSUE TITLE
Mouse wheel zoom should zoom to cursor position, not center of screen

### ISSUE THREAD

**Issue by crubier** [iTowns/itowns#1222]
All is in the title, when zooming, the camera should zoom into the cursor position instead of zooming to the center of the screen.

We are considering moving from cesium to itowns, but this (and a few other bugs) are preventing us from doing so.

**Comment by gchoqueux** [comment]
Thank you for your interest in itowns.

We want to improve navigation. We will give a planning date for this feature.

**Comment by jailln** [comment]
done in #2041
