### ISSUE TITLE
Change globe color

### ISSUE THREAD

**Issue by OlegYarko** [iTowns/itowns#1224]
Hello!
Is there a way to change the color of the globe?
![earth](https://user-images.githubusercontent.com/33403994/64485739-d7a7c080-d22c-11e9-8c4a-cef653bf593d.PNG)

**Comment by zarov** [comment]
Yes there is one way, but not a really pretty one:
```js
view.tileLayer.object3d.traverse((tile) => { 
	if (tile.isTileMesh) tile.material.diffuse = new THREE.Color(0x000000);
});
```

The value is "hardcoded" [here](https://github.com/iTowns/itowns/blob/master/src/Renderer/LayeredMaterial.js#L134), but it could be a great addition to be able to specify it at the creation of the globe for example.

**Comment by OlegYarko** [comment]
Thank you!
