### ISSUE TITLE
Choose new name for Class Layer

### ISSUE THREAD

**Issue by gchoqueux** [iTowns/itowns#124]
Choose new name for Class Layer

**Comment by peppsac** [comment]
This is my understanding of *Layer*:

A *Layer* is used to display data sources.
Currently we only support *Layers* that are geometries + textures|colors, e.g:
* globe (tilemesh + layerematerial)
* point cloud
* mobilemapping or 360 panorama
* buildings

Geometries, textures and colors can be data layers (wmts, geojson, etc) or computed by itowns (tilemesh)

Some *Layers* depends on other *Layers* (e.g: buildings may depend on globe to get accurate vertical positionning).

A `Scene` is composed of `N` (>=1) of *Layers*.

**Comment by peppsac** [comment]
Here's an example from OpenLayers:
```js
  new ol.Map({
    layers: [
      new ol.layer.Tile({source: new ol.source.OSM()})
    ],
    view: new ol.View({
      center: [0, 0],
      zoom: 2
    }),
    target: 'map'
  });
```

They only support 2D so their API can be simpler (textures are always mapped to a 2D plane).

**Comment by gchoqueux** [comment]
move in #217
