### ISSUE TITLE
GlobeView light not working

### ISSUE THREAD

**Issue by dataangel** [iTowns/itowns#1247]
![QQ图片20191022135632](https://user-images.githubusercontent.com/587849/67262037-de854c80-f4d5-11e9-8977-02daada0e2ce.png)

**Comment by dataangel** [comment]
a

**Comment by zarov** [comment]
Hello, please provide a better explanation so we can understand the issue you encountered.

**Comment by dataangel** [comment]
OK img
![QQ图片20191023012535](https://user-images.githubusercontent.com/587849/67312644-45d1e980-f534-11e9-824e-19e9ff8b32a8.png)
error img
![QQ图片20191023012633](https://user-images.githubusercontent.com/587849/67312682-52eed880-f534-11e9-9880-048d45e5af25.png)
![QQ图片20191023013158](https://user-images.githubusercontent.com/587849/67313083-f213d000-f534-11e9-848e-3241ba4ce95e.png)

**Comment by dataangel** [comment]
hello

**Comment by gchoqueux** [comment]
Hello @dataangel 
The lighting on globe isn't supported. We plan to add this feature, but we can't set a date yet.
