### ISSUE TITLE
Add vectorTile layer only with the styleUrl parameter

### ISSUE THREAD

**Issue by elias75015** [iTowns/itowns#1251]
With itowns, to add a vectorTile Layer, the user must firstly parse the style.json, then pass the serviceUrl (.pbf) : 

```js
itowns.Fetcher.json('style.json').then(function (style) {
var mvtSource = new itowns MVTSource() {
    url : layerUrl.pbf
}

var vectorTileLayer = new itowns ColorLayer ('MVT', 
{
    source : mvtSource
})

return itowns.addlayer(vectorTileLayer)
})
```

The mapbox spec says (:lying_face: ) that the .pbf has to be accessible in the style.json. If not, it is in the metadata.json, whose url is accessible in the style.json.

The idea is to simplify the adding of vectorTile Layer with itowns, by adding the possibilty to only give the styleUrl parameter. Then, iTowns could retrieve the .pbf by himself and add the layer to the globe.

Something like : 

```js
var mvtSource = new itowns MVTSource() {
    style : style.json
}

// the .pbf is retrieved in the style.json
// the mvtSource object has the .pbf
var vectorTileLayer = new itowns ColorLayer ('MVT', 
{
    source : mvtSource
})

itowns.addlayer(vectorTileLayer)
```

**Comment by gchoqueux** [comment]
seeing #1256

**Comment by elias75015** [comment]
Works perfectly, thanks !
