### ISSUE TITLE
Support for EPSG:3857 / WMTS:PM elevation sources

### ISSUE THREAD

**Issue by BossensM** [iTowns/itowns#1252]
When creating an ElevationLayer with a TMS Source in projection EPSG:3857, the following error is returned:

_Only WMTS:WGS84 tileMatrixSet is currently supported for elevation layers._

What is the reason WMTS:PM / EPSG:3857 is not supported for ElevationLayer, but is supported for ColorLayer? Would be great if somebody could provide some background on this so I could look into making this compatible.

**Comment by gchoqueux** [comment]
Effectively, `ElevationLayer` isn't supported with `GlobeView`, but is supported with `PlanarView`.
The reason comes from an old constraint but itowns' evolutions will allow to correct this default.

**Comment by BossensM** [comment]
Ok Thanks ! I got it to work with the PlanarView indeed.
