### ISSUE TITLE
Can this library use mapbox api?

### ISSUE THREAD

**Issue by rakuda-daraku** [iTowns/itowns#1259]
Can this library use mapbox api?
I wanted to show mapbox style but couldn't

I'm not good at English, so I'm sorry if it's strange.

**Comment by zarov** [comment]
If you are talking about Vector tiles, the format specified by mapbox, yes, iTowns partially supports it. You can see it in action [here](http://www.itowns-project.org/itowns/examples/#vector_tile_raster_3d) and [here](http://www.itowns-project.org/itowns/examples/#vector_tile_raster_2d). 

There is still some parts of the specification we don't support yet, but we are currently developing it.

**Comment by rakuda-daraku** [comment]
Thank you for your answer.

I understood why binary vector tiles created with OpenMapTiles and Mapbox API could not be displayed correctly.
