### ISSUE TITLE
Create globeView with an advanced center object

### ISSUE THREAD

**Issue by elias75015** [iTowns/itowns#1263]
Actually, to create the view we use a position on globe which is an simple object with lon, lat, altitude : 

```
var positionOnGlobe = { longitude: 0.089, latitude: 42.8989, altitude: 80000 }; 
var view = new itowns.GlobeView(viewerDiv, positionOnGlobe);
```

Would it be possible to create the view with a CameraUtils.CameraTransformOptions object ?
This object takes a tilt, a heading, and other useful parameters to avoid multiple calls of functions to move the camera after globe initialization.

**Comment by gchoqueux** [comment]
yes, it's good idea!

**Comment by gchoqueux** [comment]
seeing #1273
