### ISSUE TITLE
Ortho image is not displayed

### ISSUE THREAD

**Issue by rakuda-daraku** [iTowns/itowns#1267]
Was the Ortho image used in this example unavailable?
Probably because of CORS

[Itowns - Globe](http://www.itowns-project.org/itowns/examples/index.html#view_3d_map)

- Execution environment
  - Mac OS: v 10.14.6
  - Chrome v 78.0.3904.108

**Comment by zarov** [comment]
There is no CORS example, but there is a large maintenance on some servers we are using, and they are unavailable until at least today evening (GMT+1), but expect working examples not until Monday unfortunately. Sorry for the inconvenience !

**Comment by zarov** [comment]
I'm reopening this issue and I'll close it when servers are back !

**Comment by rakuda-daraku** [comment]
Sorry for the late reply

I was able to confirm that it was displayed
