### ISSUE TITLE
Does the VectorTilesSource API support label display?

### ISSUE THREAD

**Issue by rakuda-daraku** [iTowns/itowns#1268]
Does the VectorTilesSource API support label display?
I couldn't find a way to display the label

If not, are there any future plans?

**Comment by zarov** [comment]
Not yet, but I'm working on it in another branch. I would say that you can expect a first version at the start of january 2020.

**Comment by rakuda-daraku** [comment]
Sorry for the late reply

Thank you for answering
Looking forward to the January 2020 version
