### ISSUE TITLE
Raycasting on ElevationLayer to get position coordinates

### ISSUE THREAD

**Issue by roelandwyns** [iTowns/itowns#1275]
Raycasting on ElevationLayer to get position coordinates

## Your Environment

* Version used: 2.16.0
* Browser Name and version: not applicable
* Operating System and version (desktop or mobile): not applicable

## Context
I'm looking for a good way to get the world-position when using the elevation layer. At the moment when raycasting, it will be raycasting on the planarlayer (which has only x,y position and no z). 
Visually the surface changes from a flat surface to a surface that has elevation, but it does not change anything to the three object, thus not allowing to get a specific position. 

Any idea's for a clean way to do this raycasting? Willing to contribute as well :)

**Comment by gchoqueux** [comment]
You use `THREE.Raycaster` on `PlanarLayer`?

A way to get world position and convert to other projection
```js
const worldPosition = new THREE.Vector();
view.getPickingPositionFromDepth(mouse, worldPosition);

const coordinate = new itowns.Coordinates(view.referenceCrs,0 ,0 ,0);
coordinates.setFromVector3(positionVector).as('EPSG:4326');
```

We plan to add soon (itowns `v2.18.0`) a method that returns a `Coordinates` in function of the position of the mouse.

**Comment by roelandwyns** [comment]
Great! Thank you! :) 

Had already looked into this function, but was doing something wrong in the View of Itowns that blocked the normal working of the function. 

Thank you very much 😄
