### ISSUE TITLE
Bug on Globe Control when Console opened 

### ISSUE THREAD

**Issue by nosy-b** [iTowns/itowns#1277]
Globe control is buggy when console is opened (Chrome linux & win tested)

When the camera is far (we see the whole globe) and try to turn it it 's buggy. It only happens when the Console is opened

Tested on Chrome on Linux and Win

**Comment by zarov** [comment]
This is a known bug, but we can't seem to find a solution to this. If someone can find the problem here, we'll be happy to fix it !

**Comment by mgermerie** [comment]
Fixed in #1704.
