### ISSUE TITLE
After removing ColorLayer memоry  is not cleared

### ISSUE THREAD

**Issue by OlegYarko** [iTowns/itowns#1278]
Hello !
I noticed that after removing  ColorLayer memory occupied by the application does not decrease. 
But  after adding  back the same layer it increases.  I'm not sure if this is a bug or feature , сould you suggest something to prevent such a memory leak?

![memory](https://user-images.githubusercontent.com/33403994/71257613-d06c7480-233c-11ea-919d-97f53e418e3d.gif)

Simple test   - use W to add layer, E - to remove 

 ```js
    let viewerDiv = document.getElementById('viewerDiv');
        let position = {
            longitude: 2.351323,
            latitude: 48.856712,
            altitude: 25000000
        };

        let view = new itowns.GlobeView(viewerDiv, position);

        let optionsGeoJsonParser = {
            buildExtent: true,
            crsIn: 'EPSG:4326',
            crsOut: view.tileLayer.extent.crs,
            mergeFeatures: true,
            withNormal: false,
            withAltitude: false,
        };

        var mapp = itowns.Fetcher.json('https://raw.githubusercontent.com/johan/world.geo.json/master/countries.geo.json');

        mapp.then(function _(geojson) {
            mappp = geojson;
            return itowns.GeoJsonParser.parse(geojson, optionsGeoJsonParser);
        }).then(function _(parsedData) {
            let ariegeSource = new itowns.FileSource({
                parsedData,
                zoom: {
                    min: 2,
                    max: 20
                }
            });
            let ariegeLayer = new itowns.ColorLayer('ariege', {
                name: 'ariege',
                transparent: true,
                style: {
                    fill: {
                        color: 'orange',
                        opacity: 0.5,
                    },
                    stroke: {
                        color: 'white',
                    },
                },
                source: ariegeSource,
            });
            return view.addLayer(ariegeLayer);
        });


        document.addEventListener('keydown', function(e) {
            if (e.key === 'w')
                mapp.then(function _(mappp) {
                    return itowns.GeoJsonParser.parse(mappp, optionsGeoJsonParser);
                }).then(function _(parsedData) {
                    let ariegeSource = new itowns.FileSource({
                        parsedData,
                        zoom: {
                            min: 2,
                            max: 20
                        }
                    });
                    let ariegeLayer = new itowns.ColorLayer('ariege', {
                        name: 'ariege',
                        transparent: true,
                        style: {
                            fill: {
                                color: 'orange',
                                opacity: 0.5,
                            },
                            stroke: {
                                color: 'white',
                            },
                        },
                        source: ariegeSource,
                    });
                    return view.addLayer(ariegeLayer);
                });
            view.notifyChange();

        });

        document.addEventListener('keydown', function(e) {
            console.log('e');
            if (e.key === 'e') {
                let xxx = view.getLayerById('ariege');
                xxx.delete();
                view.removeLayer('ariege');
                view.notifyChange;
            }

        });
```

**Comment by zarov** [comment]
Hello, and sorry for the late answer !

I could not reproduce your problem, but I'm on Linux so it might be different. I'll try to find a Windows computer here to test it.

Also, there was a release the day before you opened this issue, with some correction on the Cache management: maybe give it a try ?

**Comment by OlegYarko** [comment]
Thanks for the answer, but I think I found the problem :) 
I reduced the cache lifetime from 15 minutes to 30 seconds in this place

_Cache.js_ `    POLICIES: {
        INFINITE: Infinity,
        TEXTURE: 900000,
        ELEVATION: 900000,
    },
`

Perhaps I did not describe exactly how to repeat my experience - you need to add and remove a layer many times. Obviously, the cache from each layer lives longer than the layer itself, which leads to an increase in the memory occupied by the application.

Thus, this is not a bug but a feature :)

**Comment by zarov** [comment]
Indeed I tried it with a lot of add/remove, but it didn't quite show a change in memory. 

Anyway, it still needs some fix, as I'm not sure what the problem is. I'll try to find something this week, other than changing the cache lifetime.

**Comment by zarov** [comment]
So I think we identified the problem: a `THREE.Texture` has an `image` property, which is not correctly removed when disposing of the texture. As we create every time in `Feature2Texture` a `<canvas>`, it is not correctly removed from the memory, at least not until the `Cache` comes in. This is a classical detached DOM problem.

In theory, the new DOM shouldn't be created, as it is in the `Cache`, but as you declare a new `Source` every time, it is considered with a different cache key. One solution for you would be to move the `Source` declaration. But we are still looking in deleting the DOM correctly, so stay tuned !
