### ISSUE TITLE
Pan speed in Globe on different browsers

### ISSUE THREAD

**Issue by am2222** [iTowns/itowns#1281]
Hi, It is a few days that I have started to work with this library. I faced a different behavior in each browser when rotating globe. In Opera browser it seems the pan speed is higher than Chrome and a small pan results in confusion in controlling the globe.
Also Is there any ability to customize the controls? I guess in some 3d environment right-click+drag is for rotation and change in tilt, while in most of three.js related apps I have seen ctrl+left-click. It would be great to customize the camera controls and movements.

P.S: I just saw the same behavior in Chrome too.
## Your Environment

* Version used: Built the latest version from git
* Browser Name and version: Opera 65.0
* Operating System and version (desktop or mobile): Windows, Desktop
* Link to your project: Local

## Steps to Reproduce (for bugs)

check this example in browser 
```
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Simple globe with iTowns</title>
    <style>
        html { height: 100%; }
        body { margin: 0; overflow: hidden; height: 100%; }
        #viewerDiv { margin: auto; height: 100%; width: 100%; padding: 0; }
        canvas { display: block }
    </style>
</head>
<body>
<div id="viewerDiv"></div>
<script src="itowns/dist/itowns.js"></script>
<script type="text/javascript">
    var viewerDiv = document.getElementById('viewerDiv');
    var position = new itowns.Coordinates('EPSG:4326', 2.35, 48.8, 1e3);
    var view = new itowns.GlobeView(viewerDiv, position);

    // Create the source
    const tmsSource = new itowns.TMSSource({
        format: 'image/png',
        url: '	https://cartodb-basemaps-1.global.ssl.fastly.net/light_all/${z}/${x}/${y}.png',
        projection:'EPSG:3857',
        attribution: {
            name: 'OpenStreetMap',
            url: 'http://www.openstreetmap.org/',
        },
        tileMatrixSet: 'PM',
    });

    // Create the layer
    const colorLayer = new itowns.ColorLayer('OPENSM', {
        source: tmsSource,
    });

    // Add the layer
    view.addLayer(colorLayer);

    var mvtSource = new itowns.GeojsonVectorTilesSource({
                style: 'https://raw.githubusercontent.com/Oslandia/postile-openmaptiles/master/style.json',
                // eslint-disable-next-line no-template-curly-in-string
                url: 'http://127.0.0.1:3000/mvt/test/vector/${z}/${x}/${y}.json',
                attribution: {
                    name: 'OpenStreetMap',
                    url: 'http://www.openstreetmap.org/',
                },
                filter: function (layer) { return ['fill', 'line'].includes(layer.type) },
                zoom: {
                    min: 2,
                    max: 16,
                },
            });
            var mvtLayer = new itowns.ColorLayer('MVT', {
                // isValidData: isValidData,
                source: mvtSource,
                fx: 2.5,
            });
            view.addLayer(mvtLayer);

</script>
</body>

</html>

```

## Expected Behavior

Slower pan speed
## Actual Behavior

Very high pan speed
## Possible Cause/Fix/Solution

This might happen when windows size changes. for example when debugging window is open and ducked into main browser's window

**Comment by zarov** [comment]
Can this be related to #1277, occurring when the console is opened ?

As for the customization of the `GlobeControls`, it is indeed not great for the moment, even if there is a few parameters that can be changed ([see the documentation](http://www.itowns-project.org/itowns/docs/#api/Controls/GlobeControls) and by typing `view.controls` in the console). Personally, I wanted for a long time to add the possibility to specify the keys and buttons that we want to use, but as always, we have some other priorities to attend to.

What I can recommand you to do is fork the [current `GlobeControls`](https://github.com/iTowns/itowns/blob/master/src/Controls/GlobeControls.js) to suit your needs, and use it like this:
```js
// specify no controls when creating the view
var view = new itowns.GlobeView(viewerDiv, position, { noControls: true });
// declare manually the controls
view.controls = new ForkedGlobeControls(view, options...);
```

**Comment by am2222** [comment]
@zarov Thanks, Yes I guess it is the same bug. 
Thanks for the help
