### ISSUE TITLE
After removing GeometryLayer it still exists in view.scene

### ISSUE THREAD

**Issue by OlegYarko** [iTowns/itowns#1283]
Windows , iTowns 2.17.0
[source_file_geojson_3d.zip](https://github.com/iTowns/itowns/files/4022648/source_file_geojson_3d.zip)

![изображение](https://user-images.githubusercontent.com/33403994/71772343-7e3d6d00-2f52-11ea-80c0-9e848ddaafcb.png)

1.Run code
2.Open console
3.Press Space to remove Marne layer 
4.Type _view.scene.children_

**Comment by OlegYarko** [comment]
update :
after 32 cycles of adding / removing   layer  got warning
`c3DEngine.js:224 Too much three.js layers. Starting from now all of them will use layerMask = 31`

**Comment by zarov** [comment]
It is indeed not removing the children as intended. I'm working on a fix right now.

Concerning the `c3DEngine` warning, that is a thing that is badly implemented, as the layers counter is never decreased. I'm looking into a fix too.
