### ISSUE TITLE
Removing a layer before it is fully loaded causes an error

### ISSUE THREAD

**Issue by OlegYarko** [iTowns/itowns#1286]
Hello again )

Steps to reproduce 
1. Run code , open console / network / throttling and set 3G 
2. Reload and wait for first tiles to appear.
3. Press E to remove Ortho layer

![remove_layer gif](https://user-images.githubusercontent.com/33403994/72057728-85100b00-32d7-11ea-8232-5fcb59d1526b.gif)

[test.zip](https://github.com/iTowns/itowns/files/4039735/test.zip)

**Comment by zarov** [comment]
Thanks for finding this bug ! It seems we are missing some checks when processing data. I can see the quick fix to do, but I'll look into something more stable. If you have a nice solution don't hesitate to do a PR !

**Comment by OlegYarko** [comment]
I think I'm not ready to present a solution but  will look forward to yours :)

 -- offtopic -- 
I'm an artist not a programmer actually)  Mixing several layers  I create pictures like these :

![изображение](https://user-images.githubusercontent.com/33403994/72098347-f32fee80-3326-11ea-8ee4-78932a110a7e.png)
