### ISSUE TITLE
3dTilesExtensions Singleton

### ISSUE THREAD

**Issue by gchoqueux** [iTowns/itowns#1296]
If it is supposed to be a singleton, you can ditch the class to use a frozen Object like in `Cache`.

_Originally posted by @zarov in https://github.com/iTowns/itowns/pull/1288_

**Comment by mgermerie** [comment]
The complete 3d-tiles support is planned in the short term road map. We are currently studying possibilities in terms of libraries to enhance support (as mentioned in https://github.com/iTowns/itowns/discussions/1917).

**Comment by jailln** [comment]
Obsolete, deprecated implementation
