### ISSUE TITLE
Supported Color system

### ISSUE THREAD

**Issue by am2222** [iTowns/itowns#1300]
Hi, 
While I am comparing output of the same color between itowns and leaflet I see some differences in them, I think the reason is because of threejs's color system, what color system is recommended for itowns?
![3d](https://user-images.githubusercontent.com/4707503/72634697-0e06f200-3929-11ea-97a6-a2d7d534ddff.PNG)
![lulc](https://user-images.githubusercontent.com/4707503/72634698-0e9f8880-3929-11ea-8ae1-7c030ae0ddf1.PNG)
and this is the same color function which is used for both maps

```
function getColor(d) {
				return d == 1 ? chroma(0, 61, 0).hex() :
					d == 2 ? chroma(0, 99, 0).hex() :
					d == 3 ? chroma(20, 140, 61).hex() :
					d == 4 ? chroma(30, 171, 5).hex() :
					d == 5 ? chroma(92, 117, 43).hex() :
					d == 6 ? chroma(186, 212, 143).hex() :
					d == 7 ? chroma(179, 158, 43).hex() :
					d == 8 ? chroma(179, 138, 51).hex() :
					d == 9 ? chroma(156, 117, 84).hex() :
					d == 10 ? chroma(225, 207, 138).hex() :
					d == 11 ? chroma(107, 163, 138).hex() :
					d == 12 ? chroma(230, 174, 102).hex() :
					d == 13 ? chroma(220, 33, 38).hex() :
					d == 14 ? chroma(148, 156, 112).hex() :
					d == 15 ? chroma(255, 250, 255).hex() :
					d == 16 ? chroma(168, 171, 174).hex() :
					d == 17 ? chroma(76, 112, 163).hex() :
					"#fff";

			}
```

**Comment by zarov** [comment]
Methods used for drawing stuff on a `ColorLayer` (which I assume you are using) are all the one from `CanvasRenderingContext2D`, and for the color here it is using [`fillStyle`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/fillStyle). So in fact no, it isn't using the THREE.js color system, don't be mistaken by that !

However, if you are using a `GeometryLayer`, it is using it, but I doubt that is what you are doing ;)

Maybe here your color is missing a `#` to be valid ?

**Comment by zarov** [comment]
It also seems you have some depth issue (see the weird oceans for example), that might be related. You might need to enable hardware acceleration on your computer/browser. There are a few issues about this already (like #964 ), but we don't know how we can fix it on our side unfortunately.

**Comment by am2222** [comment]
Well I am using `ColorLayer` in this case, So the reason of the difference in colors is something else. I will try to double check the validation of the colors. But it seems the colors are valid since they are in the same spectrum, but for example both blue areas in leaflet and itowns are not rendered the same, 
Yes that is another issue that I have faced, I am developing on a VM which does not have any graphic card. So that can also be a reason, however I have seen the same thing on the android browser.

**Comment by jailln** [comment]
@am2222 Is this issue still relevant?

**Comment by am2222** [comment]
Hi @jailln thanks for the comment, I think it was because I was developing on a vm which could not use hardware acceleration.

We can close this topic.

Thanks!
