### ISSUE TITLE
Elevation gradient 

### ISSUE THREAD

**Issue by BossensM** [iTowns/itowns#1301]
Is it possible to display the elevation gradient of the terrain? This basically means, using the elevation of a vertex to define its color, based on a min/max range and gradient

**Comment by zarov** [comment]
Not 100% sure, but if you take a look into [`TileFS/VS`](https://github.com/iTowns/itowns/tree/master/src/Renderer/Shader) shaders, you should be able to add some `uniform` to help you perform this. You would also have to modify a few things in [`LayeredMaterial`](https://github.com/iTowns/itowns/blob/master/src/Renderer/LayeredMaterial.js), but nothing impossible. The only con here is the fact that you need to change the core of iTowns, it can't be done from outside.

**Comment by jailln** [comment]
Closing since @zarov provided a solution. Don't hesitate to reopen it if needed.
