### ISSUE TITLE
Performance improvement 

### ISSUE THREAD

**Issue by am2222** [iTowns/itowns#1302]
Hi, 
I was just exploring around and found this package which uses gpu for js functions, 
https://www.npmjs.com/package/gpu.js/v/2.6.0
I was thinking maybe it is possible to integrate it for rendering tiles and geometry related functions, probably a good impact on the performance.

**Comment by am2222** [comment]
here is an example of using gpu.js with leaflet canvas
https://observablehq.com/@rveciana/leaflet-gpu-js-canvas

**Comment by zarov** [comment]
Thanks for the share ! We'll take a look at it, maybe it could be used for coordinates conversion. Concerning rendering tiles, we already know what to do (hint: don't use the Canvas in `Feature2Texture`) but we terribly miss time to do it.

**Comment by am2222** [comment]
@zarov I think using GPU can help with the rendering as well as far as you are using Canvas, I have not seen anyone uses this library in their rendering to see how it can improve rendering performance but it might be good to try it, I actually tried to edit some parts of the code to be able to render using GPU canvas but could not make it work. 
May I ask if we should not use Canvas, what other option we have for drawing?

**Comment by zarov** [comment]
> I actually tried to edit some parts of the code to be able to render using GPU canvas but could not make it work.

Could you explain where did you try to use it ? I might take a look at it when I got some time. 

> May I ask if we should not use Canvas, what other option we have for drawing?

It would be to render it directly in WebGL, like Mapbox do for example (I'm talking for things like vector tiles, geojson, gpx here). It is faster to initialise (no drawing phase) and faster to update when moving the camera. However it implies spending quite some time on it before having something comparable of what we currently have (visually speaking), and as we are only two working on iTowns (comparing to a lot of people at Mapbox, or Cesium), we can't work on all things that needs to be done.

**Comment by am2222** [comment]
@zarov Thanks for your help,
I aimed to add it to this part:
https://github.com/iTowns/itowns/issues/1289#issuecomment-574471063
since I wanted to improve the rendering performance. 
I am not expert in js library development but If you think there is anything that I can help I would be happy to contribute.

**Comment by zarov** [comment]
> I aimed to add it to this part:

That could be a good idea, I'm curious to see the result if you try it ! And if it improves greatly those performance, it would be open for a PR directly on `Feature2Texture` of course ;)

> I am not expert in js library development but If you think there is anything that I can help I would be happy to contribute.

You already contributes by opening issues and sharing with us, and we thank you for that ! If you want to contribute in the development of the library, we are currently cleaning all the issues and re-tagging all of them, including the [good first issue](https://github.com/iTowns/itowns/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) one. And as I already said, please don't hesitate to open PR for little bug fixes or new features you think can benefit iTowns.

**Comment by am2222** [comment]
@zarov I am currently working on it, I hope I can make it work and see how it will effect on the performance.
thanks so much for your help. I'll try to see what I can do.
