### ISSUE TITLE
Update tiles on globe rotate

### ISSUE THREAD

**Issue by Chucky66** [iTowns/itowns#1311]
I want to implement globe rotation in real time using requestAnimationFrame loop. So my question is how can i redraw scene/update tiles on globe rotation, outside mouse events?

**Comment by zarov** [comment]
See [this example](http://www.itowns-project.org/itowns/examples/#misc_camera_animation). In it we are setting [a few waypoints to follow](https://github.com/iTowns/itowns/blob/master/examples/misc_camera_animation.html#L49-L58), we [animate it](https://github.com/iTowns/itowns/blob/master/examples/misc_camera_animation.html#L64-L68) and finally we [loop through it](https://github.com/iTowns/itowns/blob/master/examples/misc_camera_animation.html#L94)

**Comment by Chucky66** [comment]
Thanks for your reply but i'm afraid that's not what i'm looking for. I change globe rotation every frame (it can be done with different speed), by changing quaternion value. I don't want to transform the camera, just rotate the globe because there are other objects in the scene. And I can't get new coordinates to use CameraUtil's animateCameraToLookAtTarget(). I need to update tile when it get in camera's view or smth like this. 
That's what i get now on globe rotation.
![globe](https://user-images.githubusercontent.com/60619717/73739956-49425700-4758-11ea-89eb-d56121530196.JPG)

**Comment by zarov** [comment]
I see ! Without searching, I would say that you miss a `view.notifyChange()` call maybe ? Otherwise can you share some code to see what you are currently doing ? Thanks

**Comment by Chucky66** [comment]
I tried `view.notifyChange()` with different params with no result. The simplest way to rotate globe is to change a little GlobeView's constructor:
 
```
     constructor(viewerDiv, coordCarto, options = {}) {
        THREE.Object3D.DefaultUp.set(0, 0, 1);
        const scene = new THREE.Scene();
        const object3d = new THREE.Object3D();
        options.object3d = object3d;
        options.scene3D = scene;
        scene.add(object3d);
        // Setup View
        super('EPSG:4978', viewerDiv, options);

        ...
        
        setInterval(() => {
          tileLayer.object3d.rotateZ(0.003);
          this.notifyChange(this.camera);
        }, 20);
    }
```
Curiously enough that `tileLayer.object3d.rotateZ()` does't work with default object3d.

**Comment by zarov** [comment]
I don't know how the update of the tiles can be forced and done, maybe @gchoqueux can answer this question ?

> Curiously enough that tileLayer.object3d.rotateZ() does't work with default object3d.

Seems to work here with
```js
const z = () => {
    view.tileLayer.object3d.rotateZ(0.003);
    view.tileLayer.object3d.updateMatrixWorld();
    view.notifyChange();
    requestAnimationFrame(z);
};

requestAnimationFrame(z);
```

**Comment by Chucky66** [comment]
Thanks a lot for your help! Hope someone else can clarify this issue.
