### ISSUE TITLE
Feature and layer Style

### ISSUE THREAD

**Issue by gchoqueux** [iTowns/itowns#1318]
There isn't simple method to get `feature/featureCollection/layer Style`. 
It's necessary to improve the architecture and expose methods to obtain the `style`.

**Comment by zarov** [comment]
My suggestion:
- `FeatureCollection` has the master style
- `Feature` has its own style, with default values read from the `FeatureCollection` style
- same goes for `FeatureGeometry` which inherits from the style of `Feature` (and so `FeatureCollection`)

With this, only two things need to be done:
- add a `Style#clone()` method
- in the constructor of each of these types, add an option to initiate the style, `true` by default

Generally speaking, regarding these types, what we are also missing either a great tutorial concerning the creation of `FeatureCollection/Feature/FeatureGeometry`, or either a better API (it is too complicated to understand `bindNewGeometry/startSubGeometry/...` imho.

**Comment by am2222** [comment]
Can this approach is able to apply to the diffrent layers? such as vector tiles?

**Comment by zarov** [comment]
@am2222 what do you mean ?

**Comment by jailln** [comment]
Created #1924 and #1923 as followups of this issue. Closing
