### ISSUE TITLE
Feature2Mesh.convert and Altitute function option

### ISSUE THREAD

**Issue by gchoqueux** [iTowns/itowns#1330]
In `Feature2Mesh.convert`, it's possible to add callback to get altitude when mesh is built.

But this callback doesn't work the same way if we're building point, line or polygon.

It's necessary to unify the behaviours and in particular to be able to acquire the altitudes in the `properties`.

**Comment by zarov** [comment]
I think we should ditch the `Feature2Mesh.convert` callbacks, and use the `Style` instead.

**Comment by gchoqueux** [comment]
Yes, and move all the process in Features
