### ISSUE TITLE
Issue / difficulties with globe controls since 2.18.0

### ISSUE THREAD

**Issue by mthh** [iTowns/itowns#1333]
Hi and first, thanks for the great work !

## Your Environment

* Version used: 2.18.0
* Browser Name and version: Chromium (80.0.3987.87) & Firefox (73.0)
* Operating System and version (desktop or mobile): Linux 
* Link to your project: [https://github.com/mthh/example-dockpanel-itowns](https://github.com/mthh/example-dockpanel-itowns)

## Context

I'm currently using Itowns in combination with [Lumino](https://github.com/jupyterlab/lumino) (a library providing various components for building desktop-style web applications such as a tab-based layout - it's notably used for [Jupyter-lab](https://github.com/jupyterlab/jupyterlab) project).

Since the 2.18.0 release of Itowns, I'm having some troubles with the controls of the `GlobeView` when it's used in a tab from the aforementioned library (they call this functionality a `DockPanel`).

It's a bit hard to explain but when I'm doing a pan gesture on the globe while the `tilt` value is less than 89.5, the movement of the globe is slightly skewed (it's OK when the tilt is 89.5).
It gets worse when I set a tilt value away from 89.5 and in this case, depending on both the canvas size and the location clicked, the pan event might not move the globe at all.

This problem does not appear in version 2.17.0.

## Steps to Reproduce

1. Creating a new `GlobeView` inside one of the tab of a `DockPanel`. 
2. Changing the titl value from 89.5 to a lower value.
3. Moving the globe with the cursor.

As the first step involves a bit of code I have set up a repo with two examples :
- using itowns v. 2.17.0 : [web page](https://mthh.github.io/example-dockpanel-itowns/217/) / [source](https://github.com/mthh/example-dockpanel-itowns/tree/master/217)
- using itowns v. 2.18.0 : [web page](https://mthh.github.io/example-dockpanel-itowns/218/) / [source](https://github.com/mthh/example-dockpanel-itowns/tree/master/218)

These examples are based on the [`DockPanel` example](https://github.com/jupyterlab/lumino/tree/master/examples/example-dockpanel) from Lumino, and on examples from Itowns documentation.

## Comments

I'm missing something while moving from 2.17.0 to 2.18.0 ? (the code is the same in these two examples).

The 2.18.0 version and the globe controls seem to work on their own and maybe I just need to change some stuff in my code to adapt it to Itowns ?
I've been searching on my side without success so any help would be greatly appreciated !

**Comment by gchoqueux** [comment]
Thank you for your interest in itowns and to report this issue.

I confirm the bug, I try to fix it for 2.19.0.

**Comment by mthh** [comment]
OK, thanks for considering it !

**Comment by zarov** [comment]
@mthh your issue has been fixed in #1336. In the same time, I added a `View#resize()` method, so you can avoid what you are doing [here](https://github.com/mthh/example-dockpanel-itowns/blob/master/218/src/index.js#L156-L163).

**Comment by mthh** [comment]
Many thanks for this fix !

I was also going to ask about exposing a `resize` method, so, thanks for that too !
(I have to admit that I've been searching a bit, wondering if I wasn't doing it correctly, which explains the rather long and groping version you were pointing to in my example code!)

**Comment by zarov** [comment]
No problem, don't hesitate to ask if you don't find something !
