### ISSUE TITLE
Tiles of vectorTile Layers not correctly reloaded

### ISSUE THREAD

**Issue by elias75015** [iTowns/itowns#1334]
# Your Environment
Ubuntu 18
Chrome 80

## Context
On our map interface, buttons make user able to change the style of an already added vectorTileLayer.

Unfortunately, for the moment, the only way to do it is to remove the layer A with style X from the map, and to add again this layer A, but with the style Y.

The problem is that the already loaded tiles of the layer A with the original style X are not cleaned and are still displayed. 
Only tiles not loaded yet will be displayed with the selected Y style.

Cache problem ? 

NB : the layerID is the same, only the style changes.

## Steps to Reproduce (for bugs)
1. add a vectorTileLayer (layerId = A, style = X)
2. remove layer with layerId = A
3. add a vectorTileLayer (layerId = A, style = Y)

## Expected Behavior
The layer A is displayed with style Y only.

## Actual Behavior
The layer A is displayed with a mix of X style for the tiles already loaded before, and Y style for the new requested tiles.

Mix of "color" and "grey" styles : 
![Capture d’écran de 2020-02-28 15-15-25](https://user-images.githubusercontent.com/6764800/75556440-88ee1d00-5a3e-11ea-9044-854adabac5fb.png)

**Comment by gchoqueux** [comment]
Thanks to report this issue.
There are two problems: 
 * images cache isn't cleared.
 * styles cache  isn't cleared.

We try to fix it to 2.19.0!

**Comment by gchoqueux** [comment]
Fixed in #1335

**Comment by elias75015** [comment]
Unfortunately, it seems that the problem is not completely resolved by your fix. Few tiles of the previous style are still visible on the map when changing the style of a layer.

**Comment by gchoqueux** [comment]
You add a new `VectorTileSource` and a new `VectorTileLayer` ?

**Comment by elias75015** [comment]
Yes :)

**Comment by elias75015** [comment]
Finally, it's OK ! Thanks for your fix.
