### ISSUE TITLE
add an automatic publication of demo, doc and example on github.io

### ISSUE THREAD

**Issue by gmaillet** [iTowns/itowns#134]
using travis to automatically publish demo, doc and example on github.io when a new version pushed on master

**Comment by tbroyer** [comment]
FWIW, see https://github.com/google/dagger/blob/deb480ccc091a2ed22530107c4928c207a8260f5/.travis.yml (along with https://github.com/google/dagger/blob/deb480ccc091a2ed22530107c4928c207a8260f5/util/generate-latest-docs.sh) for an example (this is a Java project but you can get the idea)

They chose to put the credentials encyrpted in the `.travis.yml`, but maybe we could put them in Travis CI through their web interface instead.

**Comment by gmaillet** [comment]
what do you think about this solution: https://gist.github.com/domenic/ec8b0fc8ab45f39403dd

**Comment by tbroyer** [comment]
Sounds better (security-wise at least). Only thing I'd change would be to do it in an `after_success`: when the build is OK, then we deploy it; the `doCompile` in our case would be a) copy the output of webpack from `dist/` to the cloned `gh-pages` and b) generate the doc. BTW, that also means that a failed "deployment" won't mark the build as failed AFAIK
