### ISSUE TITLE
Not able to add pictures on top of the digital elevation model

### ISSUE THREAD

**Issue by Syn-crow** [iTowns/itowns#1347]
I have a .png image (which I generate with coordinates), I want to stick it on the elevation model in mountainous area. Also I want to add geotiff file and I didn't get the example to work ([http://www.itowns-project.org/itowns/docs/#api/Plugins/TIFFParser](http://www.itowns-project.org/itowns/docs/#api/Plugins/TIFFParser)).

**Comment by zarov** [comment]
Unfortunately, single images are not yet supported in iTowns, which is the case for your two files. The TIFF example on the website is using a pyramidal TIFF, not a single TIFF (equivalent to GeoTIFF here).

We don't have a view on when this will be implemented unfortunately, sorry about that.

**Comment by Syn-crow** [comment]
thanks anyway
