### ISSUE TITLE
DTM bug

### ISSUE THREAD

**Issue by nosy-b** [iTowns/itowns#137]
First time I see this bug:) Looks like the tile got the elevation of a another level. But the geometry is unlikely, it might be a bug in the wmts elevation tile itself.
![bug](https://cloud.githubusercontent.com/assets/158514/16650247/7ed98dd8-443d-11e6-8567-defd43524de9.jpg)

**Comment by gchoqueux** [comment]
How reproduce this bug?

If there's no more bug, close this issue please.

**Comment by gchoqueux** [comment]
@nosy-b 
How reproduce this bug?
Any news?

**Comment by nosy-b** [comment]
seems to never happen now
