### ISSUE TITLE
3dtiles material  issues

### ISSUE THREAD

**Issue by D-WPanda** [iTowns/itowns#1370]
**load 3dtiles has a  issues，failing to load material.** 
The 3dtiles httpurl is "http://earthsdk.com/v/last/Apps/assets/dayanta/tileset.json"

**Comment by gchoqueux** [comment]
Hello,

I try your 3dtiles url. I noticed 2 problems:

1.  There's points cloud with [quantized position](https://github.com/CesiumGS/3d-tiles/blob/master/specification/TileFormats/PointCloud/README.md#quantized-positions) but **iTowns doesn't support quantized position**. I could add quick support.

2. I check the the `gltf` embedded in your b3dm with [gltf validator](https://gltf.insimo.com/) there are 2 errors:
   * undeclared extension : Extension `KHR_materials_unlit` was not declared in `extensionsUsed`,  **it's the fail reason of material loading.**
   * Override of previously set bufferView target or usage.

The THREE.GltfLoader doesn't handle the error.

**Comment by mgermerie** [comment]
The complete 3d-tiles support is planned in the short term road map. We are currently studying possibilities in terms of libraries to enhance support (as mentioned in https://github.com/iTowns/itowns/discussions/1917).

**Comment by jailln** [comment]
Closing since the input dataset is not valid and there has been no response for 2 years, feel free to reopen if needed.
