### ISSUE TITLE
Intregrate Deepscan in Pull request checking

### ISSUE THREAD

**Issue by gchoqueux** [iTowns/itowns#1372]
How intregrate Deepscan in Pull request checking.

### Pull request checks:
* travis: unit and functional tests; 
* coveralls:  code coverage;

## Possible Solution

with weebhook : https://deepscan.io/docs/guides/get-started/analyzing-source-code#webhooks

**Comment by zarov** [comment]
What about using Github Actions ? https://github.com/iTowns/itowns/actions/new
