### ISSUE TITLE
Looking for a dev to hire 

### ISSUE THREAD

**Issue by LeoFlandin** [iTowns/itowns#1386]
## Looking for a dev to hire 

Our company is looking for a dev (or software company) to hire to build a wrapper around iTowns to add a level of abstraction and speed-up the integration process. 

Can I post here the specification ?

**Comment by gchoqueux** [comment]
Hello, Thank you for your interest in itowns.

We prefer that you post on itowns mailing lists
You can subscribe to the mailing lists here:
    Developer: https://lists.osgeo.org/mailman/listinfo/itowns-dev
    User: https://lists.osgeo.org/mailman/listinfo/itowns-user
