### ISSUE TITLE
 Feature2Color ?

### ISSUE THREAD

**Issue by manuamador** [iTowns/itowns#1390]
Possible, enhancement, exactly like the Feature2Mesh, I can't find a way to apply different fill colors, strokes and point appearance on features with a ColorLayer.
I have to filter the data and create a different Colorlayer for each type.
I may missing something, if not, I think it would be a great enhancement.

Thanks for this great framework.

**Comment by zarov** [comment]
I am not sure to understand the problem. Could you elaborate your usecase ?

To specify colors, strokes and filling, you can use [`Style`](http://www.itowns-project.org/itowns/docs/#api/Base/Style). If you append a `.style` property to each feature you got from the parser, it will be read when drawing the feature, without having to create several `ColorLayer`. Currently, there is no easy way to do this, but here is something you can try:
```js
const styles = {
  ...
  road: new Style(),
  forest: new Style(),
  ...
};

const source = new SomeSource({
  ...
  parser: (data, options) => {
    // hijack the parser
    itowns.GeojsonParser.parse(data, options).then((collection) => {
      // append a `style` property to each feature, given some criteria 
      collection.features.forEach((feature) => {
         if (feature.properties.type == 'road') feature.style = styles.road;
         else if (feature.properties.type == 'forest') feature.style = styles.forest;
      });
    });
  },
  ...
});
```

**Comment by manuamador** [comment]
Sorry  I am struggling with this, I am trying to add a style to each feature :
``` javascript

const stylesDomanialité = {
  Privé: new itowns.Style({
				fill: {
				  color: '#008000',
				  opacity: 0.7,
				},
				stroke: {
					color: '#008000',
				}
			}),
  Concédé: new itowns.Style({
				fill: {
				  color: '#ffa07a',
				  opacity: 0.7,
				},
				stroke: {
					color:'#ffa07a',
				}
			}),
  Mixte: new itowns.Style({
				fill: {
				  color: '#da70d6',
				  opacity: 0.7,
				},
				stroke: {
					color:'#da70d6',
				}
			}),
  Tiers: new itowns.Style({
				fill: {
				  color: '#666',
				  opacity: 0.5,
				},
				stroke: {
					color:'white',
				}
			}),
  Vide: new itowns.Style({
				fill: {
				  color: 'transparent',
				  opacity: 0,
				},
				stroke: {
					color:'white',
				}
			})
};


var optionsGeoJsonParser = {
			buildExtent: true,
			crsIn: 'EPSG:4326',
			crsOut: 'EPSG:4326',
			mergeFeatures: false,
			withNormal: false,
			withAltitude: false,
};

itowns.Fetcher.json('parcelles.geojson')
	.then(function _(geojson) {
		return itowns.GeoJsonParser.parse(geojson, optionsGeoJsonParser);}).then((collection) => {
		
		console.log(collection);
	  // append a `style` property to each feature, given some criteria 
	  collection.features.forEach((feature) => {
	  
	  //
		 if (feature.geometry[0].properties.PCM == 'P'|| feature.geometry[0].properties.PCM ==="PF") {feature.geometry[0].properties.style = stylesDomanialité.Privé;}
		 else if (feature.geometry[0].properties.PCM  == 'C'|| feature.geometry[0].properties.PCM  ==="CF"){ feature.geometry[0].properties.style = stylesDomanialité.Concédé;}
		 else if (feature.geometry[0].properties.PCM  == 'M'|| feature.geometry[0].properties.PCM  ==="MF"){ feature.geometry[0].properties.style = stylesDomanialité.Mixte;}
		 else if (feature.geometry[0].properties.PCM  == '2'|| feature.geometry[0].properties.PCM  ==="2F"){ feature.geometry[0].properties.style = stylesDomanialité.Tiers;}
		 else  {feature.geometry[0].properties.style = stylesDomanialité.Vide;}
	  })
	}).then(function _(parsedData) {
		var parcellessource = new itowns.FileSource({
			projection: 'EPSG:4326',
			parsedData,
			
			
		});

		var parcellesLayer = new itowns.ColorLayer('Parcelles', {
			name: 'Parcelles',
			//transparent: true,
			source: parcellessource,
		});

		return view.addLayer(parcellesLayer);
	}).then(FeatureToolTip.addLayer);
	
				
```
FileSource does not seem to work 	:
```
Error: url, fetchedData and parsedData are not set in
                FileSource; at least one needs to be present			
```
I am wondering if `feature.geometry[0].properties	` is th correct way to parse the collection...

Sorry for the noob question, I am just starting to use iTowns.

**Comment by zarov** [comment]
> FileSource does not seem to work :

You forgot a `return collection;` after all your `if`.

> I am wondering if feature.geometry[0].properties is th correct way to parse the collection...

You can read if from `feature.geometry[0].properties` if it suits your needs, but you'll need to set the style to `feature` if you want to make it work. 

> Sorry for the noob question, I am just starting to use iTowns.

No problem, we are happy to clarify things up, and it helps us identify what needs improvement in the documentation and all.

**Comment by manuamador** [comment]
Thanks a lot, it works.

The thing with Colorlayer is that applying a symbology is not as straigth forward as geometry layers beacause, there is no equivalent of Feature2mesh.
The second issue I had, coming from Leaflet is that the properties are parsed and added to the geometry key in each feature (feature.geometry[0].properties) that is not intuitive coming from leaflet or OL. But when you get it, it is quite easy :)

Thanks again.

**Comment by zarov** [comment]
> The thing with Colorlayer is that applying a symbology is not as straigth forward as geometry layers beacause, there is no equivalent of Feature2mesh.

`Feature2Mesh` is going to use `Style` in the future, so that should harmonize things ;)

> The second issue I had, coming from Leaflet is that the properties are parsed and added to the geometry key in each feature (feature.geometry[0].properties) that is not intuitive coming from leaflet or OL.

I am not familiar with OL/Leaflet, could you share what you would have expect ?

Thanks for the feedback !
