### ISSUE TITLE
accessing displayed features

### ISSUE THREAD

**Issue by mbredif** [iTowns/itowns#1394]
Status :
- For FileSources, there is a parsedData member that may be accessed to go through the features (with an JS object similar to geojson).
- view.pickFeaturesAt does some raycasting to retrieve an array of features.

Problem:
How to retrieve or inspect the list of all features that are being displayed when it is not a FileSource (such as a WFS server) ?

**Comment by zarov** [comment]
Assuming you are using `PlanarView` or `GlobeView`, you can do this to get all features from visible tiles:
```js
const result = []; 
view.tileLayer.info.displayed.tiles.forEach(t => 
    t.children.forEach((c) => { 
        if (c.feature) result.push(c.feature); 
    })
);
console.log(result);
```

**Comment by mbredif** [comment]
I wouldn't have guessed up front ! thanks for the trick :)

**Comment by zarov** [comment]
It is not trivial indeed, this needs some proper documentation ;)

**Comment by QSafariallahkheili** [comment]
Thank you for the very tactful solution. But, in my code it seems "c.feature" returns an empty array. Any recommendation or solution would be appreciated.

**Comment by zarov** [comment]
Indeed, if the feature is fixed to a specific tile, the tile may be hidden while the feature is still visible. As far as I know, I don't see a solution beside `pickFeatureAt`. We will need to think of a way to do that without picking things.
