### ISSUE TITLE
Picking issue when updating itowns and threejs

### ISSUE THREAD

**Issue by jailln** [iTowns/itowns#1399]
Updating itowns to v2.18.0 and threejs to 0.112.1 breaks picking on 3D Tiles layers in our project ([UD-Viz](https://github.com/VCityTeam/UD-Viz/tree/master)).

## Your Environment
* Version used: v2.18.0
* Browser Name and version: Chromium 81.0.4044.138
* Operating System and version (desktop or mobile): Ubuntu 18.04
* Link to your project: https://github.com/jailln/UDV/tree/package-updates-2

## Steps to Reproduce (for bugs)

* Install and start:
````
git clone https://github.com/jailln/UDV.git
git checkout package-updates-2
npm install
npm start
````
* Open the following URL: http://localhost:8080/examples/DemoFull/Demo.html
* Click on the second to last icon on the sidebar situated on the left (the loop with a spider in it, displaying "3dtiles debug" when hovering it).
* Click on any building from the 3D scene

## Expected Behavior
The selected building should turn to green and its metadata attribute should be displayed in the 3dtiles debug window. See the expected behavious in [this live demo](http://rict.liris.cnrs.fr/UDVDemo/UDV/UDV-Core/examples/DemoFull/Demo.html).

## Actual Behavior
Nothing happens.

## Possible Cause/Fix/Solution

I've looked into it and I don't find where this issue may come from. It only appears when updating itowns and threejs (and doing the subsequent modifications in our project, maybe that's where it's coming from?). I've found out that no intersection is found by the [picking function of Picking.js](https://github.com/iTowns/itowns/blob/v2.18.0/src/Core/Picking.js#L207). Also, note that this issue persists with itowns v2.19.0 and three 0.113.1. Finally, this may be unrelated (but just in case it is): itowns v2.17.0 and threejs 0.111.0 gives the following error that goes away with itowns v2.18.0 and three 0.112.1:
````  
three.module.js:25121 Uncaught TypeError: Cannot read property 'getUniforms' of undefined    
at wt (three.module.js:25121)     
at ws.renderBufferDirect (three.module.js:24125)    
at xt (three.module.js:24886)     
at gt (three.module.js:24856)    
at ws.render (three.module.js:24633)     
at t.<anonymous> (c3DEngine.js:52)    
at s._renderView (MainLoop.js:326)     
at s._step (MainLoop.js:308)     
at MainLoop.js:50 
````

Do you have any clue where this issue may come from ?
Thanks.

**Comment by zarov** [comment]
I cloned your repo to try it and I can't understand why you are getting nothing. I even applied some patch added later, but nothing seems to change it.

Nothing seems to have been broken when updating to THREE 112 in iTowns, so I don't understand how this update affect things.

The error you get in 2.17.0, does it mean it is not working as well ?

**Comment by jailln** [comment]
Thanks for your quick response.

> I cloned your repo to try it and I can't understand why you are getting nothing. I even applied some patch added later, but nothing seems to change it.

I've also tried [this patch](https://github.com/iTowns/itowns/pull/1397) on my side but it does not change anything. However, it just made me think that maybe it comes from the fact that my project uses the planar view while the 3D Tiles examples of itowns uses the globe view.

> Nothing seems to have been broken when updating to THREE 112 in iTowns, so I don't understand how this update affect things.

> The error you get in 2.17.0, does it mean it is not working as well ?

With 2.17.0 and three 0.111.0 (which is the version used in itowns 2.17.0), the rendering is not done and the above-mentioned error appears. I tried to resolve this for a bit, also without success, but since it disappeared with itowns 2.18.0 I stopped trying.

**Comment by zarov** [comment]
> my project uses the planar view while the 3D Tiles examples of itowns uses the globe view.

Good catch, I'll take a look at this !

> With 2.17.0 and three 0.111.0 (which is the version used in itowns 2.17.0), the rendering is not done and the above-mentioned error appears. I tried to resolve this for a bit, also without success, but since it disappeared with itowns 2.18.0 I stopped trying.

Ok !

**Comment by jailln** [comment]
> Good catch, I'll take a look at this !

Thanks :)

**Comment by jailln** [comment]
I tested it with itowns v2.19.0 (see [this branch](https://github.com/jailln/itowns/tree/test-picking)) and with the master branch (see [this branch](https://github.com/jailln/itowns/tree/test-picking-master)) and the bug is reproduced: open http://localhost:8080/examples/planar_3dtiles.html and click on a building for picking. 

Therefore, it seems to come from the planar view/controls; any idea on what is the issue ?

**Comment by zarov** [comment]
Yes, from what I tried too it seems to be on the master, which is easier to debug. For me, it is the `PlanarView`, because I can't see how the `PlanarControls` could affect anything here. One way to check that is to simply disable the controls. I suspect the `raycaster.setFromCamera` in `Picking` is a lead here.

**Comment by jailln** [comment]
Ok, thanks! Let me know if you find where it comes from; I'll try to search too.

**Comment by jailln** [comment]
The commit introducing the bug is bacc5f3109c7e42fe94ddfeaa63ed9169ce9f644 .
By reintroducing the changes of this commit one by one; I narrowed it down to updating threejs to 0.111.0 (and adding the `LegacyGLTFLoader` to itowns since it has been removed from threejs in 0.111.0). I looked at the [threejs migration guide](https://github.com/mrdoob/three.js/wiki/Migration-Guide#r110--r111), I don't know what can introduce this issue...  Any ideas ?

**Comment by zarov** [comment]
Thanks for finding this, I can confirm that this is the problematic commit. After checking and trying a lot of commit of threejs, I can confirm the problem results of this merge https://github.com/mrdoob/three.js/commit/fb405ea69e96a8bbbfb18641f606f4e67be935f5.

> Instead of relying on three.js to compute bounding box/sphere, we now
> compute them from attribute min/max specified in glTF file. These are
> mandatory as per glTF spec.

So from what I understand, it is only a matter of glTF version ? It seems our 3dTiles resources are not using glTF 2.0, as well as yours. Can you confirm that ?

Then, if it is this problem, two solutions comes in mind:
- don't support glTF 1.0 and update our examples (not the best)
- force the computing of bounding box/sphere when loading with glTF 1.0 (preferred solution)

**Comment by zarov** [comment]
In fact, I mispoke: we already handle glTF 1.0 in `b3dmParser`, so maybe this has nothing to do with this, but only badly generated 3dtiles.

**Comment by zarov** [comment]
Your b3dm files look good, the only message I am getting from  `3d-tiles-validator` is `Feature table binary must be aligned to an 8-byte boundary`. Maybe you need to add [`targets`](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#primitivetargets) to expand the bounding box/sphere to the correct size of the mesh ?

**Comment by jailln** [comment]
Thanks for looking into this!

Our 3DTiles dataset is written in glTF 2.0 and it seems that those used in the current 3D Tiles examples of itowns are also written in glTF 2.0 (it can be checked with [this variable](https://github.com/iTowns/itowns/blob/master/src/Parser/B3dmParser.js#L213)).

One possibility is that the `min` and `max` attributes of our 3D Tiles dataset (that are used to compute the bounding box/sphere in https://github.com/mrdoob/three.js/commit/fb405ea69e96a8bbbfb18641f606f4e67be935f5) are wrong. I will verify them. However, if that's the issue, I found it weird that our 3DTiles dataset is correctly rendered.

**Comment by jailln** [comment]
It was indeed coming from the `min` and `max` attributes that where wrong in our 3D Tiles datasets. Thanks for your help!!
