### ISSUE TITLE
Simplify Code Organisation!

### ISSUE THREAD

**Issue by nosy-b** [iTowns/itowns#14]
Arborescence 2 levels max for Source. Ideally 1 subdirectory per main package.

Three js should not be explosed too.

**Comment by gchoqueux** [comment]
donne des arguments

**Comment by nosy-b** [comment]
Typiquement pour ton test dans le Main, pour ton initialisation tu as besoin d'un module: 
['Core/Commander/Interfaces/ApiInterface/ApiGlobe']

Ca fait trop de subdirectory. Certains modules auront besoins parfois de nombreux modules on peut pas faire une demi page de require :).
Et faire des alias (shim) serait trop sale.

Le max qu'on puisse faire c'est  par ex : PackageX/ModuleOfX/SubModuleofModuleOfX

Et encore je pense qu'on peut mettre les sous classes ac les classes ds le même dossier. Ainsi on  aurait (SRC/)PackageX/ModuleOfX

Et Pour THREE JS  il faut le mettre en lib externe et ne pas l'explisé en sous partie.  

We discuss that on the 7th afternoon :)
