### ISSUE TITLE
Overwritten properties in GeoJsonParser

### ISSUE THREAD

**Issue by zarov** [iTowns/itowns#1406]
Some properties may be overwritten by [this part](https://github.com/iTowns/itowns/blob/0d400730e274d0840102adfb6092b4324658deb0/src/Parser/GeoJsonParser.js#L131-L136) in the `GeoJsonParser`. 

If you take the `source_stream_wfs_3d` for example and you read the properties before and after this loop, you got two different `id` properties. I don't think this should be the case, and the first one should be kept. However, where can the second one be stored ? I am not really sure of this.

**Comment by gchoqueux** [comment]
fixed in #1625
