### ISSUE TITLE
menu sliders moves the view

### ISSUE THREAD

**Issue by gmaillet** [iTowns/itowns#1423]
For example, opacity slider on Ortho Layer for 3d map example move the view

## Environment
* Version used: master 
* Browser Name and version: Chrome 83.0.4103.116
* Operating System and version (desktop or mobile): macOS 10.13.6

## Description
The bug is not visible in the initial placement for the [3D map example](http://www.itowns-project.org/itowns/examples/index.html#view_3d_map) (because there is nothing under the menu so the picking is not active), but if you zoom enough using the opacity slider moves the globe.

**Comment by gchoqueux** [comment]
yes, I'm fixing it right now.
