### ISSUE TITLE
Error WebGL 1.0/2.0

### ISSUE THREAD

**Issue by gchoqueux** [iTowns/itowns#1444]
#### Chrome error 

>    **WebGL: INVALID_OPERATION: drawElements: no buffer is bound to enabled attribute**

#### Firefox error 

>  **WebGL warning: drawElementsInstanced: Index buffer not bound.**

### Problem's cause
 * The bug appears with PR Three.js **VAO Support without breaking API** mrdoob/three.js/pull/16287

Attributes aren't updated when they should be. A [function (`needsUpdate`)](https://github.com/mrdoob/three.js/pull/16287/files#diff-d1d3e9b3d0928ce5d609d6e4f2cb51a5R174), to determine whether they should be updated, doesn't appear to be robust ([as signaled by this comment](https://github.com/mrdoob/three.js/pull/16287/files#r277266397)).

`needsUpdate` doesn't check if the **program attributes** are identical to the **cached attributes**.

**Fix**
```js
function needsUpdate( geometry, program ) {
	const cachedAttributes = currentState.attributes;
	const geometryAttributes = geometry.attributes;
	const programAttributes = program.getAttributes();

	const cachedAttributesCount = Object.keys( cachedAttributes ).length;

	if ( cachedAttributesCount !== Object.keys( geometryAttributes ).length || 
		cachedAttributesCount !== Object.keys( programAttributes ).length
	 ) return true;

	for ( const key in cachedAttributes ) {

		const cachedAttribute = cachedAttributes[ key ];
		const geometryAttribute = geometryAttributes[ key ];
		const programAttribute = programAttributes[ key ];

		if ( cachedAttribute.attribute !== geometryAttribute ) return true;

		if ( cachedAttribute.data !== geometryAttribute.data ) return true;

		if ( programAttribute == undefined ) return true;

	}
	return false;
}
```

fix #1443

**Comment by gchoqueux** [comment]
comment added https://github.com/mrdoob/three.js/pull/16287#discussion_r462131993

**Comment by takahirox** [comment]
Thanks for the bug report. Let's discuss in Three.js thread.

**Comment by gchoqueux** [comment]
**On Chrome v85**

* [JsFiddle example three v117.1 without webgl error](https://jsfiddle.net/iTownsIGN/9ax61ebL/9/) 
* [JsFiddle example three v118.0 with webgl error](https://jsfiddle.net/iTownsIGN/borcfx0p/3/)
   **WebGL: INVALID_OPERATION: drawElements: no buffer is bound to enabled attribute**
