### ISSUE TITLE
TypeError: intersection.distanceTo is not a function

### ISSUE THREAD

**Issue by iamvdo** [iTowns/itowns#147]
Using `getRange()` from ApiGlobe when altitude is high (eg when you see the whole globe), I get this error

`TypeError: intersection.distanceTo is not a function`

Turning the globe once seems to fix the issue O_o

**Comment by gchoqueux** [comment]
@vcoindet  can you check?

**Comment by vcoindet** [comment]
works fine as a callback in the itowns.viewer.addEventListener('globe-loaded', callback)
