### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by mgermerie** [iTowns/itowns#1504]
## Your Environment

* Version used: release 2.26.0
* Browser Name and version: Mozilla Firefox for Ubuntu Version 81.0
* Operating System and version (desktop or mobile): Ubuntu (desktop)

## Context
The issue does not concern a bug. It concerns an possible error in the documentation.
On the webpage http://www.itowns-project.org/itowns/docs/#tutorials/Create-a-simple-globe, it is said to create a Coordinates object with a CRS argument value set to 'WGS84'. However, when I try this, I get the following error : _Uncaught Error: Invalid crs parameter value 'WGS84'_.
Reading the documentation for the Coordinates class, I find out that the CRS parameter can be placed as an EPSG number. Doing so - with 'EPSG:4326' instead of 'WGS84' - I do not get any error.

## Possible Cause/Fix/Solution

It might be possible that the documentation I mentioned earlier is out of date regarding the CRS attribute of Coordinates isntances.

**Comment by gchoqueux** [comment]
Effectively, this tutorial is obsolete.

You're right , `WGS84` was be removed from `crs`, and needs to replace by `EPSG:4326`.

Also, `position` is no longer used to place itself on the globe, we use `placement` instead. ( see this [example](https://github.com/iTowns/itowns/blob/master/examples/view_3d_map.html#L24-L26)).

Could you do PR to modify it?
