### ISSUE TITLE
ApiGlobe setLayerVisibility and setLayerOpacity affect only the current loaded tiles

### ISSUE THREAD

**Issue by gmaillet** [iTowns/itowns#151]
Visibility or opacity modifications with the controls widget only affect loaded data. After a zoom or a large pan, the visibility is always "on" and the opacity is always "1" whatever the state of the controls widget.

**Comment by gmaillet** [comment]
It's not a bug on master, but a problem on #150 
unfortunately it affects the gh-pages branch due to #152

**Comment by nosy-b** [comment]
I might have missed the issue but the visibility set to off (such as opacity to 0) doesn"t hide the globe, it just get white.

BasicMaterial must have `this.transparent = true;`
Then in globe shader `gl_FragColor.a` <- layeropacity.
- It does create problem with atmosphere, also for picking as alpha is used to compute depth. 
  As @gchoqueux, you are working on a separate shader for the picking, modifications will wait

**Comment by gchoqueux** [comment]
It's not a bug on master
