### ISSUE TITLE
Tile culling using negative elevation ( bathymetry )

### ISSUE THREAD

**Issue by etienleigh** [iTowns/itowns#1515]
Hi!

Firstly - love the program.

Secondly - im having a challenge with some extreme culling using negative elevation tiles. - the tiles dont get culled when > 0 - naturally all is perfect on land :) - but if you zoom in close to lets say... a boat over some bathymetry ( 0 to -1000 meters or such ) - then the tiles get culled hardcore and sometimes cam decides to go to Mars when rotating.

maybe something to do with min/max distance - but my guess is the system was designed for positive elevations. - by the way negatives ones work great! - just not zoomed in real close. i tried frustum culling = false but no luck. im thinking perhaps tile matrix selection operates different when things are < 0 (is this hardcoded?)

anyways - bathymetry is a big thing for our project - would be very cool if someone could advise me what to tweak to stop the tiles disappearing with < 0 elevation tiles. oh yeah and the camera point selection ASSUMES a point on the ground ( it uses demutils - would be amazing if it could allow user to specify elevation to focus on -> imagine a submarine at -500m )

If < 0 elevation is simply not on the roadmap at all at the moment i understand also.

**Comment by gchoqueux** [comment]
> Firstly - love the program.

Thanks!

> Secondly 

Have you WMTS, WMS or TMS with negative elevation? 
then I could try to solve the problem

**Comment by etienleigh** [comment]
Hi yeah - its offline at the moment. hmmm. Ill have to put simple TMS on i guess. ill see what i can do for yah and post a link here. Thanks for the reply!

**Comment by etienleigh** [comment]
Hi there,
I have put up a simple TMS onto a raspberry pi - hopefully it dishes out enough .bil to see the issue.

{"id": "1","zmin": -10871,"zmax": 8850,"updateStrategy": { "type": 1, "options": { "groups": [ 7, 12 ] } },"tileMatrixSet": "WGS84G","source": {"projection": "EPSG:4326","networkOptions": {"crossOrigin": "anonymous"},"isInverted": false,"format": "image/x-bil;bits=32","url": "http://86.88.221.106/service/elevation_tms/${z}/${x}/${y}/1","attribution": {"name":"PANDEM","url": ""},"zoom": {"min": 7,"max": 12}}}
http://86.88.221.106/service/elevation_tms/{z}/{x}/{y}/1

**Comment by etienleigh** [comment]
Just an after-thought: 

I have developed 3D tile generation system based on PHP which can output ASTER 30m, SRTM 30m, 90m and also GEBCO 500m. The system also blends elevation - so you can have a tile with 30 meter SRTM blended with GEBCO for negative elevations along the coastline.

Anyways its very fast and can extract data directly from ZIP files which means all SRTM30 data...fits on a raspberry pi :) - which is obviously much slower than than a regular server. I was just wondering if this is something commercially interesting for ITowns core community / primary system users?

**Comment by gchoqueux** [comment]
>  I was just wondering if this is something commercially interesting for ITowns core community / primary system users?

it may interest users but I don't know exactly what their needs in web services are.

> `http://86.88.221.106/service/elevation_tms/{z}/{x}/{y}/1`

Thanks for this service, but it's unavailable.

**Comment by mgermerie** [comment]
Hi !
Some news were brought on the bathymetry subject with the recent #1871 issue.

**Comment by jailln** [comment]
Closing this there has not been activity on this issue and discussion on this matter has followed in #1871
