### ISSUE TITLE
LAS/LAZ parser and crs

### ISSUE THREAD

**Issue by manuamador** [iTowns/itowns#1516]
Hi, I am trying to use the news LAS/LAZ parser.
I am trying to add LAZ files in EPSG:2154 to a map.
It doesn't seem to work and I can't see any projection option.
Am I missing something ?

**Comment by gchoqueux** [comment]
Have you try to drag and drop a laz file in this example ?
http://localhost:8080/examples/#laz_dragndrop

**Comment by manuamador** [comment]
Yes, I was expecting to load the LAZ files from alex.ign.fr (EPSG:2154) on a globe. But I may be a bit naive. :)
I am trying to get how the classification coloring works.

**Comment by gchoqueux** [comment]
To load data on the globe, the crs projection must be `EPSG:4978`.
You could use `pdal` or `entwine` to convert the laz in other crs projection.

To load directly on other projection you could use `View` or `PlanarView`.

I works to display on the globe, the LAZ files from `alex.ign.fr`.
I try a new approach with **local coordinate system** on the normal ellipsoid.

I will come back to propose an example

**Comment by gchoqueux** [comment]
The web site https://alex.ign.fr/visu3d is open.

**Comment by jailln** [comment]
Closing since @gchoqueux provided a solution (pre-processing reprojection). We also openned #1925 that could also help you.
