### ISSUE TITLE
Autodeploy commits on gh-pages for each PR

### ISSUE THREAD

**Issue by gmaillet** [iTowns/itowns#152]
Autodeploy script (launched by travis) pushs on gh-pages for each commit on master, but the script also push for each PR and it's not the expected behavior because the ph-pages is supposed to always works

**Comment by tbroyer** [comment]
Huh, right:

> `TRAVIS_BRANCH`: For builds not triggered by a pull request this is the name of the branch currently being built; whereas for builds triggered by a pull request this is the name of the branch targeted by the pull request (in many cases this will be `master`).

Source: https://docs.travis-ci.com/user/environment-variables/

So the script should also exit `if [[ TRAVIS_PULL_REQUEST != "false" ]]`

**Comment by tbroyer** [comment]
We may want to also test `TRAVIS_REPO_SLUG` to be equal to `iTowns/itowns2`

**Comment by tbroyer** [comment]
Looks like we may have other issues with the script: https://travis-ci.org/iTowns/itowns2/jobs/144100391#L386

Also, we might want the script to delete everything in gh-pages before recreating content, to make sure we don't keep stale files around.

**Comment by gmaillet** [comment]
exactly, can you fix it?
