### ISSUE TITLE
Save "raw" style in vectorTile layer object

### ISSUE THREAD

**Issue by elias75015** [iTowns/itowns#1520]
The style.json is retrieved by iTowns, then parsed to create a new object. The style.json should be kept somewhere.

## Expected Behavior

We can retrieve the vector tile style in the vectorTileLayer

## Actual Behavior

We cannot retrieve the vector tile style in the vectorTileLayer.

**Comment by Mkonini** [comment]
Could you precise please which is the release you're testing? Thnx

**Comment by gchoqueux** [comment]
This issue is present in all itowns releases.
