### ISSUE TITLE
VectorTile pictograms too tiny when displayed

### ISSUE THREAD

**Issue by elias75015** [iTowns/itowns#1535]
## Context 

Pictograms size is too tiny, and make them almost unreadable. 

See the screenshot below :

![Capture d’écran de 2020-12-04 18-08-49](https://user-images.githubusercontent.com/6764800/101194996-0fcfc600-365f-11eb-9821-6a4e65596c14.png)

School and other pictograms from the IGN Map are displayed, but can't really be distinguished.

Tested with iTowns 2.27.0 on the geoportail website in local. Soon I will be able to give an URL to reproduce the problem.

**Comment by gchoqueux** [comment]
@elias75015 could give a url?

**Comment by elias75015** [comment]
Can't reproduce it. Probably a problem with the layer's style. I close the issue, thanks
