### ISSUE TITLE
THREE.LineBasicMaterial() : 'linewidth' attribut doesn't work on Windows

### ISSUE THREAD

**Issue by vcoindet** [iTowns/itowns#155]
I tried to create lines with Three.js this way :

```
var material = new THREE.LineBasicMaterial({
       color: 0xffffff, opacity: 1, linewidth: 5
});

var line = new THREE.Line(geometry, material); 
```

But the attribut 'linewidth' doesn't have any effect on Windows, it's always returning a line with the width of 1px.
It seems that it's a limitation of ANGLE.

Is there any alternative way to change the width of the line ?

**Comment by nosy-b** [comment]
Yes,
Three js got a tube geometry (but expensive as it creates many triangles!).
Or you can write a specific shader for a buffer geometry when we detect
non-native gl browser.

**Comment by qdnguyen** [comment]
I propose that we should create our lineShaderMaterial, i may need this shader for wfs also, i can see this problem next week if you want!

**Comment by vcoindet** [comment]
That would be great @qdnguyen !

**Comment by qdnguyen** [comment]
@vcoindet this was done in my new commits, can you review it please?

**Comment by gchoqueux** [comment]
A solution is added in PR #158
