### ISSUE TITLE
Mapbox color layer example

### ISSUE THREAD

**Issue by mathildeavgdr** [iTowns/itowns#1551]
Hello everyone,

I'm looking to stylize my map by integrating a link to my mapbox map as a color layer. I saw that the subject has been mentioned here :
https://github.com/iTowns/itowns/issues/182
Then here:
https://github.com/iTowns/itowns/issues/658

But I didn't succeed. So I contact you to know if there is an example with mapbox that I could follow?

Thank you !

**Comment by gchoqueux** [comment]
You could find examples :

https://www.itowns-project.org/itowns/examples/#vector_tile_raster_2d
https://www.itowns-project.org/itowns/examples/#vector_tile_raster_3d

**Comment by mathildeavgdr** [comment]
Yes, I saw examples and also this : https://github.com/iTowns/itowns/issues/1251

       var mvtSource = new itowns.VectorTilesSource({
              style: 'js/style.json',
               });
       var mvtLayer = new itowns.ColorLayer('MVT', {
              source: mvtSource,
             labelEnabled: true,
             });
       view.addLayer(mvtLayer);

And then I had the following errors :
Fetch API cannot load mapbox://sprites/...../......json. URL scheme must be "http" or "https" for CORS request.

Uncaught (in promise) TypeError: Failed to fetch

Do you have an idea about how to fix it ?

**Comment by gchoqueux** [comment]
Could drag `js/style.json` in zip file, in this issue ?

**Comment by mathildeavgdr** [comment]
This is the style.json
[style.zip](https://github.com/iTowns/itowns/files/5880691/style.zip)

**Comment by gchoqueux** [comment]
itowns doesn't support mapbox url format. We'll add support on itowns 2.31.0.

**Comment by mathildeavgdr** [comment]
Thank you very much,
I download milestones 2.31.0, and I still have the same errors. Is it because the issue is on the milestones 2.30.0 ?
Do you know other ways to use Mapbox without having mapbox url format ?

**Comment by gchoqueux** [comment]
Ooops, sorry, I make patch to fix it.

**Comment by gchoqueux** [comment]
This issue will be patch soon. (see #1609 )

**Comment by gchoqueux** [comment]
Finally, we will integrate this support in 2.32.0 because it was also necessary to improve the handling of mapbox styles .

**Comment by gchoqueux** [comment]
The support is added in new release [itowns 2.32.0](https://github.com/iTowns/itowns/releases/tag/v2.32.0)

**Comment by mathildeavgdr** [comment]
Thank you very much !! I'm trying to understand how I can play with label size with the zoom. But I have questions concerning the support : I don't know why the map is not working on mobile phone. Is it something that you already noticed ?
