### ISSUE TITLE
Incomplete view of 3d-tiles

### ISSUE THREAD

**Issue by ikemarv** [iTowns/itowns#1559]
* Version used: 2.18.1
* Browser Name and version: Chrome 87.0 & Firefox 84.0
* Operating System and version: macOS Big Sur 11.1

As you can see in the screenshot, the view of the buildings is incomplete. It looks like only the backs of the buildings are visible, even when rotating the camera around the buildings. Therefore, the geometry is fully contained, but not completely visible.

<img width="1262" alt="Bildschirmfoto 2021-01-21 um 10 09 01" src="https://user-images.githubusercontent.com/64950534/105332297-c0286800-5bd4-11eb-94f9-25c1edbf0656.png">
(No elevation model is included in the example.)
<br><br>
We have taken the example 3dtiles_25d and modified the code (extent, camera) to other locations and included other WMS services (e.g. ESRI/ArcGIS World Imagery).  The 3d-tiles (b3dm) were created with pg2b3dm.

The source files are CityGML data from Germany ( https://www.opengeodata.nrw.de/produkte/geobasis/3dg/lod2_gml/ ) but we also tried other CityGML data.

In Cesium the buildings are completely visible, but with transparency and colouring (red/brown instead of white).

If required, we can provide the converted data or also the modified code of the example.

**Comment by gchoqueux** [comment]
it's a normal of face problem.
I think there's a error in itowns.
Could you provide your data and code?

**Comment by ikemarv** [comment]
Thanks for the support.
I created a repository for providing the code & data -> https://github.com/ikemarv/test-itowns-nrw

**Comment by gchoqueux** [comment]
The bug is fixed in  #1566 yesterday
The patch will be published soon in itowns 2.29.2
