### ISSUE TITLE
zoomFactor parameters inconsistance in planarView

### ISSUE THREAD

**Issue by mgermerie** [iTowns/itowns#1586]
## Context

`zoomInFactor` and `zoomOutFactor` are two optional parameters when instantiating `PlanarControls`. They are supposed to quantify the 'amount' of zoom which is performed when a user roll the mouse wheel.

If these parameter are set to the same values, the effect they will have on the zoom will differ according to the camera type (the example of `zoomInFactor` is given here) :
- When a user wheels the mouse with a `PerspectiveCamera`, the camera performs a fraction of a travel between its position before wheeling and the position on the ground pointed by the mouse. The `zoomInFactor` describes this fraction. Therefore, if a user wants to double the size of the world on a single mouse wheel movement, the `zoomInFactor` shall be set to `0.5`.
- If the mouse is wheeled with an `OrthographicCamera`, the camera is not moved, but its `zoom` attribute is multiplied by `(1 + zoomInFactor)`. The `zoom` attribute of a camera scales the world seen by the camera : if the `zoom` is multiplied by `n`, the size of the objects visible will be multiplied by `n` too. In this context, having a zoom which doubles the size of the world on a single mouse wheel movement requires `zoomInFactor` value to be set to `1`.

## Expected Behavior
The zoom for an `OrthographicCamera` and a `PerspectiveCamera` shall be standardized so that the same value of `zoomInFactor` and `zoomOutFactor` produce the same visual effect on zoom.

**Comment by gchoqueux** [comment]
thanks, @ftoromanoff we validate the issue.
