### ISSUE TITLE
Precision loss when adding a new color layer from a geojson

### ISSUE THREAD

**Issue by ftoromanoff** [iTowns/itowns#1596]
## Your Environment
* Version used: 2.30
* Browser Name and version: Windows
* Operating System and version (desktop or mobile): desktop
* Link to your project: PackO

## Context

I'm trying to add a new Layer from a GeoJson in Lambert83 and the resulting layer has a wrong positioning for the y axes.

![image](https://user-images.githubusercontent.com/47628509/108869384-6feb5e00-75f7-11eb-9f21-a80e190a38cb.png)

le polygone vert et le fond rouge devraient être superposable. 
On peut aussi remarquer sur le polygone orange qui devrait être continu que seuls des segments verticaux sont représentés (j'ai utilisé une width: 3)

**Comment by gchoqueux** [comment]
Yes, the issue is the data are in float 32 bit.
If floor value is big, so it' loose precision.

**Comment by gchoqueux** [comment]
Could you up load a zip with a geojson?

**Comment by ftoromanoff** [comment]
[activePatchs.zip](https://github.com/iTowns/itowns/files/6191206/activePatchs.zip)

Here is an example on which there is incoherence with precision.

**Comment by gchoqueux** [comment]
thanks, I will see this
