### ISSUE TITLE
bug in the error raising during zoom travel

### ISSUE THREAD

**Issue by ftoromanoff** [iTowns/itowns#1618]
During a zoom in or out, a removeLayer/addLayer/notifyChange raises an error in 
handlerNodeError.js:12
>node.layerUpdateState[layer.id].success();

as layer.id seems undefined.

**Comment by mgermerie** [comment]
This issue is caused by the same bug mentioned in #1286.

**Comment by gchoqueux** [comment]
yes, already open in #1286
