### ISSUE TITLE
Vue js three dependency error

### ISSUE THREAD

**Issue by Jarakoto** [iTowns/itowns#1620]
## Your Environment
* Version used: 2.31.0
* Browser Name and version: 87.0
* Operating System and version (desktop or mobile): Ubuntu 20.04 LTS

## Context
Currently, THREE.js is a dependency packed with itowns module. With a project using Webpack 4.46.0, a THREE.js object instanciated from the itowns dependency are undefined (for example THREE Group).

## Steps to Reproduce (for bugs)
1. Create a default webpack project
2. import itowns webpack module
`import * as itowns from 'itowns'`
3. Instanciate a Three Group from the itowns module
`new itowns.THREE.Group()`

## Expected Behavior
The geometry layer should be instanciated

## Actual Behavior
Console returns this error
![Capture d’écran du 2021-04-02 11-37-29](https://user-images.githubusercontent.com/52926992/113404039-d8242100-93a7-11eb-84d3-ea40f3238319.png)

## Possible Cause/Fix/Solution
Quick fix is to use a separated THREE.js module in the webpack project.

**Comment by tbroyer** [comment]
`three` (and `proj4`) are `peerDependencies` so you are expected to add them as dependencies to your project; your `npm install` likely warned you about those missing dependencies.

And `itowns.THREE` should't even exist AFAICT; it should only be in the standalone bundle (for when you don't use a bundler like webpack).
