### ISSUE TITLE
Edge/poor video card/Mobil Support

### ISSUE THREAD

**Issue by gchoqueux** [iTowns/itowns#164]
iTowns must  support maximum devices and navigator.
Some WebGL extensions is not supported :

- float texture (use in elevation)
- log depth

**WebGL 2.0 is now supported on mobile and Edge.**
As webgl 2.0 is also supported by itowns, 
Float texture and log depth are no longer a issue for these platforms.

**Comment by vpicavet** [comment]
Please be more specific with the intended target : 
- we will definitely not support all version of IE
- some versions do not even have webgl
- the situation is quickly evolving with Edge replacing IE ( and other browsers rising)

Reminder of Web browsers shares : 
- IE 11 : 6%
- IE 9 : 2%

Source : W3 Counter

It would be interesting to have statistics from Geoportail over the last 3 months to be able to focus on the important things.

One option would be to have a very degraded mode for IE compatibility.

**Comment by tbroyer** [comment]
Only IE11 continues to be supported by Microsoft (announced on January this year), and is the only one to natively support WebGL anyway. This is WebGL 0.94 though, when all other browsers support WebGL 1.

**Comment by gchoqueux** [comment]
Only IE11, I think
IE11 support will open the support of certain cards and mobile

**Comment by gchoqueux** [comment]
It's work on IE11 058517f6da10bf763a81ab3f5bd6ac272a096bc6

![ie](https://cloud.githubusercontent.com/assets/11291849/17019434/83c68eb8-4f3c-11e6-912f-91caa3405734.PNG)

**Comment by gchoqueux** [comment]
PR merged #174 Best support Internet Explorer

**Comment by lazd** [comment]
There is discussion of solutions to the lack of `EXT_frag_depth` on this three.js issue: https://github.com/mrdoob/three.js/issues/13047

**Comment by jailln** [comment]
@LoicUTC @PhilippeMarc-IGN, what web browsers, in which versions and what platforms do we aim to support with itowns? Depending on this answer, we can close this issue or not.

Currently, itowns is known to be supported on last versions Chrome, Firefox, Safari and on these browsers for mobile. Others needs to be tested.

**Comment by PhilippeMarc-IGN** [comment]
Browser market share : 

- Chrome 65 %
- Safari 19 %
- Edge 4 %
- Firefox 3 %

Edge is now Chromium based, I think it could be added.
For geoportail we support the last year versions, it seems to be a good option.

**Comment by Desplandis** [comment]
We validated in proposal/issue #2256 that we now only support the `defaults` browserlist target with mandatory support of WebGL 2.0.

This was implemented in itowns in PR #2252.

@jailln We can now close this issue.
