### ISSUE TITLE
Lensflare takes a lof of time to render (and is not visible anyway...)

### ISSUE THREAD

**Issue by peppsac** [iTowns/itowns#167]
This profiler output show that LensFlare rendering time is way bigger than the globe rendering time:

![lensflare_bug](https://cloud.githubusercontent.com/assets/2198295/17058109/cdc10c18-501e-11e6-8a75-170fc4bf0961.png)

Do others notify the same issue (testing with 0cbdd7265c355f80a4fad8c1d020d7bd546a034c and Firefox/Linux) ?

**Comment by nosy-b** [comment]
Deleted.
