### ISSUE TITLE
How to customize the management of 3DTiles refinement with iTowns ?

### ISSUE THREAD

**Issue by LorenzoMarnat** [iTowns/itowns#1685]
## Your Environment
* Version used: 2.33.0
* Browser Name and version: Mozilla Firefox 89.0.2
* Operating System and version (desktop or mobile): Windows 10
* Link to your project: [UD-Viz-demo](https://github.com/VCityTeam/UD-Viz-demo/tree/master/DemoFull)

## Context
Hi, I'm working on levels of details for 3DTiles, at the [Liris](https://liris.cnrs.fr/) (Lyon, France). I create tilesets of buildings with several levels of details, and visualize those tilesets with our web application [UD-Viz](http://rict2.liris.cnrs.fr/UD-Viz/UD-Viz-Core/examples/DemoStable/Demo.html) (using iTowns).  
![part_dieu_lod](https://user-images.githubusercontent.com/32875283/124722753-a5d81180-df0a-11eb-8218-8a5c7492b039.gif)

To handle refinement when zooming in/out, I change the _geometric error_ of the different levels of details when creating the tileset.json  
![image](https://user-images.githubusercontent.com/32875283/124726906-7cb98000-df0e-11eb-906a-923ff192fd85.png)  
and I change the _seeTreshold_ in the 3DTileslayer.
![image](https://user-images.githubusercontent.com/32875283/124734216-3156a000-df15-11eb-8816-467e302db99c.png)

With this, I can handle the distance to refine pretty well (by letting iTowns refine when necessary), but I'm lacking control and precision on which tiles to refine and when to refine them.

## Expected Behavior
I would like to know if there is a way to 'customize' the management of refinement in iTowns (i.e use another parameter than the geometric error to know when to refine). For example, I'd like to use the distance between the camera and a tile to refine, or semantic data.

Is there a way to override/customize the iTowns refinement strategy ? or a way to implement our own refinement strategy ?

**Comment by gchoqueux** [comment]
Yes, it's possible to customize but the default methods aren't exposed in itowns.

I will do a PR to expose the default methods :
- `process3dTilesNode` : default method to update 3dtiles node depending on the context.
- `$3dTilesCulling` : default culling method
- `$3dTilesSubdivisionControl` : default refinement strategy method.

To customize it's necessary to overload the `C3DTilesLayer.update`  method.

```js
const yourMethod = (context, layer, node) => {
    //...
    return childrenVisible;
}

c3d_tiles_layer.update = yourMethod;
```

When default methods will be exposed, you could just redefine refinement strategy:

```js
const yourRefinementStrategy = (context, layer, node) => {
    const default = $3dTilesSubdivisionControl(context, layer, node);
    // your code
    // return true to refine node
}
// to overload refinement strategy
c3d_tiles_layer.update = itowns.process3dTilesNode(itowns.$3dTilesCulling, yourRefinementStrategy);
```

**Comment by gchoqueux** [comment]
Pr opens #1689

**Comment by gchoqueux** [comment]
The PR #1689 is merged and is in release 2.34.0.
Could you confirm that it meets your expectations?

**Comment by LorenzoMarnat** [comment]
Hi, thank you, it seems very promising, I think I'd be able to do what I want.  
I will try this and come back to you if I have any question or remark.

**Comment by LorenzoMarnat** [comment]
Hi, I'm back to share what I've been able to produce thanks to your modifications. I didn't encounter any major difficulty and I found what I needed in the iTowns API.

The goal of my production was to use the __mouse__ position to refine the 3DTiles buildings. In order to do that, I have created customized [subdivision control](https://github.com/iTowns/itowns/blob/master/src/Process/3dTilesProcessing.js#L374) and [SSE computation](https://github.com/iTowns/itowns/blob/master/src/Process/3dTilesProcessing.js#L257) methods to use to mouse position instead of the camera position.  
![mouse](https://user-images.githubusercontent.com/32875283/135054716-42961f02-39fa-4e79-930e-29be93459703.gif)

The produced code can be found in [this repo](https://github.com/VCityTeam/UD-Demo-vcity-lods-lyon), especially in [3dtilesProcessing.js](https://github.com/VCityTeam/UD-Demo-vcity-lods-lyon/blob/master/src/3dtilesProcessing.js) for the code using customized iTowns methods.

An online demo is available [here](https://lods-lyon.vcityliris.data.alpha.grandlyon.com/) if you want to see the result.  
A docker version is also available in [this repo](https://github.com/VCityTeam/UD-Demo-vcity-lods-lyon-docker).

Thank you for your time and your work on this issue !
