### ISSUE TITLE
customized material for layers

### ISSUE THREAD

**Issue by qdnguyen** [iTowns/itowns#172]
i want to develop specific shaders for some wmts layers, but for now every layers have the same material (LayeredMaterial), if I want to add something in shader, I must modify GlobeVS and GlobeFS.

**Comment by vpicavet** [comment]
Duplicate with #175 ? Choose one and close the other @qdnguyen

**Comment by gchoqueux** [comment]
Ok #175 is closed

**Comment by gchoqueux** [comment]
The PR #912 has introduced the shader chunks which allows to add simply its own code.
