### ISSUE TITLE
Warning CORS in IE for xbil

### ISSUE THREAD

**Issue by gchoqueux** [iTowns/itowns#173]
With fetch in IoDriver_XBIL with IE (test in c0c1ef9b4b430762e395d3287fc9418f126507f4) : 
XMLHttpRequest  needs  specification for CORS (Cross Origin Resource Sharing)

Have you a idea?

**Comment by gchoqueux** [comment]
@vcoindet Can you check, on your IE?

**Comment by vcoindet** [comment]
Tested with ie11.0.9600.18524

"Unhandled promise rejection TypeError: Cet objet ne gère pas cette action"

I'm not sure that ie11 correctly supports ES6...

I can test with Edge later if you want.

**Comment by tbroyer** [comment]
@vcoindet Browsers don't run ES6 directly: we transpile to ES5 with Babel; and promises are polyfilled in browsers that don't support them (i.e. IE11)

> "Unhandled promise rejection TypeError: Cet objet ne gère pas cette action"

What that means is that some code used with promises threw a `TypeError` (resulting in the promise being _rejected_) and the promise didn't have a `.catch()` to handle the rejection.
Now to find the origin of the error…

**Comment by gchoqueux** [comment]
All issues on IE are obsolete
