### ISSUE TITLE
Wrong point selection with PickPointsAt/pickObjectAt

### ISSUE THREAD

**Issue by clemencestr** [iTowns/itowns#1745]
## Your Environment

* Version used:  2.32.0 modified
* Browser Name and version: Mozilla 94.0
* Operating System and version (desktop or mobile): Linux Ubuntu 20.04.3 LTS

## Context

In the example [Pointcloud - Potree 2.5D map](http://www.itowns-project.org/itowns/examples/index.html#potree_25d_map), we can double click on a point to have its position printed in the console.
We want to do the same thing with our data. 
At the beginning we tried on our large dataset, but we realised that the coordinates were not exactly accurate. Therefore, we tried on a small portion of our data (around 30 000 points). And on this new dataset whatever point we click on, the same coordinates appear. We found out that the coordinates returned were the ones of the boundingbox in the equivalent of eglise_saint_blaise_arles.js file.

## Steps to Reproduce
1. Launch the potree 2.5D map example 
2. Convert the selected points with cartesianToCartographic function
3. Copy and paste these coordinates on Google Earth
4. Notice the difference between the click and the position shown by Google

**Comment by gchoqueux** [comment]
Thanks to report this issue.

There were two problems, they fixed in #1746

- the projection `EPSG:3946` was wrong, the correct projection is `EPSG:2154`.
- the picking point position was wrong, it was the one from the bounding box.

**Comment by clemencestr** [comment]
Thank you very much the bug seems fixed now !
