### ISSUE TITLE
Examples WMTS dont load

### ISSUE THREAD

**Issue by crubier** [iTowns/itowns#1763]
On the website, I currently get this, while it worked a week ago.

<img width="839" alt="Screenshot 2021-11-26 at 21 02 03" src="https://user-images.githubusercontent.com/2954572/143668730-542377b3-3d6f-4d9d-8aac-3003c63ab054.png">

**Comment by mgermerie** [comment]
Hi, thanks for your feedback !

However, I could not reproduce the error you mentioned, as you can see in the picture bellow. Do you still encounter it ?

![Capture d’écran du 2021-11-29 12-08-47](https://user-images.githubusercontent.com/73115044/143857796-248da813-b173-4205-97a8-b9e9a9368b3e.png)

**Comment by gchoqueux** [comment]
Hi, the server was down this week-end.
