### ISSUE TITLE
Extrusion problem

### ISSUE THREAD

**Issue by manuamador** [iTowns/itowns#1797]
Hi, I am using the latest  version of Itowns, using Firefox 91.6
![image](https://user-images.githubusercontent.com/1217972/154920990-3cdc4c26-cd5d-40d4-9403-48855c5ccf88.png)
The building using the example code do not have all their expected faces.
Thanks for your help.

**Comment by gchoqueux** [comment]
We will fix this

**Comment by gchoqueux** [comment]
see #1799
