### ISSUE TITLE
forme d'ellipsoid

### ISSUE THREAD

**Issue by qdnguyen** [iTowns/itowns#18]
En conversant de lambert93 à wgs84, j'ai vu que les axes ellipsoïde n'est pas bien scallé, ça ne va pas poser des problèmes de visu, ni la co-visualization si on utilise le code javascript pour convertir de lon/lat à cartesian. 

Par contre, si on fait la conversion des données hors ligne, on va avoir un décalage des km.

A corriger!

**Comment by gchoqueux** [comment]
je l'ai corrigé il y a quelques jours mais je n'ai pas poussé

**Comment by qdnguyen** [comment]
ok, peux tu pousser tes codes, j'arrive de corriger le lon/lat de mes points lasers mais l'alti n'est jamais bon avec ce scale. 

![v1_pointclouds](https://cloud.githubusercontent.com/assets/3224540/12680173/9ba80e0c-c6a8-11e5-9ce5-558c3280b825.jpg) 

![pccesium](https://cloud.githubusercontent.com/assets/3224540/12680181/a4c1b7ae-c6a8-11e5-8cec-bd2bb369f2f3.jpg)
![pccesium1](https://cloud.githubusercontent.com/assets/3224540/12680180/a4bf1684-c6a8-11e5-8c92-025047b678cd.jpg)

**Comment by qdnguyen** [comment]
la première photo montre les points lasers converti avec le repère de globe V1 mais l'alti n'est pas bon.
deux derniers photos montrent le globe de ceisum et les points lasers en wgs84 cartesians.

**Comment by gchoqueux** [comment]
j'ai poussé

**Comment by gchoqueux** [comment]
See example in https://github.com/iTowns/itowns2/blob/master/src/Globe/Globe.js#L81
to add transformation in root node. This layer have Z axis in Up
