### ISSUE TITLE
MeshPhysicalMaterial and shadow look weird in a small scene rendering

### ISSUE THREAD

**Issue by yuzhou2013** [iTowns/itowns#1801]
Hello everyone,
I just start a itowns environment , and put a whole city gltf model on the map. For the large scale scene, the materials and shadows looks good. Then I place another independent building on the map corresponding with  a spotlight on it. When the camera zoom in, the MeshPhysicalMaterials on the building is blured and the shadows is distored, everything look weird.
When I enlarge the model to 500x times, the MeshPhysicalMaterials and shadows looks good again.

I think may be the large scene is the reason, but I don't know how to fix this. Can anyone offer some suggestions? Thanks a lot!

**Comment by gchoqueux** [comment]
Hello,
Could you share an code example ?

what do you mean by `I enlarge the model to 500x times` ?

**Comment by yuzhou2013** [comment]
Thank you for reply.
Here are the screenshot:
this is a small model, and the shadow looks wierd
<img width="995" alt="wecom-temp-5c98b1c49fcf1e4e52a73397c18f9587" src="https://user-images.githubusercontent.com/10216476/156603634-72be85ad-4975-41e5-859a-80e1aeab9327.png">

then I enlarge the model, things looks better.
<img width="1063" alt="wecom-temp-a9e4cff4d953625b2d5168ca1c75f5a6" src="https://user-images.githubusercontent.com/10216476/156603804-0873fd6e-adb8-4172-9830-5af64837fa79.png">

In the end, I enlarge the model 500x times, the model become sharpe, and materials looks good.
<img width="1135" alt="wecom-temp-6053118c64b524e3853ac6e6c7dfe408" src="https://user-images.githubusercontent.com/10216476/156604129-4eaa97dd-0a23-405c-bd3e-2ee74ed2e198.png">

In order to express this question more clearly, I upload a whole building in the scene.
From the screenshot, we can see the distored shadow and bured shining shadow
<img width="1327" alt="wecom-temp-16f0f518c1e6c1747c30032dad3d23ca" src="https://user-images.githubusercontent.com/10216476/156604856-b9918300-4a91-4ba2-9c94-0eca417487a0.png">

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/10216476/156605283-cb85544f-2954-44d0-ba94-1259557ff673.png">


I refer to the writing of react-fiber, and try to make the effects
`    const bottleMaterial = new THREE.MeshPhysicalMaterial({
      color: '#ffffff',
      transmission: 1,
      roughness: 0.1,
      thickness: 100,
      envMapIntensity: 20,
      clearcoat: ,
      ior: 1
    })
   
   
    return new Promise((resovle,reject) => {
        itowns.glTFLoader.load(`/summodel2.glb`,(glb) => {
            const {nodes,materials} = convertNodeMaterial(glb)
            resovle(
                <group position={[-2839591.5155920475, 4664200.675698617,3284803.339808643]}>
                    <spotLight useHelper={SpotLightHelper} position={[10, 10, 50]} castShadow intensity={1}/>
                    <ambientLight intensity={0.2} />
                    <pointLight position={[-10, 50, -10]} color="white" intensity={0} />
                    <pointLight position={[0, 60, 5]} intensity={0} />
                    <directionalLight position={[0, 40, 0]} color="grey" intensity={0} />
                    <group rotation={[Math.PI/2,0,0]}>
                    <mesh receiveShadow castShadow material={material} geometry={nodes.Cube.geometry} position={[10, 10, -50]} scale={[500, 500, 500]} rotation={[0, 0, 0]}/>
                    <mesh receiveShadow castShadow material={material} geometry={nodes.Cube1.geometry} position={[10, 10, -50]} scale={[500, 500, 500]} rotation={[0, 0, 0]}/>
                    <mesh receiveShadow castShadow material={material} geometry={nodes.Cube2.geometry} position={[10, 10, -50]} scale={[500, 500, 500]} rotation={[0, 0, 0]}/>
                    <mesh receiveShadow castShadow material={material} geometry={nodes.Plane.geometry} position={[10, 10, -50]} scale={[500, 500, 500]} rotation={[0, 0, 0]}/>
                </group>
                </group>
            )
        })
    })`

In react-fiber, the rendering effect is as follows:
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/10216476/156606393-13b46bfc-c9c4-4bc8-8ced-e8152f80822d.png">

I think it is very meaningful to combine the big city scene and the small architectural scene to show. Thanks a lot

**Comment by yuzhou2013** [comment]
Hello,
I made another test as follows:
This is the original effect in gltf-viewer:
<img width="838" alt="image" src="https://user-images.githubusercontent.com/10216476/156698303-e81f340b-f92a-445c-8fd7-002bad93a5bb.png">

Then I load it in itowns:
Enlarge the dragon 20x times, we can see a lot of noise in the refraction
<img width="1727" alt="image" src="https://user-images.githubusercontent.com/10216476/156699032-70b7707e-3c55-4325-8612-34a26e920ab6.png">
<img width="1694" alt="image" src="https://user-images.githubusercontent.com/10216476/156699502-b6ae8f75-ab35-4625-981c-2aa6b17439e9.png">


Enlarge the dragon 2000x times， the refraction is much better now
<img width="1594" alt="image" src="https://user-images.githubusercontent.com/10216476/156699166-56cc8c18-f9fa-4c61-a57f-50c6eeb42447.png">

Enlarge the dragon 50000x  times,
<img width="1727" alt="image" src="https://user-images.githubusercontent.com/10216476/156698395-0c3a6bc3-7de9-4da5-8b41-3afc0ebbced3.png">

Anyone knows how to fix this?

**Comment by GGBond-GIS** [comment]
How do tiles receive shadows

**Comment by gchoqueux** [comment]
@yuzhou2013 I have you try in `THREE.js` scene without `itowns`?

https://discourse.threejs.org/t/should-i-use-a-light-for-every-object-to-cast-high-quality-shadow/2154/2

https://stackoverflow.com/questions/49332256/how-to-improve-shadow-quality-in-three-js

**Comment by gchoqueux** [comment]
> How do tiles receive shadows

For the moment it isn't possible

**Comment by GGBond-GIS** [comment]
> > 瓷砖如何接收阴影
> 
> 暂时不可能

![image](https://user-images.githubusercontent.com/92559206/160519559-a3d67cf5-a646-4805-b744-3606df543be7.png)
I can only try to modify the ground mesh object to achieve the effect, but it's a little contrary

**Comment by GGBond-GIS** [comment]
> 



> > 瓷砖如何接收抱
> 
> 暂时可能

Can I add a layer of ground mesh objects to the whole earth
![image](https://user-images.githubusercontent.com/92559206/160520225-315e7b11-bf75-4eae-9b62-97112f06e6a5.png)

**Comment by GGBond-GIS** [comment]
> > How do tiles receive shadows
> 
> For the moment it isn't possible

Can I use tilemesh and change the material to three Shadowmaterial to receive shadows, but I found that tilemesh is not a constructor
![image](https://user-images.githubusercontent.com/92559206/160559972-70e5b9b2-643f-4d94-98ae-048fcfba1db6.png)

**Comment by gchoqueux** [comment]
> but I found that tilemesh is not a constructor

`TileMesh` isn't exported in itowns
