### ISSUE TITLE
Vector data clamping to ground

### ISSUE THREAD

**Issue by vpicavet** [iTowns/itowns#181]
Right now vector data are displayed, but not clamped to the ground.
We will need to be able to clamp the data for 2D vector data visualization : 
- [x] Points
- [x] Lines
- [x] Polygons

@vmora already implemented a clamping algorithm previously, he may be able to help.

Clamping should be usable by all loaders for vector data, like WFS ( #115 ), GPX ( #114 #158 ), KML ( #24 ), GeoJSON, SHP and vector tiles.

**Comment by gchoqueux** [comment]
Some functions to add
- [ ] map.getCurrentAltitude(longitude, latitude)
  This function returns altitude of the current MNT displayed
- [ ] process.PlaceMeshOnMapSurface(node,map) 
  This process place the node/object3d on 3d surface of map

**Comment by gchoqueux** [comment]
This features are in itowns
