### ISSUE TITLE
How to load such tiles? No error is reported but tilt photography is not displayed. Can you see where the error is

### ISSUE THREAD

**Issue by GGBond-GIS** [iTowns/itowns#1826]
![image](https://user-images.githubusercontent.com/92559206/160763301-07646af1-ed3b-4f83-80b2-58c65866437e.png)

I can't see my tilt photography

**Comment by GGBond-GIS** [comment]
I can load it in cesium and how to use it in itowns

**Comment by GGBond-GIS** [comment]
Can you add a demo using cesium's 3dfiles to the document instance. thank

**Comment by jailln** [comment]
Hi,
There is some examples for 3d tiles visualisation: [visualisation in a globe view](https://github.com/iTowns/itowns/blob/master/examples/3dtiles_basic.html) (3D Tiles in EPSG:4978), [visualisation in a globe view with batch table hierarchy extension](https://github.com/iTowns/itowns/blob/master/examples/3dtiles_batch_table.html) and [3D Tiles visualisation in a planar view](https://github.com/iTowns/itowns/blob/master/examples/3dtiles_25d.html) (any CRS, you just have to instance the planar view in the same CRS).

If your 3D Tiles is displayed in Cesium, I guess it's in EPSG:4978, so you should visualize it in a globe view. Have you tried replacing [this URL](https://github.com/iTowns/itowns/blob/master/examples/3dtiles_basic.html#L52) to display it ?

Do you have any error in the console ?

**Comment by GGBond-GIS** [comment]
> Hi, There is some examples for 3d tiles visualisation: [visualisation in a globe view](https://github.com/iTowns/itowns/blob/master/examples/3dtiles_basic.html) (3D Tiles in EPSG:4978), [visualisation in a globe view with batch table hierarchy extension](https://github.com/iTowns/itowns/blob/master/examples/3dtiles_batch_table.html) and [3D Tiles visualisation in a planar view](https://github.com/iTowns/itowns/blob/master/examples/3dtiles_25d.html) (any CRS, you just have to instance the planar view in the same CRS).
> 
> If your 3D Tiles is displayed in Cesium, I guess it's in EPSG:4978, so you should visualize it in a globe view. Have you tried replacing [this URL](https://github.com/iTowns/itowns/blob/master/examples/3dtiles_basic.html#L52) to display it ?
> 
> Do you have any error in the console ?

![image](https://user-images.githubusercontent.com/92559206/160797559-0fffec05-c7a0-4870-8e14-0453358a0390.png)
The "blob: http://localhost:8081/953d3ee9 -255e-44e4-ad13-f8952f4b0a6b",

I don't know why?

, the console does not report an error

**Comment by GGBond-GIS** [comment]
> > Hi, There is some examples for 3d tiles visualisation: [visualisation in a globe view](https://github.com/iTowns/itowns/blob/master/examples/3dtiles_basic.html) (3D Tiles in EPSG:4978), [visualisation in a globe view with batch table hierarchy extension](https://github.com/iTowns/itowns/blob/master/examples/3dtiles_batch_table.html) and [3D Tiles visualisation in a planar view](https://github.com/iTowns/itowns/blob/master/examples/3dtiles_25d.html) (any CRS, you just have to instance the planar view in the same CRS).
> > If your 3D Tiles is displayed in Cesium, I guess it's in EPSG:4978, so you should visualize it in a globe view. Have you tried replacing [this URL](https://github.com/iTowns/itowns/blob/master/examples/3dtiles_basic.html#L52) to display it ?
> > Do you have any error in the console ?
> 
> ![image](https://user-images.githubusercontent.com/92559206/160797559-0fffec05-c7a0-4870-8e14-0453358a0390.png) The "blob: http://localhost:8081/953d3ee9 -255e-44e4-ad13-f8952f4b0a6b",
> 
> I don't know why?
> 
> , the console does not report an error

![image](https://user-images.githubusercontent.com/92559206/160799244-86bc80f0-dfae-4e2d-88f3-db4823ad6323.png)

**Comment by GGBond-GIS** [comment]
> > > Hi, There is some examples for 3d tiles visualisation: [visualisation in a globe view](https://github.com/iTowns/itowns/blob/master/examples/3dtiles_basic.html) (3D Tiles in EPSG:4978), [visualisation in a globe view with batch table hierarchy extension](https://github.com/iTowns/itowns/blob/master/examples/3dtiles_batch_table.html) and [3D Tiles visualisation in a planar view](https://github.com/iTowns/itowns/blob/master/examples/3dtiles_25d.html) (any CRS, you just have to instance the planar view in the same CRS).
> > > If your 3D Tiles is displayed in Cesium, I guess it's in EPSG:4978, so you should visualize it in a globe view. Have you tried replacing [this URL](https://github.com/iTowns/itowns/blob/master/examples/3dtiles_basic.html#L52) to display it ?
> > > Do you have any error in the console ?
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/92559206/160797559-0fffec05-c7a0-4870-8e14-0453358a0390.png) The "blob: http://localhost:8081/953d3ee9 -255e-44e4-ad13-f8952f4b0a6b",
> > I don't know why?
> > , the console does not report an error
> 
> ![image](https://user-images.githubusercontent.com/92559206/160799244-86bc80f0-dfae-4e2d-88f3-db4823ad6323.png)
Normal should be like this
![image](https://user-images.githubusercontent.com/92559206/160799885-7b86c35c-33cb-4149-a7ec-ce1cde76f844.png)

**Comment by jailln** [comment]
Is it possible for you to share your dataset so I can take a look at what may be the issue ?

**Comment by GGBond-GIS** [comment]
> > > > Hi, There is some examples for 3d tiles visualisation: [visualisation in a globe view](https://github.com/iTowns/itowns/blob/master/examples/3dtiles_basic.html) (3D Tiles in EPSG:4978), [visualisation in a globe view with batch table hierarchy extension](https://github.com/iTowns/itowns/blob/master/examples/3dtiles_batch_table.html) and [3D Tiles visualisation in a planar view](https://github.com/iTowns/itowns/blob/master/examples/3dtiles_25d.html) (any CRS, you just have to instance the planar view in the same CRS).
> > > > If your 3D Tiles is displayed in Cesium, I guess it's in EPSG:4978, so you should visualize it in a globe view. Have you tried replacing [this URL](https://github.com/iTowns/itowns/blob/master/examples/3dtiles_basic.html#L52) to display it ?
> > > > Do you have any error in the console ?
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/92559206/160797559-0fffec05-c7a0-4870-8e14-0453358a0390.png) The "blob: http://localhost:8081/953d3ee9 -255e-44e4-ad13-f8952f4b0a6b",
> > > I don't know why?
> > > , the console does not report an error
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/92559206/160799244-86bc80f0-dfae-4e2d-88f3-db4823ad6323.png)
> > Normal should be like this
> > ![image](https://user-images.githubusercontent.com/92559206/160799885-7b86c35c-33cb-4149-a7ec-ce1cde76f844.png)
It should be because of the problem of cutting, not the same level directory
![image](https://user-images.githubusercontent.com/92559206/160804352-90f46e26-7d96-49c9-bc91-816e9ea77b04.png)

**Comment by jailln** [comment]
Normally your tiles being in directories should not be an issue if they are correctly referenced in the tileset.json (but this should be the case since they are correctly displayed in Cesium).

Could you share the code you are using to display the 3D Tiles?
Is it possible for you to share the 3D Tiles ?

**Comment by GGBond-GIS** [comment]
> Normally your tiles being in directories should not be an issue if they are correctly referenced in the tileset.json (but this should be the case since they are correctly displayed in Cesium).
> 
> Could you share the code you are using to display the 3D Tiles? Is it possible for you to share the 3D Tiles ?

I'm a little sorry. This is 3dfiles of the company. I'm asking the leader

**Comment by jailln** [comment]
If it's not possible, only the tileset.json and one b3dm tile might be a good start to help debugging, without giving us access to the full tileset.

**Comment by GGBond-GIS** [comment]
> If it's not possible, only the tileset.json and one b3dm tile might be a good start to help debugging, without giving us access to the full tileset.

Can Axios be used to make up for this defect by repeating recursive requests

**Comment by GGBond-GIS** [comment]
> If it's not possible, only the tileset.json and one b3dm tile might be a good start to help debugging, without giving us access to the full tileset.
How to load the 3dfiles of cesium, as shown in the following figure
![image](https://user-images.githubusercontent.com/92559206/160976570-b897e517-3797-47d1-98aa-f25f05b96cdd.png)

**Comment by jailln** [comment]
Could you share the code you use to try to display it with itowns ?

**Comment by GGBond-GIS** [comment]
> Could you share the code you use to try to display it with itowns ?
I rendered these with cesium, but the use of tile sets in itowns did not respond
![image](https://user-images.githubusercontent.com/92559206/161030154-5fb23234-d401-425a-801b-b977565e6c20.png)
![image](https://user-images.githubusercontent.com/92559206/161030312-4a0b9dba-b8dc-4fc1-a8c4-7a77a76f7a2d.png)

**Comment by GGBond-GIS** [comment]
> > Could you share the code you use to try to display it with itowns ?
> > I rendered these with cesium, but the use of tile sets in itowns did not respond
> > ![image](https://user-images.githubusercontent.com/92559206/161030154-5fb23234-d401-425a-801b-b977565e6c20.png)
> > ![image](https://user-images.githubusercontent.com/92559206/161030312-4a0b9dba-b8dc-4fc1-a8c4-7a77a76f7a2d.png)

I don't know where. Except for the problem, it can be displayed in cesium, but itowns doesn't have any translation. The tile set in the example can be displayed, but I can't display the tile set of the company in itowns

**Comment by GGBond-GIS** [comment]
> Could you share the code you use to try to display it with itowns ?
This is the code I wrote using itwons.  There is no display on the map
![image](https://user-images.githubusercontent.com/92559206/161032015-edb4102a-9de3-46c6-8ecd-48c79d1859e5.png)
![image](https://user-images.githubusercontent.com/92559206/161032190-112c4501-0520-4948-8ea1-dbb9b565075b.png)
The console does not report an error

**Comment by jailln** [comment]
I think it may be due to the fact that binary batch table content is currently not supported. Try commenting out [these lines](https://github.com/iTowns/itowns/blob/master/src/Core/3DTiles/C3DTBatchTable.js#L33-L54) (33-54) and adding `this.content = {};` instead.

I will open a PR for binary batch table support soon.

**Comment by GGBond-GIS** [comment]
> I think it may be due to the fact that binary batch table content is currently not supported. Try commenting out [these lines](https://github.com/iTowns/itowns/blob/master/src/Core/3DTiles/C3DTBatchTable.js#L33-L54) (33-54) and adding `this.content = {};` instead.
> 
> I will open a PR for binary batch table support soon.

Thank you, I will try it again tomorrow to see the effect

**Comment by GGBond-GIS** [comment]
> I think it may be due to the fact that binary batch table content is currently not supported. Try commenting out [these lines](https://github.com/iTowns/itowns/blob/master/src/Core/3DTiles/C3DTBatchTable.js#L33-L54) (33-54) and adding `this.content = {};` instead.
> 
> I will open a PR for binary batch table support soon.

Still no effect

**Comment by jailln** [comment]
I suppose it worked since you opened #1835 ? Can you confirm please so we can close this issue if this is the case ?
Thanks.
