### ISSUE TITLE
 Problem adding 3dtile

### ISSUE THREAD

**Issue by GGBond-GIS** [iTowns/itowns#1830]
![Q`C4AFC1(3RV3@%_K6KIY`3](https://user-images.githubusercontent.com/92559206/161434768-7d7e8922-3677-4402-8bc7-66061b6a0eb8.png)

**Comment by jailln** [comment]
Hi,
Could you try with [this branch](https://github.com/iTowns/itowns/tree/feat/binary-batch-table) please and let me know if it works ? It implements the support for binary batch table which seems to be the problem with your dataset.

One way to test it is to replace [this URL](https://github.com/iTowns/itowns/blob/feat/binary-batch-table/examples/3dtiles_basic.html#L64) by your tileset URL.

**Comment by jailln** [comment]
I suppose it worked since you opened #1835 ? Can you confirm please so we can close this issue if this is the case ?
Thanks.
