### ISSUE TITLE
File ../dist/itowns.js   ../dist/debug.js 

### ISSUE THREAD

**Issue by Takieddinex** [iTowns/itowns#1831]
![image](https://user-images.githubusercontent.com/95845810/161570326-c2df1147-40ea-4009-99e8-ed4ddafb75d0.png)
![image](https://user-images.githubusercontent.com/95845810/161571063-74aea7e6-9c73-4253-bc06-0b342df2bf29.png)

Hello ! i'm beginner and i use the example basic 3d tiles to visualiz my own file but i can't find itowns.js and debug.js files.

**Comment by jailln** [comment]
Hi,
If you want to serve it with nginx or apache (which seems to be your case), you have to run `npm install` and `npm run build` in itowns folder to create `itowns.js` and `debug.js` bundles.
Otherwise you can also use npm (which runs a webpack server) by running: `npm install` and `npm start`.
