### ISSUE TITLE
Loading the binary 3dfile will cause the viewing angle to get stuck and the position of the 3dfile on the map is misplaced

### ISSUE THREAD

**Issue by GGBond-GIS** [iTowns/itowns#1835]
![image](https://user-images.githubusercontent.com/92559206/162124595-5866346a-2d9f-4548-a111-b992a61c9686.png)
Loading the binary 3dfile will cause the viewing angle to get stuck and the position of the 3dfile on the map is misplaced

**Comment by GGBond-GIS** [comment]
![image](https://user-images.githubusercontent.com/92559206/162125047-a4b62184-b3ca-479b-970e-e4430ec499d0.png)
This flicker block may be

**Comment by GGBond-GIS** [comment]
![image](https://user-images.githubusercontent.com/92559206/162137699-250fdd92-9ec8-42c5-8c3e-50862ad5cbd3.png)
Memory burst

**Comment by GGBond-GIS** [comment]
3dfile can't request dynamically. The memory is bursting

**Comment by jailln** [comment]
Hello,

Could you give more context about the issue you are experiencing please ? :

> Loading the binary 3dfile will cause the viewing angle to get stuck and the position of the 3dfile on the map is misplaced

* What do you mean by "the viewing angle to get stuck"? Can you provide instructions and a dataset to reproduce this bug ?
* How is the 3d tiles misplaced ? Can you provide instructions and a dataset to reproduce this bug ?

> This flicker block may be

* Could you give more details ? This block should be above ground while it is not ? Are you sure it is not coming from the model itself (e.g. is it above ground in cesium?) ? Is the terrain elevation right ?

> 3dfile can't request dynamically. The memory is bursting

What do you mean by "3dfile can't request dynamically" ? The tiles are requested dynamically depending on camera position. Memory increase may come from itowns and / or from the model. From my tests, itowns memory usage is similar to Cesium when displaying 3D Tiles. Can you confirm or is there a big difference for your tileset ? I will look into it to see if we can reduce memory usage.

**Comment by GGBond-GIS** [comment]
> Hello,
> 
> Could you give more context about the issue you are experiencing please ? :
> 
> > Loading the binary 3dfile will cause the viewing angle to get stuck and the position of the 3dfile on the map is misplaced
> 
> * What do you mean by "the viewing angle to get stuck"? Can you provide instructions and a dataset to reproduce this bug ?
> * How is the 3d tiles misplaced ? Can you provide instructions and a dataset to reproduce this bug ?
> 
> > This flicker block may be
> 
> * Could you give more details ? This block should be above ground while it is not ? Are you sure it is not coming from the model itself (e.g. is it above ground in cesium?) ? Is the terrain elevation right ?
> 
> > 3dfile can't request dynamically. The memory is bursting
> 
> What do you mean by "3dfile can't request dynamically" ? The tiles are requested dynamically depending on camera position. Memory increase may come from itowns and / or from the model. From my tests, itowns memory usage is similar to Cesium when displaying 3D Tiles. Can you confirm or is there a big difference for your tileset ? I will look into it to see if we can reduce memory usage.

The content of my 3dfile is very large. The bandwidth of my mapping from China to France is very slow. Itowns loads it and fills up all my 16GB, but not in cesium. However, cesium needs to re request some 3dfiles every other period of time

**Comment by GGBond-GIS** [comment]
![image](https://user-images.githubusercontent.com/92559206/162178391-25dfc679-bb40-4d63-b5b8-2eaecedd6424.png)
This perspective will get stuck

**Comment by GGBond-GIS** [comment]
> Hello,
> 
> Could you give more context about the issue you are experiencing please ? :
> 
> > Loading the binary 3dfile will cause the viewing angle to get stuck and the position of the 3dfile on the map is misplaced
> 
> * What do you mean by "the viewing angle to get stuck"? Can you provide instructions and a dataset to reproduce this bug ?
> * How is the 3d tiles misplaced ? Can you provide instructions and a dataset to reproduce this bug ?
> 
> > This flicker block may be
> 
> * Could you give more details ? This block should be above ground while it is not ? Are you sure it is not coming from the model itself (e.g. is it above ground in cesium?) ? Is the terrain elevation right ?
> 
> > 3dfile can't request dynamically. The memory is bursting
> 
> What do you mean by "3dfile can't request dynamically" ? The tiles are requested dynamically depending on camera position. Memory increase may come from itowns and / or from the model. From my tests, itowns memory usage is similar to Cesium when displaying 3D Tiles. Can you confirm or is there a big difference for your tileset ? I will look into it to see if we can reduce memory usage.

![image](https://user-images.githubusercontent.com/92559206/162374690-e1da89f1-59f8-4f3c-b4b5-cf784b303852.png)

**Comment by GGBond-GIS** [comment]
> > Hello,
> > Could you give more context about the issue you are experiencing please ? :
> > > Loading the binary 3dfile will cause the viewing angle to get stuck and the position of the 3dfile on the map is misplaced
> > 
> > 
> > 
> > * What do you mean by "the viewing angle to get stuck"? Can you provide instructions and a dataset to reproduce this bug ?
> > * How is the 3d tiles misplaced ? Can you provide instructions and a dataset to reproduce this bug ?
> > 
> > > This flicker block may be
> > 
> > 
> > 
> > * Could you give more details ? This block should be above ground while it is not ? Are you sure it is not coming from the model itself (e.g. is it above ground in cesium?) ? Is the terrain elevation right ?
> > 
> > > 3dfile can't request dynamically. The memory is bursting
> > 
> > 
> > What do you mean by "3dfile can't request dynamically" ? The tiles are requested dynamically depending on camera position. Memory increase may come from itowns and / or from the model. From my tests, itowns memory usage is similar to Cesium when displaying 3D Tiles. Can you confirm or is there a big difference for your tileset ? I will look into it to see if we can reduce memory usage.
> 
> ![image](https://user-images.githubusercontent.com/92559206/162374690-e1da89f1-59f8-4f3c-b4b5-cf784b303852.png)

It's because it's stuck
