### ISSUE TITLE
How to modify the color of 3dfile, like this

### ISSUE THREAD

**Issue by GGBond-GIS** [iTowns/itowns#1837]
![image](https://user-images.githubusercontent.com/92559206/162410765-556438b7-ca4c-40e1-832d-230c4a96de96.png)
![image](https://user-images.githubusercontent.com/92559206/162410894-624b82e3-762f-4e63-bbe9-2831f7dbf042.png)
How to modify the color of 3dfile, like this

**Comment by jailln** [comment]
You can use the `onTileContentLoaded` callback of `C3DTilesLayer` (not documented yet, but I add documentation to it in PR #1867) to access the content of a tile once it has been loaded. In this callback, you can apply whichever color function you want. For instance, you can write something like:

```
            var changeColor = function(tileContent) {
                tileContent.traverse((o) => {
                    if (o.material && o.material.color) {
                        o.material.color.set('blue');
                    }
                })
            };

            var threeDTilesLayer = new itowns.C3DTilesLayer('id', {
                name: 'name',
                source: new itowns.C3DTilesSource({
                    url: 'http://some-url/tileset.json',
                }),
                onTileContentLoaded: changeColor
            }, view);

            itowns.View.prototype.addLayer.call(view, threeDTilesLayer);
```

Let me know if this answers your question.
