### ISSUE TITLE
Assembled Panoramic views support

### ISSUE THREAD

**Issue by vpicavet** [iTowns/itowns#184]
As this kind of data is quite easy to find and user are used to this kind of immersive environment ( <= Google Streetview ), it would be nice to support it.

Different kind of assembled panoramic images : 
- cubemaps
- equirectangular images
- ?

Some resources for 360° images : 
- here
- flickr groups ( some have GPS coordinates)
- mapillary ?
- Add some more..

We will have to check for TOS and licences before using the images inside iTowns.

We first have to discuss here about formats and metadata. One or more formats can be implemented. We would probably want a quick-and-easy solution as well as a feature-complete solution. See also #144 for metadata discussion.

**Comment by vpicavet** [comment]
@mbredif and @nosy-b should have their word on this subject ( and preliminary implementation ?)

**Comment by vpicavet** [comment]
@pblottiere is going to work on the server side for https://github.com/LI3DS/api-li3ds/issues/1

Discussion on formats and API is welcome

**Comment by gchoqueux** [comment]
move in #23
