### ISSUE TITLE
Widget navigation broken with update

### ISSUE THREAD

**Issue by manuamador** [iTowns/itowns#1844]
Hi,
Just trying out the new version.

The addButton function is not working.
The third argument is displayed as a label like ' () => {
                    view.controls.lookAtCoordinate({
                        tilt: view.controls.getTilt() - 10,
                        time: 500,
                    });
                }'
and the buttons are not working.

This part of the code need to be updated: 
// Example on how to add a new button to the widgets menu
            widgets.addButton(
                'rotate-up',
                '<p style="font-size: 20px">&#8595</p>',
                () => {
                    view.controls.lookAtCoordinate({
                        tilt: view.controls.getTilt() - 10,
                        time: 500,
                    });
                },
                'button-bar-rotation',
            );
            widgets.addButton(
                'rotate-down',
                '<p style="font-size: 20px">&#8593</p>',
                () => {
                    view.controls.lookAtCoordinate({
                        tilt: view.controls.getTilt() + 10,
                        time: 500,
                    });
                },
                'button-bar-rotation',
            );
            widgets.addButton(
                'reset-position',
                '&#8634',
                () => { view.controls.lookAtCoordinate(placement) },
            );

**Comment by manuamador** [comment]
a quick fix:
// Example on how to add a new button to the widgets menu
widgets.addButton(
'rotate-up',
'

&#8595

','Rotate up',
() => {
view.controls.lookAtCoordinate({
tilt: view.controls.getTilt() - 10,
time: 500,
});
},
'button-bar-rotation',
);
widgets.addButton(
'rotate-down',
'
&#8593

','Rotate down',
() => {
view.controls.lookAtCoordinate({
tilt: view.controls.getTilt() + 10,
time: 500,
});
},
'button-bar-rotation',
);
widgets.addButton(
'reset-position',
'&#8634','Reset view',
() => { view.controls.lookAtCoordinate(placement) },
);

**Comment by mgermerie** [comment]
Indeed, thank you for reporting it.

At some time before the release, I added the `title` parameter to `addButton` method (which appears in [the documentation](http://www.itowns-project.org/itowns/docs/#api/Widgets/Navigation)) but I forgot to update the example accordingly.

I will update the example in a new PR.
