### ISSUE TITLE
How generate data for ElevationLayer from geotiff?

### ISSUE THREAD

**Issue by vladimir-rybalko** [iTowns/itowns#1848]
Hi.
I try generate data for ElevationLayer from my geotiff.
For this i use this code
```
var extent = new itowns.Extent('EPSG:4326', 29.140435, 29.152530, 60.89478, 60.899569);

var elevationSource = new itowns.WMSSource({
        extent,
        version: '1.3.0',
        name: 'graund:Vuoksa_ground_1m',
        crs: 'EPSG:4326',
        width: 256,
        format: 'image/jpeg',
        url: 'http://localhost:9090/geoserver/graund/wms',
});

var elevationLayer = new itowns.ElevationLayer('wms_elevation', {
        source: elevationSource,
        useColorTextureElevation: true,
        colorTextureElevationMinZ: -14.554,
        colorTextureElevationMaxZ: 16.768,
});

view.addLayer(elevationLayer);
```

As a result, the relief appears on the scene, but it breaks the textures of the tiled layer.

How do I get the ElevationLayer with little blood?

![image](https://user-images.githubusercontent.com/3933179/164167806-304550ea-c07e-450f-afd5-df47f72c179d.png)

**Comment by gchoqueux** [comment]
You use `GlobeViewer` or `PlanarViewer`?

could you open access on your geoserver?

**Comment by vladimir-rybalko** [comment]
False alarm.

My problem was in dynamic style on tiles.
I set a static style for all tiles in the same gray range and the problem was solved.

![image](https://user-images.githubusercontent.com/3933179/164712478-78e055cd-2990-4431-bd22-aaeabe77a19f.png)
