### ISSUE TITLE
3D Tiles support

### ISSUE THREAD

**Issue by vpicavet** [iTowns/itowns#185]
The 3D Tiles specification is starting to take shape and approaches a stable version : 
- https://github.com/AnalyticalGraphicsInc/3d-tiles

As the specification also enters OGC proposed work as community standard, it will be important to support this protocol at some point.
- https://www.gim-international.com/content/news/ogc-proposed-work-item-for-3d-tiles-as-community-standard

The spec will take the following parts into account for planned version 1.0 : 
- [x] tileset.json
- [x] Batched 3D Model (b3dm)
- [ ] Instanced 3D Model (i3dm)
- [x] Point Cloud (pnts)
- [ ] Vector Data
- [ ] Composite (cmpt)
- [ ] Declarative Styling

Cesium already implements the draft version of the specification : 
- https://github.com/AnalyticalGraphicsInc/cesium/issues/3241

Some issues which must be solved before being able to implement 3D Tiles :  
- [x] Vector data clamping #181 ( and related vector tiles support #182 )
- [x] Tile creation and update #71 
- [x] gltf support in THREE.js

Do not hesitate to comment and add information on this large issue.

**Comment by Jeremy-Gaillard** [comment]
Working on it, starting with the tileset.json import.

**Comment by Jeremy-Gaillard** [comment]
tileset.json support:
- [x] asset
  - [x] version
  - [x] tilesetVersion
  - [x] gltfUpAxis
- [x] bounding volume
  - [x] box
  - [x] region
  - [x] sphere
- [x] geometric error
- [x] viewer request volume
- [x] refine (add or replace)
- [x] transform
- [x] content
  - [x] bounding volume
  - [x] url
     - ~~additional tileset.json are not supported~~ Done
     - ~~the url extension should be used to determine the tile type~~ 3d-tiles specification has been updated to remove this constraint
- [x] children

Known issues:
- [x] the transformation matrix should apply to the box and sphere bounding volumes and viewer request volumes
- [ ] if a viewer request volume is defined, the loading of the content should be delayed until the camera is in the volume (currently, only the culling part is done)

**Comment by Jeremy-Gaillard** [comment]
Batched 3D Model (b3dm) support:
- [x] Geometry
- [x] Batch table
- [ ] Feature table

Additional issues:
- Three doesn't seem able to handle the batchId shader attribute

**Comment by vpicavet** [comment]
@nikosaul is working on this issue

**Comment by qdnguyen** [comment]
What is he doing exactly? i'm also working on 3dtile generation, first test with 3d model of lyon.

**Comment by vpicavet** [comment]
Please consider contributing to https://github.com/Oslandia/py3dtiles/ if you want to work on the server-side aspects of 3D Tile : support for all the specs in the module and converter scripts are welcome.

@nikosaul will start working on the client side, implementing 3D tiles support in iTowns, first with spec examples.

And please, please please, _communicate_ before you start working on a subject, and try to consolidate / mutualize your efforts with existing projects.

**Comment by qdnguyen** [comment]
it's server-side that i'm doing now, but my objectif is to have a 3dtiles of Bati3D (paris, lyon) from cityGML format, so i used 3dcitydb and some javascript tools (ex. gltf to b3dm, 3dtile tool) to do that.

**Comment by NikoSaul** [comment]
Read the .pnts file
  - [x] .pnts 
    - [x] Point semantic
      - [x] Position
      - [ ] Position quantized 
      - [ ] RGBA
      - [x] RGB
      - [ ] RGB565
      - [ ] Normal
      - [ ] Normal oct16p
      - [ ] BatchId
    - [x] global semantic
      - [x] Point length
      - [x] RTC center
      - [ ] Quantized Volume offset
      - [ ] Quantized Volume scale 
      - [ ] constante RGBA
      - [ ] Batch length

**Comment by qdnguyen** [comment]
Can we support a b3dm file with embeded resources such as texture?

For now, when i load an embeded b3dm file, i got this error from gltf loader.
GLTFLoader.js:980 Uncaught (in promise) TypeError: Cannot read property 'binary_glTF' of undefined
at GLTFLoader.js:980
at _each (GLTFLoader.js:592)
at GLTFLoader.js:978
at

**Comment by Jeremy-Gaillard** [comment]
Some issues that need fixing:
- [x] SSE computation is too simplistic (only takes into account the distance to the centre of the tile). EDIT: for reference, [Cesium](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Cesium3DTilesetTraversal.js#L687) uses distance to the tile
- [ ] the first level of tiles is loaded whether the SSE condition is true or not
- [x] the refine parameter should be inherited from the parent when omited

Other welcome additions:
- [ ] tile loading prioritisation based on the depth of the tile in the tileset and the distance between the camera and the tile

**Comment by autra** [comment]
> tile loading prioritisation based on the depth of the tile in the tileset and the distance between the camera and the tile

Could it be relevant to prioritize according to the space taken on screen like for pointclouds for examples? (by projecting the bounding box?)

**Comment by Jeremy-Gaillard** [comment]
Sure. We'll need to think about which weight to give each of the metrics we use to compute the priority.

**Comment by ladislavhorky** [comment]
> Batched 3D Model (b3dm) support:
> 
> * [x]  Geometry
> * [x]  Batch table
> * [ ]  Feature table
> 
> Additional issues:
> 
> * Three doesn't seem able to handle the batchId shader attribute

Hello, 
is there any progress or plan to support the feature table in 3D tiles?

I am preparing a talk for FOSS4G NA 2019 about performance comparison of CesiumJS, iTowns and [VTS](http://vtsdocs.melown.com/en/latest/index.html) on 3D cadastre example (terrain + 3D city + vector parcels). I seemed that iTowns support 3D tiles with LODded, textured mesh 3D city models but it does not so far which is a major drawback. All models I use work just fine in Cesium, in iTowns I get `3D Tiles feature table not supported yet.`.

Thanks, 
Ladislav

**Comment by ladislavhorky** [comment]
Maybe @Jeremy-Gaillard ?

**Comment by Jeremy-Gaillard** [comment]
Hello @ladislavhorky,

Unfortunately, I am no longer active on this project since the end of my PhD, so I'm not sure what the status of the implementation of the feature table is.

I may still be able to help you though. I think the problem comes from an evolution of how the 3D Tiles specification handles the RTC. It used to be in the glTF part of the B3DM file, but it seems it is now in the feature table. If that's indeed the problem (you can check easily by looking if your B3DM file has an RTC_CENTER property in its feature table), you (or someone that is still active on the project) can fix this quite easily by adapting the code [here](https://github.com/iTowns/itowns/blob/master/src/Parser/B3dmParser.js#L40) and [here](https://github.com/iTowns/itowns/blob/master/src/Parser/B3dmParser.js#L130).

**Comment by ladislavhorky** [comment]
Hello @Jeremy-Gaillard,

thanks for the pointers. At least for our data, the RTC_CENTER is in the featureTable as you pointed out (there is not much more than that). We will probably check data from other vendors to be sure. 

From the code you linked it seems the correct solution is to parse the feature table, note the RTC_CENTER if present and then pass it to `applyOptionalCesiumRTC` as optional override for the `CESIUM_RTC.center` - that would make it BW compatible (no center in the feature table -> unchanged behavior) and working for us (provided it is the only problem). 

There is a slight chance I may manage to make a PR. If not, let this serve as a reference for anyone working on the project (@gchoqueux probably?).

Thanks, L.

**Comment by gchoqueux** [comment]
Hello @ladislavhorky , thanks for your interest in itowns.

For the moment iTowns doesn't support the `features tables.`

We are in 3dtiles refactoring  with @jailln . I couldn't work, in full time, on 3d tiles until the second semester. 

@jailln do you plan to implement  `features tables`?

**Comment by ladislavhorky** [comment]
Hello @gchoqueux,

I may manage to give it a day - I would not exactly call it an implementation, a quick hack at best. If I manage to get it working, I will make a PR and link the 3D tiles data I used.

**Comment by jailln** [comment]
@gchoqueux I don't plan to work on the feature table implementation for now (I am currently more focused on the extensions of 3D Tiles) but it would indeed be nice to support it.

**Comment by ladislavhorky** [comment]
Hi, 
I managed to get a 3D tiles city model downloadable from [here](https://hri.fi/data/en_GB/dataset/helsingin-3d-kaupunkimalli) that does not contain a batch table. Model can be displayed in Cesium and it looks fine. When displayed in iTowns, the model shows up but looks completely black (no textures) with no warnings in the console. 

Therefore, I guess there is more to implement to support textured-meshes 3D tiles than just batch table. As the batch table is just one step towards support of textured 3D models in iTowns I have to drop the matter for time reasons.

**Comment by adam314315** [comment]
Hi,

Does the last version of iTown implement 3D Tiles Next format  (as presented by Cesium https://github.com/CesiumGS/3d-tiles/blob/main/specification/README.md)  to avoid having a single large tileset.json file rather than a tileset.json file with references to smaller tileset.jon files attached to their corresponding bounding boxes ?

**Comment by gchoqueux** [comment]
Hi
At the moment itowns doesn't support 3d tiles next

**Comment by mgermerie** [comment]
The complete 3d-tiles support is planned in the short term road map. We are currently studying possibilities in terms of libraries to enhance support (as mentioned in [this discussion](https://github.com/iTowns/itowns/discussions/1917).

**Comment by jailln** [comment]
Closing this since we've moved to 3DTilesRendererJS (see the new OGC3DTilesLayer) that supports most of the 3.0 spec and part of the 1.1 spec. 3D Tiles spec support can now be followed there directly.
