### ISSUE TITLE
Cesium has more detailed tiles texture render on zoom

### ISSUE THREAD

**Issue by alexLuky** [iTowns/itowns#1853]
@gchoqueux @mgermerie 

I faced with issue that itowns renders tiles textures much less detailed than cesium does from the same source.

## Your Environment
* itowns version used: 2.38.1
* b3dm tiles
* link to json: hided

## Context
Here is cesium:
![image](https://user-images.githubusercontent.com/43720642/166926025-3b3beb3b-f489-49b4-b456-29944ee566d0.png)

Here is itowns:
![image](https://user-images.githubusercontent.com/43720642/166926703-5c6f7a33-54c9-4279-a593-0a3fe8476e11.png)

Also itowns has darker light wich makes the scene more nasty. How can I make it lighter? Should I use three,js light instances for this?

## Steps to Reproduce (for bugs)
Here is the itowns code:
```
const tiles3dLayer = new itowns.C3DTilesLayer(datasetTilesSet3dObject.id, {
    name: datasetTilesSet3dObject.name,
    source: new itowns.C3DTilesSource({
      url: datasetTilesSet3dObject.url,
    }),
    sseThreshold: 1,
}, this.itownsViewer)
itowns.View.prototype.addLayer.call(this.itownsViewer, tiles3dLayer)
```

## Expected Behavior
I expect that LOD will be increased to maxim while zooming. Now it looks like itowns just stops to update the LOD on zoom.

Any thoughts how can I achieve the same render quality as cesium does? I've attached the link to the source 3dTiles set for experiments.

**Comment by jailln** [comment]
see https://github.com/iTowns/itowns/issues/1859#issuecomment-1239206538

**Comment by mgermerie** [comment]
The complete 3d-tiles support is planned in the short term road map. We are currently studying possibilities in terms of libraries to enhance support (as mentioned in https://github.com/iTowns/itowns/discussions/1917).

**Comment by jailln** [comment]
@alexLuky this should be resolved with #2143 , can you test it and let me know please?

**Comment by alexLuky** [comment]
@jailln it's fantastic news. I surely would. Give me some time!

**Comment by jailln** [comment]
Closing this it has been fixed (and still works with the new OGC3DTilesLayer based on 3DTilesRendererJS). Feel free to reopen if needed.
