### ISSUE TITLE
migrate to typescript

### ISSUE THREAD

**Issue by uundedd** [iTowns/itowns#1862]
hi 

in very famous library for  better  documentation and reuse  migrate to typescript ; 

even they wont to migrate just write definition type file for own code ; 

please migrate your code to typescript if not just write definition type file  ; 

i work an gis application and work with typescript for 4 years . i happy to help itowns to be better

**Comment by aurelien-boubennec** [comment]
I agree with you uundedd

**Comment by jailln** [comment]
It would require a lot of work and it is currently not planned.

**Comment by uundedd** [comment]
such humans work with a square wheel and the other one says common to use this circle wheel and they say ...

https://media.licdn.com/dms/image/C4D12AQH3JLVFSpPm8A/article-cover_image-shrink_600_2000/0/1520204567520?e=2147483647&v=beta&t=bDPQfi4woSijSRMhvg79nq9Ug7tbU68liTdybX-Krk4

it is so important for fast improvement and develops

**Comment by gchoqueux** [comment]
@uundedd How typescript will improve and/or accelerate our itowns developments?

**Comment by uundedd** [comment]
in my experience  when your library writes with typesafe language 

- you don't need to remember what the input and output functions and class
- you don't need to remember what method exists in the class or object that you can access 
- Better tooling - TypeScript integrates well with tools like text editors, linters, and build systems, making development more productive.
- Code scalability - As your project grows, TypeScript allows you to easily manage your codebase using features like interfaces, classes, and modules.
- Improved teamwork - With TypeScript, teams can more easily collaborate on large projects, as the type system acts as documentation for developers.
- Code scalability - As your project grows, TypeScript allows you to easily manage your codebase using features like interfaces, classes, and modules.
- Compatibility with existing JavaScript code - TypeScript is a superset of JavaScript, which means that all valid JavaScript is also valid TypeScript.

**Comment by uundedd** [comment]
excuse me the 4 must replace with this
Type checking - TypeScript catches errors at compile-time, making it easier to debug and maintain code.

**Comment by uundedd** [comment]
please read more about it in this link https://serokell.io/blog/why-typescript
