### ISSUE TITLE
Line width in features

### ISSUE THREAD

**Issue by AHamers** [iTowns/itowns#1864]
## Your Environment
* Version used: 2.38.2
* Browser Name and version: Google Chrome Version 102.0.5005.63 (official build) (64 bits)
* Operating System and version (desktop or mobile): Windows 10 Pro version 21H2

## Context
When displaying lines from a feature, the lines have a constant width (seemingly 1 pixel), even after changing the style.stroke.width attribute. This issue seems to only happen on Windows. The line width works fine on Linux.

![image](https://user-images.githubusercontent.com/51396638/173621287-2c84d8b1-4042-4d49-9706-be07a75efd1a.png)
![image](https://user-images.githubusercontent.com/51396638/173621458-f09787a8-444a-41a7-8370-f7f4414f04b6.png)

According to the forums, WebGL, in some cases, can't handle line width depending on the graphic drivers used on the computer. This line width problem seems pretty common on ThreeJS.
We tried a few workarounds but none worked so far.

## Expected Behavior
The displayed line width changes when style.stroke.width is changed.

## Actual Behavior
The displayed line width doesn't change.

## Possible Cause/Fix/Solution
The issue seems to have been addressed in the past : https://github.com/iTowns/itowns/pull/158 , but the fix has been removed from ITowns since.

Adrien from CirilGROUP.

**Comment by gchoqueux** [comment]
yes it's a bug on Windows
THREE mesh line should be used 
You cloud replace by a `ColorLayer`

**Comment by gchoqueux** [comment]
see #155

**Comment by jailln** [comment]
That give some insights on how to do it but itowns implementation of lines has been removed since then, do you know why ? Maybe we should add it back ?
