### ISSUE TITLE
3D measurement tools

### ISSUE THREAD

**Issue by jailln** [iTowns/itowns#1868]
We are interested in having 3D measurement tools and in particular:

* a tool to mesure the elevation (terrain or 3D models) in the scene:

![image](https://user-images.githubusercontent.com/16967916/176690961-17a98f6f-1d53-42e7-87f0-0c48cb85a5ad.png)

* a tool to mesure the distance and the height between two points:

![image](https://user-images.githubusercontent.com/16967916/176691507-7dc978e1-f49b-46c7-92dd-f5d9b945070c.png)

I was thinking to add these tools as widgets. Would this be the good way to add such tools ?

**Comment by mgermerie** [comment]
Hi !
You're wright, the widgets would be a relevant place for this, as they theoretically should gather all user graphical tools and interface. 
Moreover, the addition of a tool to pinpoint coordinates -including elevation- on the terrain would indeed be interesting. An extension of this tool to measure height and distance between two points would then be pretty straight forward -the most difficult part being displaying the rectangular triangle as the one shown in your second screenshot.

**Comment by jailln** [comment]
Hi,
Thanks for your feedback. I'm currently working on it on [this branch](https://github.com/iTowns/itowns/tree/feat/elevation-measure). I still have a few things to improve but the main features are working.
