### ISSUE TITLE
Sub-domains URL templating does not work

### ISSUE THREAD

**Issue by jailln** [iTowns/itowns#1883]
Either using sub-domains URL templating (such as described [here](https://github.com/iTowns/itowns/blob/master/src/Provider/URLBuilder.js#L25)) does not work or I don't use it properly.

The following error is thrown:

```
ypeError: Failed to construct 'URL': Invalid URL
    at Scheduler.execute (Scheduler.js:181:1)
    at updateLayeredMaterialNodeImagery (LayeredMaterialNodeProcessing.js:142:1)
    at ColorLayer.update (ColorLayer.js:145:46)
    at updateElements (MainLoop.js:88:1)
    at MainLoop._update2 (MainLoop.js:274:1)
    at MainLoop._step5 (MainLoop.js:326:1)
    at MainLoop.js:212:1
```

## Your Environment
* Version used: 2.38.2
* Browser Name and version: Google Chrome Version 104.0.5112.79 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Ubuntu 20.04

## Context
Url sub domains templating has been implemented in #1189

## Steps to Reproduce (for bugs)
1. Create a GlobeView
2. Add a TMSSource with the following config:
```
{
        "crs": "EPSG:3857",
        "isInverted": true,
        "format": "image/png",
        "url": "https://${u:a|b|c}.tile.openstreetmap.org/${z}/${x}/${y}.png",
        "attribution": {
            "name":"OpenStreetMap",
            "url": "http://www.openstreetmap.org/"
        },
        "tileMatrixSet": "PM"
}
```
4. Add a ColorLayer with this TMSSource
5. Add the layer to the globe
6. Launch the app in your browser

**Comment by mgermerie** [comment]
Hi !

Thanks for reporting it. I think you are using correctly, there was an issue in the Scheduler that I fixed in the linked PR.
