### ISSUE TITLE
3D Tiles debug tools: bounding spheres are not displayed

### ISSUE THREAD

**Issue by jailln** [iTowns/itowns#1888]
## Your Environment
* Version used: 2.38.2
* Browser Name and version: Firefox and Chrome
* Operating System and version (desktop or mobile): Linux

## Context

3D Tiles debug tools "bounding box" checkbox does not work for 3D Tiles tilesets with bounding spheres. There is no error in the console. It is limiting for debugging such tilesets.

## Steps to Reproduce (for bugs)
1. Create an example with a 3D Tiles tileset with bounding spheres (e.g. https://storage.yandexcloud.net/gis-3d-models/data/tiles3d/Valaam_Aerial_Survey/Scene/Cesium.json from #1859) and with a 3D Tiles debug UI (e.g. `debug.create3dTilesDebugUI(menuGlobe.gui, view, tileset, d);`)
2. Zoom to the tileset. Camera position for the above-mentioned tileset:
```
        var placement = {
            coord: new itowns.Coordinates('EPSG:4326', 30.950135, 61.395949, 0),
            range: 3000,
            tilt: 22,
        }
```
4. Check the "Bounding box" checkbox

## Expected Behavior
Bounding spheres should be displayed (the code exists but I don't know if it ever worked ?).

## Actual Behavior
Nothing is displayed.

**Comment by mgermerie** [comment]
The complete 3d-tiles support is planned in the short term road map. We are currently studying possibilities in terms of libraries to enhance support (as mentioned in https://github.com/iTowns/itowns/discussions/1917).
