### ISSUE TITLE
itowns-project website is broken in https

### ISSUE THREAD

**Issue by jailln** [iTowns/itowns#1896]
[itowns website in https](https://www.itowns-project.org/) is broken due to a `Mixed Content` error:

![image](https://user-images.githubusercontent.com/16967916/189357647-7c9caefc-a16f-433b-961f-f0bc5a14cd48.png)

**Comment by zarov** [comment]
You may try to update the [`url` in the website config](https://github.com/iTowns/itowns.github.io/blob/master/_config.yml#L7). If you take a look at it, a defined URL in the HTML file is `/itowns.github.io/js/init.js`, which is in fact `https://www.itowns-project.org/itowns.github.io/js/init.js`, but then it redirects to `http://www.itowns-project.org/js/init.js` (notice the missing `s`).

**Comment by scriptura** [comment]
Je confirme. Même [la documentation IGN pour iTowns](https://geoservices.ign.fr/documentation/services/utilisation-web/affichage-wmts/itowns-et-wmts) arrive sur des liens morts.

**Comment by jailln** [comment]
Problem solved with the website update. Regarding the IGN documentation for itowns, I informed the Geoportail team.
