### ISSUE TITLE
zero meridian ne passe pas par Greenwich?

### ISSUE THREAD

**Issue by qdnguyen** [iTowns/itowns#19]
j'ai vu que la repère a été décalé dans la fonction CoordCarto.prototype.setFromDegreeGeo, du coup la latitude zéro ne passe pas par Greenwhich comme dans la définition standard de Globe?

**Comment by gchoqueux** [comment]
Les params setFromDegreeGeo sont inversés etre longitude et latitude. Elle semble etre correct quand on l'utilise pour placer un object3D.

**Comment by qdnguyen** [comment]
Oui, en effet, tu décale la repère par rapport à longtitude, donc la longtitude varie entre (0, 360), latitude est toujours entre (-90, 90)

CoordCarto.prototype.setFromDegreeGeo = function(longitude,latitude,altitude)
    {
        this.longitude  = defaultValue(longitude \* Math.PI / 180 + Math.PI,0);
        this.latitude   = defaultValue(latitude  \* Math.PI / 180,0);
        this.altitude   = defaultValue(altitude,0);

```
    return this;
};
```

Puis dans le calcul de normal, tu ajoute un sign negative 

```
    var x = cosLatitude * Math.cos(-longitude);
    var z = cosLatitude * Math.sin(-longitude);
```

mais cos(theta + Pi) = -cos(theta) et cos(-theta) = - cos(theta)

donc je ne vois pas l'idée de décaler la longtitude et ajoute un négative dans le cos. 

et je ne sais pas si t'as utilisé cette fonction pour calculer le méridian zéro ou pas?

**Comment by qdnguyen** [comment]
D'après cette définition, les coordonées cartésians (x,y,z) de la france doivent être positives.
![globe](https://cloud.githubusercontent.com/assets/3224540/12717034/4c23922c-c8e5-11e5-856c-f0f87b4edb65.jpg)

Par contre, avec tes fonctions, j'ai des coords X négatives 

x:-4214069.296031713
y:4768605.457064305
z:171464.59457268883

c'est à dire la latitude zéro est inversé???

**Comment by vpicavet** [comment]
Please keep later issues in english only

**Comment by qdnguyen** [comment]
@gchoqueux : I saw your solution with the rotation of axis in Dev branch, i think the problem is not only rotation but also scale, as WGS84 is an ellipsoid. I did a test with a point and i see that it's under globe and it shift a bit from right position. It's because of scale and the way when we compute geodetic surface normal!

**Comment by gchoqueux** [comment]
A answer is provided in #178
