### ISSUE TITLE
Untitled in-place of iTowns in footer

### ISSUE THREAD

**Issue by Vinitvh** [iTowns/itowns#1907]
## Your Environment

* Version used: 2.38.2
* Browser Name and version: Firefox 104.0.2
* Operating System and version (desktop or mobile): Fedora 36 desktop

## Context

On the landing page footer, for copyright, it says Untitled instead of iTowns.
![footer](https://user-images.githubusercontent.com/42197888/191788851-4ac90711-2219-4b1e-a7e0-55432f33847d.png)

## Steps to Reproduce (for bugs)

1. On the homepage, scroll down to the footer.

**Comment by mgermerie** [comment]
Hi, thanks for noticing that ! I will make a PR to change it.

**Comment by Desplandis** [comment]
This issue was on the old website, we can close this issue.
