### ISSUE TITLE
Add tileset type in C3DTilesLayer

### ISSUE THREAD

**Issue by jailln** [iTowns/itowns#1913]
I think we should add booleans indicating which type of tileset a 3D Tiles is (i.e. which type of tiles it contains): 
* `hasPntsTiles` set to true if it has point cloud tiles (pnts tiles)
* `hasB3dmTiles` set to true if it has b3dm tiles (meshes)

And when it will be supported:
* `hasi3dmTiles` 
* `hasCmptTiles`

This would help itowns' users to process tilesets differently depending on what they represent (e.g. apply a style only to point cloud tilesets and another to meshes tilesets for instance).

Note: I chose `has...Tiles` on purpose instead of `is...` (e.g. isPointCloud) since 3D tiles tilesets can in theory have tiles of different types (which is actually rarely the case in practice).

@mgermerie WDYT?

**Comment by mgermerie** [comment]
The complete 3d-tiles support is planned in the short term road map. We are currently studying possibilities in terms of libraries to enhance support (as mentioned in https://github.com/iTowns/itowns/discussions/1917).

**Comment by mgermerie** [comment]
Once the support is implemented, it would be a good addition.

**Comment by jailln** [comment]
A piece of code that I have written in another context to check if a tileset has point cloud tiles and that might help to implement this issue:

```
    /**
     * Checks if a 3D Tiles layer represents a point cloud.
     * @param {itowns.C3DTilesLayer} nativeLayer the 3D Tiles layer to check
     * @returns true if the layer represents a point cloud and false otherwise 
     */
    function isLayerPointCloud(nativeLayer) {
        if (!nativeLayer || !nativeLayer.isC3DTilesLayer) {
            return false;
        }
        var tiles = nativeLayer.tileset.tiles;
        // Some tiles may not have a content and be there only for spatial subdivision. Find the first non empty tile 
        for (var i = 0; i < tiles.length; i++) {
            if (tiles[i].content && tiles[i].content.uri && tiles[i].content.uri.endsWith('pnts')) {
                return true;
            } else {
                return false;
            }
        }
        $log.warn("All 3D Tiles tiles are empty, this is unexpected. Cannot determine if it's a point cloud.");
        return false;
    };
```

**Comment by jailln** [comment]
Obsolete
