### ISSUE TITLE
Uncaught TypeError: THREE.Vector3 is not a constructor

### ISSUE THREAD

**Issue by alienatorZ** [iTowns/itowns#1932]
I am getting the this error when running a simple example from http://www.itowns-project.org/itowns/docs/#home

## Your Environment

itowns v:2.38.2
Chrome v:106.0.5249.119
Ubuntu Linux v22.04

## Steps to Reproduce (for bugs)
create-react-app
yarn add itowns three
replace App with 
`import logo from './logo.svg';
import './App.css';
import React from 'react';
import * as itowns from 'itowns';
import THREE from 'three';

class App extends React.Component{
  constructor(props){
    super(props);
    this.mapRef = React.createRef()
  }

  componentDidMount(){
    const mapNode = document.getElementById('mapDiv');
    let position = { longitude: 0, latitude: 0, altitude: 250000 };
    let view = new itowns.GlobeView(mapNode, position);

    itowns.Fetcher.json('http://www.itowns-project.org/itowns/examples/layers/JSONLayers/Ortho.json')
      .then(ortho => {
        var orthoSource = new itowns.WMTSSource(ortho.source);
        var orthoLayer = new itowns.ColorLayer('Ortho', {
          source: orthoSource,
        });
        view.addLayer(orthoLayer);
      });

    itowns.Fetcher.json('http://www.itowns-project.org/itowns/examples/layers/JSONLayers/IGN_MNT.json')
      .then(mnt => {
        var mntSource = new itowns.WMTSSource(mnt.source);
        var mntLayer = new itowns.ElevationLayer('IGN_MNT', {
          source: mntSource,
        });
        view.addLayer(mntLayer);
      });

  }

  render(){
    return(
      <div height="100%" width="100%" ref={this.mapRef} id='mapDiv'></div>
    )
  }
}

export default App;
`
yarn start

## Expected Behavior
I should see a map or something.

## Actual Behavior
blank screen with console error `Ellipsoid.js:26 Uncaught TypeError: THREE.Vector3 is not a constructor
    at ./node_modules/itowns/lib/Core/Math/Ellipsoid.js (Ellipsoid.js:26:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/itowns/lib/Core/Geographic/Coordinates.js (Coordinates.js:22:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/itowns/lib/Core/Geographic/Extent.js (Extent.js:18:1)
    at options.factory (react refresh:6:1)`

## Possible Cause/Fix/Solution
I dont know

**Comment by jailln** [comment]
Hi @alienatorZ, 
Can you try to replace `import THREE from 'three';` by `import * as THREE from 'three';` and let me know if it's better?

**Comment by alienatorZ** [comment]
Yes that does work. Thank you!
