### ISSUE TITLE
Wrong bounding box computing for negative elevation data

### ISSUE THREAD

**Issue by mgermerie** [iTowns/itowns#1945]
When displaying some negative elevation data in an `ElevationLayer`, the bounding boxes of tiles are clamped above `-10` meters.
This is caused by [this line](https://github.com/iTowns/itowns/blob/master/src/Parser/XbilParser.js#L53) when computing the minimal and maximal value of elevation data within a given tile.

This value has been hard coded to prevent an issue with geoportail elevation data. Along the coast line, these data contain isolated points with extremely low altitude (sometimes lower than the earth radius). The bounding sphere of the tiles is therefore huge, exceeding the `sse` threshold above which tiles are subdivided. It causes tiles along the coast line to be subdivided too much. This can be seen in the screenshot bellow.

![Capture d’écran du 2022-11-08 17-33-27](https://user-images.githubusercontent.com/73115044/200622318-61acae84-5ed3-417d-bf83-7da1fe98a5e3.png)

Clamping the minimal elevation value of a tile prevents this. However, relevant negative elevation values should not be clamped.

The `-10` hard coded value should be parametrized in the `ElevationLayer` creation, with a default value of `-Infinity`.

**Comment by jailln** [comment]
There is another one [here](https://github.com/iTowns/itowns/blob/master/src/Parser/XbilParser.js#L12) :)
