### ISSUE TITLE
How to unload invisible tiles from the memory ?

### ISSUE THREAD

**Issue by LorenzoMarnat** [iTowns/itowns#1947]
I have a 3D Tiles tileset with textured tiles. The tileset use a `replace` refinement to load tiles with more or less detailled texture images when zooming in/out.

After being replaced, the tiles aren't unloaded from the browser memory. I would like to know if there is a way to unload invisible tiles from the memory ?

## Your Environment

* Version used: 2.38.0
* Browser Name and version: Firefox 106.0.5 (64 bits)
* Operating System and version (desktop or mobile): Windows 11
* Link to your project: [UD-Demo-vcity-py3dtilers-lyon](https://github.com/VCityTeam/UD-Demo-vcity-py3dtilers-lyon), based on [UD-Viz](https://github.com/VCityTeam/UD-Viz)

## Context

I have a 3D Tiles tileset with textured tiles. The tileset use a `replace` refinement to load tiles with more or less detailled texture images when zooming in/out.

![image](https://user-images.githubusercontent.com/32875283/202210320-86346a47-dd7b-451d-9e80-8a847ae28a07.png)
[_Link to online demo_](https://py3dtilers-demo.vcityliris.data.alpha.grandlyon.com/html/textured.html)

[_Link to tileset_](https://dataset-dl.liris.cnrs.fr/three-d-tiles-lyon-metropolis/Demo/UD-Demo-vcity-py3dtilers-lyon/Lyon-1_2018_Textured/)

After being replaced, the tiles aren't unloaded from the browser memory. Memory usage increases as more tiles are loaded, and never decreases.

![image](https://user-images.githubusercontent.com/32875283/202212156-1776374a-4dbb-498d-8515-7e1912c2fe01.png)

![image](https://user-images.githubusercontent.com/32875283/202212593-4f784ef1-ed2f-498c-a770-6dc9f87e4467.png)

I tried using the `cleanupDelay` config option of `C3DTilesLayer`, but it doesn't seem to change anything.

```js
  const $3dTilesLayer = new itowns.C3DTilesLayer(
    layer['id'],
    {
      name: layer['id'],
      source: new itowns.C3DTilesSource({
        url: layer['url'],
      }),
      registeredExtensions: extensions,
      overrideMaterials: overrideMaterial,
      cleanupDelay: 1,
    },
    itownsView
  );
```

I would lke to know if there is a way to unload invisible tiles from the memory ?

## Expected Behavior

I'd like the tiles to be unloaded after being set invisible, or after a few seconds after being set invisible (and loaded again we need to display them).

## Actual Behavior

Invisible tiles stay in memory after being displayed once.

**Comment by jailln** [comment]
Hi @LorenzoMarnat ,

Currently it is not possible to specify that invisible tiles should be removed from the cache but `cleanupDelay` should work and allow to clean tiles from the cache x ms after the time a tile becomes invisible. I think it may be due to `_cleanupObject3D` that does not dispose all threejs sources correctly (for instance textures are not disposed). It should use `Object3DRemovalHelper`. I will push a fix.

In the future, we plan to improve the cache system by allowing to activate cache or not and by providing an API to clear it totally or partially, etc. (see #1928).

**Comment by LorenzoMarnat** [comment]
Thanks ! I'll take a look at these methods and follow the evolution of the cache system

**Comment by jailln** [comment]
@LorenzoMarnat [this branch](https://github.com/iTowns/itowns/tree/fix/1947-3d-tiles-cache-cleanup) should improve 3d tiles cache cleaning. I think we can still do better but let me know if that's better (or not :grin: )

I'll open a PR once #1886 is merged.
