### ISSUE TITLE
Dead link in the documentation (RasterNode)

### ISSUE THREAD

**Issue by loopfinito** [iTowns/itowns#1950]
Hello,

I've found a dead link in the documentation : http://www.itowns-project.org/itowns/docs/#api/Layer/RasterNode

Thank you

**Comment by mgermerie** [comment]
Hi !

Thanks for noticing this issue. It is indeed an error on the class name which appeared after some refactoring and renaming.
This issue shed lights on a related one, which is that code ofen times calls for `RasterNode` name (like [here](https://github.com/iTowns/itowns/blob/fd0f01bf9eaa7277e2627fde40eda4ced3805a03/src/Layer/ColorLayer.js#L106)). We need to harmonize names. I open an issue about this in #1951
