### ISSUE TITLE
potree layer source CRS & globeView CRS

### ISSUE THREAD

**Issue by PerspectivesLab** [iTowns/itowns#1959]
I there, i am trying to display a potree point cloud that was referenced in EPSG:3944, i would like to know if that is possible ?
 **i cant seem to view it in the scene**
 
 
```
   proj4.defs("EPSG:3944","+proj=lcc +lat_0=44 +lon_0=3 +lat_1=43.25 +lat_2=44.75 +x_0=1700000 +y_0=3200000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs +type=crs");
   
   const viewerDiv = document.getElementById("#mydiv_id");
    let view = new itowns.GlobeView(viewerDiv ) // default EPSG:4978
    
     var potreeLayer = new itowns.PotreeLayer( "my name", {
            source: new itowns.PotreeSource({
                file: 'cloud.js',
                url: mypotreeUrl,
                crs:  "EPSG:3944" // << here i precise crs source
            }),

        });
```
    when loaded, if i log : 
console.log( potreeLayer.crs ) => EPSG:4978 => same as the globe view
do potree point clouds need to be converted in the destiantion crs as the globe view, and then viewed in itowns,
or potree sources can have different crs as the globe view, but specified like i do ?
thank you

**Comment by jailln** [comment]
Hello,
iTowns doesn't support reprojecting point clouds on the fly for now so your dataset needs to be in the same CRS as the view. Therefore, you either have to convert your point cloud to EPSG:4978 and display it with a `GlobeView` or to create a `PlanarView` in EPSG:3944.

**Comment by PerspectivesLab** [comment]
@jailln thank you, it is clear now
