### ISSUE TITLE
Explicit link between itowns next version and associated PR

### ISSUE THREAD

**Issue by jailln** [iTowns/itowns#1963]
#1909 adds a deployment of itowns after each PR (published with names such as `2.39.1-next.0`, `2.39.1-next.1`, etc.). However, there is no easy way to know which next version is associated with which PR (from the itowns-next versions lists available on the npm registry to the PR or from the PR to the itowns next version).

Is it possible to add such a link between the two ? (e.g. add the associated PR number in a `description` field of the itowns-next version and the itowns-next version in a comment of the PR).

**Comment by jailln** [comment]
What could be done instead (and which would be easier) would be to create a tag for each published next version. It would allow to checkout the next versions easily. WDYT @mgermerie  @Desplandis ?

**Comment by mgermerie** [comment]
Maybe what could be easier than having a tag - which we would have a lot to manage - would be to have an automatic comment on a PR when it is merged. Could be something like "Merged in `X.x.x-next.x`." I think implementing this in deployment script would be fairly easy with existing actions like [this one](https://github.com/marketplace/actions/comment-pull-request).

**Comment by jailln** [comment]
Actually I just found out today about the recent [npm provenance](https://github.blog/changelog/2023-09-26-npm-provenance-general-availability/) wich seems to bind releases to github repositories and commits sha1. It doesn't seem to complicated to implement. We can try to use it for the next release and see if it answers this need, wdyt?

**Comment by mgermerie** [comment]
That's a good finding ! I just have one interrogation : if we can link a npm version to a specific commit, what will happen when a multiple commits PR is merged ? Only the latest will be linked ?

**Comment by jailln** [comment]
Yes the last one because the version will be built from the last one

**Comment by Desplandis** [comment]
Yeah, we could link to the last commit on the `master` branch which is merged into the `next` branch (and before the `2.40.1-next.X` commit). As such a user of the `itowns-next` package could know that a release contains all merged developments until this commit.

@jailln: You found a way to tag the provenance of a release on `npmjs`, maybe we could use this to provide this information?

**Comment by jailln** [comment]
> @jailln: You found a way to tag the provenance of a release on `npmjs`, maybe we could use this to provide this information?

yep, see previous comments :grin:
