### ISSUE TITLE
3D tiles camera view LOD issue

### ISSUE THREAD

**Issue by alexLuky** [iTowns/itowns#1987]
## Your Environment
Itowns example page

## Context
3D tiles rendering is not good because it makes not visible (or low LOD) tiles that are closely near the camera ( [video](https://youtu.be/WxRkMlW9TO8) ). Theoritically I can understand this behavior for further tiles but not for the closest. If we compare the behavior with cesium rendering we can see that further tiles also dissappears but not the closest ones. They are stable. It looks like basic algorythmic 3D tiles rendering issue in iTowns. 

## Steps to Reproduce (for bugs)
Video to reproduce: [https://youtu.be/WxRkMlW9TO8](https://youtu.be/WxRkMlW9TO8)

## Expected Behavior
Only further tiles has to be hidden, but not the closest ones. 
Can you suggest a better way to control the far limit of dissappearing of further tiles without editing dataset's json schema?

## Possible Cause/Fix/Solution
It looks like there is a problem with calculating the SSE of the tiles and the camera. May be the closest tile dissappears because it's too big and when I move the camera it reaches the far limit and as a result the render hides it. Perhaps iTowns uses less LOD in this case than Cesium does,

**Comment by jailln** [comment]
Hi, 
thanks for this issue, I will take a look at it.

**Comment by alexLuky** [comment]
@jailln 
Why this happening? It looks like this behavior and the previous one have the same reason... it looks like itowns has basic tiles rendering algorythmic shortcomings... 
[https://www.youtube.com/watch?v=qGOsbA2-IZs](https://www.youtube.com/watch?v=qGOsbA2-IZs)

**Comment by alexLuky** [comment]
> @jailln Why this happening? It looks like this behavior and the previous one have the same reason... it looks like itowns has basic tiles rendering algorythmic shortcomings... https://www.youtube.com/watch?v=qGOsbA2-IZs

I think it would be better to hide the tiles nodes and meshes only after the new one's data has been loaded and rendered. Now it looks like firstly we hidding the old one and only then rendering the new one. Also why do we have to hide the tiles that are in our field of view?

**Comment by jailln** [comment]
Fixed with the new layer OGC3DTilesLayer
