### ISSUE TITLE
Expose B3dm parser 

### ISSUE THREAD

**Issue by clementcolin** [iTowns/itowns#1990]
The 'default' [B3dm parser](https://github.com/iTowns/itowns/blob/master/src/Main.js#L94) is not exposed yet, making it impossible to use from the package.
Is it possible to expose it ?

**Comment by jailln** [comment]
Hi @clementcolin,
What is your usecase?

**Comment by clementcolin** [comment]
I want to be able to drag and drop a 3DTiles and visualize it using itowns, following the same mechanism as [this geojson/kml example](http://www.itowns-project.org/itowns/examples/#plugins_drag_n_drop).
Therefore, I need to be able to read a json and the tiles as b3dm. The json can easily be read, but I need to be able to use the B3dm parser to read the tiles.  

To give you a glimpse of my usecase, I have a first working [WIP result ](https://github.com/VCityTeam/UD-Viz/tree/draganddrop) that import the parser in a very non recommended way (from the node modules)
![local_3dtiles](https://user-images.githubusercontent.com/31923744/214820569-78457200-2d7c-43fa-ae8d-6fb59f9bf717.gif)

**Comment by jailln** [comment]
Ok, I don't see any issue in exposing it since all other parsers are already exposed. We should also expose the `pntsParser` at the same time. Do you want to open a PR to do it ? (you just need to add them to the list of exports in `Main.js`)

**Comment by jailln** [comment]
Obsolete since the migration to 3d-tiles-renderer
