### ISSUE TITLE
cache et gestion de mémoire CPU/GPU

### ISSUE THREAD

**Issue by qdnguyen** [iTowns/itowns#20]
On utilise des caches pour cacher les bil/images téléchagés depuis l'internet mais ces caches ne sont pas paramétrés pour s'adapter au capacité de chaque device, ni un policy à remplacer si la cache est plein. 

Il nous faut penser à une cache non seulement pour stocker les résultats du téléchargement, mais aussi pour la gestion de mémoire de CPU et GPU.

Technique note: le transfert PCI Express entre mémoire CPU et GPU est expensive, donc cacher les tuiles sur la mémoire GPU en utilisant juste (tuile.visible = true/false) est cool, mais il nous faut penser à nettoyer la mémoire GPU quand elle est pleine par scene.remove. 

A améliorer???

**Comment by gchoqueux** [comment]
in english, please
