### ISSUE TITLE
Picking API modification

### ISSUE THREAD

**Issue by jailln** [iTowns/itowns#2003]
I would like to propose a little modification in the picking API of `View.js` to ease its usage.

My use case (which may be pretty common I think) is to pick objects in a scene with several itowns Layers and also 3D objects  that have been added directly to the threejs scene (e.g. representing gltfs). Currently, to pick objects from itowns layers and from the gltf objects, I have to do something like:

```
    // Pick objects from layers added in itowns directly
    var pickedObjs = this.view.pickObjectsAt(event);
    // Pick gltf objects (added directly to the threejs scene so we have to explicitely pass them to itowns
    // picking method)
    var gltfLayers =getLayersOfType('gltf');
    for (var i = 0; i < gltfLayers.length; i++) {
        var picked = this.view.pickObjectsAt(event, 0, gltfLayers[i]);
        if (picked && picked.length > 0) {
            pickedObjs = pickedObjs.concat(picked);
        }
    }
```

I propose to allow to pass an array of layers (which can be itowns layers or threejs `Object3D`) that should be picked. Therefore, to make the `where` argument of [view.pickObjectsAt](https://github.com/iTowns/itowns/blob/master/src/Core/View.js#L706) an array of layers. 

WDYT @gchoqueux @mgermerie @ftoromanoff ?

**Comment by mgermerie** [comment]
Hi ! From what I see in [the doc](https://github.com/iTowns/itowns/blob/c83bfcf74ceee1358d2070b1c90079900744086e/src/Core/View.js#L691-L693), the `where` argument can already be an array of `GeometryLayers` and `THREE.Object3D`. Do you mean that the `where` argument should allow any type of `Layer` and not only `GeometryLayer` ?

**Comment by jailln** [comment]
That's what I thought from the documentation too but it can only be an array of ids or a single `GeometryLayers` or `Object3D`. If it is an array of `GeometryLayers` and/or `Object3D`, [this line](https://github.com/iTowns/itowns/blob/c83bfcf74ceee1358d2070b1c90079900744086e/src/Core/View.js#L709) turns it into an array with only one entry that contains the array of layers passed as arguments.

Maybe it's not an API modification but a bugfix then ^^ I will open a PR
