### ISSUE TITLE
Bounding boxes of 3D Tiles are always displayed

### ISSUE THREAD

**Issue by jailln** [iTowns/itowns#2021]
Bounding boxes of 3D Tiles are always displayed by default:

![image](https://user-images.githubusercontent.com/16967916/223730978-01d83912-df39-4f63-b353-10fb4b38c1c7.png)

See http://www.itowns-project.org/itowns/examples/index.html#3dtiles_basic for example

@gchoqueux related to #1974 ?

**Comment by gchoqueux** [comment]
@jailln, I'll look at
