### ISSUE TITLE
Jiggling lines

### ISSUE THREAD

**Issue by jailln** [iTowns/itowns#2023]
In a project using iTowns I added [threejs lines](https://threejs.org/docs/#api/en/objects/Line) in the scene. When moving the camera in the scene, the lines are vibrating / jiggling, see the following gif:

![vibratin-lignes](https://user-images.githubusercontent.com/16967916/223996956-bcaac7e4-21a8-4d68-b701-50f82b570f9e.gif)

This happens no matter what the size of the line is.

While searching online I found several similar issues in big 3D worlds (which is obviously our case) and they mainly say it's a precision issue but I haven't found out a solution yet. 

Did you ever experienced this error in iTowns? Is it why there is an implementation of a logarithmic depth buffer?

**Comment by gchoqueux** [comment]
@jailln it's a jittering, because the vertex position are too big.
The transformations aren't precise enough in the `vertex shader` because the data are in `float32 `.
To fix it, the data must be moved in a local system.

**Comment by jailln** [comment]
ah yes thanks this fixes the problem :)
