### ISSUE TITLE
Is there a public roadmap beyond the milestones ?

### ISSUE THREAD

**Issue by EricBoix** [iTowns/itowns#2024]
## Your Environment
Environment is not relevant.

## Context
Not relevant.

The [itowns milestones](https://github.com/iTowns/itowns/milestones) express (are a form of) a short term roadmap with an horizon of one to two months (two minor releases of one-month development cycles). Does there exist a mid-term roadmap and is it public ?

**Comment by jailln** [comment]
Hi @EricBoix, 
The milestones are not up to date but we plan to use them better in the coming weeks to give a more precise short-term vision on the tickets we plan to develop in the next versions.
Moreover, we are currently re-designing the website where there will be such a mid-term roadmap. It should be up online in the coming month hopefully :)
