### ISSUE TITLE
WMTS Source and vendor specific attributes

### ISSUE THREAD

**Issue by mbenevole** [iTowns/itowns#2027]
## Your Environment

* Version used: any
* Browser Name and version: any
* Operating System and version (desktop or mobile): any
* Link to your project: https://www.telecense.com

## Context
WMTS sources are not accepting vendor specific values as WMS Sources

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Expected Behavior
Same as WMS Sources : hability to add vendorSpecific attributes.

## Actual Behavior
vendorSpecific attributes are not accepted

## Possible Cause/Fix/Solution
Put inside WMTS Source the same code as WMS Source. 

After line 88  

this.vendorSpecific = source.vendorSpecific;
        for (const name in this.vendorSpecific) {
            if (Object.prototype.hasOwnProperty.call(this.vendorSpecific, name)) {
                this.url = `${this.url}&${name}=${this.vendorSpecific[name]}`;
            }
        }

**Comment by jailln** [comment]
Thanks for this issue :)
Since you know how to fix this issue, would you be willing to open a PR for it ? (see the [contributing guide](https://github.com/iTowns/itowns/blob/master/CONTRIBUTING.md))
