### ISSUE TITLE
3dTiles bounding box displayed by default

### ISSUE THREAD

**Issue by alavenant** [iTowns/itowns#2040]
Hy, 

The 3dTiles bounding box is displayed by default, even if the option is unchecked

Thanks,
Antoine

<img width="1049" alt="Capture d’écran 2023-03-17 à 10 45 01" src="https://user-images.githubusercontent.com/28431743/225869831-feb1a6c2-f97c-49c5-86dd-be5a53c18441.png">

**Comment by jailln** [comment]
Duplicate of #2021
