### ISSUE TITLE
Minor event name error in C3DTilesLayer events

### ISSUE THREAD

**Issue by mgermerie** [iTowns/itowns#2113]
The PR #2060 introduced a change on how `C3DTilesLayer.onTileContentLoaded` callback was used. It was switched from a function that is passed as a layer parameter to an event dispatched - leaving the user with the responsibility to call the callback when event is triggered. This change is a good move on layer's architecture.

However, there is an issue in its implementation : the event type is defined [here](https://github.com/iTowns/itowns/blob/1ec89f283ca1d3cc7eca5535f4bc19da039a6b6a/src/Layer/C3DTilesLayer.js#L18), with the name `C3DTILES_LAYER_EVENTS.ON_TILE_CONTENT_LOADED`. In the deprecation part for the previous `onTileContentLoaded` parameter for `C3DTilesLayer` constructor, an event listener is added ([here](https://github.com/iTowns/itowns/blob/1ec89f283ca1d3cc7eca5535f4bc19da039a6b6a/src/Layer/C3DTilesLayer.js#L99)) but its type is `C3DTilesLayer.EVENT_TILE_CONTENT_LOADED`, which is undefined. It should be renamed to `C3DTILES_LAYER_EVENTS.ON_TILE_CONTENT_LOADED`.

**Comment by jailln** [comment]
Obsolete since we moved to 3DTilesRendererJS
