### ISSUE TITLE
C3Dtiles ON_TILE_CONTENT_LOADED doesn't catch the root content

### ISSUE THREAD

**Issue by gchoqueux** [iTowns/itowns#2121]
https://github.com/iTowns/itowns/blob/619a611dd9a318bda0466734c49befc9b652d36a/src/Layer/C3DTilesLayer.js#L109-L112

1. ~`C3DTilesLayer.EVENT_TILE_CONTENT_LOADED`  doesn't exit, it's `C3DTILES_LAYER_EVENTS.ON_TILE_CONTENT_LOADED` this should be instead?~ fixed in #2122
2. `c3DTilesLayer.addEventListener(C3DTilesLayer.ON_TILE_CONTENT_LOADED, config.onTileContentLoaded);`   can use just after instancing, but the listener doesn't catch the root content.

**Comment by jailln** [comment]
Obsolete since the migration to 3d-tiles-renderer-js
