### ISSUE TITLE
3D tiles -wrong bounding volume box orientation

### ISSUE THREAD

**Issue by jogarnier** [iTowns/itowns#2126]
When I zoom or pan some tiles just not render or whole tileset destructs until the view angle or zoom will not be changed. (really similar to https://github.com/iTowns/itowns/issues/1859) but with bouding boxes

## Your Environment

https://github.com/iTowns/itowns/assets/111570217/4d987951-2f27-4566-beca-4a92e55e256f

* Version used: 2.39.0
* Browser Name and version: Chrome 114.0.5735.199 / Firefox 114.0.2
* Operating System and version (desktop or mobile): Windows 10
* Link to your project:  https://github.com/jogarnier/itowns/tree/feat/google3dTiles (you'll need an instanciation of a C3DTilesGoogleSource with your own Google api key, example is not provided yet)

## Steps to Reproduce (for bugs)

1. https://github.com/jogarnier/itowns/tree/feat/google3dTiles
2. add a C3DTilesGoogleSource with your own Google api key
3. deactivate globe layer view
4. zoom on globe

## Expected Behavior
Tiles rendered should stay visible until replaced by a lower / higher level tile

## Possible Cause/Fix/Solution
Bouding boxes seems to be non oriented as expected ?

**Comment by jailln** [comment]
It's because bounding volumes of type 'box' are interpreted as AABB while there are OBB in [this method](https://github.com/iTowns/itowns/blob/master/src/Core/3DTiles/C3DTBoundingVolume.js#L70).

**Comment by jailln** [comment]
Fixed by the move to 3DTilesRendererJS
