### ISSUE TITLE
Bug when we use custom renderer with potree point cloud

### ISSUE THREAD

**Issue by ketourneau** [iTowns/itowns#2142]
We try to use itowns in a vite project to display potree point cloud but we got error:

![Capture d’écran 2023-07-17 à 15 41 08](https://github.com/iTowns/itowns/assets/39763266/0cd8835d-329a-4941-a71d-a45d79fa2469)

Error appears when we pass custom renderer to itowns view.
```
const customRenderer = new THREE.WebGLRenderer();
const customCamera = new THREE.PerspectiveCamera(...);
...

const view = new itowns.View('EPSG:3946', viewerDiv, {
    camera: { cameraThree: customCamera },
    renderer: customRenderer,
});
```

I made a codesanbox to reproduce the issue [here](https://codesandbox.io/p/github/bloc-in-bloc/itowns-starter/potree-loader?file=%2Fsrc%2Fmain.ts%3A25%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clk6wi4et01e42e6ezwwzlai8%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clk6wi4et01dy2e6enfkf2q1d%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clk6wi4et01e12e6enfw6uzlw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clk6wi4et01e32e6e2wt2kwnx%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clk6wi4et01dy2e6enfkf2q1d%2522%253A%257B%2522id%2522%253A%2522clk6wi4et01dy2e6enfkf2q1d%2522%252C%2522activeTabId%2522%253A%2522clk6wjzvm01u52e6eyx4bnyop%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clk6wi4et01dx2e6eaaa9pm5j%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fmain.ts%2522%252C%2522id%2522%253A%2522clk6wjzvm01u52e6eyx4bnyop%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clk6wi4et01e32e6e2wt2kwnx%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clk6wi4et01e22e6eu7dajqbh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252Fitowns-starter%252F%2522%257D%255D%252C%2522id%2522%253A%2522clk6wi4et01e32e6e2wt2kwnx%2522%252C%2522activeTabId%2522%253A%2522clk6wi4et01e22e6eu7dajqbh%2522%257D%252C%2522clk6wi4et01e12e6enfw6uzlw%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clk6wi4et01dz2e6eyiji8p3h%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clk6wi4et01e02e6e79mem3gw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clk6wgnty000ph4es5rmx90gq%2522%257D%255D%252C%2522id%2522%253A%2522clk6wi4et01e12e6enfw6uzlw%2522%252C%2522activeTabId%2522%253A%2522clk6wi4et01dz2e6eyiji8p3h%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by jailln** [comment]
And yet [your code works in an itowns example](https://github.com/jailln/itowns/blob/debug/2142-vite-itowns/examples/view_3d_map.html). The error appears when importing fragment shaders (which is done in the point clouds shaders in itowns). I'm not familiar with vite but maybe it's not supported with vite and you need to use a plugin [like this one](npmjs.com/package/vite-plugin-glsl) ?

**Comment by Desplandis** [comment]
I manage to reproduce your issue locally. From the warning on the console, it seems that `Multiple instances of Three.js [are] being imported`.

Three.js glsl prepocessor resolves include directives from the [ShaderChunk]( https://threejs.org/docs/#api/en/renderers/shaders) object. When imported, itowns appends its own "chunks" of glsl (e.g. `itowns/WebGL2_pars_vertex`) to its three's instance `ShaderChunk`. If your project and itowns import different instances of three, such chunks would not be available to your project's three instance leading to such error.

I suspect that vite, when bundling, duplicates the `three` dependency.
