### ISSUE TITLE
Errors in cesium ion example 

### ISSUE THREAD

**Issue by jailln** [iTowns/itowns#2144]
## Your Environment
* Version used: current master
* Browser Name and version: Chrome and FF
* Operating System and version (desktop or mobile): Linux
* Link to your project: https://github.com/iTowns/itowns/blob/master/examples/3dtiles_ion.html

## Context
The following errors occurs when running the 3D Tiles from Cesium ion example:

![image](https://github.com/iTowns/itowns/assets/16967916/662f11e9-862c-4235-98c9-95c5bc8d1289)

**Comment by valentinMachado** [comment]
may be related https://github.com/iTowns/itowns/issues/2074

**Comment by jailln** [comment]
Obsolete
