### ISSUE TITLE
3DTiles pointcloud stop being loaded/requested

### ISSUE THREAD

**Issue by valentinMachado** [iTowns/itowns#2147]
## Your Environment
Google chrome Version 112.0.5615.49 (Build officiel) (64 bits), Ubuntu

## Context
Part of a 3DTiles pointcloud are not being loaded anymore after the camera point of view has changed. As you can see in the video below:
[BUG Pointcloud example.webm](https://github.com/iTowns/itowns/assets/14295096/08ce247c-752e-4234-b09a-f19e847905ff)

To reproduce you can pull this [branch](https://github.com/VCityTeam/UD-Viz/tree/bug_3DTiles_pointcloud) then run `npm i` and `npm run debug` and finally browse to this url http://localhost:8000/examples/bug.html. In the bug example typing `n` move the camera point of view to the next one over an array of 3 point of view. Making a full iteration (0->1->2->0) should reproduce this bug.

Note that tile requested display a box3 and if there is at least one tile requested an ui element is displayed on the top right corner of the screen (to be sure that no tiles are being loaded/requested)

If this bug reproduction is not convenient tell me where and how to do one.

## Expected Behavior
For a camera point of view the 3DTiles point cloud loaded should always be the same.

## Actual Behavior
Not the case as you can see in the video.

**Comment by jailln** [comment]
Not reproduced with the new OGC3DTilesLayer
