### ISSUE TITLE
Control Class

### ISSUE THREAD

**Issue by vcoindet** [iTowns/itowns#215]
Create the class "Control" : 

- [x] Control (constructor) 

**Methods**

- [x] getName()  
- [x] getMap()  
- [x] getElement()  
- [x] setOptions(pOptions)  
- [x] getOptions()  _In Progress_
- [x] listenToMap(pEventName, pCallback) 
- [x] getGlobe()  
- [x] setGlobe(map)  

**In API**

- [x] addControl(control)  
- [x] getControl(control)  
- [x] removeControl(control)

**Comment by vcoindet** [comment]
see PR #222

**Comment by gchoqueux** [comment]
move in #222
