### ISSUE TITLE
error THREE.GLTFLoader: setKTX2Loader 

### ISSUE THREAD

**Issue by vladimir-rybalko** [iTowns/itowns#2170]
### Your Environment
**Version used**: current master
**Browser Name and version**: Chrome and FF
**Operating System and version (desktop or mobile)**: Windows
**Link to your project**: https://codesandbox.io/s/itowns-3d-tiles-kt6r4x
### Context
When loading 3D tiles, an error occurs - _THREE.GLTFLoader: setKTX2Loader must be called before loading KTX2 textures._
Data prepared in Agisoft Metashape.
![image](https://github.com/iTowns/itowns/assets/3933179/68df9eca-d6d9-4ca6-b921-e7b6b6b7d833)

**Comment by jailln** [comment]
Some 3D Tiles contains GLTFs with textures compressed with KTX2. To load them, you need to specify to the `GLTFLoader` a [KTXLoader](https://threejs.org/docs/index.html?q=ktx2loade#examples/en/loaders/KTX2Loader) that points to the ktx2 decoder library. I implemented an helper function `enableKtx2Loader` (similar to `enableDracoLoader`) to do so in #2172. I tested it with your model and it works

**Comment by vladimir-rybalko** [comment]
> Some 3D Tiles contains GLTFs with textures compressed with KTX2. To load them, you need to specify to the `GLTFLoader` a [KTXLoader](https://threejs.org/docs/index.html?q=ktx2loade#examples/en/loaders/KTX2Loader) that points to the ktx2 decoder library. I implemented an helper function `enableKtx2Loader` (similar to `enableDracoLoader`) to do so in #2172. I tested it with your model and it works

Thank you for your quick response.
I compiled the code from your [repository](https://github.com/jailln/itowns/tree/feat/add-ktx2-loader) and fixed some of the code in the my [sandbox](https://codesandbox.io/s/itowns-3d-tiles-kt6r4x). The error has fixed, but I don't see the model in the scene.
@jailln, сan you attach a working example of the code here so that I can understand what my problem?

**Comment by jailln** [comment]
I pushed it on [this branch](https://github.com/jailln/itowns/tree/vladimir-example). You can clone it, do `npm install`, `npm start` and go to `http://localhost:8080/examples/vladimir-example.html` :

![image](https://github.com/iTowns/itowns/assets/16967916/3a2152aa-83d0-4e4d-b44f-c0766644fac6)

It has no roof though :grin: but this may come from the model?

**Comment by vladimir-rybalko** [comment]
The no roof though is a model problem.
Thanks for the help, it works.
![image](https://github.com/iTowns/itowns/assets/3933179/2e146d9e-f24d-445d-a424-bea66fbad0da)
