### ISSUE TITLE
2 packages are missing in the 3d-tiles branch

### ISSUE THREAD

**Issue by Tofull** [iTowns/itowns#219]
Hi,

I tried to compile Itowns (3d-tiles branch) from scratch. 
Some packages are missing in the *package.json* file : *proj4* and *earcut*. 
I suggest to add these lines in the *dependencies* lists : 
>
>    "earcut": "^2.1.1",
>    "proj4": "^2.3.15"
>

Otherwise the developer who wants to use that branch needs to launch : 
```bash
npm install earcut --save
npm install proj4 --save
```

This issue seems to come from these packages have been installed with "-g* option once.

**Comment by Jeremy-Gaillard** [comment]
Hi,

You are perfectly right. I was reluctant to add proj4 as it is only a temporary workaround until the planar mode is finalised. Since other people may want to test the branch, I'll add the dependencies.

**Comment by Jeremy-Gaillard** [comment]
It's done. By the way, if you want a working demo (that does not rely on a local server), you can try the branch 3d-tiles_POC.
