### ISSUE TITLE
[Bug - Example] source_file_from_parsed_data examples broken 

### ISSUE THREAD

**Issue by jailln** [iTowns/itowns#2207]
The example `source_file_from_parsed_data.html` is broken.

## Your Environment
* Version used: master
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Ubuntu 22
* Link to your project: https://www.itowns-project.org/itowns/examples/#source_file_from_parsed_data

## Context
Nothing is displayed and the following error is thrown:

```
View.js:10 Uncaught TypeError: Cannot read properties of undefined (reading 'source')
    at GlobeView.<anonymous> (source_file_from_parsed_data.html:99:67)
    at GlobeView.dispatchEvent (three.module.js:281:1)
    at GlobeView.fn (View.js:229:1)
    at GlobeView.dispatchEvent (three.module.js:281:1)
    at View._this._allLayersAreReadyCallback (View.js:220:1)
    at GlobeView.execFrameRequesters (View.js:775:1)
    at MainLoop._step5 (MainLoop.js:290:1)
    at MainLoop.js:169:1
```

**Comment by ftoromanoff** [comment]
If I'm not mistaken, this Issue was already raised (issue #2188) and closed as it has been solved with PR #2187.
I tested the exemple on the current master and it is working but it is still bug on itowns-project (the last release).

**Comment by ftoromanoff** [comment]
I cannot reproduce this error. The exemple is working on my side...
It might have been linked with a connection problem at the time you was testing.

**Comment by jailln** [comment]
Indeed it's working now. The error could be more explicit though, we could add a try/catch or a promise reject when the source is not available
