### ISSUE TITLE
WGS84

### ISSUE THREAD

**Issue by Jeremy-Gaillard** [iTowns/itowns#223]
Hi,

Is there a reason why the iTowns globe doesn't use the standard WGS84 axes? [In the WGS specification](http://www.unoosa.org/pdf/icg/2012/template/WGS_84.pdf), the z axis goes through the north pole, while in iTowns, it is the y axis. This is pretty annoying when trying to import external data, since it requires rotating the axes in the providers.

**Comment by gchoqueux** [comment]
In iTowns, Three.js use Y axe is axe up.
You can import your data in this [`layerWGS84Zup`](https://github.com/iTowns/itowns2/blob/master/src/Globe/Globe.js#L40) 
And uncomment
```js
// this.add(this.layerWGS84Zup);
```

**Comment by qdnguyen** [comment]
i think this problem was resolved longtime ago? #19

**Comment by Jeremy-Gaillard** [comment]
There is a workaround using `layerWGS84Zup`. But not having the proper WGS84 axes by default can easily lead to errors, so we should fix it.
