### ISSUE TITLE
[BUG - GlobeView] Mismatch between 3D georeferenced object and GlobeView

### ISSUE THREAD

**Issue by ketourneau** [iTowns/itowns#2238]
We modify misc_collada sample to place 3D georeferenced object with GlobeView and we see a mismatch with ortho (it's working with PlanarView). 

## Your Environment
* Version used: 2.4.1-next.9
* Browser Name and version: Firefox 120.0.1
* Operating System and version (desktop or mobile): macos (sonoma)
* Link to your project: https://github.com/bloc-in-bloc/itowns/blob/hackhaton/examples/misc_collada.html

## Context
![globeView](https://github.com/iTowns/itowns/assets/39763266/cd422841-1bfa-458a-b8ca-22f758fe8f73)

## Steps to Reproduce (for bugs)
[GlobeView live example](https://demo-hackathon.netlify.app/examples/misc_collada)
1. Replace [example/misc_collada.html](https://github.com/bloc-in-bloc/itowns/blob/hackhaton/examples/misc_collada.html)

## Expected Behavior
Object 3D match ortho.
Like with a PlanarView : 
- [online demo](https://demo-hackathon.netlify.app/examples/misc_collada_planar_view)
- [Source code](https://github.com/bloc-in-bloc/itowns/blob/hackhaton/examples/misc_collada_planar_view.html)

![planarView](https://github.com/iTowns/itowns/assets/39763266/d166a95f-d877-43e0-a553-a9d78a47e7ec)

## Actual Behavior
Object 3D doesn't match ortho.

## Possible Cause/Fix/Solution
We're not sure if it's a bug.
Our 3D georeferenced object was build in cartesian system (CC47) and we suppose GlobeView is in ellipsoidal system.
So maybe mismatch is normal and we need to use only PlanarView with this object ?

**Comment by mgermerie** [comment]
Hi !

If your data is in a cartesian system, it will indeed appear displaced when viewed in an ellipsoidal system.

As I discussed this subject recently, I'm thinking this must be mainly linked to the [meridian convergence](https://jerrymahun.com/index.php/home/open-access/32-vi-directions/265-chapter-c-meridian-conversion?start=3) of the cartesian projection. There are other effects which induce a displacement of a projected model viewed in an ellipsoidal system, such as the linear alteration of the projection. However, this should not be noticeable on a relatively small model such as the one in your example.

Therefore, I think you need to unproject your model for it to be well placed on a GlobeView.

**Comment by ketourneau** [comment]
Hi,
Thank for the answer !
This confirm our hypothesis, so we'll use PlanarView in our case.
