### ISSUE TITLE
[Architecture] inconsistent role of `C3DTilesBatchTable`

### ISSUE THREAD

**Issue by mgermerie** [iTowns/itowns#2261]
## Your Environment

* Version used: 2.41.0

## Context

When parsing B3DM 3d-tiles with [B3dmParser](https://github.com/iTowns/itowns/blob/master/src/Parser/B3dmParser.js) and if needed, we instantiate a [`C3DTilesBatchTable`](https://github.com/iTowns/itowns/blob/master/src/Core/3DTiles/C3DTBatchTable.js) at [those lines](https://github.com/iTowns/itowns/blob/f146262ac98b0237c5256b11f6700f85794b47d5/src/Parser/B3dmParser.js#L175-L176). The arguments given for `C3DTilesBatchTable` instantiation are an `ArrayBuffer` containing raw batch table data, and lengths of the table as well as its json and binary parts. Then, in [`C3DTilesBatchTable` constructor](https://github.com/iTowns/itowns/blob/f146262ac98b0237c5256b11f6700f85794b47d5/src/Core/3DTiles/C3DTBatchTable.js#L27), the `ArrayBuffer` is parsed : the json part and the eventual binary attribute values are decoded and the resulting JS Object is stored in a [`C3DTilesBatchTable` property](https://github.com/iTowns/itowns/blob/f146262ac98b0237c5256b11f6700f85794b47d5/src/Core/3DTiles/C3DTBatchTable.js#L82).

I believe this is an error in terms of architecture. A `C3DTilesBatchTable` should only store data from a given batch table and grant method to access, edit or eventually delete this data. It should not be also responsible for parsing raw data from a B3DM file.

## Possible Cause/Fix/Solution

The parsing of the batch table from a B3DM file should be done directly in the `B3dmParser`, and `C3DTilesBatchTable` should take an already parsed batch table as constructor argument.

**Comment by jailln** [comment]
Obsolete since we moved to 3DTilesRendererJS
