### ISSUE TITLE
[OrientedImage] Visualize oriented images

### ISSUE THREAD

**Issue by nosy-b** [iTowns/itowns#23]
First test of integration of the visualization of oriented images. Currently getting cleaned in V1

**Comment by gchoqueux** [comment]
Issue #184 

As this kind of data is quite easy to find and user are used to this kind of immersive environment ( <= Google Streetview ), it would be nice to support it.

Different kind of assembled panoramic images : 
- cubemaps
- equirectangular images
- ?

Some resources for 360° images : 
- here
- flickr groups ( some have GPS coordinates)
- mapillary ?
- Add some more..

We will have to check for TOS and licences before using the images inside iTowns.

We first have to discuss here about formats and metadata. One or more formats can be implemented. We would probably want a quick-and-easy solution as well as a feature-complete solution. See also #144 for metadata discussion.

**Comment by gchoqueux** [comment]
Merged in master
