### ISSUE TITLE
Factorization updateNode

### ISSUE THREAD

**Issue by gchoqueux** [iTowns/itowns#231]
Factorize 2 functions [from `LayeredMaterialNodeProcessing`](https://github.com/iTowns/itowns/blob/master/src/Process/LayeredMaterialNodeProcessing.js) in one function :
* [ `updateLayeredMaterialNodeImagery`](https://github.com/iTowns/itowns/blob/master/src/Process/LayeredMaterialNodeProcessing.js#L45)
* [`updateLayeredMaterialNodeElevation`](https://github.com/iTowns/itowns/blob/master/src/Process/LayeredMaterialNodeProcessing.js#L158)

**Comment by jailln** [comment]
Closing in favor of #2421
