### ISSUE TITLE
Unit and functional test

### ISSUE THREAD

**Issue by gchoqueux** [iTowns/itowns#232]
Write unit and functional tests
Add automatic testing in PR

**Comment by Mkonini** [comment]
@gchoqueux 
IMHO, we should separate tests and split this CR into : 
- Unit test, as part of development
- Functional tests, to run before merging a PR to the master, aiming the test of the new functionality before merging it to the master.
- Non-regression  tests, ideally to be runned automatically after the build.  They does not target testing the new functionality, but check that what was implemented before runs allways OK.
