### ISSUE TITLE
Problem adding vector tiles map

### ISSUE THREAD

**Issue by vladimir-rybalko** [iTowns/itowns#2328]
Hello!

I want to display a MapBox vector tile map just like the OpenLayers 2D map does.
An example of my code is in the sandbox, here is the [link](https://nrgygm.csb.app/).
1. Why does iTowns draw a sprite of pictures, and not just one icon?
2. How can I add vector tiles from maptiler.com?

@AnthonyGlt, can you help?

**Comment by AnthonyGlt** [comment]
Hello, 
I think @ftoromanoff you work on the style recently, could you check what is happening here please ?  Is it related to the recent changes in the style ? 
Thank you

**Comment by ftoromanoff** [comment]
Hello,
Thanks for the issue @vladimir-rybalko. It was indeed an oversight.
Hopefully #2330 can fix it.

For the 2nd question, I don't know but i can try to have a look, I never used maptiler.com..
PS: maptiler seems to have its own standard
https://docs.maptiler.com/cloud/api/maps/
I'm not sure if is currently supported in itowns without some modifications.
PS2: As It seems to provide a WMTS
https://docs.maptiler.com/cloud/api/maps/#wmts-capabilities
Using a WMTSSource might be possible to get the data from maptiler.

**Comment by vladimir-rybalko** [comment]
> Hello, Thanks for the issue @vladimir-rybalko. It was indeed an oversight. Hopefully #2330 can fix it.
> 
> For the 2nd question, I don't know but i can try to have a look, I never used maptiler.com.. PS: maptiler seems to have its own standard https://docs.maptiler.com/cloud/api/maps/ I'm not sure if is currently supported in itowns without some modifications. PS2: As It seems to provide a WMTS https://docs.maptiler.com/cloud/api/maps/#wmts-capabilities Using a WMTSSource might be possible to get the data from maptiler.

@ftoromanoff, thank you for your work!

I couldn't check the style fixes for mapbox earlier. Now I see that for the mapbox style the problem with duplicating icons has really been solved.
I want to use maptiler format maps. I have my own server with a base map, but itowns behavior is the same on the standard maptiler map.
[style-winter-v2.json](https://github.com/user-attachments/files/17017345/style-winter-v2.json)
I have attached an example of the style in the attachment.

@ftoromanoff, tell me where I can look at style parsing to try to implement support.
