### ISSUE TITLE
Eslint errors : linebreak-style & import/no-extraneous-dependencies on windows

### ISSUE THREAD

**Issue by vcoindet** [iTowns/itowns#237]
After some tests, I have those follwing errors : 
- _errors with `linebreak-style`_
- _9:1   error  'Renderer' should be listed in the project's dependencies. Run 'npm i -S Renderer' to add it  import/no-extraneous-dependencies
  9:22  error  Unable to resolve path to module 'Renderer/NodeMesh'                                          import/no-unresolved
  9:22  error  Missing file extension for "Renderer/NodeMesh"                                                import/extensions_
(the Renderer file is just an exemple, I have this issue for many files...)

Tested on windows 7, chrome 55 and firefox 51

**Comment by autra** [comment]
@vcoindet bad news: from a fresh VM, i cloned the repo, run `npm install` and I don't have any problems.... What do you have in `core.autocrlf` config entry?

**Comment by autra** [comment]
@vcoindet what's the value of `core.autocrlf` in your repo ?
also, can you try re-cloning the repo and running `npm install && npm run lint` in it?

**Comment by vcoindet** [comment]
@autra 
I just put the value of `core.autocrlf` at `true`, it seems to have solved the problem of linebreak.
I re-cloned the repo and run your command `npm install && npm run lint` and I have an error :  `Cannot find module 'eslint-config-airbnb-base/rules/strict'`, but I found it in node_modules...

**Comment by autra** [comment]
IIRC @vcoindet told me everything works fine now. So closing :-)

**Comment by vcoindet** [comment]
@autra 
The problem of linebreak came back after rebasing a branch.
I checked : `core.autocrlf` is set at `true`
@Mkonini has the same problem...

Did you change something since last time ?

**Comment by autra** [comment]
No, you can check yourself (`git log --author "augustin"`) :-) Which branch are you rebasing? On which other branch? Also could you pastebin your logs?

You guys might want to check your editor config too.

**Comment by tbroyer** [comment]
You should let `core.autocrlf` to its default (`false`) to have LF line endings on disk (with `core.autocrlf=true`, you're converting line endings to CRLF on checkout, and back to LF on commit); and make sure your text editor won't use CRLF (we have `.editorconfig` set to LF and `eol=lf` in `.gitattributes`, so if your editor respects `.editorconfig` and your Git client respects `.gitattributes` –some unofficial reimplementations, e.g. EGit/JGit, don't–, it should be OK).

The only reason to set `core.autocrlf` to `true` is if you use some tools that are unable to work with LF line endings. This should be a thing of the past. And it shouldn't (with a proper Git client) affect iTowns as the `.gitattributes` overrides `core.autocrlf`.

So the question: which editor are you using? (and is it configured to use LF line endings? either explicitly or implicitly through `.editorconfig`) and which Git client are you using?

**Comment by vcoindet** [comment]
I tried to set `core.autocrlf` to `true`, `input` and `false` => same problem
In `.editorconfig` : `end_of_line = lf`
In `.gitattributes` : `eol=lf`

I'm using Sublime Text 3 and git bash (https://git-for-windows.github.io/)

**Comment by vcoindet** [comment]
As none of my test was improving my situation on windows, I put the line `"linebreak-style": 0,` in `.eslintrc.js` as a temporary solution, but I guess this solution won't please people working on linux...

**Comment by tbroyer** [comment]
As long as the modification is not committed and the repository only contains LF line endings (i.e. `npm run lint` passes on Travis), it'd be a perfectly viable workaround.

We should try to make it temporary though, and find a way for developers on Windows to be able to work on iTowns without having to make that local change. I'll try to find time doing some testing.

(btw, changing `core.autocrlf` won't change files on your disk, so if they have CRLF line endings following a checkout with `core.autocrlf=true`, ESLint would still complain after changing `core.autocrlf` to `false` or `input`; files would need to be changed to turn their line endings to LF)

**Comment by vcoindet** [comment]
Well I put core.autocrlf to false and did a checkout, it seems to have solved the problem, but I'm pretty sur I did the same thing yesterday (as rebased some of my branch...).

Maybe we should warn users of this problem in the readme ? explain users has to change the core.autocrlf value in their environment ? WDYT ?

**Comment by autra** [comment]
@vcoindet normally, this value should be superseded by what is in .gitattributes. I was supposing your git client was ignoring .gitattributes, but actually it does not (it is recent enough). So user should not have to do anything apart not using Notepad (and if they do, we can't do anything for them, really). In other word, core.autocrlf value does not affect itowns working copy any more.

Wild guess, were you rebasing a branch from *before* the .gitattributes or .editorconfig change?

**Comment by vcoindet** [comment]
Yep I was rebasing a branch from before the .gitattributes change, the problem must come from here I guess (as I am concerned, I don't know for @Mkonini and @nosy-b )

**Comment by autra** [comment]
> Yep I was rebasing a branch from before the .gitattributes change,

Don't look any further then :-) Just be sure to resave any affected files with your editor (and be sure to use the .editorconfig plugin for this).

**Comment by autra** [comment]
Closing, I assume this is fixed now :-)
