### ISSUE TITLE
地图加载一服务存在跨域问题

### ISSUE THREAD

**Issue by liangyuan1** [iTowns/itowns#2390]
地图加载一服务存在跨域问题，例如天地图,和geoserver发布的服务，但是同样的地址在opnlayer和cesium中请求不存在跨域问题

**Comment by jailln** [comment]
Can you provide more details about your bug please ?

**Comment by liangyuan1** [comment]
> Can you provide more details about your bug please ?

var orthoSource1 = new itowns.WMTSSource({
        url: 'http://t0.tianditu.gov.cn/img_w/wmts?tk=6e3de5b9cfca24b0f43d7c431acf56b9',
        crs: 'EPSG:3857',
        name: 'img',
        tileMatrixSet: 'w',
        format: 'tiles',
        style: 'default',
      })
      var orthoLayer1 = new itowns.ColorLayer('Ortho1', {
        source: orthoSource1,
      })
      view.addLayer(orthoLayer1)
![image](https://github.com/user-attachments/assets/b9ae12a4-544a-455a-98c7-11fe1baf7bce)

**Comment by AnthonyGlt** [comment]
Thank you for the issue.
Could you type in English please ? :)
As far as I understand, you are getting CORS issues on iTowns but for the same url you don't have issue on cesium ?

**Comment by liangyuan1** [comment]
> Thank you for the issue.
> Could you type in English please ? :)
> As far as I understand, you are getting CORS issues on iTowns but for the same url you don't have issue on cesium ?

Yes, using the same service on both Cesium and Openlayer did not encounter cross domain issues

**Comment by jailln** [comment]
I tested the layer you provided and I cannot reproduce your issue

**Comment by jailln** [comment]
![image](https://github.com/user-attachments/assets/04a385df-7d58-4f1d-a3b7-a40b3c6d5e35)
