### ISSUE TITLE
[Loader] Loading KML/Collada

### ISSUE THREAD

**Issue by vcoindet** [iTowns/itowns#24]
iTowns should be able to load KML/Collada of the french building.

Next step : load collada according to the LOD, only at the position where the user is located.

**Comment by vcoindet** [comment]
Loading collada according to the LOD : done.

Step 2: Remove collada from the viewer when dezooming.
Step 3 : Load locals .kmz files

**Comment by vpicavet** [comment]
@vcoindet please refer to the issues when commiting related stuff, so that we can track code modifications.

As for model loading according to LOD, @Jeremy-Gaillard 's work may help

**Comment by vcoindet** [comment]
Of course I will do that, but I haven't been working on this subject for a few month

**Comment by gchoqueux** [comment]
move in #214
