### ISSUE TITLE
3D Tiles 1.1 - Implicit Tiling - Octree support?

### ISSUE THREAD

**Issue by bertt** [iTowns/itowns#2423]
I'm trying to get the Cesium demo with Implicit Tiling and Octree (https://github.com/CesiumGS/3d-tiles-samples/tree/main/1.1/SparseImplicitOctree) working in ITowns, but I'm getting errors.

Demo in Cesium (works): https://bertt.github.io/itowns_issues/octree/index.html

Demo in ITowns (does not work): https://www.itowns-project.org/itowns/examples/3dtiles_loader.html?tileset=https://bertt.github.io/itowns_issues/octree/tileset.json

Error "Failed to load tile at url "content/content_1__0_0_undefined.glb"."

Is Implicit Tiling and Octree supported?

**Comment by AnthonyGlt** [comment]
Thank you for the issue.
Octree is not yet supported for implicitTiling.
There is a list of what's left to implement for this feature:
https://github.com/NASA-AMMOS/3DTilesRendererJS/issues/608#issuecomment-2283364305
I  don't think that a MR is ongoing concerning Octree implementation.If you feel like it, don't hesitate to try to add it in the 3DTilesRendererJS lib, it could be a nice addition :D

**Comment by bertt** [comment]
ok thanks, good to see it as first item on the list :-)

**Comment by AnthonyGlt** [comment]
Related MR 
https://github.com/NASA-AMMOS/3DTilesRendererJS/pull/791

**Comment by AnthonyGlt** [comment]
Merged in 3DTilesRenderer, will be available in next version bump
