### ISSUE TITLE
3Dtiles issue when 2 view are created

### ISSUE THREAD

**Issue by AnthonyGlt** [iTowns/itowns#2426]
I have 2 itowns view loaded on the same page.
On each view, I'm loading a 3dtiles dataset.
I have to wait for the 3dtiles from the first view to finish loading before seeing the tiles from the second view.
Also, when I switch from one view to the other, the 3dtiles disappear and starts requesting all the tiles again.

## Context
Manage 2 view with 3dtiles in each

## Steps to Reproduce
1. Create 2 views with 2 3dtile dataset
2. Interact with each view
3. Observe that the whole dataset disappear before reloading completely

[Screencast from 04-10-2024 15:11:49.webm](https://github.com/user-attachments/assets/e4c6997b-d8bc-4185-8f2a-8193d90af88b)

## Possible Cause/Fix/Solution
Looks like it's caused by:
https://github.com/iTowns/itowns/blob/c862ca7376c195596c1111064f8189ccaad04348/src/Layer/OGC3DTilesLayer.js#L197

**Comment by jailln** [comment]
We indeed share the 3D tiles cache, download and parse queues among all tilesets. 

With this new use case in mind, one solution would be to share them **per view**. To do so, we could:
* Add an `id` property to `View`
* Declare a `Map` of 3DTilesRendererJS with the view id as key and `lruCache`, `downloadQueue` and `parseQueue` as value. 
* Take care of filling this map and setting up the cache and queues in `OGC3DTilesLayer._setup` (that is called by `View.addLayer(3DTilesLayer)`)

That would have the advantages to manage 3DTiles independently for each view and to take care of this setup for our users (which in many cases won't want to deal with this kind of stuff I think). I also can't think of any usecase where one would want to share the same cache and queues amongst views.

WDYT @AnthonyGlt @Desplandis ?

**Comment by jailln** [comment]
Done in https://github.com/iTowns/itowns/pull/2435
