### ISSUE TITLE
Add publiccode.yml

### ISSUE THREAD

**Issue by bzg** [iTowns/itowns#2430]
PublicCode is a [standard](https://yml.publiccode.tools/schema.core.html) for describing software projects led by public sector organizations.

See for example this [publiccode.yml](https://github.com/SocialGouv/dashlord/blob/main/publiccode.yml) file for the Dashload project, led by a public sector incubator.

Since iTowns is led/funded by IGN, I think it would make sense to add a `publiccode.yml` file.

And because the project seems important enough, with many users, we could promote it on the "Awesome code.gouv.fr" webpage : https://code.gouv.fr/fr/awesome/

WDYT? Do you want me to make a PR for a first draft?

**Comment by alavenant** [comment]
The PR [2417](https://github.com/iTowns/itowns/pull/2417) is open. Don't hesitate to improve it.

**Comment by bzg** [comment]
Thanks! I made some comments.

**Comment by Desplandis** [comment]
@alavenant @bzg `publiccode.yml` merged in iTowns :partying_face:

**Comment by bzg** [comment]
And you're in! https://git.sr.ht/~codegouvfr/codegouvfr-data/commit/2e7b31493

This will appear in the website for our next release of https://code.gouv.fr/sources in november.

Thanks again!
