### ISSUE TITLE
Instanced 3D Tiles - Getting attributes 

### ISSUE THREAD

**Issue by bertt** [iTowns/itowns#2434]
Hi, I want to show attributes of Instanced 3D Tiles (I3dm), like it works with Batched 3D Tiles (b3dm)

Sample (does not work): Click on cube in https://www.itowns-project.org/itowns/examples/3dtiles_loader.html?tileset=https://bertt.github.io/cesium_3dtiles_samples/samples/instanced/traffic_lights/tileset.json

Cesium Sample shows attributes Id, Bevestiging on click on cube : https://bertt.github.io/cesium_3dtiles_samples/samples/instanced/traffic_lights/

![image](https://github.com/user-attachments/assets/199c89aa-fac1-4894-9fa3-0f20eff248d9)

**Comment by AnthonyGlt** [comment]
Fix in 
https://github.com/iTowns/itowns/pull/2467
