### ISSUE TITLE
[HELP] Display Vector Tiles (MVT) from BDNB

### ISSUE THREAD

**Issue by ketourneau** [iTowns/itowns#2464]
We try to use [BDNB API](https://api-portail.bdnb.io/catalog/api/f4905edc-db58-3a3b-a8e5-c5dfc6692ee5) to display Vector Tiles of buildings.

We just try to modify [vector_tile_raster_2d.html](https://github.com/iTowns/itowns/blob/master/examples/vector_tile_raster_2d.html) with : 

```
var mvtSource = new itowns.VectorTilesSource({
    zoom:{
        min: 14,
        max: 14,
    },
    style: {
        sources: {
            sourceTiles: {
                type: "xyz",
                tiles: ['https://api.bdnb.io/v2/gorenove/tiles/public/buildings/{z}/{x}/{y}.pbf']
            }
        },
        layers: [
            {
                id: "batiment-groupe",
                type: "fill",
                source: "Gorenove",
                "source-layer": "sql_statement",
                paint: {
                    "fill-color": "#FF0000",
                    "fill-opacity": 1
                }
            }
        ]
    },
});
```
But the tiles doesn't appear. How we can find layers to correctly configure the style ?

**Comment by ftoromanoff** [comment]
Hello,
Using the exact same lines as you copied here, I got some data on the view as soon as you get in a zone where there is tile to display.

I set up the view at:
```
      // Paris
      const coord = new itowns.Coordinates('EPSG:4326', 2.351323, 48.856712);
      const placement = {
        coord,
        range: 10000,
      };
      const viewerDiv = document.getElementById("viewerDiv");
      const view = new itowns.GlobeView(viewerDiv, placement);
```

And got :
![image](https://github.com/user-attachments/assets/742625de-1d3e-44d4-b24d-6aceb1498acd)
as a result

**Comment by ketourneau** [comment]
Ok thank you, I will try now with PlanarView ! Now I know it works with globe view.
