### ISSUE TITLE
WMTS imagery source is blocked by CORS policy while openlayer displays it

### ISSUE THREAD

**Issue by airnez** [iTowns/itowns#2471]
## Context
Some raster data (here WMTS) are getting their requests blocked by CORS policy. The same data can be displayed in openlayer without problems.

## Steps to Reproduce
1. Install the allow-cors extension in chrome
2. Add this layer to the view_3d_map example : 
```
            var wmtsSource = new itowns.WMTSSource({
                url: 'https://geo.pnrsud.fr/geoserver/gwc/service/wmts',
                crs: 'EPSG:3857',
                name: 'dynmap:scan25_1_paca_2022',
                tileMatrixSet: 'EPSG 3857',
                version: '1.0.0',
                style: 'raster',
                format: 'image/jpeg',
                isInverted: false,
                tileMatrixCallback: (zoomLevel) => 'EPSG 3857:' + zoomLevel
            });
```

4. zoom to the french city "Alès"
5. See that allowing CORS enables displaying the layer

![image](https://github.com/user-attachments/assets/b683aa09-8baf-488f-8b94-3b80eca0d553)

**Comment by jailln** [comment]
After analysis it turns out the cors error is legitimate since the server has no cors configuration for images (see https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image#web_server_configuration for an example of server configuration to allow cors on images)
