### ISSUE TITLE
loadGPX(url)

### ISSUE THREAD

**Issue by vcoindet** [iTowns/itowns#258]
- [x]  It goes wrong if a `<ele>` tag is missing in the GPX file.
 
- [x] How to manage the min and max zoom because the display range is reduced ?

- [x] How to manage the visibility/opacity of GPX layers (they don't have index)

Maybe we should wait for itowns to support features layers for the two last points

**Comment by autra** [comment]
@vcoindet did you have a chance to test these points since #450 got merged?

**Comment by gchoqueux** [comment]
fix in #450
