### ISSUE TITLE
Complete LICENSE.md with third-party code licences

### ISSUE THREAD

**Issue by vpicavet** [iTowns/itowns#26]
We should keep a dependency list somewhere, but having it in the build system in addition to LICENSE.md can be enough.

**Comment by vpicavet** [comment]
That's in  orgfiles branch

**Comment by tbroyer** [comment]
Do we really need it if we externalize the dependencies through NPM?
And would it be different we didn't bundle (some of) them in the "dist" scripts? (and instead require users to include them before include iTowns)

BTW, you only list Three.js but the repo currently also contains Require.js (and requirejs/text), parallel.js, when.js, and JSZip.

**Comment by vpicavet** [comment]
No position on the dependency management rule.
This was only to not forget to mention other licences for included third-party code. I will update to mention the other libs you reported.

**Comment by tbroyer** [comment]
FWIW, PriorityQueue is https://github.com/adamhooper/js-priority-queue (Public Domain)
(there are several priority queues in JS, and it took me some time to find which one we're using)

**Comment by vpicavet** [comment]
Closed in #30
