### ISSUE TITLE
CPU load super heavy when close to the ground. 

### ISSUE THREAD

**Issue by nosy-b** [iTowns/itowns#27]

**Comment by markov00** [comment]
Hi, I've also seen this issue. Seems that the sceneProcess method at high zoom takes too much time to compute. It can also be related to the fact that you are using setTimeout to call the rendering phase instead of using a requestAnimationFrame.

**Comment by nosy-b** [comment]
Agreed, the setTimeout should go away for  requestAnimationFrame.

**Comment by nosy-b** [comment]
The 3d scene rendering should happen every requestAnimationFrame but the heavy sceneProcess should occur on camera move (or every 15 frames for ex) @gchoqueux

**Comment by gchoqueux** [comment]
fixed
