### ISSUE TITLE
Collada Up geodeticSurfaceNormal is applied to the whole slab. It's an approximation

### ISSUE THREAD

**Issue by nosy-b** [iTowns/itowns#28]

**Comment by gchoqueux** [comment]
precise, please @nosy-b

**Comment by nosy-b** [comment]
When loading large tiles of 3D models (building boxes) with kmz/collada, we use only one normal to orient the whole tile. This approximation can be bad for large tiles if buildings have locale pivot/orientation.
If building boxes from collada are already computed using per-point geodesic normal then this remark has to be forgotten

As this was done in a test for kmz/collada. We'll see in the next developpement
