### ISSUE TITLE
Heading and Tilt change when 'state = MOVE_GLOBE'

### ISSUE THREAD

**Issue by vcoindet** [iTowns/itowns#286]
The heading and the tilt should be changing only when the state is at ORBIT (`state = CONTROL_STATE.ORBIT;`).

But they also change when the state is at MOVE_GLOBE (`state = CONTROL_STATE.MOVE_GLOBE;`).

**Comment by gchoqueux** [comment]
The tilt is fixing and doesn't change
But the heading changes with mouse globeControls, it's normal behavior.
If you moves camera with `globeView.controls.lookAtCoordinate({cood : new Cordinnates } )`, so heading and tilt will not change.
