### ISSUE TITLE
Remove init functions

### ISSUE THREAD

**Issue by vmora** [iTowns/itowns#33]
Constructing an object and initializing it later is IMO a bad habit, and this kind of construct 

```
        var scene = Scene();

        scene.init(); 
```

Does not make much sense to me. init should be private and called in the Scene ctor.

In the case where an object should be used before initialized, a temp object (of a different type) can be used instead. Even if we have no strong typing in js, I thing it make things clearer.

I propose to add that in coding guidelines.

**Comment by gchoqueux** [comment]
[remove init singleton](https://github.com/iTowns/itowns2/commit/b657d2570219ec3d3b4d021530c97cb5de763db8)
