### ISSUE TITLE
3d model is not shown in 3d-tiles

### ISSUE THREAD

**Issue by qdnguyen** [iTowns/itowns#335]
Hi,

I created a 3d tile and visualized it in itowns by using 3dtile branch of @NikoSaul. 

Everything is fine, except only the bounding box of tile is shown, but not 3D model. 

Have you any idea why? 

Do you known what is coordinate system/projection used in gltf format? 

![image](https://user-images.githubusercontent.com/3224540/27225681-9b641b18-529b-11e7-9984-b17852d7406d.png)

![image](https://user-images.githubusercontent.com/3224540/27225759-f0d425f2-529b-11e7-8f60-c98080a68b99.png)

**Comment by NikoSaul** [comment]
I think it's because the feature b3dm - RTC is not implemented yet, i'm working on the feature right now.

**Comment by qdnguyen** [comment]
Thank @NikoSaul, do this RTC resolves the geoferencing problem? 

In wireframe mode, i see my model inside of globe, it means that my model is not well aligned with its bbox. 

![image](https://user-images.githubusercontent.com/3224540/27228529-4a764af2-52a8-11e7-917b-ef5a5b7c0a28.png)

**Comment by NikoSaul** [comment]
I can't know, can you share your model please.
Ho ok if you see your model, it's not the RTC problem.

**Comment by qdnguyen** [comment]
yes i can share it but you may needs my version to visualize it.

i think the transformation matrix is not applied to the model, do you know how to do it proprely ? what did you do to dragon model to visualize it correctly? 

Many thanks,

**Comment by NikoSaul** [comment]
First i need to know, what is your file ? b3dm, pnts ? 

no problem :+1:

**Comment by NikoSaul** [comment]
Can you share your tileset please :) 

no problem :+1:

**Comment by qdnguyen** [comment]
my file is glb, i attach it in zip file. 
[TilesetBuilding.zip](https://github.com/iTowns/itowns2/files/1084224/TilesetBuilding.zip)

i can not commit to your branch so i copy here some modifs that you must add to your code to use this tileset. 

you must add this function in 3dTiles_Provider.js

$3dTiles_Provider.prototype.glbToMesh = function glbToMesh(data, layer) {
        return this.b3dmLoader.parseGlb(data).then((result) => {
            const init = function f_init(mesh) {
                if (layer.overrideMaterials) {
                    mesh.material = new BasicMaterial();
                    mesh.material.uniforms.useRTC.value = false;
                }
            };
            result.scene.applyMatrix(layer.glTFRotation);
            result.scene.traverse(init);
            return result.scene;
        });
};

add this code at line 150

glb: this.glbToMesh.bind(this),

and this at line 164
 
else if (magic == 'glTF') {
                    func = supportedFormats.glb;
} 

and add this function to b3dmLoader

B3dmLoader.prototype.parseGlb = function parseGlb(buffer) {
    if (!buffer) {
        throw new Error('No array buffer provided.');
    }
   // TODO: missing feature and batch table
    return new Promise((resolve/* , reject*/) => {
            const onload = (gltf) => {
                resolve(gltf);
            };
            this.glTFLoader.parse(buffer, onload);
        });
    
};

Thank for your help

**Comment by qdnguyen** [comment]
ok, i saw that our code support only georeference by transformation matrix but not boundingVolume yet!

**Comment by autra** [comment]
> i can not commit to your branch so i copy here some modifs that you must add to your code to use this tileset.

You can create a new branch from another one (`git checkout -b newbranch` when on oldbranch) and add your commit there and push it on your fork. Makes sharing easier than copy-pasting a (unformatted) bunch of code on github ;-)

**Comment by Jeremy-Gaillard** [comment]
> ok, i saw that our code support only georeference by transformation matrix but not boundingVolume yet!

As far as I know, the definition of a bounding volume has no incidence on the position of the objects. If no transformation matrix is passed, it is set to the identity matrix, as specified [here](https://github.com/AnalyticalGraphicsInc/3d-tiles#tile-transform). Are you sure your tileset is created correctly?

**Comment by qdnguyen** [comment]
in the case of region, do we need transformation matrix? by exemple in this tileset, i did not see transformation matrix.

https://github.com/AnalyticalGraphicsInc/3d-tiles/blob/master/examples/tileset.json

**Comment by Jeremy-Gaillard** [comment]
Transformations are never mandatory. My point was that defining a bounding volume (**any** type of bounding volume) will not set the center of your geometry as the center of the of your bounding volume.

**Comment by qdnguyen** [comment]
You are right  but how we explain the exemple above? There is no transformatrin matrix and bounding geographic region is in WGS84 / EPSG:4326, i think they can use it to have a pivot point?

**Comment by Jeremy-Gaillard** [comment]
The transformation (or center point for RTC rendering) is most likely in the b3dm/glTF files.

**Comment by qdnguyen** [comment]
ok, with transformation matrix, it works, it's enough for me now to show 3d model, i will close this issue!
