### ISSUE TITLE
Create a flat mode

### ISSUE THREAD

**Issue by Jeremy-Gaillard** [iTowns/itowns#34]
We should be able to visualise the data in a flat projected space.

A branch has been created where such a mode is being worked on, porting the current globe functionalities.

Tasks:
- [ ] Create a flat camera mode
- [ ] Change some classes that should be generic enough to be used by both flat and globe mode. Currently identified classes: Scene, NodeProcess, Quadtree, Bounding Box, c3DEngine (init function, camera), BrowseTree, ManagerCommands
- [ ] Load DEM and Imagery in the flat model
- [ ] Clean up code, remove unused files and functions

**Comment by gchoqueux** [comment]
after reflection, I think it is possible to have a flat globe in very little change

**Comment by gchoqueux** [comment]
I did not even look at the code, your changes are minor?
Because I think that we should change only the mathematical model: ellipsoid. #34

**Comment by vpicavet** [comment]
\o/
