### ISSUE TITLE
how to show texture embeded in b3dm

### ISSUE THREAD

**Issue by qdnguyen** [iTowns/itowns#344]
Hello,

It seems that the 3d-tiles nodejs server could not stream the texture along with the 
3d model. 

Other solution is to embed the texture inside of b3dm, but how can we activate it in itowns please?

![image](https://user-images.githubusercontent.com/3224540/27474269-2a6066e4-5802-11e7-9325-55b2ff0f9319.png)

**Comment by Jeremy-Gaillard** [comment]
The glTF loader (used in the b3dm loader) should be able to load textures. Check this in the network queries if the textures aren't already embed in the b3dm file.

The problem may stem from the shader or badly handled attributes. Check that you have no errors at runtime and that the attributes are well set in the model.

**Comment by qdnguyen** [comment]
>The glTF loader (used in the b3dm loader) should be able to load textures. Check this in the network queries if the textures aren't already embed in the b3dm file.

Hi Jeremy, my texture is embeded in glb file, i tested it with gltf loader example of threejs and it work!

>The problem may stem from the shader or badly handled attributes. Check that you have no errors at runtime and that the attributes are well set in the model.

i do not see error at runtime, i can print my shader here if you need to check?  

the same file but the texture is not shown in our case

![image](https://user-images.githubusercontent.com/3224540/27476151-e4e6f3ac-5807-11e7-9d7b-4ecf6b0e1706.png)

**Comment by Jeremy-Gaillard** [comment]
> i do not see error at runtime, i can print my shader here if you need to check?

Yes, it's hard to help debugging without having the actual data!

**Comment by qdnguyen** [comment]
i attach glb file here, you can test it with threejs gltf example, the file was generated by Collada2gltf convertor and it works in threejs. 
[LYON_1ER_00138.zip](https://github.com/iTowns/itowns2/files/1101739/LYON_1ER_00138.zip)

**Comment by Jeremy-Gaillard** [comment]
Did you think to remove the overrideMaterials parameter in 3dtiles.html? This would explain why you have no shading on your buildings.

**Comment by qdnguyen** [comment]
when i set overrideMaterials=false, i have a problem of scale, i attach a 3d tiles here so you can try to find the bug.
[Test.zip](https://github.com/iTowns/itowns2/files/1105087/Test.zip)

**Comment by Jeremy-Gaillard** [comment]
I found two bugs:
- the matrix uniforms are not updated properly
- the buildings are rendered behind the terrain (z-buffer issue I think)

I am working to fix them.

**Comment by Jeremy-Gaillard** [comment]
Both bugs are fixed. If everything works on your end, please close this issue.

**Comment by qdnguyen** [comment]
thanks but it still does not work! 

i have created a real 3d-tiles, you can use it to debug your program. It work with master branch.

[Test.zip](https://github.com/iTowns/itowns2/files/1112662/Test.zip)

the model is loacated in Lyon

![image](https://user-images.githubusercontent.com/3224540/27697309-232e8daa-5cf4-11e7-968c-2b406f8f0749.png)

**Comment by Jeremy-Gaillard** [comment]
> overrideMaterials = false;

![opera](https://user-images.githubusercontent.com/1814191/27727922-bb02bc96-5d80-11e7-97ac-c8594ba41efc.png)

**Comment by qdnguyen** [comment]
ok, it works, i will close this issue!
thanks!
