### ISSUE TITLE
Zooming on Antartic produces incoherent results

### ISSUE THREAD

**Issue by autra** [iTowns/itowns#346]
**Description**

When moving/zooming the globe while aiming at Antartic, it appears at a wrong scale sometimes, then jumps back to correct scale. It appears that tiles are not set correctly at some zoom level

**Steps**
- Load index.html
- aim at Antartic
- zoom in/out
- observe Antartic

**Expected**

Antartic is always at correct size

**Actual**
Antartic is sometimes 2 times bigger, see this gif: ![peek 2017-06-27 18-50](https://user-images.githubusercontent.com/1576598/27599615-9d59d2c4-5b69-11e7-94b9-1280db2ba43f.gif)

(and it does very odd things at bigger zoom level)

**Comment by gchoqueux** [comment]
fix in #376
