### ISSUE TITLE
[Control] Camera Control bug on rotation

### ISSUE THREAD

**Issue by nosy-b** [iTowns/itowns#35]
Basically needs to have a clean interface for the camera. If we want to rotate  the camera on itself for ex (shift-move on usual 3D gis)

**Comment by nosy-b** [comment]
Function for camera rotation on itself added.
Remains to debug dragging .Later, tweening should be added to provide smooth moves

**Comment by nosy-b** [comment]
Bug on rotate on axis (shift click) when not clicking on the ground. It should work for any click position

**Comment by gchoqueux** [comment]
Redirected #153
