### ISSUE TITLE
Camera FOV induces bug on atmosphere, possible other side effect.

### ISSUE THREAD

**Issue by nosy-b** [iTowns/itowns#36]
Need check

**Comment by nosy-b** [comment]
Camera.preSSE seems to be badly correlated with Camera.fov

**Comment by gchoqueux** [comment]
@nosy-b Try the new commit _debug resize_  (#17)
Can you debug atmosphere resize and remove `window.innerWidth, window.innerHeight` and replace by size renderer
`screenSize: {
                type: "v2",
                value: new THREE.Vector2(window.innerWidth, window.innerHeight)}`

**Comment by nosy-b** [comment]
Ok , I removed those uniforms, not really useful anyway.
Resize seems to work fine! with new atmo too
