### ISSUE TITLE
OSM services crash with cross origin

### ISSUE THREAD

**Issue by nosy-b** [iTowns/itowns#360]
Adding wmts services OPENSM.json or Dark.json now causes cross origin problem

> THREE.WebGLState: DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The cross-origin image at http://b.tile.openstreetmap.fr/osmfr/3/1/5.png may not be loaded.

**Comment by autra** [comment]
Yes, it's now the user responsibility to configure CORS, because it's server-dependent. Just add 
```js
"networkOptions": { crossOrigin: 'anonymous' } 
```
To your layer conf.

**Comment by nosy-b** [comment]
So we need to add it to the existing examples. I do the PR in a minute

**Comment by autra** [comment]
@nosy-b it should be already done, `git pull` ?

**Comment by autra** [comment]
What test is broken?

**Comment by nosy-b** [comment]
@autra Seems you forgot those 2

**Comment by peppsac** [comment]
Fixed with #361
