### ISSUE TITLE
[Loader] Loading glTF

### ISSUE THREAD

**Issue by vcoindet** [iTowns/itowns#38]
As for the KML, iTowns should be able to load glTF files.

**Comment by vpicavet** [comment]
This may help : https://github.com/mrdoob/three.js/commit/9963eed18a778059a8f170afbbc6f7d54965a8af

**Comment by vcoindet** [comment]
Thank you @vpicavet ! we already saw an old version of those files a few months ago and we are using them. Maybe the new improvements will help us, we will keep it in mind.
Right now, loading glTF is not priority for us, I'm focussing on the API.

**Comment by gchoqueux** [comment]
**Somes news in THREE gltf**

* r84
  * Added Line and LineSegments support to GLTFLoader
  * Added glTF 1.1 support to GLTFLoader
  * Added glTF Binary (.glb) support to GLTFLoader 

[THREE js gltf loader](https://github.com/mrdoob/three.js/blob/master/examples/js/loaders/GLTFLoader.js)
[THREE js gltf loader example](https://threejs.org/examples/?q=gltf#webgl_loader_gltf)

**Comment by Jeremy-Gaillard** [comment]
glTF import is already used in the 3d-tiles branch by the way.

**Comment by autra** [comment]
And this branch got merged! I think we can consider this to be done :-)
