### ISSUE TITLE
iTowns compatibility with QWebView

### ISSUE THREAD

**Issue by gmaillet** [iTowns/itowns#385]
I try to use iTowns in a QWebView (from Qt4/QWebKit based on https://webkit.org/) to create a QGis plugin and there are at least two problems:

1. a syntax error on line 28 of GUI/GuiTools.js (SyntaxError: Expected token ')')
2. problems with promise (SyntaxError: Expected an identifier but found 'promises' instead)

the first one can be easily bypassed, but the second seems to be more serious, isn't it?

Can you help me please @tbroyer @gchoqueux?

**Comment by vpicavet** [comment]
Do not forget that next QGIS will be based on Qt5, and the web views framework changed a lot inbetween

**Comment by gmaillet** [comment]
Yes, but I don't know if it's possible/easy to work on a QGis 3 plugin during the next FOSS4G code sprint?

**Comment by vpicavet** [comment]
You can already work on QGIS3 plugins using the master ( 2.99 ) version, which is in the OSGeo4W distribution on Windows. Not sure there will be a lot of QGIS developers at the FOSS4G codesprint, but you should be able to find some support there among the OSGeo devs.

**Comment by gmaillet** [comment]
I have made a first test on PyQt5 version 5.9 (without QGis): it's not perfect, but it works enough to start. Let's go for QGIS3!

**Comment by autra** [comment]
@gmaillet I bet your 2/ isn't a problem with `promise` (`promises` is an array if I guess correctly where it fails), but with the use of the keyword `let` just before or after in an example files. Can you replace all the `let` by `var` and tell me what happens?

for 1, yes, it seems that your js engine does not support the use of default parameter values. Actually, we shouldn't have used it here. (In our src/ folder, we transpile the code to make it compatible with older browser, but it's not the case for the `examples/` folder which should be ES5 compatible). 

Both problems are valid bugs imho.

**Comment by autra** [comment]
To elaborate: I think we could greatly improve the support of older browser just by avoiding these special ES6 syntax in `examples` folders.

**Comment by gmaillet** [comment]
branch pluginQGIS (0570511586b2ba8fb3a0da363a55d7af2c2f60d7) has been created with some corrections to be compatible with PyQt4 QWebView (with some side effects)

**Comment by autra** [comment]
@gmaillet I'm closing this since the particular issues you reported should have been fixed by https://github.com/iTowns/itowns/pull/389. Please don't hesitate to open other issues for any other compatibility issues you might have, or reopen this one if you believe it's not fully fixed.

To elaborate, there are still some IE11 and older webkit-browsers that are missing some javascript API we need to shim.
