### ISSUE TITLE
Tiles are not loaded because of CORS errors

### ISSUE THREAD

**Issue by elias75015** [iTowns/itowns#390]
Hi,
we try to upgrade our geoportal projects with the release 2.0 of iTowns, and we encounter a new problem (did not encounter it with older versions of itowns). 

Tiles are not loading because of something looking like a CORS problem with THREEJS : 

`THREE.WebGLState: DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The cross-origin image at https://wxs.ign.fr/an7nvfzojv5wa96dsga5nk8w/geoportail/wmts?LAYER=ORTHOIMAG…etTile&STYLE=normal&TILEMATRIXSET=PM&TILEMATRIX=10&TILEROW=362&TILECOL=537 may not be loaded.`

Problem met under the latest versions of FF and GC (at least), and Ubuntu 14.04
This error is triggered from the texImage2D function.

![cors](https://user-images.githubusercontent.com/6764800/28125699-a52077dc-6727-11e7-9638-fc39796a60af.png)

To test, try samples/itowns from the "itowns-controls" branch of the geoportal-extensions project (https://github.com/IGNF/geoportal-extensions/tree/itowns_controls)
 
I don't know if it is an itowns bug : in doubt, I do not tag this issue as it.
Thanks for your help.

**Comment by tbroyer** [comment]
Related to https://github.com/iTowns/itowns/commit/73edf6e23bc6a3eaab0a297e6d8ee29471d9b212?

**Comment by elias75015** [comment]
@tbroyer 
Indeed, I did not see that. Thanks for your help !
So we just have to add the networkOptions parameter when adding a layer.
