### ISSUE TITLE
Window resize causes camera to jump in examples/orthographic.html

### ISSUE THREAD

**Issue by nosy-b** [iTowns/itowns#399]
When changing window size, the camera target location of the view jumps far away
It is the only example with this bug.
I can reproduce by following these steps:
- Launch examples/orthographic.html
- Move the map
- Go FullScreen

Expected results: Map center location stay the same
Actual results: Map center location moves far

**Comment by peppsac** [comment]
Can you add [detailled repro steps](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Bug_writing_guidelines#Writing_precise_steps_to_reproduce) please?

**Comment by peppsac** [comment]
Sorry it took so long to fix, I missed the edit in your original post.

**Comment by peppsac** [comment]
Fixed with #503
