### ISSUE TITLE
3DTiles: tile transformation matrix should be local to its parent

### ISSUE THREAD

**Issue by qdnguyen** [iTowns/itowns#414]
The transformation from each tile's local coordinate to the tileset's global coordinate system is computed by a top-down traversal of the tileset and post-multiplying a child's transform with its parent's transform. This is not the case now in Itowns.

https://github.com/AnalyticalGraphicsInc/3d-tiles#tile-transform

![image](https://user-images.githubusercontent.com/3224540/28622466-e9b42d24-7214-11e7-9600-997e4b66dce4.png)

he computed transform for each tile is:

TO: [T0]
T1: [T0][T1]
T2: [T0][T2]
T3: [T0][T1][T3]
T4: [T0][T1][T4]

```js
function computeTransforms(tileset) {
    var t = tileset.root;
    var transformToRoot = defined(t.transform) ? Matrix4.fromArray(t.transform) : Matrix4.IDENTITY;

    computeTransform(t, transformToRoot);
}
```

```js
function computeTransform(tile, transformToRoot) {
    // Apply 4x4 transformToRoot to this tile's positions and bounding volumes

    var inverseTransform = Matrix4.inverse(transformToRoot, new Matrix4());
    var normalTransform = Matrix4.getRotation(inverseTransform, new Matrix3());
    normalTransform = Matrix3.transpose(normalTransform, normalTransform);
    // Apply 3x3 normalTransform to this tile's normals

    var children = tile.children;
    var length = children.length;
    for (var k = 0; k < length; ++k) {
        var child = children[k];
        var childToRoot = defined(child.transform) ? Matrix4.fromArray(child.transform) : Matrix4.clone(Matrix4.IDENTITY);
        childToRoot = Matrix4.multiplyTransformation(transformToRoot, childToRoot, childToRoot);
        computeTransform(child, childToRoot);
    }
}
```

**Comment by autra** [comment]
@qdnguyen I fixed the formatting. Please check I didn't mess up. 

What are the 2 methods you put in the description? Is one the current function and the other the suggested one? Or else? Please edit your comment to describe them if you find it relevant.

If it's the case, then may I suggest you open a PR with your modification instead?

**Comment by peppsac** [comment]
@qdnguyen please have a look at:
- https://developer.mozilla.org/en-US/docs/Mozilla/QA/Bug_writing_guidelines#Writing_a_clear_summary 
- https://developer.mozilla.org/en-US/docs/Mozilla/QA/Bug_writing_guidelines#Writing_precise_steps_to_reproduce 

to help you format your issues. Thanks!

**Comment by Jeremy-Gaillard** [comment]
Do you have a tileset where this bug occurs to help me fix it?

**Comment by qdnguyen** [comment]
@autra : No, the picture and the functions are copied from the link above to help us understand how to do it, i will delete it if you want because it is in the link i cited.

@peppsac: ok, thanks

**Comment by qdnguyen** [comment]
@Jeremy-Gaillard  i try to push dataset to github withou success, you can download it from this link http://stereopolis.ign.fr/videosDemos/Test.7z 

the models are located in lyon, here is how it look like using cesium.

![image](https://user-images.githubusercontent.com/3224540/28661823-4cf6443c-72b8-11e7-8f71-adfacea947b8.png)

**Comment by NikoSaul** [comment]
@qdnguyen hi :) if you can check on the master if it's ok for you :+1:

**Comment by nguyenign** [comment]
it's ok for matrix transformation but the texture is desactivated and culling/loading priority still does not work.

**Comment by NikoSaul** [comment]
Yes, the culling it's not perfect, but if you want the texture, you have to put false [here](https://github.com/iTowns/itowns/blob/master/examples/3dtiles.html#L75) for your tileset.

**Comment by nguyenign** [comment]
ok, but when we desactivate the texture, we needs to have a default shader?

**Comment by Jeremy-Gaillard** [comment]
There is a default shader. If the buildings appear black, it is because no light source has been added to the scene.

**Comment by mgermerie** [comment]
The complete 3d-tiles support is planned in the short term road map. We are currently studying possibilities in terms of libraries to enhance support (as mentioned in #1917). Don't hesitate to reopen if needed.
