### ISSUE TITLE
Picking should perform on specific object (globe). not all scene3D

### ISSUE THREAD

**Issue by nosy-b** [iTowns/itowns#42]

**Comment by nosy-b** [comment]
enablePickingRender will set visibility to true to all its children so beware... 
But if your object is child of chid of scene , no problem. Will need a cleaner solution

**Comment by gchoqueux** [comment]
A part of the solution is brought into PR #111

**Comment by peppsac** [comment]
This was fixed in #301 (see `GlobeView.prototype.screenCoordsToNodeId method`)
