### ISSUE TITLE
Support for multiple provider

### ISSUE THREAD

**Issue by Jeremy-Gaillard** [iTowns/itowns#43]
I am currently stuck in the development of my application because of the lack of support for multiple providers (in my case, terrain + 3D buildings).
I propose an overhaul of the provider/commander code. The goal is to take out of the manager and interface commander all mention of a specific data type or provider in order to facilitate the integration of new providers.

I am willing to take care of the issue myself. These are the tasks I have in mind:
- Build the provider outside of the manager
- Unique get() function in the InterfaceCommander. Replace parameter array by parameter object (more flexible)
- Providers and the provided data types should be bound (i.e. each Provider has a _type_ attribute which stores the provided data type)
- (Slight) rework of the command class: store the function or the provider to call instead of the data type (which is already contained in the provider)
- Add provider to quadtree

Any objections or comments ?

Warning: this will break most of the branches. Better now than later.

NB: the same sort of work should be done for the nodeProcess/browseTree classes in my opinion

**Comment by tbroyer** [comment]
Just a note in passing: if it's going to break everyone, you might as well start from the webpack (#4) or amdtoes6 branches (I'll rebase them and resolve conflicts) and possibly use ES6 then to declare your classes.

**Comment by Jeremy-Gaillard** [comment]
Good point. I'll start working on it this afternoon if no one objects before.

**Comment by nosy-b** [comment]
It's a big move so we should exchange on it today :) 
At least you should talk directly to Gerald Choqueux on the providers/Comanders as he implemented it.

**Comment by Jeremy-Gaillard** [comment]
It may be easier to talk this out on IRC (#itowns @ irc.freenode.org) and post the conclusion in this issue afterwards. I'll be available to speak about it from 1PM onwards.

**Comment by gchoqueux** [comment]
- Build the provider outside of the manager --> why
- Unique get() function --> it is not a good function and is  temporary. I will make generic function.
- Replace parameter array by parameter object is good idea.
- Add provider to quadtree --> no provider in data structure, in good design architecture
- Providers and the provided data types should be bound --> I don't understand
- Rework of the command class: store the function or the provider to call instead of the data type --> I don't understand

The command manager regulate the commands by priority (for all commands : data request, animation, task in worker...). It's no possible if the provider is in data structure.

There is already provider terrain 3D + building, it's works with the current architecture.

PS : in future command manager will have a loaded queue.

**Comment by Jeremy-Gaillard** [comment]
1 - This may not be necessary. I just need to be able to define the options of my provider from outside the manager (and also I should not have to modify the manager each time I create a new provider type)
2 - I am aware that some of the code is temporary, but I still mentioned everything that needed changing according to me
4 - Okay, so there should be a dictionary linking a Layer to a Provider somewhere maybe ? Or the command should store the provider (6 -). [This is the problematic code](https://github.com/iTowns/itowns2/blob/master/src/Core/Commander/ManagerCommands.js#L116): `arrayTasks.push(this.providers[0].get(this.deQueue()));`.

 I think it should be changed to something like this: 
`var command = this.deQueue();
arrayTasks.push(command.provider.get(command));`
5 - Forget it, I'm not sure of the relevance of this point anymore
7 - I'm not sure about that, but anyway, we can keep a strict separation between data structure and provider
8 - The example works because the terrain and the buildings share the same data structure. In my case, the buildings are in a separate structure from the terrain (a hierarchy of bounding boxes vs a quadtree), so I need two providers.

**Comment by gchoqueux** [comment]
4 --> it's problematic
8 --> In my case, i have 3 separate datas structures (1 quatree WGS84, 1 quatree PM, 1 tree KML )

**Comment by Jeremy-Gaillard** [comment]
8 - I'd like to see how you do it, is the code available on the repository ?

**Comment by nosy-b** [comment]
@tbroyer 
For dev purpose, avoiding the build is useful (to see the sources organisation in debug + no compiling). How do we keep the old way ? The build should be done on release or for tests, or at least it should not change the main.js so we can still use it with require.

**Comment by Jeremy-Gaillard** [comment]
My updated suggestion to solve this issue: 
- In managerCommands, replace createProvider by an addLayer(layer, provider) function. This function updates the manager's new dictionary attribute, which links each layer to a provider
- Commands now have a layer attribute

This solution maintains a strict separation between the providers and the data structures and the providers. The manager is in charge of linking a provider to the right data structure.
This also allows us to define a provider without having to go through the manager, which seems to be a good idea to me.

One small concern: nothing prevents a developer from linking a provider to an incompatible layer. I don't think it's that important.

Thoughts ?

**Comment by gchoqueux** [comment]
there's change little change in provider in dev branch.
@Jeremy-Gaillard if you're in Paris next week, come to ign to discuss provider

**Comment by Jeremy-Gaillard** [comment]
I started some work on a [branch](https://github.com/iTowns/itowns2/tree/multiple_providers), implementing my second proposition.
The manager part works, but problems have arisen with the quadtree. The reason: the quadtree tries to fetch data during its initialisation, but the provider is not instantiated yet. Trying to solve this problem led me to other issues, see #40.
@gchoqueux I'll be in Paris, I'll try to see you there. I just looked at the changes, and they don't seem to conflict too much with those in my branch

**Comment by nosy-b** [comment]
I just pushed on the master some work on the WMTS provider and Browstree. You can now switch between 2 providers without changing the original quadtree (test with menu). It needed a function to update the already created nodes (updateNodeMaterial in Browstree.js). Not super clean but it works to test other wmts on same tree.
