### ISSUE TITLE
addLayer protocol parameter "wms" given in uppercase throws unhandled errors  

### ISSUE THREAD

**Issue by elias75015** [iTowns/itowns#455]
If we add a WMS layer with the globe.addLayer function, the parameter "protocol" needs to be in lowerCase.
If not, all the other tiles queries are freezed (for any layer), and the following error is launched : 
```
Uncaught TypeError: m.tileInsideLimit is not a function
    at Object.hasEnoughTexturesToSubdivide
```

These errors could be handled and not completely freeze the view.
Moreover, maybe the API documentation could be more explicit about the importance of the case of the "protocol" parameter (or even better, the function could accept any case for the protocol parameter ! ).

**Comment by autra** [comment]
2 things here: 
- If `layer.protocol` is not undefined but we don't recognize it, we should fail fast. This is #457. @elias75015 I believe this would have saved you some pain :-) Please tell me what you think about this PR.
- Unrelated to @elias75015 issue: do we want to support custom color and elevation layers without provider as soon as we have some mandatory functions attached to them (like `tileInsideLimit`)? If yes, we should do some sanity check after layer preprocessing. If no, we should throw an error if type is `color` or `elevation`, but provider is unknown. @iTowns/core-devs thoughts?

**Comment by elias75015** [comment]
I'm agree with your solution to the unknown protocol issue (#457), it is nicer for external devs if the error is quick with an explicit message.
