### ISSUE TITLE
Unlimited loop in "BrowseTree.prototype.processNode" on zoom out

### ISSUE THREAD

**Issue by nosy-b** [iTowns/itowns#46]
This 
`if (node.loaded && this.nodeProcess.frustumCullingOBB(node, camera)) {
                if (this.nodeProcess.horizonCulling(node, camera)) {
                    if (node.parent.material !== undefined && node.parent.material.visible === true)
                             return node.setVisibility(false);`

will be always executed after one zoom-out.

**Comment by nosy-b** [comment]
Not a real bug but should be processed on each camera position change and not at each render loop

**Comment by gchoqueux** [comment]
@nosy-b  this issue is still relevant?

**Comment by nosy-b** [comment]
Fine now
