### ISSUE TITLE
options.zoom parameter not taken into account for WMTS layers

### ISSUE THREAD

**Issue by elias75015** [iTowns/itowns#469]
Issue encountered with :
* G. Chrome v60.0.3112.113
* Ubuntu 14.04

## Context
When we add a WMTS/WMS layer, the parameters `options.zoom.min` and `options.zoom.max` allow to limit the display of the layer to the specified TileMatrixSet levels.

Unfortunately, these parameters are not taken into account for the WMTS layers (it works for WMS layers). 

As we can't limit the queries to specific TMS levels with the zoom parameter, if a layer is only defined from levels 5 to 10 (for instance), iTowns will try to request levels 1,2,3,4. This causes a big issue : all the queries, for all the layers added to the globe, are frozen. **No more queries will be launched until the WMTS layer is on the globeView.** 

## Steps to Reproduce
1 - Add parameter `"zoom" : { "min" : 8, "max" : 15 }` to the itowns/examples/layers/JSONLayers/ScanEX.json layer

## Expected Behavior
The ScanEX layer should only be displayed from level 8 to level 15

## Actual Behavior
The ScanEX layer is displayed for all zoom levels. The same with a WMS layer (REGION.json for example) works.

**Comment by peppsac** [comment]
Could you confirm that the PR https://github.com/iTowns/itowns/pull/473 fixes this bug?

**Comment by elias75015** [comment]
I confirm that the PR #473 fixes this bug, thanks !
