### ISSUE TITLE
Some Ortho Tiles don't load. Cause no elevation data? 

### ISSUE THREAD

**Issue by nosy-b** [iTowns/itowns#47]
Try moving from europe to africa, and zoom.
Easier to see with map wmts, ex: 
![bug](https://cloud.githubusercontent.com/assets/158514/13171883/72e057ce-d6f5-11e5-9d36-b58fb9041076.jpg)

**Comment by gchoqueux** [comment]
this issue is still relevant? @nosy-b

**Comment by nosy-b** [comment]
Not anymore
