### ISSUE TITLE
Adopt angular convention for git commit messages

### ISSUE THREAD

**Issue by peppsac** [iTowns/itowns#518]
As we adopted a code style for the js code, I'd like to explicitely adopt a style for git messages.

IMHO the style proposed at https://github.com/bcoe/conventional-changelog-standard/blob/master/convention.md is good and has an extra benefit: it allows to simplify changelog generation.

The important bits are:
- the template to follow:
```
<type>(<scope>): <subject>
<BLANK LINE>
<body>
<BLANK LINE>
<footer>
```
- the allowed types:
  * feat, perf, fix => these 3 are special because they are pickup when building the changelog
  * docs, chore, style, refactor, test

Last but not least, we should choose a set of allowed scopes to allow grouping of relevant changes in the changelog.
~Here's a first proposal~
Second version:
- core (when modifying MainLoop / View / core logic)
- gis (Coordinates, Extent, Ellipsoid)
- controls (GlobeControls, etc)
- ~process (or update) (when modifiying TileNodeProcessing..)~
- ~providers~
- examples
- protocols (wfs, wmts, etc changes)
- 3dtiles
- pointcloud
- vector (not using 'feature' here because it's already used for 'type' prefix)
- geometry (e.g when adding features to TileVS)
- debug

**Comment by peppsac** [comment]
(just edited the first post)

**Comment by zarov** [comment]
Good idea, I propose to add a file at the root of the repo, similar as this one https://gist.github.com/adeekshith/cd4c95a064977cdc6c50.

By doing `git config commit.template .git-commit-template.txt`, people will have the template with explanations on how to write their commit message, when doing a `git commit`. Maybe we could "force it" in a npm task ? Like a `init` (in `scripts` section) that would do this command, or at the beginning of `start` (but ugly...).

**Comment by autra** [comment]
Or, as a first step, we could start by amending https://github.com/iTowns/itowns/blob/master/CONTRIBUTING.md. 

I'm all to have a commit template file in the repo, and have the `git config` documented in CONTRIBUTING.md, but I'm not comfortable having it installed automatically (I do already use a custom commit template). That being said, if the majority of you want it installed automatically, I'll live with it.

**Comment by tbroyer** [comment]
+1 to the commit template, -1 to installing it automatically.

Would it be possible to have a check in Travis for PRs targeting the master branch? (`$TRAVIS_BRANCH == "master") or possibly for all PRs. Similar to https://github.com/angular/angular.js/blob/master/scripts/travis/build.sh#L22-L28

Also why not maybe add config for http://commitizen.github.io/cz-cli/

(note: I, for one, am not a fan of that convention, though I actually never practiced it; but if we put it in place, then better make it as easy as possible to follow it, and enforce it at CI level)

**Comment by zarov** [comment]
So this seems to have been acted, so I added it in CONTRIBUTING.md: https://github.com/iTowns/itowns/blob/master/CONTRIBUTING.md#pull-request-guidelines
