### ISSUE TITLE
[PointCloud] some issues with potreeviewer

### ISSUE THREAD

**Issue by qdnguyen** [iTowns/itowns#52]
Hello,

I have a potree which runs on our itowns V2 now. I needs more time to clean code but you can test it in my fork, branch dev, https://github.com/qdnguyen/itowns2.

Some probs i have recognized:
- When we zoom in to approach terrain, our globe runs very slowly, i think it's because of memory leak problem as our cache has unlimited size and is never cleaned. 
- My camera gets stuck, i can not turn it to see globe horizontally. It may be because of quaternion on WGS84? or maybe we need to to activate some option? 
- An important thing when we add a new provider/layers is that the new provider/layers can see camera and renderer, because in some provider/layers, we need camera to check visibility and renderer to have gl context. For now, to run Potree, i must initialize it in c3Dengine et update it there. Ceisum has the frameState where they pass camera and renderer to their quadtree provider. What is our solution?

**Comment by qdnguyen** [comment]
here is some image with point cloud on our globe

<img width="1280" alt="capture d ecran 2016-02-23 a 12 39 03" src="https://cloud.githubusercontent.com/assets/3224540/13252871/44e678ca-da39-11e5-842a-83630b9a5325.png">

**Comment by nosy-b** [comment]
For the third point, Potree is a good example effectively because it uses
its own independant Tree (octree) to analyze what should be loaded and seen.
So the Potree Layer (using potree provider) should have access to Camera
yes. Through the use of c3DEngine?

2016-02-23 14:25 GMT+01:00 qdnguyen notifications@github.com:

**Comment by nosy-b** [comment]
(But the c3DEngine SHOULD have NO potree or any specific layer written in its class)

**Comment by qdnguyen** [comment]
I'm ok that c3Dengine should not have potree, it's why i suggest to have a solution to pass camera and renderer to provider, and what they did in cesium is frameState. 

what is our solution?

**Comment by nosy-b** [comment]
First cheap solution: Your provider could import c3DEngine Module to make
use of its camera.

Second solution: Pass camera reference to your provider. **_But the fact is
the provider should not need the camera**_, just the BrowseTree of your layer
(Potree) (The actual BrowseTree is initiated with the c3DEngine for ex.)

2016-02-23 14:44 GMT+01:00 qdnguyen notifications@github.com:

**Comment by qdnguyen** [comment]
when i said provider, i mean provider for potree, but it's better to say "potree layer" than "potree provider".

1) it's similaire to what i did to see potree, but in fact, i dont need everything in c3DEngine, i need just camera and renderer, so i added potreeProvider directly in c3DEngien to do a test. 

2) yes, browsetree is our best choice, and it's good idea to improve it to be more generic to support other tree such as octree, kd-tree, etc, like 3D Tiles? 

I think we should not include c3DEgine in BrowseTree, only camera and renderer are fine?

**Comment by nosy-b** [comment]
@qdnguyen Yes, when close to the ground it can get very slow, I'll check.
And, talking about performance (@gchoqueux), we should try to lighten elevation processing 
![stats](https://cloud.githubusercontent.com/assets/158514/13259264/f18168a2-da56-11e5-829a-952109b90171.jpg)

**Comment by qdnguyen** [comment]
i'am totally sur that we have a memory leak because of our cache. It not come from potree as we dont have too much of test points now and my potree/cesium version is very fast...

**Comment by nosy-b** [comment]
Yes it is the globe itself. While working on projective texturing I implemented a pause function on the globe browserTree to verify the perf of the projection (adding a freeze attribute); you can use it too (branch immersive navigation)

**Comment by nosy-b** [comment]
@qdnguyen Can you try with the last master ( https://github.com/iTowns/itowns2/commit/90e132286b0c2a66a790a5c25a906fa1843896df ), at least with the new SSE function of Renderer/Camera.js? 
It should work much faster when lookin more horizontally, as it weight SSE with tile orientation to camera.

**Comment by qdnguyen** [comment]
yes, it's faster, but i can not look horizontally, my camera gets stuck, can you do a check on your PC?

**Comment by nosy-b** [comment]
Are you using the shift-MouseMove to orientate camera horizontally?

2016-02-24 10:24 GMT+01:00 qdnguyen notifications@github.com:

**Comment by nosy-b** [comment]
Elevation processing is now much lighter using sub sampling and leaving the buffer as it was
![idle](https://cloud.githubusercontent.com/assets/158514/13287327/c0fb244c-db06-11e5-8316-6a172153abed.jpg)

**Comment by peppsac** [comment]
I opened a new PR to get PointCloud rendering support in iTowns: see #400
