### ISSUE TITLE
Best way to update tree elements synchronously

### ISSUE THREAD

**Issue by gchoqueux** [iTowns/itowns#520]
the elements of the viewer are updated asynchronously in the `MainLoop` (via `notifyChange`)
I need to refresh elements synchronously and immediately when I use `viewer.getPickingPositionFromDepth`

this part should be made accessible, WDYT?
```js
if (geometryLayer.ready) {
            // `preUpdate` returns an array of elements to update
            const elementsToUpdate = geometryLayer.preUpdate(context, geometryLayer, updateSources);
            // `update` is called in `updateElements`.
            updateElements(context, geometryLayer, elementsToUpdate);
            // `postUpdate` is called when this geom layer update process is finished
            geometryLayer.postUpdate(context, geometryLayer, updateSources);
  }
```

**Comment by peppsac** [comment]
Could you expand a little more on why you need `to refresh elements synchronously and immediately`?
Or can you write an example usage of this?

**Comment by gchoqueux** [comment]
If I move camera and immediately I use `viewer.getPickingPositionFromDepth`, the result is wrong because the elements are not updated.

**Example 1 doesn't work** 
```js
camera.position.copy(newPosition);
camera.lookAt(newTarget);
const pick = viewer.getPickingPositionFromDepth();
// ---> pick is wrong because the elements aren't updated 
```
**Example 2 doesn't work** 
```js
camera.position.copy(newPosition);
camera.lookAt(newTarget);
// this isn't enough because the update is asynchronous
viewer.notifyChange();
const pick = viewer.getPickingPositionFromDepth();
// ---> pick is wrong because the elements aren't YET updated 
```
**Example 3 works** 
```js
camera.position.copy(newPosition);
camera.lookAt(newTarget);
// Force to update immediately (but not the right way)
view.mainLoop._step(view);
const pick = viewer.getPickingPositionFromDepth();
// ---> pick is good because the elements are updated 
```

**Comment by autra** [comment]
Maybe we can make view.notifyChange return a promise resolved after next update?

**Comment by peppsac** [comment]
> Maybe we can make view.notifyChange return a promise resolved after next update?

Another option is: 
1. modify `viewer.getPickingPositionFromDepth()` to return a promise
2. (optionnally) call notifyChange() from `getPickingPositionFromDepth()` if needed (if camera.matrixWorldNeedsUpdate is true)

The best choice is probably to experiment with different solutions and see what works best.

**Comment by gchoqueux** [comment]
@autra 

> Maybe we can make view.notifyChange return a promise resolved after next update?

I'm not for an asynchronous promise to get depth information about our scene, because it's possible to have the depth synchronously.

@peppsac 

> 1. modify viewer.getPickingPositionFromDepth() to return a promise

How know if the geometry layer is updated, to resolve the Promise?

> 2. call `notifyChange() `

Doesn't work see example 2
 



I will be more for something like : 
```js
if (camera.matrixWorldNeedsUpdate) {
   view.update(layerGeometry);
}
view.getPickingPositionFromDepth()
```

**Comment by autra** [comment]
I'm not very fond of doing update outside of MainLoop. The whole point was to have a unified mechanism for these update to make them easier to reason with. This code would break this assumption. 

It's possible to get the depth synchronously *when* the scene is up-to-date. So reliably getting the depth is actually a 2-step process:
- update the scene (asynchronous)
- measure the depth (synchronous)

The whole process is therefore asynchronous. So it makes sense to me to make this function return a promise (which can directly be Promise.resolve(depth) is camera.matrixWorldNeedsUpdate is false). Thoughts?

**Comment by autra** [comment]
Anyhow, I think it's generally useful to have view.notifyChange return a promise (and it's necessary for your solution to work anyway @peppsac, right?).

**Comment by gchoqueux** [comment]
@autra I agree, this is justified by the `requestAnimationFrame` that is asynchronous

but it should be noted that in function `MainLoop._step`
- update the scene is synchronous, because we have to make sure the scene is updated
- render scene is synchronous

and `getPickingPositionFromDepth` it is also a rendering, updating scene should also be synchronous

WDYT?

I will explore your proposals
