### ISSUE TITLE
Some layers are not displayed

### ISSUE THREAD

**Issue by elias75015** [iTowns/itowns#525]
##  Environment

* Browser Name and version: Chrome 61
* Operating System and version (desktop or mobile): Ubuntu 14.04

## Context

I try to update the geoportal project with the last version of the iTowns library (branch master). 
I encounter a bug : some layers are not displayed, even if in the network tab of the Chrome development console the queries are correctly launched, and responses are "200".

The issue happens on the main iTowns example. The Scan Express layer is not displayed (see below to reproduce).

## Steps to Reproduce (for bugs)

1. Open the main itowns example (index.html) in a web browser.
2. In the GuiTools Menu, set as "not visible" all the color layers except the "ScanEX" one.

## Expected Behavior

The Scan Express layer should be displayed.

## Actual Behavior

The Scan Express layer is not displayed (even if queries are correctly launched)

![scanex_notdisplayed](https://user-images.githubusercontent.com/6764800/31445636-ba546d66-ae9e-11e7-9272-44daa2f0e5a0.png)

## Possible Cause/Fix/Solution

I tried to checkout on old master commits, to identify the origin of the problem. The commit b2e616c seems to have introduced this bug. Before it, the problems described above were not visible.
If the bug is confirmed, maybe it could be interesting to add tests on the build to check if layers were correctly added/displayed.

**Comment by peppsac** [comment]
My bad, see PR #526 for a fix.

**Comment by elias75015** [comment]
Thanks for the fix !
