### ISSUE TITLE
Update of layers opacity and visibility is broken 

### ISSUE THREAD

**Issue by elias75015** [iTowns/itowns#562]
## Your Environment
* Browser Name and version: Chrome 61
* Operating System and version (desktop or mobile): Ubuntu 14.04

## Context
With the globe, the layer opacity and visibility is not correctly updated when we change it. 
It seems like this problem was not visible before commit e3db2308f3cca7f6eaa17f68779d48909d92339c.

## Steps to Reproduce (for bugs)
1. open the main globe itowns example
2. play with the layer manager tool (change opacity/visibility of the layers).

## Expected Behavior
The layers states (opacity/visibility) are immediately changing.

## Actual Behavior
The layers states are not changing, unless we zoom/de-zoom, and tiles are not fully loaded.

**Comment by gchoqueux** [comment]
it isn't fixed

**Comment by autra** [comment]
The opacity is working. Apparently the visible checkbox is not.

**Comment by autra** [comment]
This has been auto-closed since I merged #565. Don't hesitate to double-check @elias75015 @gchoqueux.Thanks!

**Comment by elias75015** [comment]
It is fixed, thanks !
