### ISSUE TITLE
Clean Repository

### ISSUE THREAD

**Issue by gchoqueux** [iTowns/itowns#595]
I start to clean repository,  I remove dead or redundant branches.
Can you move/delete a maximum of your dead or redundant branches.

For my part I move some of my branches on my fork. 
Do you know a way to automatically synchronize upstream repo with a github fork (without cloning the fork locally).

**Comment by gchoqueux** [comment]
I found this [https://upriver.github.io/](https://upriver.github.io/)
But there are so many branches that it doesn't show them all in combo box :)

**Comment by zarov** [comment]
Not automatically, but there are some resources online about simple synchronization:
https://gist.github.com/EvanDotPro/1506822

**Comment by autra** [comment]
Or a simpler solution: don't synchronize it ;-) After all, you don't need an updated master on your fork, just create local branches from itowns/itowns#master, you can still push your wip branches to \<user\>/itowns first, then open a PR from them, or push them to itowns/itowns later.
