### ISSUE TITLE
providers and copyright

### ISSUE THREAD

**Issue by massea** [iTowns/itowns#60]
What is the politic about copyrights ?
For the moment, we use IGN otho and elevation but we will also use global elevation and global imagery (and for my part, bathymetry and tidal data) and it will be necessary to cite the sources.

**Comment by nosy-b** [comment]
Yes you're right we should mention the geographic sources at the bottom of the screen

**Comment by nosy-b** [comment]
(Each active provider **domain** should be inserted into the Copyright List and displayed.)

**Comment by gcebelieu** [comment]
More generaly, I think itowns should provide the ability to display mention of resources providers through a widget like openlayers (http://openlayers.org/en/v3.14.2/apidoc/ol.Attribution.html) or leaflet (http://leafletjs.com/reference.html#control-attribution) do.
The responsibility to display (or not) ressources references is left to itowns users.

**Comment by vpicavet** [comment]
+1 @gcebelieu 
Let's transform this ticket into "create a widget for resources attributions"
Meanwhile we can list providers and attribution somewhere in the doc or code.

**Comment by gcebelieu** [comment]
sounds good to me.
@vpicavet @nosy-b @gchoqueux @massea In the same time, another issue may also be created (I'll do it) : "Data resources (elevation, images, features and others ) should not be hardcoded in itowns2 code but only in examples".

**Comment by gcebelieu** [comment]
These 2 issues will be handled in : #62
