### ISSUE TITLE
add single THREE.Object3D management in GeometryDebug interface

### ISSUE THREAD

**Issue by gchoqueux** [iTowns/itowns#641]
Come from an [idea](https://github.com/iTowns/itowns/pull/626#pullrequestreview-94260886) of @autra in PR #626 : 

 * What would be very great is to have debug tools for this. A good possible way to do it would be to just adapt `GeometryDebug` to take an object3d. (ie renaming and testing for the type of the layer parameter, and do a traverse if it's a Object3D).
In this case collada example, the actual Mesh containing the house has an array in .material, not a single material, so you'll need to deal with this case too.

 * we can also see the usefulness of a picking function without a layer parameter

**Comment by peppsac** [comment]
> we can also see the usefulness of a picking function without a layer parameter

I have some good news for you: PR #635 adds exactly this :-) (see
https://github.com/iTowns/itowns/pull/635/files#diff-11ecfe7e737c10e75920ac54de872437R104)

**Comment by gchoqueux** [comment]
These features have been integrated.
