### ISSUE TITLE
Question about npm and file watching

### ISSUE THREAD

**Issue by gliegard** [iTowns/itowns#647]
How can I make the tool NPM to watch "example" and "test" folder during development,
like it doest with the "src" folder when I use "npm start" command ?

## Description
Actually, the command "npm start" shows lint errors and warnings,
when you modify a file in the source folder, and it's a good thing.

I'd like to have the same behavior when I modify a file in the "example" and "test" folder.

How can I do that ?

## Context
The context is the development of 
- a new example
- a unit test

**Comment by autra** [comment]
Actually, it's not npm that watches `src/`, but the `webpack-dev-server`. Then files are linted with `eslint-loader` (see webpack.config.js).

AFAIK eslint doesn't have a --watch option, but there is [eslint-watch](https://www.npmjs.com/package/eslint-watch) that does that. You'll have to install both eslint and this package globally, and then use a cli similar to the one in `npm run lint`.

**Comment by gchoqueux** [comment]
@gliegard the question is still topical?
