### ISSUE TITLE
Remove CVML and utils.js and clean GeoJSONToThree.js

### ISSUE THREAD

**Issue by gchoqueux** [iTowns/itowns#65]
CVML is too big and redundant

**Comment by qdnguyen** [comment]
CVML is used for do triangulation, without it, we can not contruct the roof of RGE footprints.

In the module, i also stock some other algorithmes to do alignement/recalage, ransac, pcl... they can be removed as they are not used for visualization.  

Same for utils.js some parts must keep and other needs to be cleaned.

**Comment by gchoqueux** [comment]
I know what it is,  it's too redundant.
It's same thing for utils.js. you must rename this file.  Several functions are already in THREE. 
Where is used  utils.js and why?
the organization must be clean, limit external files and store them in third party.

**Comment by nosy-b** [comment]
Yes utils should actually be removes it's not used.
CVML must go extern and be strongly lightened to keep jsute the
triangulation function  (useful for roof but also any 2D polygon we 'll
want to extrude later)

2016-03-23 11:20 GMT+01:00 Gérald Choqueux notifications@github.com:

**Comment by qdnguyen** [comment]
Attention: if you keep only triangulation part, CVML become poly2tri, and this lib exists a version of nodejs, so i strongly recommand you to use it directly. 

Otherwise, we need to put copyright in module.

https://www.npmjs.com/package/poly2tri

**Comment by Jeremy-Gaillard** [comment]
As an alternative, [earcut](https://www.npmjs.com/package/earcut) seems to be way faster and regularly updated. I used it in my branch with success.

**Comment by nosy-b** [comment]
@Jeremy-Gaillard  good news! we should go for it so

**Comment by qdnguyen** [comment]
i think it's better to select one!

@Jeremy-Gaillard why do you needs to do triangulation? your models are already in mesh, non?

**Comment by mbredif** [comment]
Some input data are not already triangulated.
eg we may want to show planar (or almost planar) 3D polylines as filled
polygons.

## 

Mathieu Brédif
IGN - Institut National de l'Information Géographique et Forestière
Laboratoire MATIS
73 avenue de Paris 94165 Saint-Mandé
recherche.ign.fr/labos/matis/~bredif
Tel: +33 (0)1 43 98 83 19

**Comment by Jeremy-Gaillard** [comment]
@qdnguyen no, the data I receive consists of polygons
See: https://github.com/iTowns/itowns2/blob/BoundingBoxHierarchy/src/Core/Commander/Providers/GeoJSONToThree.js

**Comment by gchoqueux** [comment]
GeoJSONToThree.js needs to clean up, there are redundants functions : 

`function dot(u,v)`
`function minus(u,v)`
`function cross(u,v)`
`function normsq(u)`
`function norm(u)`
`function mult(u, x)`

and may be others

the code needs to be factorized

**Comment by Jeremy-Gaillard** [comment]
Yeah, probably. It's not ready for pull yet, I just mentioned it to illustrate the use of earcut.

**Comment by qdnguyen** [comment]
well, i found this too http://threejs.org/examples/#webgl_geometry_extrude_shapes2
Seem the problem can be resolved by THREE.ExtrudeGeometry

**Comment by gchoqueux** [comment]
nice, who replace the code?
