### ISSUE TITLE
Sky turns black when low altitude and high tilt

### ISSUE THREAD

**Issue by fnicollet** [iTowns/itowns#652]
Hello,

Trying iTowns, with only the ortho. As I tilt the map, the sky suddently renders black instead of being blue:
![image](https://user-images.githubusercontent.com/1240481/36096763-01a28292-0ff8-11e8-9589-c84acaf8af11.png)

Reproduced in Chrome with the following code:
```
var positionOnGlobe = { longitude: 2.471311, latitude: 49.258868, altitude: 25 };
// iTowns namespace defined here
var viewerDiv = document.getElementById('viewerDiv');
var globeView = new itowns.GlobeView(viewerDiv, positionOnGlobe);
globeView.addLayer(ORTHO);
globeView.addEventListener(itowns.GLOBE_VIEW_EVENTS.GLOBE_INITIALIZED, function(){
	console.log("itowns.GLOBE_VIEW_EVENTS.GLOBE_INITIALIZED");
globeView.controls.setTilt(80, true);
});
```

As you zoom out, the sky turns back to blue

Fabien

**Comment by zarov** [comment]
@peppsac this is the fault of `t` being a `NaN`. Do you know why, as you seem the most recent contributor to this piece of code ? https://github.com/iTowns/itowns/blob/master/src/Core/Prefab/GlobeView.js#L267

**Comment by peppsac** [comment]
No idea. But this formula comes from `00b17d26dbe3842c656a2fcb4486e6268f8ca41d` (it was moved from `c3DEngine.js` to `GlobeView.js`).

**Comment by gchoqueux** [comment]
I'll fix it, simplify and explain the code
