### ISSUE TITLE
When using a custom position and (low) altitude, iTowns fetches many useless tiles

### ISSUE THREAD

**Issue by fnicollet** [iTowns/itowns#653]
Hello,

With an "hello world" example:
```
var positionOnGlobe = { longitude: 2.471311, latitude: 49.258868, altitude: 25 };
// iTowns namespace defined here
var viewerDiv = document.getElementById('viewerDiv');
var globeView = new itowns.GlobeView(viewerDiv, positionOnGlobe);
globeView.addLayer(ORTHO);
globeView.addEventListener(itowns.GLOBE_VIEW_EVENTS.GLOBE_INITIALIZED, function(){
	console.log("itowns.GLOBE_VIEW_EVENTS.GLOBE_INITIALIZED");
	 globeView.controls.setTilt(80, true);
});
```
iTowns requests about 173 ortho tiles, including z2, z3, etc. tiles. For instance, this tile is downloaded, while I am creating a map located in France:
![image](https://user-images.githubusercontent.com/1240481/36097354-e8e9ad5e-0ffa-11e8-8632-e366e78e44a3.png)
It looks like iTowns request all the z2, z3, etc. tiles for the whole world, which is quite surprising. Is iTowns loading these tiles as a "backup" in case the low-level tiles are not loading? In any case, downloading tiles located in the US sounds like a bug more than anything

Thanks,
Fabien

**Comment by gchoqueux** [comment]
After PR #644, iTowns requests 25 Ortho tiles. This PR seems to have significantly optimize fetching.
But there is still work to optimize the fetching.

**Comment by gchoqueux** [comment]
In the current version of **itowns 2.6.1**, there are now 20 downloaded textures -> 4 displayed textures  + 16 forced textures with zoom 2.

if you use `minSubdivisionLevel = 1` in viewer option, there are only 8 downloaded textures.
```js
view = new itowns.GlobeView(viewerDiv, positionOnGlobe, { minSubdivisionLevel: 1 });
```
