### ISSUE TITLE
WEBGL issues on mobile devices

### ISSUE THREAD

**Issue by fnicollet** [iTowns/itowns#654]
As a followup on #645, here is a test that fails on my Sony Xperia Z3 mini.
I try the "Globe" example, and WebGL crashes. In the console, I have:
```
THREE.WebGLRenderer 89
itowns.js:1 THREE.WebGLRenderer: Error creating WebGL context.
Me @ itowns.js:1
itowns.js:5 Failed to create WebGLRenderer TypeError: Cannot read property 'getExtension' of null
    at Object.get (itowns.js:1)
    at n (itowns.js:1)
    at new Me (itowns.js:1)
    at new r (itowns.js:5)
    at i.r [as constructor] (itowns.js:5)
    at new i (itowns.js:5)
    at globe.js:16
r @ itowns.js:5
itowns.js:5 Uncaught Error: WebGL unsupported
    at new r (itowns.js:5)
    at i.r [as constructor] (itowns.js:5)
    at new i (itowns.js:5)
    at globe.js:16
globe.html:107 Uncaught TypeError: Cannot read property 'addEventListener' of undefined
    at globe.html:107
```
The THREE.js example work on this device. Here is what Webglreport.com says:
![screenshot_20180212-135829](https://user-images.githubusercontent.com/1240481/36097838-eb952d6a-0ffc-11e8-8eca-975c48f6bff4.png)
![screenshot_20180212-135823](https://user-images.githubusercontent.com/1240481/36097843-ed345484-0ffc-11e8-9cb0-f31e8e26b4e9.png)

Is iTowns using some WebGL 2 features that would prevent it from loading on some devices?

Thanks,

**Comment by autra** [comment]
Hi @fnicollet. I reproduce your issue. Please note that the error you have is probably not  the real error, which is:

> 
> THREE.WebGLProgram: shader error:  0 gl.VALIDATE_STATUS false gl.getProgramInfoLog   
> le @ itowns.js:1
> acquireProgram @ itowns.js:1
> x @ itowns.js:1
> w @ itowns.js:1
> Me.renderBufferDirect @ itowns.js:1
> y @ itowns.js:1
> g @ itowns.js:1
> Me.render @ itowns.js:1
> (anonymous) @ itowns.js:5
> r._renderView @ itowns.js:5
> r._step @ itowns.js:5
> (anonymous) @ itowns.js:5
> requestAnimationFrame (async)
> r.scheduleViewUpdate @ itowns.js:5
> r.notifyChange @ itowns.js:5
> (anonymous) @ itowns.js:5
> Promise.then (async)
> i.runCommand @ itowns.js:5
> (anonymous) @ itowns.js:5
> setTimeout (async)
> i.execute @ itowns.js:5
> i @ itowns.js:5
> r.preprocessDataLayer @ itowns.js:5
> i @ itowns.js:5
> r.addLayer @ itowns.js:5
> i.addLayer @ itowns.js:5
> i @ itowns.js:5
> (anonymous) @ globe.js:16

After you get this first error, if you refresh the page, you get the error you included above (maybe the driver crashes?), until you restart chrome. Do you confirm that?

> Is iTowns using some WebGL 2 features that would prevent it from loading on some devices?

No, itowns is pure webgl1 AFAIK. 

I've tested #309, and it should fix this issue.

**Comment by fnicollet** [comment]
Thanks for working on this issue. I'll wait for #309 to be merged so that I can try out the examples online and let you know

**Comment by mgermerie** [comment]
This is linked with #164. You can decide to use WebGL1 instead of the default WebGL2 as explained [here](http://www.itowns-project.org/itowns/docs/#tutorials/webgl).
