### ISSUE TITLE
TODO fix wrong OBB for 3DTiles

### ISSUE THREAD

**Issue by gchoqueux** [iTowns/itowns#655]

**Comment by autra** [comment]
Issues are more than a TODO list, they are also a way of communicating. Maybe someone else found the same bug. Seeing that an issue already exists and that you are assigned to it is a valuable info for them. So: can we have a proper description and repro steps on this please? We didn't put an issue template to have it blindly deleted, thanks.

**Comment by gchoqueux** [comment]
yes, I know, it was temporary
