### ISSUE TITLE
Mapbox tilelayer layer support 

### ISSUE THREAD

**Issue by jamesdeantv** [iTowns/itowns#658]
## Your Environment
Web

## Context
Is it currently possible to add mapbox tile layers to a globe view?  if so, is there a demo/fiddle available? I fetched the mapbox vector layer branch, but it doesn't provide a working example using a globe view.

**Comment by zarov** [comment]
Ah, you are too quick ! We are currently looking into the mapbox tiles, so the branch you fetched is in progress. I didn't pushed yet the globe demo I have on my computer, as it is not working at all for the moment.

You can follow the discussion about mapbox tiles in #182, and feel free to participate too !

**Comment by zarov** [comment]
Solved through multiples PRs, you can see it in https://github.com/iTowns/itowns/blob/master/examples/planar_vector_tiles.html and https://github.com/iTowns/itowns/blob/master/examples/globe_vector_tiles.html
