### ISSUE TITLE
Post-processing

### ISSUE THREAD

**Issue by Jeremy-Gaillard** [iTowns/itowns#66]
I have been trying to integrate post-processing into iTowns the past few days and stumbled on a lot of difficulties. I put this project on hold since I don't have enough time for it right now. This is a summary of what I learned and the different approaches I tried. This is not a pressing issue, its purpose is mostly informational.

Adding additional render passes is pretty easy with ThreeJS. The [Effect Composer](https://github.com/mrdoob/three.js/blob/master/examples/webgl_postprocessing.html) class allows the addition of any number of passes and there are already a lot of [shaders already implemented](https://github.com/mrdoob/three.js/tree/master/examples/js/postprocessing).

This is the easy part. This allows us to do simple post-processes based solely on the colour of each pixel. More advanced prost-processes require additional information, such as depth or normal directions.

The hard part is outputting the necessary data from the first pass, i.e. depth texture, normal texture, etc. The standard way ThreeJS applications handle this is to do several full render pass (i.e. vertex shader + fragment shader):

``` javascript
composer = new THREE.EffectComposer( renderer );
composer.addPass(...);
...
scene.overrideMaterial = materialDepth; // force the use of a material that draws the depth of the object
renderer.render(scene, camera, TextureDepth); // render to texture
scene.overrideMaterial = materialDepth; // remove the material overriding
composer.render();
```

Besides being not really efficient (it would be better if all the data could be save into textures in one fragment shader pass), this method won't work in iTowns: we can't simple override the material, since we have special uniforms for RTC rendering. A solution could be replacing only the shaders of the objects, but there's no simple way of doing it: all the objects of the scene need to be traversed.

The other way of approaching the problem is using the draw_buffer WebGL extension: it allows a shader to render in multiple textures attached to a framebuffer. However, ThreeJS doesn't support this extension yet. I tried working around the problem using native WebGL calls inspired by [this](http://stackoverflow.com/questions/29770340/its-possible-to-use-the-draw-buffer-extensions-with-three-js) stackoverflow post and [this](https://hacks.mozilla.org/2014/01/webgl-deferred-shading/) blog post, but to no avail. Maybe someone with a better understanding of OpenGL and 3D would succeed?

**Comment by peppsac** [comment]
PR https://github.com/iTowns/itowns2/pull/308 allows to implement post-processing. 
Feel free to give it a try and post your feedback over there.

Thanks
