### ISSUE TITLE
Drag and drop provider

### ISSUE THREAD

**Issue by mbredif** [iTowns/itowns#702]
Add a provider that inserts drag and dropped files.

## Context
This issue leverages the new homogeneized parsers. #701 

## Expected Behavior
When a file is drag and dropped to the itowns div, it is loaded by a suitable (or specified) parser and added to the scene.

**Comment by gchoqueux** [comment]
Now, for your feature, you can use [`FileSource`](https://github.com/iTowns/itowns/blob/master/src/Source/FileSource.js). See examples in [documentation](http://www.itowns-project.org/itowns/API_Doc/FileSource.html). After drop file, you instance a new layer with `FileSource url` linking on your file.

**Comment by mbredif** [comment]
see drag'n'drop demo #1159
