### ISSUE TITLE
MultiLineString rendering is broken

### ISSUE THREAD

**Issue by ilokhat** [iTowns/itowns#711]
The rendering of Multilinestrings seems to be broken in latest master commit.
I tried with the latest deployed version (using `npm install itowns`) and it is fine, but using a build from master does not display anything, with the following errors : 
```
[.Offscreen-For-WebGL-0x56216cf303b0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 0
```

I thought it was perhaps caused by my data, but I have the same issue with the roads from BD TOPO  ('BDTOPO_BDD_WLD_WGS84G:route')

## Your Environment

* Version used: itowns build with npm pack from commit 29e0799e586a479be8bfab3d91bb9aca2b7ec080
* Browser Name and version: Chromium 65 / Firefox 59
* Operating System and version (desktop or mobile): Ubuntu 16.04 x86_64

**Comment by autra** [comment]
When you're speaking about `BD TOPO ('BDTOPO_BDD_WLD_WGS84G:route')`, am I right infering this is from the ign WFS geoportail endpoint?

**Comment by ilokhat** [comment]
yes !

**Comment by zarov** [comment]
@ilokhat could you share the json describing the layer added for the BD TOPO ('BDTOPO_BDD_WLD_WGS84G:route'), so we can test it too ?
