### ISSUE TITLE
Can't remove objects from scene

### ISSUE THREAD

**Issue by Jeremy-Gaillard** [iTowns/itowns#72]
Nodes can't be removed from the scene at the moment. The reason is simple: node.remove is not implemented yet (but is called nevertheless...).

The fix is not a simple as it seems. Implementing node.remove has some unexpected side effects.

When creating a layer, this is the structure you obtain (arrows indicate parent to child relationship): 

Layer -> root -> [level-0 nodes] -> [...]

When adding a node to the 3D scene, the root of a layer is added to the scene3D object (which is of the type THREE.Object3D): scene3D.add(root). [This is the THREE.Object3D.add code](https://github.com/mrdoob/three.js/blob/master/src/core/Object3D.js#L278). As you can see, when adding a new node to scene3D, the node is also removed from the previous node's parent.

So layer.remove(root) is called. Currently, the remove function isn't implemented,so it works fine. But adding its implementation removes the root object from the layer, and nothing is ever loaded. We can't add the layer directly to the scene because it is not a renderable object (does not inherit from THREE.Object3D).

I think the easiest solution is to cut the layer <-> root parent / child relationship and just add the root as an attribute of the layer, but this still needs verification.

**Comment by Jeremy-Gaillard** [comment]
[Temporary fix in #71](https://github.com/iTowns/itowns2/blob/tile_creation/src/Scene/Quadtree.js#L37)

I wonder if layer should really be a node.

**Comment by gchoqueux** [comment]
where you remove object?

**Comment by Jeremy-Gaillard** [comment]
When disposing of a node (TileMesh.js).
It also happens automatically when adding a node to the scene3D object, as explained in the issue.
