### ISSUE TITLE
Images not always loading

### ISSUE THREAD

**Issue by Jeremy-Gaillard** [iTowns/itowns#73]
Image loading randomly cancels. The image request is completed but the callback attached to the load event is never triggered. The problem lies with the way image loading is handled in the I/O drivers. Until the load event triggers, the image object is referenced by no other objects, so the garbage collector may destroy it before the image is loaded.

[I fixed it in a branch by adding the image to the resolve object. I'm sure there is a better way to handle it.](https://github.com/iTowns/itowns2/blob/planar/src/Core/Commander/Providers/IoDriver_Image.js)

This problem probably occurs with other I/O drivers.

**Comment by gchoqueux** [comment]
how to reproduce the bug?

**Comment by Jeremy-Gaillard** [comment]
The bug is by nature random. You should be able to increase the chance of the bug happening by slowing down the download speed of your browser.
You can then compare the number of onload calls and completed image downloads. It should be the same when the bug is solved.

**Comment by gchoqueux** [comment]
@Jeremy-Gaillard you have always the problem?

**Comment by Jeremy-Gaillard** [comment]
Not any more. I'm closing the issue.
