### ISSUE TITLE
Performance, very slow (5 FPS), in globe WFS extruded example, since hole support

### ISSUE THREAD

**Issue by gliegard** [iTowns/itowns#731]
The globe WFS extruded example is very slow since hole support.

## Steps to Reproduce (for bugs)
1. Start FPS Meter on Chrome : console -> Rendering -> FPS meter
2. Try the code before hole support
git checkout 2de6ba7a66b5332dec0bc35cb067eeae50818f8d
3. Check the WFS Extruded example.
It shows between 40 and 60 FPS
4. Try the code after the hole support
git checkout a212dde70542b2a4480eb064df45820cad847363
5. WFS Extruded example shows between 3 and 8 FPS

## Expected Behavior
The examples should give a good user experience.

## Actual Behavior
The globe WFS extruded example is very hard to use, the computer seems to freeze.

**Comment by gliegard** [comment]
ping @peppsac

**Comment by peppsac** [comment]
Could you use the profiler to find out the culprit?

**Comment by gchoqueux** [comment]
@peppsac 
The @gliegard's issue isn't a reason to assign him the work to fix it. 
or maybe you just wanted to know if the profiler has been used ?

**Comment by peppsac** [comment]
> maybe you just wanted to know if the profiler has been used

@gchoqueux yes, I only suggested ("could you?") that he took a quick look at the profiler to see if the issue is obvious.

**Comment by gchoqueux** [comment]
Since the PR #691, each feature have one mesh, right?
suggestions of culprit :
- too many drawcalls
- resolve ray casting

**Comment by gliegard** [comment]
I think the problem is the number of meshes :
- Before PR #691 , the globe WFS extruded example had to create 9 meshes for all the buildings.
- Now, it creates 8000 meshes for the same example.

Another thing, your commit a212dde70542b2a4480eb064df45820cad847363 
- do the hole support, and thanks for this work, it's great !
- remove the geometry merging (I think the problem is here)

It's shame that there is only one commit for these 2 features.
If there was one commit for the 'geometry merge', I would revert it in a branch to test performance.

@peppsac What do you think about that ? Can we go back to have less meshes to draw easily ?

**Comment by peppsac** [comment]
Thanks for your suggestions of what the problem might be.

A profiling capture would be more helpful though because I don't reproduce the problem here (maybe my machine is faster? maybe this only happens on Windows? maybe I'm not doing the same test as you?).

**Comment by gliegard** [comment]
> Thanks for your suggestions of what the problem might be.

I think PR #691 introduce a bug , drawing 8000 meshes instead of 9.


> A profiling capture would be more helpful though because I don't reproduce the problem here (maybe my machine is faster? maybe this only happens on Windows? maybe I'm not doing the same test as you?).

I'm on ubuntu 16.04.

To reproduce :
with chrome FPS meter (console -> Rendering -> FPS meter)
git checkout 2de6ba7
try the globe WFS extruded example, Note that the FPS is always near 60.
git checkout a212dde
try the globe WFS extruded example, Note the FPS 

You really don't have a FPS difference ?

**Comment by mbredif** [comment]
I think we should definitely merge these geometries in a small number of geometries. Even if 8000 meshes is not an issue on some machines, we will sooner or later want to visualize bigger datasets.

My proposal would be to add an `id` (featureId? batchId ?) attribute and merge all these geometries (using  1 `BufferGeometryUtils.mergeBufferGeometries` call per type of THREE.Object3D) so that the output will be equivalent to the parsed output of 3dtiles tiles. That will enable the upcoming stylization code to work interchangeably on both sources.

**Comment by peppsac** [comment]
> My proposal would be to add an id (featureId? batchId ?) attribute and merge all these geometries (using 1 BufferGeometryUtils.mergeBufferGeometries call per type of THREE.Object3D)

Sounds good, as long as it's optionnal.
The picking code will also need to handle both cases (merged or unmerged).

**Comment by gchoqueux** [comment]
For `batchid`, there's the possibility to use #673

**Comment by gchoqueux** [comment]
Several users reported the same problem. it's an important regression which will be fixed before the next release.

**Comment by gchoqueux** [comment]
I realised benchmark which highlights the degradation of the performances for the conversion but also for the rendering. In conclusion PR #691  divided the performances by **2.5**.

   - Before bug from PR #691, total time by functions are :
     - ` geojsonParser.parse`  320 ms
     - `feature2Mesh`  216 ms
         `parse + convert` 536 ms
     - `renderScene` 350 ms
     - **total** 866 ms

   - From introduction of bug with PR #691, total time by functions are :
     - ` geojsonParser.parse`  874 ms (x 2.7 slower)
     - `feature2Mesh`  451 ms (x 2.1 slower)
        `parse + convert ` 1325 ms (x 2.5 slower)
     - `renderScene` 885 ms (x 2.5 slower)
     - **total** 2210 ms (x 2.5 slower)
