### ISSUE TITLE
TransformControl in iTowns. 

### ISSUE THREAD

**Issue by JulienF89** [iTowns/itowns#737]
## Your Environment

* Version used: iTowns 2.0
* Browser Name and version: Google Chrome Version 65.0.3325.181 (Build officiel) (64 bits)
* Operating System and version (desktop or mobile): Windows 10 64 bits / Windows 7 64 bits
* Link to your project: ENSG Project

## Context
We are in Development Project for IGNfab, and our leader is Victor COINDET. So we want to know if it's possible to include transformcontrol (three JS) to a mesh wich is in iTowns.

**Comment by zarov** [comment]
Hi

Are you talking about [this class](https://github.com/mrdoob/three.js/blob/dev/examples/js/controls/TransformControls.js) ?

It is indeed possible to use this control I think, even as it is now. All you need is to follow [the example in three.js](https://github.com/mrdoob/three.js/blob/master/examples/misc_controls_transform.html) and tweak what needs to be changed, to move the object in the world. 

However as this is really mesh specific and nothing to do with iTowns, I don't think it will be added in iTowns.

**Comment by JulienF89** [comment]
I already tried to do this, but it didn't work because we seen axis on the mesh, but we cannot select them..

**Comment by zarov** [comment]
Do you have a usecase to share ? I can take a quick look, but keep in mind that this has nothing to do with iTowns and I'll be closing this issue after having take a look at your sample.

**Comment by JulienF89** [comment]
Thank you for your answers, I'll keep trying by myself

**Comment by zarov** [comment]
No problem, good luck !

**Comment by Jeremy-Gaillard** [comment]
You may need to tell iTowns that the scene has changed each time the user interacts with the controller: iTowns doesn't redraw the scene at a regular rate like Three (usually) does, it does it only when some changes have occurred in the scene.
```js
view.notifyChange(true);
```
