### ISSUE TITLE
Elevation problems part 1

### ISSUE THREAD

**Issue by massea** [iTowns/itowns#74]
Sometimes, elevation data is not available (at a specific zoom level) or significantly different between tiles and cause discontinuities.

Example: La Reunion

![image](https://cloud.githubusercontent.com/assets/15635750/15243874/9c349a18-18fe-11e6-9855-13ef616cd7bf.png)

In this example, there is no elevation at zoom 11.

Example 2: With Isoline

![test_2](https://cloud.githubusercontent.com/assets/15635750/15244240/772feeaa-1900-11e6-8c31-caf8806f0161.jpg)

In this example (where i had the sea) we can see the difference in resolution. For normal elevation use, it's not a big problem but when you have isolines (here for the sea/land separation) it's a problem.
The sea part implementation will be in a separate issue (for good practices).

**Comment by gchoqueux** [comment]
I'll fix the problem when elevation data is not available

**Comment by gchoqueux** [comment]
@massea you have always the problem?

**Comment by gchoqueux** [comment]
fixed
