### ISSUE TITLE
camera not moving in positionGlobe example

### ISSUE THREAD

**Issue by mbredif** [iTowns/itowns#747]
The camera does not move when the click starts on a object3D that has been added directly to the scene.

## Steps to Reproduce
1. open http://www.itowns-project.org/itowns/examples/positionGlobe.html
2. click and drag on the ground : the camera moves
3. click and drag on the red cone : the camera does not move

## Expected Behavior
the camera should move in 3.

## Actual Behavior
the camera does not move in 3.

## Possible Cause
My guess is that picking is not working with objects directly added to the threejs scene.

## Possible Solutions : 
- provide a simple function that should be applied to object3ds when added directly to the scene. [this](https://github.com/mbredif/itowns-ros/blob/develop/src/ROSProvider.js#L43-L46) seems to do the trick, but I am not sure how generic it is.
- alternatively provide an "object3d" layer that warps an object3d and does whatever itowns needs to do with it (such as [patching shaders for logdepth](https://github.com/iTowns/itowns/blob/c091b0d9532a97fc62c567121983ceee433b26f7/src/Renderer/Shader/ShaderUtils.js#L7))
- warn the user of the effects of modifying directly the three.js scene  (where?)

in any case, this should be documented somewhere

**Comment by peppsac** [comment]
Here's another fix:
```diff
diff --git a/src/Core/Prefab/GlobeView.js b/src/Core/Prefab/GlobeView.js
index a19382da..9aff0ceb 100644
--- a/src/Core/Prefab/GlobeView.js
+++ b/src/Core/Prefab/GlobeView.js
@@ -366,7 +366,10 @@ GlobeView.prototype.selectNodeAt = function selectNodeAt(mouse) {
 GlobeView.prototype.readDepthBuffer = function readDepthBuffer(x, y, width, height) {
     const g = this.mainLoop.gfxEngine;
     const restore = this.wgs84TileLayer.level0Nodes.map(n => n.pushRenderState(RendererConstant.DEPTH));
-    const buffer = g.renderViewToBuffer(this, { x, y, width, height });
+    // only draw the objects of this layer
+    const buffer = g.renderViewToBuffer(
+        { camera: this.camera, scene: this.wgs84TileLayer.object3d },
+        { x, y, width, height });
     restore.forEach(r => r());
```

**Comment by mbredif** [comment]
Is it a hack or a general fix ? Is there any implications / side effects ?

**Comment by peppsac** [comment]
It's a fix to make sure we only render objects belonging to the globe layer (and the same fix should be implemented in `PlanarView`).
