### ISSUE TITLE
Error using setCenter in Globe API 

### ISSUE THREAD

**Issue by vpicavet** [iTowns/itowns#76]
Hello,

I have the following error when using the `setCenter` function of the Globe API : 

```
Uncaught TypeError: Cannot read property 'cartographicToCartesian' of undefined(…)
s.setCenter @ ApiGlobe.js:604
(anonymous function) @ VM1704:1
InjectedScript._evaluateOn @ (program):145
InjectedScript._evaluateAndWrap @ (program):137
InjectedScript.evaluate @ (program):118
```

Steps to reproduce : 
- clone itowns2
- `npm run build`
- `npm run start` or `python -m SimpleHTTPServer 8080`
- launch index.html
- run in console : `itowns.viewer.setCenter(2, 20, 0)`

**Comment by vcoindet** [comment]
The origin of the problem has been detected.
We are now working on a solution to fix it.

**Comment by gcebelieu** [comment]
maybe the use of itowns.viewer.setCenter() should be conditionned to a "globeLoaded" event reception.

**Comment by vcoindet** [comment]
The bug is fixed now. This is a first solution, maybe we can find some others.

We need to wait that the Globe is well loaded, so we added an Event (id :  'loaded') and then we call the function in the addEventListener in index.html as followed : 

_document.addEventListener('loaded',function(){ 
                    console.log("LOADED"); 
                    itowns.viewer.setCenter({lon:2,lat:20,alt:0});
                    } , 
  false);_

Note that you the correct sentence is _setCenter({lon:2,lat:20,alt:0})_  Otherwise it will not work...

**Comment by vpicavet** [comment]
@tbroyer any comment on this particular issue, which seem to be much more general than the specific setCenter problem ?

**Comment by peppsac** [comment]
I have 2 questions on the `setCenter` API function:
- why use shortened names (`lon`, `lat`, `alt`) whereas `getCenter` returns an object with full names (`longitude`, `latitude`, `altitude`)?
- the `alitude` parameter has no effect. Is this intended or is it a bug?

**Comment by vcoindet** [comment]
- That's a really good point. We are probably gonna choose only one formalism that will be : (longitude, latitude, altitude). I will work on this.
- The altitude parameter has no effect, it's intended, not a bug. It is intended that one can set a zoom level with the fonction setCenterAdvanced, but the zoom level function is not yet implemented.

**Comment by gchoqueux** [comment]
> run in console : itowns.viewer.setCenter(2, 20, 0)

use`itowns.viewer.setCenter({longitude:20,latitude:20})`
