### ISSUE TITLE
Is it possible to do photogrammetric measurements ?

### ISSUE THREAD

**Issue by antoinebio** [iTowns/itowns#762]
Hello,
provided that I have a full dataset of MMS photo + External Orientation as index for photos, is it possible for the user in ITOWNS to perform basic measurements such as 2d/3d distance, height, cross distance to a line, etc...
Does it manage stéréoscopic view, measurement ?

antoine.

**Comment by tbroyer** [comment]
Thank you for your interest in iTowns. Issues are used to track, well, issues, as well as tasks and requests for enhancements; they're not meant as a discussion forum. Please use the mailing list instead; see https://github.com/iTowns/itowns/blob/master/CONTRIBUTING.md#submitting-an-issue

**Comment by autra** [comment]
Hi @antoinebio. Indeed the mailing list is the good place to post such a question, but apparently you had problem with it. I can at least give some hints here. Panoramic photos can be displayed in iTowns (see http://www.itowns-project.org/itowns/examples/panorama.html for instance). Of course, this probably means you'll have some data preparation to do on your side, depending on their size (do you need to tile them or not?)... 

As for measurement: iTowns doesn't do photogrammetry by itself if this was your question, but can rely on data coming from a photogrammetry pipeline to achieve these features. Which software you use for photogrammetry is up to you :-)

**Comment by antoinebio** [comment]
I don't want to perform photogram process in Itowns, I am just asking if Itowns support stereo view or 3D measurements in immersive view.
examples/panorama.html shows only a VR support display, no measurement capability.
On contrary commercial video of ITowns shows 3D measurements user-feature in pts cloud .
Does that mean I need a pt cloud ? Does It work with photos only ? Do I need both geospatial data as input ?

**Comment by autra** [comment]
@antoinebio iTowns knows how to do 3D measurement, but of course, your data needs to be 3D, so pointclouds or mesh for instance. Panoramas are not really 3D.

**Comment by antoinebio** [comment]
It is ... as long as intrinsic+extrinsic camera parameters are given. This how  photogrammetry is based on = Reproducing the human Vision, and humans see in 3d ;)
As itowns has been initially developed by IGN maybe you could ask about that capability ?
If itowns handle geospatial data it must be possible to perform measuments on photos... isn't it ?
Lidar only ?
Photo + lidar ?
Should M.Bredif comment our request ?
We just need the requirements for data format.

Antoine Billault

**Comment by autra** [comment]
> It is ... as long as intrinsic+extrinsic camera parameters are given. 

No, it is not. You need some kind of reconstruction there. You said it yourself:

> This how photogrammetry is based on = Reproducing the human Vision, and humans see in 3d ;)

Yes, thus its very existence. You need such a process to reproduce the 3D. If things were that simple, photogrammetry would simply not exist :-)

iTowns doesn't perform photogrammetry (it's not planned for the foreseeable future AFAIK). So iTowns cannot reconstruct the 3D information lost in a picture by itself. iTowns simply draw a sphere and project your picture on it. You can make measurement on a sphere, but it won't yield what you expect.

Your data needs to be pure 3D, not something-that-can-eventually-be-made-3D-again. So you need either a pointcloud, or a mesh (or maybe a depth map, with some additional development). No magic wand here unfortunately.

> We just need the requirements for data format.

I hope these requirements are clearer now :-)

**Comment by nosy-b** [comment]
@antoinebio 
Yes it is possible to do 3D measurement using images (at least two with intrinsic+extrinsic params) using ray pseudo intersections and it was implemented some time ago in the old itowns but it is not in the new version and not in the roadmap for now as mentioned @autra .
But we could discuss that as it is not especially complicated to implement :)

**Comment by autra** [comment]
@nosy-b that's interesting, do you have a link to the old itowns branch that does this?

**Comment by nosy-b** [comment]
You can find some code here:
https://github.com/nosy-b/misc/blob/master/Photogrammetry.js#L110
And a video demo here:
@36sec https://vimeo.com/57531815#t=36s
