### ISSUE TITLE
Improving the Feature type

### ISSUE THREAD

**Issue by mbredif** [iTowns/itowns#763]
The pivot [Feature type](https://github.com/iTowns/itowns/blob/master/src/Parser/GeoJsonParser.js#L233-L268), parsed by the GeoJSON parser will not scale well, with positions as an array of [Coordinates](https://github.com/iTowns/itowns/blob/master/src/Core/Geographic/Coordinates.js) objects. For instance, using that type as a pivot for binary pointclouds would mean deserializing typedarrays into Coordinates objects, just to immediately reserialize it into the typedarray of a BufferAttribute.

This issue is to propose and discuss what would be a better fit.

my proposal is to change the property `{Coordinates[]} vertices` to a `{THREE.BufferGeometry} geometry` with a mandatory 'position' attribute (which could be a [BufferAttribute](https://threejs.org/docs/#api/core/BufferAttribute) or a [InterleavedBufferAttribute](https://threejs.org/docs/#api/core/InterleavedBufferAttribute) and have an `crs` property).

**Comment by autra** [comment]
> The pivot Feature type, parsed by the GeoJSON parser will not scale well

Yep indeed :-) We cannot keep a `Coordinates[]`. It's slow to create and slow to use.

The downside of a `BufferGeometry` is that you'll loose the SIG side of Coordinates. I don't know if we care about this for the Feature type though. Thoughts?

An alternative (if we do care about it) would be to support array (or Float32/64Array) of x,y,z triplets in `Coordinates`.

**Comment by peppsac** [comment]
> my proposal is to change the property {Coordinates[]} vertices to a {THREE.BufferGeometry} geometry with a mandatory 'position' attribute (which could be a BufferAttribute or a InterleavedBufferAttribute and have an crs property).

Seems reasonnable, but I have 2 issues with this proposal:
- the `crs` issue raised by @autra in the previous comment
- the geometry -> `BufferGeometry` is "lossy". For instance:
  * linestring will be converted to polygons (if we use meshline, which is needed to support `linewidth` on windows platform)
  * polygons (and their holes) will converted to triangles

Basically this prevents implementing any transformations on the source data (remove a hole from a polygon, or add points to a line). It may not be a big deal though...

**Comment by mbredif** [comment]
> An alternative (if we do care about it) would be to support array (or Float32/64Array) of x,y,z triplets in Coordinates.

yes but soon, we will want to support other dimensions like color and classification and will want to add these dimensions to Feature as well. BufferGeometry already supports multiple attributes (and may for instance enable a very efficient parsing of a binary ply with multiple dimensions by just configuring some interleaved buffer attributes against the arraybuffer of the file content)

**Comment by autra** [comment]
> we will want to support other dimensions like color and classification and will want to add these dimensions to Feature as well

These could go in other properties.

> BufferGeometry already supports multiple attributes 

Imho it's already too specific to a particular way of translating a Feature into a THREE.js object. The way I see it, Feature is "rendering-agnostic". As you said that might be a chimera, but it's worth trying at least.

> and may for instance enable a very efficient parsing...

Yes, but that's something interleaved buffer gives you, not BufferGeometry per se.

**Comment by mbredif** [comment]
> - linestring will be converted to polygons (if we use meshline, which is needed to support linewidth on windows platform)
> - polygons (and their holes) will converted to triangles

These conversions are already part of the stylization, the Feature type is upstream and should not know about anything about that. For instance the same Feature could be stylized into 3 object3D (a Mesh of its polygons with holes, a MeshLine of its contours and a MeshLine of its holes) and 1 texture (by rasterization).

**Comment by peppsac** [comment]
> These conversions are already part of the stylization, the Feature type is upstream and should not know about anything about that.

Ok my bad, I believed you wanted to produce a ready to display `BufferGeometry`.
If you're only using `BufferGeometry` as a container of `BufferAttributes`, then why not simply have a container of `BufferAttributes`?

**Comment by zarov** [comment]
> If you're only using BufferGeometry as a container of BufferAttributes, then why not simply have a container of BufferAttributes?

In that case, I would even only store a `TypedArray`.

> An alternative (if we do care about it) would be to support array (or Float32/64Array) of x,y,z triplets in Coordinates.

Good idea !

I'm a big advocate for the removal of those big arrays of `Coordinates` in `Feature`, so I'm behind every idea here.

**Comment by mbredif** [comment]
I agree that BufferGeometry might be confusing. Since my proposition was mostly using it as an Attribute container, let's try something without it.

Using `TypedArray`s only, we would miss `itemSize` and `normalized` (and `offset` and `stride` for interleaved versions) and all convenience access functions : 
```
BufferAttribute( array : TypedArray, itemSize : Integer, normalized : Boolean )
InterleavedBufferAttribute( interleavedBuffer : InterleavedBuffer, itemSize : Integer,
  offset : Integer, normalized : Boolean )
InterleavedBuffer( array : TypedArray, stride : Integer )
```

So I propose to use a type like, that host all the parameters to create the THREE attributes and some GIS knowledge to automatize reprojection (crs, type) : 
```
FeatureAttribute = {
  name : String,
  buffer : { array : TypedArray, stride : Integer = 0 },
  itemSize : Integer,
  normalized : Boolean,
  offset : Integer = 0,
  crs : string = undefined
  type : "position", "direction", "normal" or undefined
}
```
`stride` and `offset` would default to 0 for non-interleaved attributes
`type` could help to do the proper crs reprojection and to give some semantics (undefined requires no transformation)

and then (inspired by [@zarov](https://github.com/iTowns/itowns/pull/756#issuecomment-391388005)) : 
```
// continuous range or enumerated list
FeatureIndices = { start : Number, count : Number } | Number[] 

FeatureGeometry = {
  // length is 1 for all types but polygon (where subsequent indices describe holes)
  indices : FeatureIndices[], 
  extent: Extent, // not sure
  properties: Object // all metadata, non normative (feature properties in 3Dtiles terms)
}

Feature = {
  type: "point", "polygon", "linestring", "lineloop"?, "mesh"?
  geometries : FeatureGeometry[],
  extent: Extent,
  properties: Object // all metadata, non normative (batch properties in 3Dtiles terms)
}

FeatureCollection = {
  attributes:  FeatureAttribute[],
  features : Feature[],
  extent: Extent,
  properties: Object // all metadata, non normative (global properties in 3Dtiles terms)
}
```

some notes :
- the main point is to have the attributes as a data store in the FeatureCollection and only have topology/indices and metadata in features.
- This proposition is influenced by webgl, but does not depend on THREE
- The goal is to have a compact type which could host as many input types as possible and be as efficient as possible to go from file formats (hopefully geojson, gpx, pnts, b3dm, potree, laz/las, ply, mvt...), and to a THREE.js displayable (mostly object3d or texture)
- I am not sure about the 3 levels of properties,

**Comment by peppsac** [comment]
What is `FeatureAttribute` in your proposal?

Regarding this part:
```
  buffer : { array : TypedArray, stride : Integer = 0 },
  itemSize : Integer,
  normalized : Boolean,
```
I'd be tempted to reuse `BufferAttribute` and `InterleavedBufferAttribute` from three: they already exist and are properly documented (even if they do a bit more that what we need)

Regarding:
```
crs : string = undefined
```
While I understand the choice, I'm a bit worried: in `Coordinates` I chose to hide the coords array to force the use of a GIS oriented API (x/y, latitude/longitude, as). Here the coords and the CRS are different properties and it might cause some issues (eg: reading directly `buffer.array` because in the test case of the developer the `crs` match the one of the `View`).
Also having an `undefined` crs property for color, normals or other properties bothers me a bit.

Maybe we could adapt `Coordinates` API to accept a `BufferAttributes` or/and a `InstancedBufferAttribute`. Or create a `CoordinatesAttributes`...

**Comment by mbredif** [comment]
> What is FeatureAttribute in your proposal?

That is the type you are commenting and that holds the creation parameters of a `BufferAttribute` or a `InterleavedBufferAttribute` and the `crs/type`. We can use them directly if we are OK with using THREE classes here. No strong opinion here.

> Also having an `undefined` crs property for color, normals or other properties bothers me a bit.

- for normals, you would actually benefit from specifying the crs, to enable normal reprojection (using the inverse transpose in case of an affine transform for instance)
- for colors and other non-spatial properties, crs does not make sense (reprojections are no-ops), so I do not see the point of declaring this property in that case.

> Or create a CoordinatesAttributes...

I think my FeatureAttributes is a generalization (from positions only to position/normal/direction/quaternion...) of what you have in mind with CoordinatesAttributes : it encapsulates a typedarray of values and a crs, on which we could add reprojection/GIS api : get a point/normal/direction/quaternion in a given crs or transform the whole attribute (in place or as a new FeatureAttribute).


> reading directly buffer.array because in the test case of the developer the crs match the one of the View).

that is exactly the path I do not want to prevent. For instance, if a point cloud is provided in an uncompressed form in the view crs, I would like no decoding whatsoever : just create the (Interleaved)BufferAttribute from the file buffer and pass it to the shader. If the crs does not match, then I would reproject all FeatureAttributes to the view crs with a reprojection suitable for the attribute type (position/quaternion/normal/noop...).

**Comment by peppsac** [comment]
> I think my FeatureAttributes is a generalization

I know. But generalization can also be a bad idea when it doesn't make sense (and having a `undefined` field may be a hint of this).

> that is exactly the path I do not want to prevent.

I know what you're trying to achieve (and we already discussed it before).
I don't want to prevent this fastpath, I want to prevent building something overly generic and complex that in the end only work in one case.

So IMHO, having a GIS-oriented API is important (and can be a no-op when the input and output crs match).

Anyway... discussing in an issue is nice, but I'd prefer to review (and test) an implementation.

**Comment by mbredif** [comment]
> Anyway... discussing in an issue is nice, but I'd prefer to review (and test) an implementation.

Same thing here :)
This discussion was to brainstorm ideas (and surely propose mine ;) ), so that whoever has the time to prototype it starts on some kind of agreement.

**Comment by peppsac** [comment]
FYI I implemented a "store multiple coordinates in a single Coordinates" object to see how it could work.
The code is in [this branch](https://github.com/peppsac/itowns2/tree/feat_multi_coords) (last commit).

It would allow to drop the `crs : string = undefined` from `FeatureAttribute`: we could instead store a `Coordinates` object in the `buffer` property.

**Comment by gchoqueux** [comment]
In itowns 2.6.1, `feature.vertices` is one float array, which improves performance. We don't use typed Arrays because their size is defined at instantiation.

**Comment by zarov** [comment]
This pivot format is now improved greatly, I'm closing this issue, unless you still have suggestions.
