### ISSUE TITLE
Controls do not work well when the viewer div is offseted or scaled

### ISSUE THREAD

**Issue by Jeremy-Gaillard** [iTowns/itowns#765]
## Context
iTowns doesn't take into account the viewer div offset and/or scale when processing picking events. PlanarControls is affected by scale and offset, while GlobeControls is only affected by scale.

## Steps to Reproduce (for bugs)
Replace
```html
<div id="viewerDiv"></div>
```
by
```html
<div style="height:30vh"></div>
<div id="viewerDiv" style="width:50%;height:60vh;zoom:0.5"></div>
```
in any example and try to move the camera.

## Possible Cause/Fix/Solution
I started working on some [fixes](https://github.com/Jeremy-Gaillard/itowns2/tree/fix_controls), but I still have trouble getting the scale of the viewer div (I set it manually in my code at the moment). I also think I went in a wrong direction, since my method requires to modify PlanarView.getPickingPositionFromDepth, but the globe method doesn't require it be modified to work.

**Comment by zarov** [comment]
This is an old issue, but I took a look at it:
- for the `zoom` CSS property, this is non standard and a property impossible (from what I tried) to get except reading the CSS directly, so I would recommend to not use it with iTowns, as I don't see how it could be fixed
- for the offset, I tried different values and `div` positioning, but didn't encounter any problem (in Chrome at least), do you still have a usecase (without `zoom`) that can be tested ?
