### ISSUE TITLE
Z-translation of pointclouds broken

### ISSUE THREAD

**Issue by autra** [iTowns/itowns#771]
When changing the z translation of pointclouds, iTowns doesn't load enough of the quadtree.

**steps**
- go to http://www.itowns-project.org/itowns/examples/pointcloud.html
- change z to 50 with the debug tools
- move back to be in front of the church door
- observe the pointclouds

**expected**
the church front is loaded correctly, the same way it is when z = 0 and the camera faces it.

**actual**

 less points are loaded when z is 50, see screenshots.

left: z=0                                      right: z=50
<img alt="expected" src="https://user-images.githubusercontent.com/1576598/40828732-c486d8ec-6581-11e8-9f5c-94f76f40d94e.png" width="50%"><img alt="actual" src="https://user-images.githubusercontent.com/1576598/40828736-c66039ce-6581-11e8-9d95-2475c897e879.png" width="50%">

## Possible Cause/Fix/Solution

To be checked:
- if bounding boxes are updated
- if `updateMatrixWorld` is called
- ...

**Comment by gchoqueux** [comment]
fixed
