### ISSUE TITLE
DROM COM data

### ISSUE THREAD

**Issue by massea** [iTowns/itowns#78]
I have a problem for DROM COM visualisation, for example, la Martinique :

![image](https://cloud.githubusercontent.com/assets/15635750/15774072/bcb85be4-297a-11e6-9fea-6a0736447b9e.png)

It woks on geoportail, is it a data access problem ?

![image](https://cloud.githubusercontent.com/assets/15635750/15774223/87d9fbc0-297b-11e6-8118-e09da1337adf.png)

**Comment by massea** [comment]
No problem on older version (branch TestStatisticDataRepresentation)

![image](https://cloud.githubusercontent.com/assets/15635750/15774495/ec3533c2-297c-11e6-82f4-87a063077a3a.png)

**Comment by gchoqueux** [comment]
If you comment addImageryLayer ORTHOIMAGERY.ORTHOPHOTOS.CRS84 and GEOGRAPHICALGRIDSYSTEMS.MAPS.SCAN-EXPRESS.STANDARD index.html. It 's a bug with multi-layers

**Comment by peppsac** [comment]
@gchoqueux : did you start to work on this issue?
I have some WIP code that fixes it and I can submit a PR later this week if you're interested.

**Comment by gchoqueux** [comment]
Yes, I work on this issue

**Comment by gchoqueux** [comment]
fixed
