### ISSUE TITLE
3dtilesProcessing: distance computation seems wrong when using boundingVolume.region

### ISSUE THREAD

**Issue by peppsac** [iTowns/itowns#796]
A region in 3dtiles defines a portion of the globe. See the [boundingVolume schema](https://github.com/AnalyticalGraphicsInc/3d-tiles/blob/master/schema/boundingVolume.schema.json#L19).

If we declare a region with min/max height = 0, and we move the camera above the center of this region at altitude X, then the distance from the camera to the region should be X.

Currently the returned values don't match the expectation.

See the ignored tests added by PR https://github.com/iTowns/itowns/pull/788

**Comment by gchoqueux** [comment]
[finaly fixed](https://github.com/iTowns/itowns/pull/788#discussion_r199532905) in #788
