### ISSUE TITLE
3dtiles cache clean memory failed.

### ISSUE THREAD

**Issue by Oncledjoe** [iTowns/itowns#797]
The 3dtiles cache is never clean, see picture. This test  textured cache has a size of 264.7 Mo and we can see the memory overhead and freeze my computer. This problem is also true without textured cache but the size is very lower so the problem doesn't occur.  
## Your Environment

* Version used: master
* Browser Name and version: Chrome last version
* Operating System and version (desktop or mobile): desktop ubuntu 16.4
* Link to your project: Nop

## Context
I need to visualize 3dtiles cache. 

## Steps to Reproduce (for bugs)
You need a textured  cache. A simple cache works also but doesn't crash you computer

## Expected Behavior
Clean memory and video memory. 

## Actual Behavior
Overflow memory

## Possible Cause/Fix/Solution
3dTilesProcessing.js the cleanup function : cleanup3dTileset doesn't work at all! Think to clean webgl memory too. 

Looking forward.

Best Regards,
![issue](https://user-images.githubusercontent.com/36001626/42095912-405ae880-7bb4-11e8-8f76-448f78e45647.png)

Oncledjoe

**Comment by zarov** [comment]
The problem may be coming from here https://github.com/iTowns/itowns/blob/master/src/Process/3dTilesProcessing.js#L204

Maybe we could change it to use the recently added `Cache` ?

**Comment by autra** [comment]
AFAIK this is orthogonal to a cache system: this just cleans tiles not used any more, but don't do it every frame to impact the user less (only 2% of frame, so roughly every 1,5-5 sec depending on the framerate I guess?).

It's very possible this bug comes from this part though :-)

**Comment by jailln** [comment]
Fixed in #1988
