### ISSUE TITLE
Error using "Crtl + left click" when using the Globe API in JSFiddle

### ISSUE THREAD

**Issue by vcoindet** [iTowns/itowns#81]
When we're loading the Globe API in JSFiddle, the "crtl+left click" control is not working.
It's only working after clicking on the controls panel.

Ex : http://jsfiddle.net/iTownsIGN/pxv1Lw16/

**Comment by zarov** [comment]
I don't see the problem anymore, maybe it was something coming from jsFIddle.

**Comment by gchoqueux** [comment]
it doesn't work on http://www.itowns-project.org/itowns/docs/#home

**Comment by zarov** [comment]
Well seen. But I think it is more of a JsFiddle issue than an iTowns one, as it may something to do with iframe focusing ?
