### ISSUE TITLE
Tiles are not displayed

### ISSUE THREAD

**Issue by gchoqueux** [iTowns/itowns#82]
Tiles are not displayed.
Possible reasons are : 
- wrong bouding box
- wrong frustrum
- the tile was destroyed

![capture du 2016-06-09 14-51-15](https://cloud.githubusercontent.com/assets/11291849/15930203/da57118c-2e51-11e6-959b-bc6771e59f18.png)

**Comment by peppsac** [comment]
Any STR (Steps To Reproduce) to share? Or is it occuring randomly?

**Comment by peppsac** [comment]
I can reproduce similar bugs (tile not displayed), but mostly with tiles on the edge of the screen.
![missing_tile](https://cloud.githubusercontent.com/assets/2198295/16051075/80c9367a-325e-11e6-83b7-23211db6b186.gif)
I believe this one is a culling problem (on the parent tile).

I'm not sure it's the same problem your reported though.

**Comment by gchoqueux** [comment]
In your case, indeed, it is a problem of culling cause by wrong bounding box.
![missing_tile](https://cloud.githubusercontent.com/assets/2198295/16051075/80c9367a-325e-11e6-83b7-23211db6b186.gif)

But in this image, I'm not sure whether caused by bounding box
![capture du 2016-06-09 14-51-15](https://cloud.githubusercontent.com/assets/11291849/15930203/da57118c-2e51-11e6-959b-bc6771e59f18.png)

**Comment by gchoqueux** [comment]
There is a problem :
![itowns trou 2](https://cloud.githubusercontent.com/assets/11291849/16267741/a344072e-388b-11e6-8902-d324bd65e8ea.png)
![itowns trou](https://cloud.githubusercontent.com/assets/11291849/16267750/aafa851a-388b-11e6-9259-5b9b7a5d2108.png)
![trou2](https://cloud.githubusercontent.com/assets/11291849/16267751/aff84ee4-388b-11e6-96d3-2e3dd7a72746.png)
