### ISSUE TITLE
Upgrade to THREE 95

### ISSUE THREAD

**Issue by zarov** [iTowns/itowns#822]
THREE.js v94 has been out for a month, and fixes some problems we have like in #774.

We still rely on v89 which is a 8 months old, and from my experience THREE.js is a stable enough project to allow us to upgrade to v94 almost safely.

If someone wants to do that, please assign yourself here, otherwise I'll do it but not at least until a month.

**Comment by mbredif** [comment]
v96 is out :)

**Comment by zarov** [comment]
Updated to v97 in #824
