### ISSUE TITLE
Check-node-version doesn't run for Windows

### ISSUE THREAD

**Issue by Mkonini** [iTowns/itowns#868]
Working environment Windows 7
Node.js version 10.11.0
During npm install you get the following:
"prepare": "check-node-version --npm '>= 6' || echo \"We detected that you are using npm < 6, please use npm >= 6 if you want to make modification to package-lock.json, feel free to ignore the above error if not.\n\""
 The installation process is stopped.
 
## Steps to Reproduce (for bugs)
Do a npm install in Windows environment. 

## Possible Cause/Fix/Solution
Indication: package added in #816

**Comment by zarov** [comment]
I know the original intent of adding this package, but I feel that it don't serve any purpose, as when you are running `npm install` you still get the message not really printed as a test, but as the execution of the test, like so:
```

> itowns@2.3.0 prepare /home/aberthet/Workspace/itowns
> check-node-version --npm '>= 6' || echo "We detected that you are using npm < 6, please use npm >= 6 if you want to make modification to package-lock.json, feel free to ignore the above error if not.
"

audited 8330 packages in 5.417s
found 0 vulnerabilities
```

So I'm in favor of removing this check.
