### ISSUE TITLE
Incorrect bounding box (OBB) size

### ISSUE THREAD

**Issue by peppsac** [iTowns/itowns#87]
Steps to reproduce:
- enable OBB display
- zoom on a moutain area

Result :
- for some tiles the bottom of the bounding box will be higher that the lowest point of the tile. 

Examples (see red squares):
![obb_size_bug](https://cloud.githubusercontent.com/assets/2198295/16108222/38bdd134-33a2-11e6-9e4d-cfe47974cec9.png)
- cause visibility issue because the culling code uses this OBB to determine visibility of a tile

Expected:
- the OBB should encompass the whole tile

**Comment by gchoqueux** [comment]
Yes, the computing of bounding box is sampled in DEM texture. The function used is `TileMesh.prototype.parseBufferElevation = function(image,minMax,pitScale)`. 
The errors are small, this does not justify all the problems of culling.

**Comment by peppsac** [comment]
Small or not, it will cause holes anyway (see https://github.com/iTowns/itowns2/issues/82#issuecomment-225939592 for an example).

Before filling this bug I tried various changes in the parseBufferElevation (including setting `inc` to 1) and it didn't make the problem go away.

Maybe it's an issue in the OBB construction? Alas the code in `BuilderEllipsoidTile.prototype.OBB` and `THREE.OBB.prototype.addHeight` isn't easy to grasp and lacks comments to document the maths being used.
Do you think you could take some time to document what is being done in these functions (and remove the `// TODO à vérifier --->`)?

**Comment by peppsac** [comment]
I pushed a branch to add a unit test to identify issues related to OBB computation: https://github.com/iTowns/itowns/tree/test_geometry_obb

I'd like to merge it, but currently my test fails so either:
- my test is broken
- OBB computation is wrong sometimes

(ping @gchoqueux since you wrote the OBB code)

**Comment by gchoqueux** [comment]
I'll look at it
