### ISSUE TITLE
Proposition for locking a final design in itowns

### ISSUE THREAD

**Issue by zarov** [iTowns/itowns#880]
We are currently (a lot offline) experiencing some disagreements on the design of iTowns and its modularity. So in order to share it with everyone, here's my shot at a proposition of where I see the design going, in hope to see it locked and stop refactoring it.

### TL;DR

- stop to rely on big configuration objects for initialization
- define a specified scope for the available API
- allow for a user to easily add a custom source, parser, etc...
- specify an internal format for handling data (the famous Feature)

### Final Example

Here's a complete example (of a globe view with a simple ortho layer, and a wfs one) illustrating my proposition:

```js
// Specify the position, with a real coordinate
var position = new itowns.Coordinate('WGS84', 2.35, 48.8, 25e6);

var viewerDiv = document.getElementById('viewerDiv');

// Create a view
var view = new itowns.GlobeView(viewerDiv, position);

// Specify the ortho source
var orthoSource = new itowns.WMTSSource({
    url: 'http://wxs.ign.fr/<key>/geoportail/wmts',
    format: 'image/jpeg',
    attribution : {
        name: 'IGN',
        url: 'http://www.ign.fr/'
    },
    name: 'ORTHOIMAGERY.ORTHOPHOTOS',
    tileMatrixSet: 'PM',
    tileMatrixSetLimits: {
        '2': { minTileRow: 0, maxTileRow: 4, minTileCol: 0, maxTileCol: 4 },
        '3': { minTileRow: 0, maxTileRow: 8, minTileCol: 0, maxTileCol: 8 },
        '4': { minTileRow: 0, maxTileRow: 16, minTileCol: 0, maxTileCol: 16 },
        '5': { minTileRow: 0, maxTileRow: 32, minTileCol: 0, maxTileCol: 32 },
        '6': { minTileRow: 1, maxTileRow: 64, minTileCol: 0, maxTileCol: 64 },
        '7': { minTileRow: 3, maxTileRow: 128, minTileCol: 0, maxTileCol: 128 },
        '8': { minTileRow: 7, maxTileRow: 256, minTileCol: 0, maxTileCol: 256 },
        '9': { minTileRow: 15, maxTileRow: 512, minTileCol: 0, maxTileCol: 512 },
        '10': { minTileRow: 31, maxTileRow: 1024, minTileCol: 0, maxTileCol: 1024 },
        '11': { minTileRow: 62, maxTileRow: 2048, minTileCol: 0, maxTileCol: 2048 },
        '12': { minTileRow: 125, maxTileRow: 4096, minTileCol: 0, maxTileCol: 4096 },
        '13': { minTileRow: 2739, maxTileRow: 4628, minTileCol: 41, maxTileCol: 7917 },
        '14': { minTileRow: 5478, maxTileRow: 9256, minTileCol: 82, maxTileCol: 15835 },
        '15': { minTileRow: 10956, maxTileRow: 18513, minTileCol: 165, maxTileCol: 31670 },
        '16': { minTileRow: 21912, maxTileRow: 37026, minTileCol: 330, maxTileCol: 63341 },
        '17': { minTileRow: 43825, maxTileRow: 74052, minTileCol: 660, maxTileCol: 126683 },
        '18': { minTileRow: 87651, maxTileRow: 148105, minTileCol: 1320, maxTileCol: 253366 },
        '19': { minTileRow: 175302, maxTileRow: 294060, minTileCol: 170159, maxTileCol: 343473 },
        '20': { minTileRow: 376733, maxTileRow: 384679, minTileCol: 530773, maxTileCol: 540914 }
    }
});

// Create an ortho layer associated to the source
var orthoLayer = new itowns.ColorLayer('Ortho', { source: orthoSource });

// Specify a WFS source for the buildings in 3D
var buildingsSource = new itowns.WFSSource({
    url: 'http://wxs.ign.fr/<key>/geoportail/wfs?',
    version: '2.0.0',
    typeName: 'BDTOPO_BDD_WLD_WGS84G:bati_remarquable,BDTOPO_BDD_WLD_WGS84G:bati_indifferencie,BDTOPO_BDD_WLD_WGS84G:bati_industriel',
    projection: 'EPSG:4326',
    ipr: 'IGN',
    format: 'application/json',
    zoom: { min: 5, max: 5 },
    extent: {
        west: 4.568,
        east: 5.18,
        south: 45.437,
        north: 46.03,
    },
});

// Create a geometry layer associated to the source
var buildingsLayer = new itowns.GeometryLayer('Buildings', {
    source: buildingsSource,
    parser: itowns.GeojsonParser,
});

// Add layers to the view
view.addLayer(orthoLayer);
view.addLayer(buildingsLayer);
```

### API
The API is currently kind of messy, I did a quick refactorization here: https://github.com/zarov/itowns/blob/f826b54ba61f8c5cbd6cf9d1354b5427e7959a39/src/Main.js
I removed some unused things, having no need to be made available (I may be wrong), but I also (and this is more important) added more things available in the API, allowing the user to do more things with iTowns, as described below.

### Configuration
One of the biggest unuseful part of iTowns that we could get rid of is all the checks we do on configuration strings. One way to remove this is by asking the configuration differently to the user of iTowns, especially in term of `layer` and `source`.

#### Layer
Instead of specifying the `type` of the layer, the user should instantiate the layer itself using `var layer = new <TYPE>Layer(...)`, and then add the layer as it is already the case, using `view.addLayer(layer)`. This way, not only iTowns doesn't have to support the fact to create a Layer if only the configuration is specified, but this also allows the user to use its own custom layer if it wants to.

#### Source
In the same idea, the `protocol` of a source, determining the type of source to use, should not be specified. Instead, the user uses `var source = new <PROTOCOL>Source(...)`, and then uses this source as an option when creating a layer. This way, we gain on the same points as for the layer above.

#### Parser
Still in the same vein, a parser should be able to be specified, to let the user more freedom and remove the map we are maintaining between formats and parsers.

#### Converter
This one should be specifiable as well, with default one being specified by the layer.

#### Fetcher
The last one thing I'm not really sure how to do it is the Fetcher, but I think we could go back to the initial idea of @mbredif and let the Fetcher be always set by the Parser used, or by default the Layer. This same way, we don't have to maintain a map between formats and fetchers.

### Customization
If we do as suggested above, we could allow more customization by a user. We could also easily add the support for advanced customization, like colorization of data like geojson or vector tile, by specifying stylizers or something like that.

### Feature specification
To ease the development for outside developers, the `Feature` specification needs to find a final stop and decision, as we have already discuss on it a lot of times. The last discussion I have in mind is in #763.

_______
This is the end of the proposition, I'm happy to discuss it before going further on this, even if we can already go in some directions without changing too much of iTowns.

**Comment by mbredif** [comment]
Thanks @zarov  for leading this action !

+1000 for class based rather than option based layers ! switches and ifs on option strings are scattered in many places in the core of itowns, which make it fragile and hard or impossible to extend !

(This comment on the bad usage of magic strings for types also applies to CRS strings, which IMHO should be moved to proj4-like objects)

### GlobeView
 ```
var view = new itowns.GlobeView(viewerDiv, position);
view.addLayer(orthoLayer);
view.addLayer(buildingsLayer);
```

What is a view exactly ? is it a scene as well ?
To go further, I think it could be improved by extracting from it some more atomic parts, at least : 
- the creation of the globe itself : I am in favor of explicitely creating the globe as a regular layer and explicitly applying RasterLayers to it (color, elevation...). It should not be the same api to apply an orthophoto or oriented images to a pointcloud, wfs meshes or the globe tile meshes.
- the creation of the camera (including its camera controls and the CRS of its world frame). I am not sure we need separate PlanarView and GlobeView. The difference in behavior could be based on the crs of the viewing camera only.

something like
 ```
var camera = new itowns.Camera('WGS84', position);
var view = new itowns.View(viewerDiv, camera);
var globeLayer = new itowns.GlobeLayer('WGS84');
view.addLayer(globeLayer);
view.addLayer(buildingsLayer);
globeLayer.addLayer(orthoLayer);
buildingsLayer.addLayer(orthoLayer);
```

###  Fetcher
I think the decoding type (arrayBuffer/text/xml...) should be provided by the format, but that we should be able to provide custom Fetcher objects (with the default being an http fetch). That would make it transparent to use the fetch or the file API (drag and drop, local storage, files submitted by a form...) to retrieve data. I have a small working example here https://github.com/mbredif/three-photogrammetric-camera/tree/master/src/sources

### Converter
Is a converter be a Layer that takes one or more Layers as input instead of a Source ?

### Feature specification
My comments in #763 still stand. The internal representation of a feature should be as close as possible to webgl with attributes as arraybuffers ready to be sent to the GPU.

**Comment by zarov** [comment]
> the creation of the globe itself : I am in favor of explicitely creating the globe as a regular layer and explicitly applying RasterLayers to it (color, elevation...). It should not be the same api to apply an orthophoto or oriented images to a pointcloud, wfs meshes or the globe tile meshes.

I agree, I would go one step further and have only a single `Globe` to instantiate, not even a `GlobeLayer`

> the creation of the camera (including its camera controls and the CRS of its world frame). I am not sure we need separate PlanarView and GlobeView. The difference in behavior could be based on the crs of the viewing camera only.

That would be wonderful yes !

> I think the decoding type (arrayBuffer/text/xml...) should be provided by the format, but that we should be able to provide custom Fetcher objects (with the default being an http fetch). That would make it transparent to use the fetch or the file API (drag and drop, local storage, files submitted by a form...) to retrieve data.

I'm not sure to understand it: what is the format here ? A string, an option of the source ? +1 for multiple type of fetchers

> Is a converter be a Layer that takes one or more Layers as input instead of a Source ?

By converters, I had in mind objects like `Feature2Mesh`, `Feature2Texture` or something else, taking a Feature in and returning something usable, like a texture or a geometry.

> My comments in #763 still stand. The internal representation of a feature should be as close as possible to webgl with attributes as arraybuffers ready to be sent to the GPU.

Yes, I think that with the recent #870 work @gchoqueux did, we are going closer to that.

**Comment by gliegard** [comment]
I think the
buildingSource.format: 'application/json',
should be part of the parser.

**Comment by mbredif** [comment]
> I'm not sure to understand it: what is the format here ? A string, an option of the source ? 

I meant the Parser : it should somehow provide the decoding format (txt, json, xml, binary...) that it supports. I do not know if the parser should be an option of the source or of the layer and whether it should always be explicitly given or if we would rather rely on a option string to infer it if not provided (in your proposal, that is "Source.format")

> By converters, I had in mind objects like Feature2Mesh, Feature2Texture or something else, taking a Feature in and returning something usable, like a texture or a geometry.

I thought Feature2Mesh and Feature2Texture were "simply" a MeshLayer and a RasterLayer  connected to a Feature source.

**Comment by zarov** [comment]
> I meant the Parser : it should somehow provide the decoding format (txt, json, xml, binary...) that it supports. I do not know if the parser should be an option of the source or of the layer and whether it should always be explicitly given or if we would rather rely on a option string to infer it if not provided (in your proposal, that is "Source.format")

We can assume default values of course, and also rely on something like `Parser.format || Source.format || Layer.format`.

> I thought Feature2Mesh and Feature2Texture were "simply" a MeshLayer and a RasterLayer connected to a Feature source.

No, it only converts data to a Mesh and add it to a GeometryLayer, or to a texture and add it to a ColorLayer.

**Comment by zarov** [comment]
iTowns is now mostly following this design, I'm closing this issue.
