### ISSUE TITLE
Proposition : creation of a layer from an object

### ISSUE THREAD

**Issue by hcaillau** [iTowns/itowns#892]
Instead of :

buildings.source = {
            	url: 'https://example.com/geosjon.json',
            	protocol: 'file',
            	projection: 'EPSG:4326',
            	format: 'application/json',
            	zoom: { min: 2, max: 2 }
            };

could be great to be able to do this :

buildings.source = {
            	source :  geojson,
            	protocol : 'object',
            	projection: 'EPSG:4326',
            	zoom: { min: 2, max: 2 }
            };

where geojson is an object.

**Comment by zarov** [comment]
Yes, thanks for the proposition: we should indeed be able to load data without fetching it, but by providing it directly. That's basically a new type of source to add, if you want you could do it, I don't see too much work on this.

**Comment by zarov** [comment]
If you need something to work right now, you can patch iTowns using this commit https://github.com/zarov/itowns/commit/2dd057a3d7ee9e9f4a06d977d15de5cc38cd424f

It is a quick hack, but I don't want to have something like this to do until I'm done with the quick reorganization explained in #880

**Comment by gchoqueux** [comment]
@zarov it's added in #1033 ?

**Comment by zarov** [comment]
Yes, and we don't even have a new protocol or whatsoever

**Comment by gchoqueux** [comment]
resolved with #1033
