### ISSUE TITLE
Deprecation of PanoramaView

### ISSUE THREAD

**Issue by zarov** [iTowns/itowns#901]
Since the discussion in #739, it seems that PanoramaLayer and all the StaticSource parts are kind of very specific to a closed format.

I would like to deprecate a few things, as I don't see a relevance to keep these in itowns. However, we could move them as a separate module from iTowns (like explained in #880):
- `src/Core/Prefab/PanoramaView.js`
- `src/Core/Prefab/Panorama/*.js`
- `src/Source/StaticSource.js`

WDYT ?

**Comment by nosy-b** [comment]
Good move!

**Comment by zarov** [comment]
Done in #948
