### ISSUE TITLE
Rename Coordinates to Coordinate

### ISSUE THREAD

**Issue by zarov** [iTowns/itowns#903]
It was crossing my mind that `Coordinates` should be `Coordinate` instead, it makes more sense as it contains only one coordinate. We could keep retrocompatibility for some versions, and remove it like in 2.9 or later.

WDYT ?

**Comment by gchoqueux** [comment]
it should be noted that `Coordinates` is an object that contains 3 coordinates.

**Comment by mbredif** [comment]
I agree with you two : Coordinates is not really good, but Coordinate is worse :)
I think it is not urgent and causes compability issues, but in the longer term, I would prefer something like itowns.Vector3 or itowns.Position (as it is conceptually just a three.Vector3 + a crs).

**Comment by zarov** [comment]
> it should be noted that Coordinates is an object that contains 3 coordinates.

Ok that's a good note, it makes sense.

Although as said @mbredif we could find a more suitable name, but that can be done some time in the future !

Thanks for the response
