### ISSUE TITLE
Bug while specifying nb of segments for Globe Tile Geometry

### ISSUE THREAD

**Issue by nosy-b** [iTowns/itowns#910]
## Context

Trying to specify a more refined geometry for the Tiled meshes composing the Globe (default is 16 *16 quads)

I did try to set  when creating the globeView:
`   var options = {segments:32};
            var view = new itowns.GlobeView(viewerDiv, positionOnGlobe, options);`

## Expected Behavior
Tilemesh geometry should be more detailed

## Actual Behavior
Options not taken to the layer

## Possible Cause/Fix/Solution

One possible working solution is to add this line in GlobeLayer.js constructor :
`        this.options.segments = this.segments;`

**Comment by zarov** [comment]
This is a problem with how we handle our `options` object. One fix would be to have [here](https://github.com/iTowns/itowns/blob/master/src/Core/Prefab/GlobeView.js#L99) is:
```js
const tileLayer = new GlobeLayer('globe', options.object3d, { options });
```

But this seems a dirty way of fixing this. A real fix would be to clean and harmonize how we take care of the `options` object in a lot of class (just follow the life of `options` in the `GlobeView` and you'll see what I'm talking about).

For now what you can do, without modifying iTowns, is: 
```js
var view = new itowns.GlobeView(viewerDiv, positionOnGlobe, { options });
```
