### ISSUE TITLE
New documentation layout proposal

### ISSUE THREAD

**Issue by zarov** [iTowns/itowns#911]
I have never been a big fan of the layout of the current iTowns documentation. 

So I have started working on a new one, as can be seen here https://zarov.github.io/itowns/docs/out/. It still looks like the THREE.js documentation (as seen here https://threejs.org/docs/), which I'm quite fond of. 

What I propose is this:
- a simple navigation, with (for now) two sections: general documentation like __Tutorials__, and the __API__
- the __API__ documentation is sorted not by classes/interfaces/modules as usual in jsdoc, but by packages, following a defined list (https://github.com/zarov/itowns/blob/gh-pages/docs/navigation.json)
- there will be a field to search the documentation, like in THREE.js
- a light colorscheme and visual, compared to the big one we currently have
- BONUS: automatically build a jsfiddle for each tutorial 

Once again, this is totally my point of view, so I would like to maybe get more inputs from others before going further. Thanks !

**Comment by Mkonini** [comment]
Good job!
Suggestion: I think it would be better to rename the first module of API documentation "socle" instead of "core" which encompasses the all

**Comment by zarov** [comment]
Yes, maybe `Base` instead: `Socle` is not very used as far as I know.

**Comment by gliegard** [comment]
Great doc !!

**Comment by gliegard** [comment]
Looking at the doc, for example  [Coordinate page](https://zarov.github.io/itowns/docs/out/#api/Geographic/Coordinates), I think it's too white : all the page is styled with white background.
- Example boxes should be like old doc color : dark blue background, or grey but not white
- Same remark for Method boxes, I prefer old doc color : blue background

**Comment by zarov** [comment]
Thanks @gliegard, I updated the general colors

**Comment by gliegard** [comment]
Nice ! And can you add something to separate two methods, like an horizontal line ?

**Comment by zarov** [comment]
Yes sorry missed that, I pushed it, it should be visible in a few minutes

**Comment by gliegard** [comment]
Also, I've seen a 404 error on [InfoLayer](https://zarov.github.io/itowns/docs/out/#api/Layer/InfoLayer) and [ColorLayersOrdering](https://zarov.github.io/itowns/docs/out/#api/Layer/ColorLayersOrdering)

**Comment by zarov** [comment]
I'm writing the missing documentation for them ! Thanks

**Comment by zarov** [comment]
I'm writing the missing documentation for them ! Thanks

**Comment by zarov** [comment]
I'm letting this issue opened for two months, if someone wants to talk about change on the layout.

**Comment by antoinebio** [comment]
@zarov your [link ](https://zarov.github.io/itowns/docs/out/)is broken

**Comment by zarov** [comment]
Yes sorry, the documentation is now available here http://www.itowns-project.org/itowns/docs/#home

I'm closing this issue now that two months passed.
