### ISSUE TITLE
Error loading b3dm build by FME 

### ISSUE THREAD

**Issue by gchoqueux** [iTowns/itowns#919]
Error loading/parsing b3dm build by FME

## Possible Cause/Fix/Solution
Error when BatchTable is parsing because start index buffer and length buffer are wrong.

**Comment by mgermerie** [comment]
The complete 3d-tiles support is planned in the short term road map. We are currently studying possibilities in terms of libraries to enhance support (as mentioned in https://github.com/iTowns/itowns/discussions/1917).

**Comment by jailln** [comment]
Done in #1834
