### ISSUE TITLE
wms provider

### ISSUE THREAD

**Issue by qdnguyen** [iTowns/itowns#92]
Through the code, I saw that all the providers are going through tileProvider that contains a single tileScheme / Projection, it is not generic? 

If we want to develop wms provider, we must pass through this module and even the wms data layer is not selected to show on globe, its provider is always intialized in this module.

Is there a solution to config this module dynamically according to data layer we need to show?

**Comment by qdnguyen** [comment]
wms provider now works well in wip_refacto_layer branch

**Comment by peppsac** [comment]
Reopening the issue until the code is merged in master.
