### ISSUE TITLE
 Does itowns support the simultaneous output of multiple cameras?

### ISSUE THREAD

**Issue by yoyomule** [iTowns/itowns#925]
Hi，  Does itowns support the simultaneous output of multiple cameras?

**Comment by gchoqueux** [comment]
Hi,
I don't say that there is full support for multiple cameras in **itowns**, but it is possible to create multiple viewers. It's possible to add the same layers to the viewers.

```js
// this code should work
const view1 = new itowns.GlobeView(viewerDiv1, positionOnGlobe);
const view2 = new itowns.GlobeView(viewerDiv2, positionOnGlobe);
const layer = new itowns.ColorLayer('Ortho', config);
view1.addLayer(layer);
view2.addLayer(layer);
```

See also examples:
* [Globe.html](http://www.itowns-project.org/itowns/examples/globe.html) with 2 `GlobeViewers`.
* [syncCameras.html](http://www.itowns-project.org/itowns/examples/syncCameras.html) with a  `GlobeViewer` and a `PlanarViewer` and cameras sync with `CameraUtils`.
