### ISSUE TITLE
Bug in planar vector example + eventual problem in tests ?

### ISSUE THREAD

**Issue by jailln** [iTowns/itowns#926]
## Your Environment
* Version used: Current master ( faaf2e3067e8d8cf0807d9a39c74017fd1989bf1 )
* Browser Name and version: Firefox 62.0.3 (same on Chromium 69.0.3497.81)
* Operating System and version (desktop or mobile): Ubuntu 18.04.1 LTS

## Context
In [planar vector example](https://github.com/iTowns/itowns/blob/master/examples/planar_vector.html), the WMS and the vector data are not loaded, c.f. the following screenshot:

![image](https://user-images.githubusercontent.com/16967916/49080502-23f8b580-f244-11e8-9def-5eb499d39440.png)

Error in the console:
```
ReferenceError: colorLayer is not defined 
planar_vector.html:60:13
```

In addition, the test of this example passed in the last PR (see [here](https://travis-ci.com/iTowns/itowns/jobs/160870834)); hence, there might be a problem with this test ?

## Steps to Reproduce (for bugs)
1. Open the [planar vector example](https://github.com/iTowns/itowns/blob/master/examples/planar_vector.html) in your browser

## Expected Behavior
The WMS Layer and the vector data should be displayed.

## Actual Behavior
Only the planar geometry is displayed.

**Comment by zarov** [comment]
Thanks for noticing this, I fixed it in #927

**Comment by jailln** [comment]
Thanks for fixing the example.

What about the test that passed even if the example was broken ?

**Comment by zarov** [comment]
Tests are weird, sometimes they passed as they shouldn't, sometimes it is the otherway. And you don't always get the same result by running the example in standalone or through the example. The current `planar_vector` is not running in test mode, but is not emitting any error and is working in standalone mode. I'm taking a look in it to see what's wrong.

**Comment by jailln** [comment]
Great, thanks!

**Comment by zarov** [comment]
It seems that the problem relies on two things:
- verification process: in most case, we only verify that the added layers are ready. In the bug you reported, the layer was never added so there never was an error. We may want to check something else to make sure everything is running smoothly.
- execution time: in the current case, performing an operation before checking that layers are ready helps executing the test. I added a `console.log` right before it, and it worked ! This problem should be more difficult to solve, at the moment nothing comes in mind.

**Comment by jailln** [comment]
Regarding the verification process: I have no experience with puppeteer but maybe we could trap the console errors and assert that there are no errors in the tests (if possible). Regarding the execution time, I don't have any hints right now either.

Anyhow, we might need to open an issue on this subject ?

**Comment by zarov** [comment]
> Regarding the verification process: I have no experience with puppeteer but maybe we could trap the console errors and assert that there are no errors in the tests (if possible).

Yes good idea !

> Anyhow, we might need to open an issue on this subject ?

Yes, I let you do it
