### ISSUE TITLE
Call to the getRange function in a loop breaks the camera

### ISSUE THREAD

**Issue by elias75015** [iTowns/itowns#937]
## Environment

* Version used:
2.5, but on the master too

* Browser Name and version:
FF or Chrome last versions

* Operating System and version (desktop or mobile):
Ubuntu 14

## Steps to Reproduce
1. In your test, add this :         

```
var loopTest = function () {
            console.log(globe.getRange());
        };
        globe.listen(GlobeView.EVENTS.AFTER_RENDER, loopTest);
```
2.  Initialize the globe view with a zoom > 14 and a tilt > 45

## Expected Behavior
We should have the range logged after every rendering, with a correctly positioned camera.

## Actual Behavior
The camera breaks after few seconds, aiming the sky. It ends with a white window/globe.

## Possible Cause
The getRange() function is clearly the problem.

**Comment by elias75015** [comment]
Hello team, and happy new year. Is there any news about this bug ?

**Comment by zarov** [comment]
Hello @elias75015 and happy new year ! Could you rewrite a correct example to reproduce ? I'm lost in what is `globe` and `globe.listen`, because AFAIK, there isn't such a method.

**Comment by elias75015** [comment]
Indeed, the sample I gave is wrong, it's a mix with code from our Geoportal API... Anyway, I can't reproduce the problem on a 100% iTowns sample, I'm closing that issue for the moment. 
Sorry for the inconvenience.
