### ISSUE TITLE
lookAtCoordinate function with tilt and without animation do not aim the good position

### ISSUE THREAD

**Issue by elias75015** [iTowns/itowns#938]
May be related to #83 and #486 

## Environment

* Version used: 

2.5, last master version too

* Browser Name and version:
FF or Chrome

* Operating System and version (desktop or mobile):

Ubuntu 14

## Steps to Reproduce (for bugs)

1. Use the lookAtCoordinate function with tilt and zoom parameters on a known position, but without animation : 

```
lookAtCoordinate({
    zoom : 15,
    tilt : 45,
    center : new Coordinate(...)
    }, false);
```

## Expected Behavior

The camera is correctly positioned

## Actual Behavior

There is a gap with the expected position

## Possible Cause

With the animation, the problem does not appear...

**Comment by gchoqueux** [comment]
@elias75015 I can't reproduce this bug. Could you give complete example with the bug?

**Comment by gchoqueux** [comment]
fixed
