### ISSUE TITLE
Enable multiple sub-domains/domains template for ULRBuilder

### ISSUE THREAD

**Issue by SesticM** [iTowns/itowns#942]
Currently it's possible to set following URL for e.g. OpenStreetMap layer source: `https://a.tile.openstreetmap.org/${z}/${x}/${y}.png`

It would be beneficial (in terms of speed and efficiency) if we could set alternating sub-domains/domains on URL based on specified rule, for example:
`https://${u:a|b|c}.tile.openstreetmap.org/${z}/${x}/${y}.png`

...or, for example:
`https://${u:xyz.org|yzx.org|zxy.org}/${z}/${x}/${y}.png`

**Comment by SesticM** [comment]
Enchancement related to enabling multiple sub-domains/domains template for ULRBuilder

**Comment by tbroyer** [comment]
With HTTP/2, you'd better use the same server to benefit from multiplexing over the same connection. Granted, for those few, older, browsers that don't support HTTP/2 (really not that much: https://caniuse.com/http2, tl;dr: IE11 on Win7, IE mobile, and UC Browser), "sharding" that way could be beneficial (particularly in this case as the setup of those OSM servers allows for HTTP/2 connection coalescing: names resolving to the same IP and covered by the same TLS certificate).

Are IE11 on Win7, IE mobile, and UC Browser the reason you ask for this feature? Or was there any other reason?

**Comment by SesticM** [comment]
Yes, exactly - IE11 on Win7 was a major reason for this request. It's a common corporate "suite" and will be hanging around for a long time...

**Comment by zarov** [comment]
> `https://${u:a|b|c}.tile.openstreetmap.org/${z}/${x}/${y}.png`

I'm not familiar with this format, what are the resulting urls ?

**Comment by SesticM** [comment]
It was just a staged example, no actual standards were taken into consideration (if any).

For example, resulting URLs based on following template:
`https://${u:a|b|c}.tile.openstreetmap.org/${z}/${x}/${y}.png`

...would produce following (continuously) alternating calls:
`https://a.tile.openstreetmap.org/${z}/${x}/${y}.png`
`https://b.tile.openstreetmap.org/${z}/${x}/${y}.png`
`https://c.tile.openstreetmap.org/${z}/${x}/${y}.png`

Or, for example, resulting URLs based on following template:
`https://${u:xyz.org|yzx.org}/${z}/${x}/${y}.png`

...would produce following (continuously) alternating calls:
`https://xyz.org/${z}/${x}/${y}.png`
`https://yzx.org/${z}/${x}/${y}.png`

**Comment by zarov** [comment]
Thanks, that seems simple to implement ! I added the tag `good first issue` if someone wants to implement it, otherwise I'll do it when I got time.

**Comment by zarov** [comment]
Implemented in #1189
