### ISSUE TITLE
Code redundancy ?

### ISSUE THREAD

**Issue by jailln** [iTowns/itowns#944]
It seems that [Camera.position()](https://github.com/iTowns/itowns/blob/master/src/Renderer/Camera.js#L54) has the same purpose as [GlobeControls.getCameraCoordinate()](https://github.com/iTowns/itowns/blob/master/src/Controls/GlobeControls.js#L1030).

**Comment by zarov** [comment]
Yes indeed, `getCameraCoordinate` can be replaced by a call to `Camera.position()`. However `GlobeControls` needs some change as `this.camera` is a reference to `Camera.camera3D` so it needs to be changed everywhere in `GlobeControls`.

**Comment by mgermerie** [comment]
`GlobeControls.getCameraCoordinates()` does no longer exist.
