### ISSUE TITLE
GETTING ERROR WHEN RUNNING THE PROJECT

### ISSUE THREAD

**Issue by augusttty** [iTowns/itowns#961]
## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by augusttty** [comment]
GETTEN ERROR WHEN RUN THE LATEST RELEASED PROJECT

cannot handle the  ThreeExtended/loaders/GLTFLoader  dependencies....

**Comment by augusttty** [comment]
Thanks for your attention,i run into some trouble with running the pro.
I just did the following steps:
1. npm install
2.npm start
and...
The 'ThreeExtended'  folder dependencies ,which refers to  GLTFLoaders and LegacyGLTFLoader , cannot be founded.and i downloaded three.js , make it refering to the files,still doesn't work .
and , i am confused of the threeExamples.js about patch files config...

**Comment by gchoqueux** [comment]
Hello, 

What's your Operating System and version?

Normally during installation, the folder  `ThreeExtended` is created and the files  `GLTFLoaders` and `LegacyGLTFLoader` are copied. `threeExamples.js` file is the list of files that are copied during this installation. Do you check if this files are present in `/src/ThreeExtended/loaders`?

**Comment by augusttty** [comment]
Turns out it is due to  the node.js version.
I run it in :  window, npm 6+ , node.js8+.
My previous node.js version is 8+, and  i updated it to 10+,problem solved!
And if it is node 8+,the ThreeExtended folder cannot be created,
the log error info is "Failed to download chromium r609904",or it just stuck in "node install.js"...
Also ,it cannot use `cnpm` ,which will skip the `ThreeExtended` folder creation(in China, we usually use `cnpm` because the `npm` is too slow)
Thanks for your TIPS，祝您生活愉快~

**Comment by zarov** [comment]
Thanks for the heads up ! Concerning the failure to download Chromium, some of us had this problem before and we solved it by fixing some `env` variables: https://github.com/iTowns/itowns/pull/740#issuecomment-391752687

We will update the README to reflect the need of node 10+, thanks !
