### ISSUE TITLE
Cleaning and updating the documentation

### ISSUE THREAD

**Issue by zarov** [iTowns/itowns#968]
Now that the layout has been updated, it would be good to re-read, clean and correct the current documentation. It looks like a big task but I think it could be done quickly if everyone gives a hand 😉 So if you are updating/cleaning a file in this list, please let us know in this issue and open your PR when you are ready. The commit message should something like `docs: cleaning and updating __filename__ (part of #968)`

Here is the list (some files may already be okay):
- [ ] Base
  - [ ] Cache
  - [ ] Scheduler
  - [ ] TileMesh
- [ ] View
  - [ ] View
  - [ ] GlobeView
- [ ] Geographic
  - [ ] Coordinates
  - [ ] Extent
  - [ ] OrientationUtils
  - [ ] OBB
- [ ] Layer
  - [ ] Layer
  - [ ] ColorLayer
  - [ ] ElevationLayer
  - [ ] GeometryLayer
  - [ ] TiledGeometryLayer
  - [ ] InfoTiledGeometryLayer
  - [ ] ColorLayersOrdering
  - [ ] GlobeLayer
  - [ ] PanoramaLayer
  - [ ] PlanarLayer
- [x] Source
  - [x] Source
  - [x] WMTSSource
  - [x] WMSSource
  - [x] WFSSource
  - [x] TMSSource
  - [x] StaticSource
  - [x] FileSource
  - [x] URLBuilder
  - [x] Fetcher
- [ ] Parser
  - [ ] GeoJsonParser
  - [ ] GpxParser
  - [ ] VectorTileParser
  - [ ] CameraCalibrationParser
- [ ] Converter
  - [ ] Feature2Mesh
- [ ] Controls
  - [ ] GlobeControls
  - [ ] StateControl
  - [ ] PlanarControls
  - [ ] FirstPersonControls
  - [ ] OrientedImageCamera
  - [ ] CameraUtils
- [ ] Renderer
  - [ ] OrientedImageMaterial

Thanks for the help !

**Comment by jailln** [comment]
Done while migrating to typescript, see #2396
