### ISSUE TITLE
Enable arbitrary TileMatrixSet naming for WMTS source

### ISSUE THREAD

**Issue by SesticM** [iTowns/itowns#972]
Currently it's not possible to set naming for WMTS source `TileMatrixSet` different than IGN-specific "PM" and "WGS84G", since it's hard-coded in `../src/Core/Geographic/Projection.js`. My suggestion is that you replace existing `tileMatrixSet` parameter with `projection` in `Projection->getCoordWMTS_WGS84()` function specifying a projection's EPSG code, as being set on `WMTSSource` side. In that way you will not constraint `TileMatrixSet` naming as such, but rather an actual projection being used for that specific grid set.

**Comment by gchoqueux** [comment]
Thank you for reporting this issue. Indeed, it's necessary to be able to set a `TileMatrixSet WMTS` source different from that specific to IGN. We are planning this feature for v2.7.0.

**Comment by gchoqueux** [comment]
@SesticM Could you open a pull request to fix it?

**Comment by gchoqueux** [comment]
it's now possible to custom `TileMatrixSet` and specif a projection's EPSG code.
