### ISSUE TITLE
Run only one test 

### ISSUE THREAD

**Issue by jailln** [iTowns/itowns#974]
Is there a way to run only one of the [examples tests](https://github.com/iTowns/itowns/tree/master/test/examples) ?

Note: I've tried using [--grep option of mocha](https://mochajs.org/#usage) in the test/examples folder but it doesn't seem to do the trick. I assume it's because the tests uses functions defined in bootstrap.js but I've no hints on how to specify it in the command line. Maybe you already had this use case and know how to do it ?

**Comment by zarov** [comment]
Yes, personally I use `node_modules/mocha/bin/mocha -t 30000 test/examples/bootstrap.js test/examples/wfs.js` for example. You need to include the `bootstrap` file before the actual test.

**Comment by jailln** [comment]
Thanks :)

**Comment by jailln** [comment]
Thanks, this seems to work but now I always get a TimeoutError :

```
 wfs
    1) "before all" hook


  0 passing (30s)
  1 failing

  1) wfs
       "before all" hook:
     TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
      at Promise.then (node_modules/puppeteer/lib/FrameManager.js:1276:21)
    -- ASYNC --
      at Frame.<anonymous> (node_modules/puppeteer/lib/helper.js:144:27)
      at Page.goto (node_modules/puppeteer/lib/Page.js:624:49)
      at Page.<anonymous> (node_modules/puppeteer/lib/helper.js:145:23)
      at global.loadExample (test/examples/bootstrap.js:95:20)
      at Context.before (test/examples/wfs.js:6:24)
```

(I have the same error when running other tests).

Do you have any hints ? It might be related to #929 ?

**Comment by zarov** [comment]
Timeout may happen frequently on some tests, like the `wfs` one, because the servers we are getting data from don't seem to have a very broad bandwidth. Increasing the `-t` parameter can help you do the trick.

**Comment by jailln** [comment]
I tried increasing it but it somehow always times out at 30000ms; which seems to be a max value (I also tried with --no-timeout option which yields the same result).

Anyhow I managed to make it work by running `npm run lint -- --max-warnings=0 && npm run build` once before running the tests individually.

Thanks for your help!
