### ISSUE TITLE
Provide mouse wheel's click-down alternative to existing "Control" button's click-down event

### ISSUE THREAD

**Issue by SesticM** [iTowns/itowns#978]
Please provide mouse wheel's click-down alternative to existing left "Control" button click-down event, as it enables single-handed scene tilt manipulation, similar to Google Earth's.

**Comment by gchoqueux** [comment]
You can use this snippet to configure controls : 
```js
view.addEventListener(itowns.GLOBE_VIEW_EVENTS.GLOBE_INITIALIZED, function m() {
    const states = view.controls.getStates();
    states.PAN.enable = false;
    states.ORBIT.keyboard = undefined;
    states.DOLLY.mouseButton = itowns.THREE.MOUSE.RIGHT;
    states.ORBIT.mouseButton = itowns.THREE.MOUSE.MIDDLE;
});
```

**Comment by SesticM** [comment]
@gchoqueux Yes, I'm aware of that, although it might be of a great help to support _both_ alternatives (keyboard _and_ mouse) out-of-the-box.

**Comment by EricBoix** [comment]
I know I'm hijacking this issue, but I really would like to see the keyboard/touchpad controls work on my Mac PowerBook (I miss all the rotations which is really a drag). Is there some hope to get it working sometime ?

**Comment by gchoqueux** [comment]
@SesticM and @EricBoix 

We propose some things during the factorizations of Controls.

**Comment by SesticM** [comment]
Just a bit of lamenting over present state of Google Earth-based mouse controls:

- Left mouse button + Drag = Pan
- Left mouse button (Single-click) = Select underlying feature (if any)
- Left mouse button (Double-click) = Zoom in one level based on selected location
- Mouse wheel up = Zoom in
- Mouse wheel down = Zoom out
- Mouse wheel click + Drag = Tilt/rotate scene
- Right mouse button (Double-click) = Zoom out one level based on selected location
- Right mouse button + Drag up = Zoom out
- Right mouse button + Drag down = Zoom in
- Right mouse button + Drag left/right = Rotate scene
