### ISSUE TITLE
Very bad performance on last master 50578cc

### ISSUE THREAD

**Issue by nosy-b** [iTowns/itowns#98]
Last master https://github.com/iTowns/itowns2/commit/50578cc21ac5e34b261418ba531ad1000b8bd119 is very slow on Mac + Chrome + intel HD4000.
Poor fps compared to current [mbredif.github.io](mbredif.github.io)

**Comment by nosy-b** [comment]
I found the commit that killed the FPS on small config: 7116371ca80c220e49f8fd786b075ff634e95db2 thanks @vcoindet ;)
I can check through the code or if you have already an idea just go for it

**Comment by qdnguyen** [comment]
i saw more textures sent to graphic card? may be PCI transfert takes time?

**Comment by nosy-b** [comment]
Yes, profiles from debugger show huge CPU time to send textures array to gpu, plus warning.
I thought even if it went from 8 to 16 textures unit, the program didn't use more than 8

**Comment by nosy-b** [comment]
Ok It might be the 16 textures for each tiles. It's just too much for small config. 
Eventhough much less than 16 per tiles are used, in _src/Renderer/LayeredMaterial.js_ you instantiate the 16 textures and they'll be send to gpu.

**Comment by nosy-b** [comment]
I tested with `var maxTexturesUnits =  8;` in _src/Renderer/LayeredMaterial.js_
It went back to a good fps
For more layer blending we should find another solution than increasing the number of texture in order to ensure it works on mobile platform and stay smooth on light config

**Comment by gchoqueux** [comment]
@nosy-b  any news?
