### ISSUE TITLE
Proposal for a contribution

### ISSUE THREAD

**Issue by claustres** [iTowns/itowns#982]
Dear all, we've started a significant effort to create a generic Open Source platform for weather forecast data called Weacast (https://github.com/weacast). Weacast is still a work in progress but we have a running base already used in some production applications. You will find an introductory article [here](https://towardsdatascience.com/introducing-weacast-e6e98487b2a8) and documentation [here](https://weacast.github.io/weacast-docs/).

Our next demo application [Kano](https://github.com/kalisio/kano) will include 3D visualization, for now we have started to build something based on CesiumJS. However, we've just discovered your work and more specifically one of your example with 3D wind visualization in your trailer video (although we did not find any source code sample related to it).

We would be interesting in starting a collaboration on this subject, let me know what you think.

**Comment by gchoqueux** [comment]
Hello, thank you for your interest in `itowns`. We are interested in your project and collaboration. We'll contact you shortly about this.

best regards
