### ISSUE TITLE
3DTiles bounding boxes debug tool erroneous display

### ISSUE THREAD

**Issue by EricBoix** [iTowns/itowns#989]
## Your Environment
 * Version used: V2.6.0 (git tag), [98abec9d](https://github.com/iTowns/itowns/commit/98abec9da9e7e5809c70b49ad2ffc35875c83989) (technically we use [this fork](https://github.com/jailln/itowns/tree/planar_3dtiles) as WIP) 
 * Browser Name and version: Firefox 64.0
 * Operating System and version (desktop or mobile): macOS 10.13.6
 * Link to your project: [this WIP fork](https://github.com/jailln/itowns/tree/planar_3dtiles) of the official iTowns

## Context
Gltf and 3D-Tiles made different choices for their referential systems ([gltf is Y-Up while 3DTiles is Z-up](https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/280)). 
Previous versions of 3D-Tiles specifications allowed to deal with this discrepancy by enabling the usage of an [`asset.gltfUpAxis` attribute](https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/175).
But the current version of 3D-Tiles specification (that [uses gltf version 2 as base for its B3dm's](https://github.com/AnalyticalGraphicsInc/3d-tiles/blob/master/specification/TileFormats/Batched3DModel/README.md#binary-gltf)) dropped this `asset.gltfUpAxis` feature as mentionned by [ lilleyse comment dated May 10, 2018](https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/280).
When working with source data that is inherently z-up, the current [3D-Tiles manner of dealing with the gltf/3DTiles axis discrepancy](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/specification#gltf-transforms) recommends the following common workflow:
```
   - Mesh data, including positions and normals, are not modified - they remain z-up.
   - The root node matrix specifies a column-major z-up to y-up transform. This transforms the source data into a y-up coordinate system as required by glTF.
   - At runtime the glTF is transformed back from y-up to z-up with the matrix above. Effectively the transforms cancel out.
```
where the considered `root node matrix` is the gltf one (as opposed to the [tile-set's root](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/specification#tileset) tile [transform matrix](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/specification#tile-transforms)).

Now when setting up, checking or adjusting, the spatial placement of some geographical data set **being able to display its bounding** often proves to be a really useful debugging tool.  
Remember that the definition of a [`tile.boundingVolume` (e.g. a Box)](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/specification#boundingvolumebox), associated e.g. to such 'inherently z-up data',  is done at the Tile level and that its positioning is constrained to use a [Tile Transform matrix](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/specification#transforms) (as opposed to the gltf's `root node matrix` of the data of which it is a bounding volume).

Is important to note that the above remark implies that a `tile.boundingVolume` is *not* related to the above mentioned historical `asset.gltfUpAxis` (because a Bounding Volume is not expressed at the gltf level). This fact seems in apparent contradiction with the iTowns' [code that displays BoudingVolumes](https://github.com/iTowns/itowns/blob/master/utils/debug/3dTilesDebug.js#L74).

Anyhow, iTowns' current [code for parsing B3dm](https://github.com/iTowns/itowns/blob/master/src/Parser/B3dmParser.js#L119) offers to support the now deprecated 3D-tiles' `asset.gltfUpAxis` trick-feature. And although this feature support should simply be deprecated, this code is still coherent with the current 3D-Tiles specification in that it allows to properly display old (using `asset.gltfUpAxis`) as well as new Tilesets . (Please note that when deprecating this code the `gltf.scene.applyMatrix(matrixChangeUpVectorZtoY);` will have to be kept, in order to properly handle the gltf vs 3DTiles axis discrepancy). 

In opposition, and in order for Bounding Volumes (and bounding boxes) of new tile-sets (i.e. tile-sets that are 3D-Tiles current specification compliant) to be properly displayed, the corresponding iTown's code seems to require some adaptation. Indeed the [Bounding Volume (debug) *display* code](https://github.com/iTowns/itowns/blob/master/utils/debug/3dTilesDebug.js#L74) mirrors its [B3dm parsing counterpart](https://github.com/iTowns/itowns/blob/master/src/Parser/B3dmParser.js#L119) and *realizes a (default) Y to Z rotation when it should NOT*.

The undesired effect (bug?) is that the displayed bounding boxes appear erroneously rotated by 90 degrees as (not so well) shown on the following illustration  ![appear erroneously rotated by 90 degrees](https://user-images.githubusercontent.com/26405741/50916242-e68a6900-143a-11e9-8e61-43d32f282220.png)

## Steps to Reproduce (for bugs)
Because we are currently working on a feature evolution of the [Py3Dtiles toolkit](https://github.com/Oslandia/py3dtiles) (WIP is on [this fork](https://github.com/MEPP-team/py3dtiles/tree/Tiler)) and its iTowns client side counterpart is also [on a fork/branch](https://github.com/jailln/itowns/tree/planar_3dtiles) providing such steps might be a little lengthy for the time being. But if providing those steps happened to be mandatory for this issue to be resolved then we shall of course comply with the demand (read we need it bad ;)

## Expected Behavior
Bounding Volume of contemporary tilesets should be properly displayed (without an erroneous rotation).

## Actual Behavior
The displayed bounding boxes  appear erroneously rotated by 90 degrees ha (not so well) shown on the following illustration  ![appear erroneously rotated by 90 degrees](https://user-images.githubusercontent.com/26405741/50916242-e68a6900-143a-11e9-8e61-43d32f282220.png)

## Possible Cause/Fix/Solution
Fixing this issue (while still allowing the display of "old" tilesets) will require to programmatically distinguish between:
 - "old" tile sets using `asset.gltfUpAxis` trick-feature
 - "new" tile sets not using this feature

A (not that clean) way of doing so might be to use make the following "heuristic" (assumption):
 - Tile sets using `asset.gltfUpAxis` trick-feature are old ones
 - Tile sets NOT using `asset.gltfUpAxis` trick-feature AND [using gltf version 2](https://github.com/iTowns/itowns/blob/master/src/Parser/B3dmParser.js#L161)  are "new" ones.

**Comment by gchoqueux** [comment]
Thank you for revealing this issue. We think we are working on this problem for release 2.9.0. Unless, you can fix in a pull request, will that be possible?

For information, we plan to completely refactor 3DTiles.

**Comment by jailln** [comment]
@gchoqueux do you know approximately when this refactorization is planned and do you have any ideas of the changes involved yet ?

**Comment by gchoqueux** [comment]
Re-factorization is planned current mid 2019. 
For now the changes are not specified, but they are basically:

* support 3Dtiles specification 1.0
* use of itowns architecture: GeometryLayer, Source and Parser.
* Fix the bugs
* Improve performances

I reiterate that we will try to fix your problem in the release 2.9.0.

**Comment by jailln** [comment]
Thanks for this roadmap information about 3d tiles. 

_Note: Some unsuccessful preliminary tests have been made in #999._

**Comment by gchoqueux** [comment]
@EricBoix could you verify if the PR #1319 fixes this issue?

**Comment by EricBoix** [comment]
Our team encountered this issue (a bit more than a year ago) while displaying 3D Tiles layers when in planar view mode. Because, at that time, iTowns had no corresponding demo (viewing 3D-Tiles in planar mode) @jailln tried to [provide such an example with this PR](https://github.com/iTowns/itowns/pull/1034).

Alas the provided example was considered too slow to be illustrative and the PR still requires quite some work on our side (reducing the size of the given tile sets) before acceptance. And this says nothing about the expected rebase after one year of iTowns evolution (for the better!). 

Without such an example of 3D-Tiles in planar mode at hand, recreating the context of this issue would require quite some work. And alas our team won't be able to deliver such an effort before a roughly estimated 3 months (sorry for that).

You might cross fingers and close this issue. If the problem reappears when adjusting the above mentioned example-PR then we will have a trivial way to reproduce the issue and we will consider reopening it.

**Comment by gchoqueux** [comment]
I'll rebase #1034 to test the fix.

**Comment by gchoqueux** [comment]
I rebase and tested on #1034, the #1319 fixes this issue. (link to  [rebased branch](https://github.com/gchoqueux/itowns/tree/3d_tile_planar))

![bbox 25D](https://user-images.githubusercontent.com/11291849/74421769-d9b22300-4e4d-11ea-9856-c636a862751c.png)

(On the other hand, the 3dtiles are raised off the ground. There's the problem with the original branch #1034.)

**Comment by jailln** [comment]
Thanks for rebasing and checking that !

Regarding flying buildings it comes from an update of the elevation layer served by the Grand Lyon. More specifically, the [min and max elevation values](https://github.com/iTowns/itowns/compare/master...gchoqueux:3d_tile_planar#diff-fe9a06c2dd6e2f37ee53b090495b2ec8R94-R95) changed to `144` and `622` respectively. These values may seem as magic numbers; however I don't know if there is yet a possibility to fetch them from the server or to compute them on the fly.

**Comment by gchoqueux** [comment]
Thanks, for new elevation values!
I'll fix the planar example!
