### ISSUE TITLE
problem on start, the paths of GLTFLoader and GLTFLoaderLegacy  are unfound

### ISSUE THREAD

**Issue by Oncledjoe** [iTowns/itowns#994]
## Your Environment
* Version used: last (master)
* Browser Name and version: FireFox
* Operating System and version (desktop or mobile): Ubuntu 18.04LTS
* Link to your project: /

npm install works. 
I can't run itowns, errors occur after the command line npm start : 
ERROR in ./src/Parser/B3dmParser.js
Module not found: Error: Can't resolve 'ThreeExtended/loaders/GLTFLoader' in '/home/myusername/itowns/src/Parser'

ERROR in ./src/Parser/B3dmParser.js
Module not found: Error: Can't resolve 'ThreeExtended/loaders/deprecated/LegacyGLTFLoader' in '/home/myusername/itowns/src/Parser'

**Comment by zarov** [comment]
It may be because you are using an older version of nodejs. Try with something at least 10+. 

The fact is that we don't store `GLTFLoader` anymore in our repository but we get it directly from THREE. The module that we use for this works only after node 10+ I think.

I'm not entirely sure about that, but @gchoqueux could confirm that.

**Comment by Oncledjoe** [comment]
It work! thanks a lot.

**Comment by aboutqx** [comment]
node 12+ the same problem， can't get threeExtended.

**Comment by zarov** [comment]
Do you have any error message ? Also, which version of itowns/npm/node are you using precisely ?

**Comment by aboutqx** [comment]
> ERROR in ./src/Parser/B3dmParser.js
Module Error (from ./node_modules/_eslint-loader@3.0.3@eslint-loader/dist/cjs.js):

> 
> D:\Github\itowns\src\Parser\B3dmParser.js
>   3:24  error  Unable to resolve path to module 'ThreeExtended/loaders/GLTFLoader'   import/no-unresolved
>   4:25  error  Unable to resolve path to module 'ThreeExtended/loaders/DRACOLoader'  import/no-unresolved
> 
> ✖ 2 problems (2 errors, 0 warnings)
> 
>  @ ./src/Main.js 70:0-86 70:0-86 70:0-86 70:0-86
>  @ ./src/MainBundle.js
>  @ multi @babel/polyfill url-polyfill whatwg-fetch ./src/MainBundle.js
> 
> ERROR in ./src/Renderer/c3DEngine.js
> Module Error (from ./node_modules/_eslint-loader@3.0.3@eslint-loader/dist/cjs.js):
> 
> D:\Github\itowns\src\Renderer\c3DEngine.js
>   10:23  error  Unable to resolve path to module 'ThreeExtended/WebGL'  import/no-unresolved
> 
> ✖ 1 problem (1 error, 0 warnings)
> 
>  @ ./src/Core/View.js 11:0-46 136:19-28 138:19-28
>  @ ./src/Main.js
>  @ ./src/MainBundle.js
>  @ multi @babel/polyfill url-polyfill whatwg-fetch ./src/MainBundle.js
> 
> ERROR in ./utils/debug/charts/ThreeStatsChart.js
> Module Error (from ./node_modules/_eslint-loader@3.0.3@eslint-loader/dist/cjs.js):
> 
> D:\Github\itowns\utils\debug\charts\ThreeStatsChart.js
>   1:19  error  Unexpected use of file extension "js" for "chart.js"  import/extensions
> 
> ✖ 1 problem (1 error, 0 warnings)
> 
>  @ ./utils/debug/Debug.js 5:0-55 29:23-38
>  @ ./utils/debug/Main.js
>  @ multi ./utils/debug/Main.js
> 
> ERROR in ./utils/debug/charts/TileObjectChart.js
> Module Error (from ./node_modules/_eslint-loader@3.0.3@eslint-loader/dist/cjs.js):
> 
> D:\Github\itowns\utils\debug\charts\TileObjectChart.js
>   1:19  error  Unexpected use of file extension "js" for "chart.js"  import/extensions
> 
> ✖ 1 problem (1 error, 0 warnings)
> 
>  @ ./utils/debug/TileDebug.js 7:0-55 73:32-47
>  @ ./utils/debug/Main.js
>  @ multi ./utils/debug/Main.js
> 
> ERROR in ./utils/debug/charts/TileVisibilityChart.js
> Module Error (from ./node_modules/_eslint-loader@3.0.3@eslint-loader/dist/cjs.js):
> 
> D:\Github\itowns\utils\debug\charts\TileVisibilityChart.js
>   1:19  error  Unexpected use of file extension "js" for "chart.js"  import/extensions
> 
> ✖ 1 problem (1 error, 0 warnings)
> 
>  @ ./utils/debug/TileDebug.js 8:0-63 74:32-51
>  @ ./utils/debug/Main.js
>  @ multi ./utils/debug/Main.js
> 
> ERROR in ./src/Renderer/c3DEngine.js
> Module not found: Error: Can't resolve 'ThreeExtended/WebGL' in 'D:\Github\itowns\src\Renderer'
>  @ ./src/Renderer/c3DEngine.js 12:0-44 74:11-16 75:30-35 76:18-23 77:30-35
>  @ ./src/Core/View.js
>  @ ./src/Main.js
>  @ ./src/MainBundle.js
>  @ multi @babel/polyfill url-polyfill whatwg-fetch ./src/MainBundle.js
> 
> ERROR in ./src/Parser/B3dmParser.js
> Module not found: Error: Can't resolve 'ThreeExtended/loaders/DRACOLoader' in 'D:\Github\itowns\src\Parser'
>  @ ./src/Parser/B3dmParser.js 5:0-60 64:2-13 67:4-15 70:24-35 72:2-13
>  @ ./src/Main.js
>  @ ./src/MainBundle.js
>  @ multi @babel/polyfill url-polyfill whatwg-fetch ./src/MainBundle.js
> 
> ERROR in ./src/Parser/B3dmParser.js
> Module not found: Error: Can't resolve 'ThreeExtended/loaders/GLTFLoader' in 'D:\Github\itowns\src\Parser'
>  @ ./src/Parser/B3dmParser.js 4:0-58 13:28-38
>  @ ./src/Main.js
>  @ ./src/MainBundle.js
>  @ multi @babel/polyfill url-polyfill whatwg-fetch ./src/MainBundle.js
> i ｢wdm｣: Failed to compile.

npm version 6.10.0
node version 12.11.1

I'm using itowns from this repo's matser.

**Comment by zarov** [comment]
So I tried to redo all the installation using your node and npm versions, completely reinstalling `node_modules`, but I can't seem to reproduce your problem. The only thing I can't test is doing this on Windows, but I don't see how can this be the cause of the problem. Have you try it on another computer ?
If you can, could you also (on your computer) reinstall it in another directory, and list all the commands you are doing here ? Thanks

**Comment by aboutqx** [comment]
Yes， i do run it on windows.
I can't find another compuer now,and I would spend some time on understanding How the `ThreeExtended/loaders/GLTFLoader` is resolved , I may find the cause.
How can i explictly import the dir `ThreeExtended/loaders/GLTFLoader`? 
I can't find it in `webpack.config.js`.
Maybe it really is a node or npm problem,not related to this repo.

**Comment by nosy-b** [comment]
@aboutqx I recently tried on a win10 machine (with an ubuntu console), after the `sudo npm install` I had to do` npm install` for the file patching to work nicely. Then build and run are ok

**Comment by aboutqx** [comment]
@nosy-b I've find that it has a problem when i install using`cnpm i` which using a china locale registry, `npm i` seems working fine on windows which i'm using.
